### ISSUE TITLE
Create VM using Managed Disk policy

### ISSUE THREAD

**Issue by darshankumarys** [Azure/azure-policy#100]
We have a requirement to use only managed disk while provisioning VMs, we are using below json provided by MS to deny if not managed, but the alias for disks is microsoft.compute/disks. we can't actually achieving the requirements, hence changed to audit instead of Deny.

Is there any other ways to achieve this?

{
  "if": {
    "anyOf": [
      {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Compute/virtualMachines"
          },
          {
            "field": "Microsoft.Compute/virtualMachines/osDisk.uri",
            "exists": true
          }
        ]
      },
      {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Compute/VirtualMachineScaleSets"
          },
          {
            "anyOf": [
              {
                "field": "Microsoft.Compute/VirtualMachineScaleSets/osDisk.vhdContainers",
                "exists": true
              },
              {
                "field": "Microsoft.Compute/VirtualMachineScaleSets/osdisk.imageUrl",
                "exists": true
              }
            ]
          }
        ]
      }
    ]
  },
  "then": {
    "effect": "[parameters('effect')]"
  }
}

**Comment by pilor** [comment]
Can you elaborate on why changing the above policy to deny doesn't accomplish your goal?  Do you have an example of a VM template that succeeds without a managed disk when the policy is in place?

**Comment by nilanjandas79** [comment]
@pilor , the Disk is provisioned under Microsoft.Compute/Disk instead of Microsoft.Compute/VirtualMachines/OsDisk . So we are not able to check if the VM is provisioned with Managed Disk or not.

**Comment by pilor** [comment]
The creation of the disk is out of band with the usage of that disk in a VM.  If your intent is to deny VMs that don't use a managed disk the above policy should handle that.  It is denying users who specify an explicit VHD for their osDisk instead of using a managedDisk reference.
