### ISSUE TITLE
Configure diagnostic settings for Storage Accounts to Log Analytics workspace - Template parameter 'metricsEnabled' invalid value

### ISSUE THREAD

**Issue by fabian-ro** [Azure/azure-policy#1008]
#### Details of the scenario you tried and the problem that is occurring

- Assign the policy 59759c62-9a22-4cdf-ae64-074495983fef ("Configure diagnostic settings for Storage Accounts to Log Analytics workspace") to a resource group containing at least one storage account
- Leave the assignment parameters default values untouched (Enable metrics = false)
- Create a remediation task for the assignment

The remediation will fail with the message below.

#### Verbose logs showing the problem

Deployment creation for policy definition '/providers/Microsoft.Authorization/policyDefinitions/59759c62-9a22-4cdf-ae64-074495983fef' and assignment '...' and deployment '...' was unsuccessful.

Code: InvalidTemplate

Message: Deployment template validation failed: 'Template parameter 'metricsEnabled' was provided an invalid value. Expected a value of type 'String, Uri', but received a value of type 'Boolean'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.

#### Suggested solution to the issue

N/A

**Comment by mbhendriks** [comment]
On lines 42-43 metricsEnabled is defined as a Boolean, on lines 97-98 metricsEnabled is defined as a string.
You can work around this by creating a custom policy and change metricsEnabled to type string. Also change the allowed and default values to strings.

**Comment by mbhendriks** [comment]
Facing the same issue. Tried to work around it by creating a custom policy by changing boolean to string for the metricsEnabled parameter. Policy can be applied, remediation is working, but detection is not working and resources stay non compliant.

**Comment by cloudchristoph** [comment]
Similar (or maybe the same) issue. 

Example with enabled metrics for the Policy ["Configure diagnostic settings for Blob Services to Log Analytics workspace"](https://www.azadvertizer.net/azpolicyadvertizer/b4fe1a3b-0715-4c6c-a5ea-ffc33cf823cb.html).

After remediation (which is successful) the resource still comes up a non-compliant.

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/204027/194984939-37465bcc-66c5-4b00-a898-a2aa854c6459.png">

**Comment by J0F3** [comment]
I think this should be fixed by add the second category of the metrics to the deployment template. (at least that's what I have done in my custom policy). Strangely the category is not shown in the portal, but it seems to exist. 

```json
"metrics": [
    {
        "enabled": "true",
        "category": "Transaction"
    },
    {
        "enabled": "true",
        "category": "Capacity"
    }
]
```

**Comment by fabian-ro** [comment]
The original issue (failing remediation tasks) was fixed by now. See the [history of the policy definition file](https://github.com/Azure/azure-policy/commits/45f993bd0df251e166a2feb1f4ef8c4b269b278b/built-in-policies/policyDefinitions/Storage/AccountStorageLogsToWorkspace_DINE.json). 

@cloudchristoph I think what you reported is a separate issue and a new issue should be created for that.
