### ISSUE TITLE
Kubernetes PodEnforceLabels should also check the label value

### ISSUE THREAD

**Issue by ddevaal** [Azure/azure-policy#1012]
I was looking for a policy that enforces labels with a specific value on pods or other resources. Why does: https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/PodEnforceLabels.json only check if the label exists? I was looking for something like: https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/requiredlabels/template.yaml

**Comment by nehakulkarni123** [comment]
Hi @ddevaal, can you please elaborate on the gap you're seeing with [this built-in definition scenario](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/PodEnforceLabels.json)? We have the custom policy functionality available for Kubernetes components now, so you can actually create your own custom Azure policy to apply [this constraint template](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/requiredlabels/template.yaml) at-scale on your Kubernetes clusters. We walk through [an example here](https://techcommunity.microsoft.com/t5/azure-governance-and-management/azure-policy-for-kubernetes-releases-support-for-custom-policy/ba-p/2699466), let me know if you have any questions!

**Comment by ddevaal** [comment]
@nehakulkarni123 Thanks for pointing me in the right direction. I have created my own policy with the ConstraintTemplate from the Gatekeeper library. The policy works fine in our AKS clusters but for some the reason the Compliance reason in the Azure portal stays empty (Loading...).
 
<img width="749" alt="CleanShot 2022-09-11 at 19 44 04@2x" src="https://user-images.githubusercontent.com/74067645/189541593-eb67f63a-da8c-4598-8cc1-43a0ce76d277.png">
