### ISSUE TITLE
deny turn on Virtual machine 

### ISSUE THREAD

**Issue by oritsee** [Azure/azure-policy#102]
Hi,
I'm trying to write policy that prevent users to turn on vm's that are stop.
I understood that I need to use deny but I'm not sure the right context.

can some one can guide me?
thanks

**Comment by DCtheGeek** [comment]
@oritsee Azure Policy is more about control and compliance of infrastructure configuration (example: preventing creation of a Virtual Machine if it is being created in the wrong region or of the wrong size as defined by organization standards).

You are looking to prevent a specific operation, which makes it part of [Role-based access control](https://docs.microsoft.com/azure/role-based-access-control/overview).  It sounds like what you need is `Microsoft.Compute/virtualMachines/start/action` (an operation in Resource Provider [Microsoft.Compute](https://docs.microsoft.com/azure/role-based-access-control/resource-provider-operations#microsoftcompute)). You'll likely need to create a [custom role](https://docs.microsoft.com/azure/role-based-access-control/custom-roles) that allows you to provide the exact allow and deny actions that you want to provide a user or set of users.

**Comment by oritsee** [comment]
so you don't think that I need to use policy to prevent actions on VM's?
what is the right way to do this so I will not need to do separately on every machine?

I tried to do this below but    **"field": "Microsoft.Compute/virtualMachines/start/action",** isn't recognized

{
  "policyRule": {
    "if": {
      "allOf": [
        {
         "field": "type",
          "in": [
                  "Microsoft.Compute/virtualMachines"
                ]
        },
          {
              "field": "Microsoft.Compute/virtualMachines/start/action",
              "equals": "start"
          }
                ]
            },
            "then": {
                "effect": "deny"
            }
        }
    }

**Comment by pilor** [comment]
Policy does not evaluate against actions (POST calls).  Azure Resource Policy is meant to help define what properties the resources in your Azure environment should have (i.e. are they encrypted, is port 80 open, do they have the right tags, etc...).  

[Role based access control](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview) is what you should use to ensure that only certain users can perform actions in your environment.  You'll have to ensure that only the users who you want to be able to "start" VMs have the following action in their role definitions:
`Microsoft.Compute/virtualMachines/start/action`

[This page](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-definitions#actions) has more information on actions and how they are granted via role based access control.
