### ISSUE TITLE
ServiceBus_AuditPublicNetworkAccess: Deny does not work

### ISSUE THREAD

**Issue by alxndr13** [Azure/azure-policy#1023]
#### Details of the scenario you tried and the problem that is occurring

Assigning the ServiceBus_AuditPublicNetworkAccess.json policy to a Subscription with the Policy Effect "Deny" does not prevent Users from creating ServiceBus Namespaces which are available over public networks. The Resource does not even show up in the non-compliant neither the compliant resources tab. 

When we're using the same policy, slightly modified with the `All` Policy Mode, then the `NetworkRuleSet` of the Service Bus Namespace gets marked as non-compliant, but the creation is still **NOT** blocked even though we're using the "Deny" Policy Effect here.

The funny thing is: When you disable public access AFTER the creation of the resource and then try to REENABLE the public access again, the policy works as expected.   

Additionally, when using the Policy Initiative `AuditPublicNetworkAccessInitiative.json`, it also does not work AND the ServiceBus Parameter is missing in the Azure Portal when modifying the parameters of the Assignment. We know the parameter is set though, through the use of `az policy assignment list`

#### Suggested solution to the issue

i don't know. It seems we can't prevent Service Bus Namespaces from using Public Network Access.

**Comment by robga** [comment]
Thanks for reporting the issue. I have notified the built-in policy owner to fix the builtin. 

1. "Microsoft.ServiceBus/namespaces/networkRuleSets" is not a tracked resource type. So, the policy mode should 'All' instead.
2.  When creating or updating a service bus, the evaluated resource type is "Microsoft.ServiceBus/namespaces". To block the creation or update of a service bus with publicNetworkAccess enabled, it needs a policy that checking both the resource type to be "Microsoft.ServiceBus/namespaces" and the field "Microsoft.ServiceBus/namespaces/publicNetworkAccess". 
3. On the policy UI create/edit assignment blade -> parameters tab, there is a check box to hide the parameters with the default value. You can try uncheck the checkbox, it will show all the parameters.

**Comment by alxndr13** [comment]
@robga Thanks a lot for the headsup!
