### ISSUE TITLE
Missing Microsoft.ServiceHealth tag for Azure Policy

### ISSUE THREAD

**Issue by oliverlabs** [Azure/azure-policy#1033]
#### Details of the scenario you tried and the problem that is occurring
While researching a DINE policy for a customer, I discovered that there is no Azure Policy tag for Microsoft.ServiceHealth alerts. Could you please implement it, so that conditions could be made against it (e.g. deployIfNotExists)?
#### Suggested solution to the issue
Implement an Azure Policy tag for Microsoft.ServiceHealth alerts, so that conditions could be made against it (e.g. deployIfNotExists)?

**Comment by kenieva** [comment]
Hi @oliverlabs , can you clarify what an Azure Policy tag is here?

**Comment by oliverlabs** [comment]
Yes, it's a service tag referring to an Azure resource used in the definition of a custom policy. Does it make sense?

**Comment by oliverlabs** [comment]
closing as no response received.
