### ISSUE TITLE
Patternization capability in Azure Policy

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#104]
@pilor  I'd like to know if we can patternize rule in Azure Policy like we do with ARM template.

Giving you an example, we would like to audit all tags & associated value in resource group, in which the rule is as follows:

```
                        "not": {
                            "field": "[concat('tags[',parameters('deployedByTagName'), ']')]",
                            "equals": "[parameters('deployedWhen')]"
                        }
```
In the assignment parameter, what I'd like to achieve is something like 

```
{
    "deployedByTagName": {
        "value": "deployedBy"
    },
    "deployedWhen": {
        "value": dateTime()
    },
```

I don't know if there can be more advanced with Azure Policy rather than mapping 1-1 (if I understand correctly), so I can control value more flexible.

**Comment by pilor** [comment]
You can do everything in the above example except for the dateTime() function as policy does not support a datetime() type function yet.

However, concat, parameter references in both "field" and "equals", etc... are supported.

**Comment by thuansoldier** [comment]
@pilor  How about the value ? I'm referencing the value which is assigned to assignment parameter. Another example is if I have a VM ID like below

```
{
    "approvedImg":{
        "value":[
            "/subscriptions/XXX/resourceGroups/shared-image/providers/Microsoft.Compute/images/baseline_windows-05072018",
            "/subscriptions/XXX/resourceGroups/shared-image/providers/Microsoft.Compute/images/baseline_linux-05062018",
        ]
    }
}
```
Every image name has date created. This field is dynamic so is there a way I could make it more flexible. Or I have to have it fixed like so.

**Comment by pilor** [comment]
The values provided to parameters cannot be dynamic.  If you are updating the list of approvedImg often you will have to update the policy assignment's parameter value each time.
