### ISSUE TITLE
Is supported alias up-to-date over test?

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#105]
I used the given PowerShell to check available alias but it seems not to be up-to-date state

```
$azContext = Get-AzureRmContext
$azProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile
$profileClient = New-Object -TypeName Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient -ArgumentList ($azProfile)
$token = $profileClient.AcquireAccessToken($azContext.Subscription.TenantId)
$authHeader = @{
    'Content-Type'='application/json'
    'Authorization'='Bearer ' + $token.AccessToken
}

# Invoke the REST API
$response = Invoke-RestMethod -Uri 'https://management.azure.com/providers/?api-version=2018-05-01&$expand=resourceTypes/aliases' -Method Get -Headers $authHeader

# Create an Array List to hold discovered aliases
$aliases = New-Object System.Collections.ArrayList

foreach ($ns in $response.value) {
    foreach ($rT in $ns.resourceTypes) {
        if ($rT.aliases) {
            foreach ($obj in $rT.aliases) {
                $alias = [PSCustomObject]@{
                    Namespace       = $ns.namespace
                    resourceType    = $rT.resourceType
                    alias           = $obj.name
                }
                $aliases.Add($alias) | Out-Null
            }
        }
    }
}
```

From the output I don't see `Microsoft.Resources/subscriptions/resourceGroups` which is available.

**Comment by pilor** [comment]
What alias are you expecting to see in the list that isn't returned by the powershell script?  

`Microsoft.Resources/subscriptions/resourceGroups` is a resource type, not an alias.  An alias is used to access fields within a resource type.

**Comment by thuansoldier** [comment]
Thank you @pilor . Is there a way to retrieve supported resource type like the above powershell?

**Comment by pilor** [comment]
This page has a bunch of examples of enumerating resource providers, resource types, etc...

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-supported-services

**Comment by thuansoldier** [comment]
@pilor  and one more if you don't mind. More than tag in resource group, is is possible to use in other resource types such as VM, storage account?

**Comment by pilor** [comment]
Sorry, I don't fully understand the question.  Tags are supported in most top level resource types (including VMs and storage accounts).  Policy is able to inspect tags on those resources (and any other resource that supports tags).

**Comment by thuansoldier** [comment]
That's exactly what I need to know. Thank you very much for your prompt support @pilor
