### ISSUE TITLE
[Preview]: Schedule recurring updates using Update Management Center: doesn't show compliant.

### ISSUE THREAD

**Issue by matswi** [Azure/azure-policy#1059]
ISSUE TITLE:
[Preview]: Schedule recurring updates using Update Management Center: doesn't show compliant.

ISSUE DESCRIPTION (this template):
Even though schedules has been applied to the VM's they still show as Non-compliant.

**Reason for non-compliance**
Current value must be equal to the target value.
**Expression**
true
**Current value**
"true"
**Target value**
"false"

Will this ever be compliant since "true" will never be "false"?

**Comment by benjamin-rousseau-shift** [comment]
I have the same issue.

**Comment by matswi** [comment]
Latest commit seem to have solved this issue. At least for me.

`"existenceCondition": {
  "field": "Microsoft.Maintenance/configurationAssignments/maintenanceConfigurationId",
  "equals": "[parameters('maintenanceConfigurationResourceId')]"
},`
