### ISSUE TITLE
Is it possible to use contains with multiple array parameters in Concat?

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#106]
I have a rule like below and not sure if it works. 

```
                        "not": {
                            "field": "Microsoft.Compute/imageId",
                            "contains": "[concat(parameters('rgName'),parameters('location'), parameters('rgString'))]"
                        }
```
Rather than having multiple conditions to check every resource group, I'd like to be dynamic to use contain to check. 

/resourceGroup/shared-image-**west**-rg/....
/resourceGroup/shared/image-**east**-rg/....

**Comment by pilor** [comment]
Yes, you can absolutely do that as long as each one of those parameters are of type "String".  Contains is going to search your imageId for the exact occurence of the fully concatenated string (case-insensitive).  You'll have to ensure your concatenated string will occur in part of the imageId string.
