### ISSUE TITLE
Feature Request: Support to scan VM using images from Azure Marketplace

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#107]
It is good to audit and deny if a VM doesn't use approved VM image. However it will block the cloud's agility in the use of images from Azure Marketplace. I'd be better if Azure Policy also supports scanning VM using Azure Marketplace images. 

I don't know if there is a way, perhaps reading to **publisher** element?

```
    "storageProfile": {
      "imageReference": {
        "publisher": "MicrosoftWindowsServer",
        "offer": "WindowsServer",
        "sku": "2016-Datacenter",
        "version": "latest"
```
@pilor

**Comment by pilor** [comment]
By scanning do you mean marking VMs that don't use expected images as non-compliant?  If so, you can create an audit policy that inspects any of the above fields with the following aliases:
```
Microsoft.Compute/imagePublisher
Microsoft.Compute/imageOffer
Microsoft.Compute/imageSku
Microsoft.Compute/imageVersion
```

**Comment by thuansoldier** [comment]
I thought of something like Microsoft.Compute/imagePublisher[*] but unsure if it returns something useful. Let's me test that out. 

Thank you very much.

**Comment by thuansoldier** [comment]
The above one was not accepted by Azure Policy but the below one is

```
       {
            "field": "Microsoft.Compute/imagePublisher",
            "exists": true
        }
```

However it's been 1 hour since I created the policy and assignment but nothing has been shown up. Waiting now!

**Comment by thuansoldier** [comment]
It is showing up now. The result looks positive. 

@pilor  Is there a way I can get up-to-date list of supported resource types and fields in Azure Policy?

**Comment by pilor** [comment]
All resource types in Azure Resource Manager are supported in policy.  The list of fields available can be seen through the methods outlined here:
https://docs.microsoft.com/en-us/azure/azure-policy/policy-definition#aliases
