### ISSUE TITLE
App Services Auth Enable Audit Policy 

### ISSUE THREAD

**Issue by nilanjandas79** [Azure/azure-policy#111]
Hi @pilor ,

I am using the following Policy to audit if any App Services Authentication is set to Anonymous or not. Compliance Report shows "Compliant" whereas we have App Services whose Authentication is not set and Anonymous is allowed. Is this Policy definition correct?

Effect I have set to Audit during assignment

{
"if": {
"allOf": [
{
"field": "type",
"equals": "Microsoft.Web/sites"
},
{
"field": "Microsoft.Web/sites/config/siteAuthEnabled",
"exists": "true"
}
]
},
"then": {
"effect": "[parameters('effect')]"
}
}

**Comment by pilor** [comment]
No, the config for Microsoft.Web/sites is kept in a child type [Microsoft.web/sites/config](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdateconfiguration).

If you change the "field"; "type" condition in your policy to "equals": "Microsoft.web/sites/config" it should show compliance status correctly.  The site the config is associated with will show under the "parent resource" column in the UX.

**Comment by nilanjandas79** [comment]
@pilor , yep it worked. Thank you!
