### ISSUE TITLE
Alias Request : Microsoft.Sql/auditingSettings

### ISSUE THREAD

**Issue by rckemry** [Azure/azure-policy#112]
Scenario: Audit SQL server audit setting for storage location endpoint and retention.
Policy:
{
  "if": {
    "field": "type",
    "equals": "Microsoft.Sql/servers"
  },
  "then": {
    "effect": "Audit",
    "details": {
      "type": "Microsoft.Sql/servers/auditingSettings",
      "name": "default",
      "existenceCondition": {
        "allOf": [
          {
            "field": "Microsoft.Sql/auditingSettings.storageEndpoint",
            "equals": "XXXXXXXXX"
          }
          {
            "field": "Microsoft.Sql/auditingSettings.retentionDays",
            "equals": "90"
          }
        ]
      }
    }
  }
}

**Comment by eladperets** [comment]
Added the following aliases:

Microsoft.Sql/servers/auditingSettings/retentionDays
Microsoft.Sql/servers/auditingSettings/state
Microsoft.Sql/servers/auditingSettings/storageEndpoint

Microsoft.Sql/servers/databases/auditingSettings/retentionDays
Microsoft.Sql/servers/databases/auditingSettings/state
Microsoft.Sql/servers/databases/auditingSettings/storageEndpoint

Elad
