### ISSUE TITLE
Changes to AzurekeyVaultFirewallEnabled_Audit cause deployments to fail 

### ISSUE THREAD

**Issue by tommyleedberg** [Azure/azure-policy#1121]
After the release of the latest AzureKeyVaultFirewallEnabled_Audit when deploying a KeyVault if you don't provide any network acls the policy fails stating you must provide a deny policy. If you provide a deny policy with an empty IP range/subnetId's it fails with the following error:

            {
                "result": "True",
                "expressionKind": "Field",
                "expression": "Microsoft.KeyVault/vaults/networkAcls.ipRules[*].value",
                "path": "properties.networkAcls.ipRules[*].value",
                "targetValue": [
                    "224.0.0.0/4",
                    "127.0.0.0/8",
                    "169.254.0.0/16",
                    "168.63.129.16/32",
                    "255.255.255.255/32",
                    "10.0.0.0/8",
                    "172.16.0.0/12",
                    "192.168.0.0/16"
                ],
                "operator": "In"
                
 If you block all of these IPs you get the following error:
 
               {
                            "result": "True",
                            "expressionKind": "Field",
                            "expression": "Microsoft.KeyVault/vaults/networkAcls.ipRules[*].value",
                            "path": "properties.networkAcls.ipRules[*].value",
                            "expressionValue": [
                                "224.0.0.0/4",
                                "127.0.0.0/8",
                                "169.254.0.0/16",
                                "168.63.129.16/32",
                                "255.255.255.255/32",
                                "10.0.0.0/8",
                                "172.16.0.0/12",
                                "192.168.0.0/16"
                            ],
                            "targetValue": [
                                "224.0.0.0/4",
                                "127.0.0.0/8",
                                "169.254.0.0/16",
                                "168.63.129.16/32",
                                "255.255.255.255/32",
                                "10.0.0.0/8",
                                "172.16.0.0/12",
                                "192.168.0.0/16"
                            ],
                            "operator": "In"
                        }
                        
                        
 The only way to get the policy to pass is to create a network acl with a deny policy and a bogus IP address

**Comment by pawel-szon** [comment]
We are experiencing the same issue.  
@pilor could you please have a look.

**Comment by joshuadmatthews** [comment]
Ditto, please fix!

**Comment by pilor** [comment]
I let the author of that policy know.

**Comment by pilor** [comment]
If anyone opens a support case about this issue you can reference internal ICM number 380489712

**Comment by pawel-szon** [comment]
I was told by Microsoft support that the changes to the policy have been reverted. I did a test deployment and it seems to work fine now.
