### ISSUE TITLE
Alias Request : Microsoft.Sql/servers/securityAlertPolicies

### ISSUE THREAD

**Issue by rckemry** [Azure/azure-policy#113]
Scenario : Audit SQL threat detection storage endpoint and retention length.
Definition :
{
  "if": {
    "field": "type",
    "equals": "Microsoft.Sql/servers"
  },
  "then": {
    "effect": "AuditIfNotExists",
    "details": {
      "type": "Microsoft.Sql/servers/securityAlertPolicies",
      "name": "default",
      "existenceCondition": {
        "allOf": [
          {
            "field": "Microsoft.Sql/securityAlertPolicies.storageEndpoint",
            "equals": "XXXXXXXX"
          },
          {
            "field": "Microsoft.Sql/securityAlertPolicies.retentionDays",
            "equals": "90"
          }
        ]
      }
    }
  }
}

**Comment by eladperets** [comment]
Added the following securityAlertPolicies related aliases:

Microsoft.Sql/servers/securityAlertPolicies/disabledAlerts
Microsoft.Sql/servers/securityAlertPolicies/emailAccountAdmins
Microsoft.Sql/servers/securityAlertPolicies/emailAddresses
Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]
Microsoft.Sql/servers/securityAlertPolicies/retentionDays
Microsoft.Sql/servers/securityAlertPolicies/state
Microsoft.Sql/servers/securityAlertPolicies/storageEndpoint

Microsoft.Sql/servers/databases/securityAlertPolicies/disabledAlerts
Microsoft.Sql/servers/databases/securityAlertPolicies/emailAccountAdmins
Microsoft.Sql/servers/databases/securityAlertPolicies/emailAddresses
Microsoft.Sql/servers/databases/securityAlertPolicies/retentionDays
Microsoft.Sql/servers/databases/securityAlertPolicies/state
Microsoft.Sql/servers/databases/securityAlertPolicies/storageEndpoint

Elad

**Comment by klawrie** [comment]
Hi Elad, thanks for adding these aliases, and the other ones I have logged.
One challenge I have with this policy, and also with 'https://github.com/Azure/azure-policy/issues/150', is that i need perform a numeric evaluation.  I need to check that 'retentionDays' is greater that 90 days.

**Comment by eladperets** [comment]
We are aware of the need to support numeric evaluations. Some work is currently being done to support it, but unfortunately I can't estimate when it'll be avaliable
Elad.
