### ISSUE TITLE
support "mode": "Microsoft.KeyVault.Data" for custom policy for keyVault secrets

### ISSUE THREAD

**Issue by nilayptl94** [Azure/azure-policy#1152]
"mode": "Microsoft.KeyVault.Data" is only supported in in-built azure policies and azure policy doesn't have inbuilt policy to audit or deny secret creation without proper tag and value. So, looking for azure to support "mode": "Microsoft.KeyVault.Data" for custom policies.

**Comment by shanhix1** [comment]
Hi @nilayptl94 - thank you for the feature request! Custom policy for "mode": "Microsoft.KeyVault.Data" is top-of-mind in our backlog to be worked on after current investments are completed. I have logged your request and scenarios.

**Comment by Ken9936** [comment]
@shanhix1 Did this ever get addressed?
