### ISSUE TITLE
Does field "name" work with all supported resource types?

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#116]
Hi @pilor 

May I know if field "name" work with all supported resource types? E.g. 

```
{
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "<supported_resource_type"
            },
            {
                "not":{
                    "field": "name",
                    "in": "[parameters('listofName')]"
                }
            }
        ]
    },
    "then": {
        "effect": "audit"
    }
}
```

**Comment by pilor** [comment]
Yes, every resource in Azure has a name.  It is the last segment in the resource ID and typically present as a "name" property at the top-level of the resource's JSON body.

**Comment by thuansoldier** [comment]
@pilor  If I would like to cover all resource types, how would this look like? Saying I'd like to audit all resource type in allowed location 

Is there something like below supported?

        "field": "type",
        "like": "(*)"

**Comment by pilor** [comment]
If you really don't care about type then you can not include a "type" condition in the policy and it will apply to all types.

See https://github.com/Azure/azure-policy/tree/master/samples/General/audit-allowed-locations for an example policy that audits if a resource is not in a defined list of allowed locations
