### ISSUE TITLE
existingResourceGroups function in Azure Policy

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#117]
Hi @pilor 

Does `existingResourceGroups` allow us to check if the target resource type is existed in an existing resource group. For example, I'd like to check if VMs belong to my managed RGs.

```
{
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "Microsoft.Compute/virtualMachine"
            },
            {
                "not":{
                    "field" : "existingResourceGroups",
                    "in": "[parameters('myRg')]"
                }
            }
        ]
    },
    "then": {
        "effect": "audit"
    }
}
```

If not, what would `existingResourceGroups` help?

Your suggestion would be greatly appreciated.

**Comment by pilor** [comment]
There is no "existingResourceGroups" field.  What you are referring to might be the "existingResourceGroups" strongType which can be set on a parameter to let users choose from a list of their resourceGroups in the Azure Portal when assigning the policy.

There isn't a way right now to write a policy condition that evaluates against the resource group name.  If you want policy to do different things for different resource groups it must be handled by assigning the policy to different scopes (or excluding certain resource groups from a higher level assignment scope).
