### ISSUE TITLE
Is there a way to verify if location is null?

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#118]
Not every piece of Azure resource has location indicated. For example job in Azure Automation, or network security group rule which does not have location, but still has resource ID. When scanning resources with location, those are shown up in compliance report. Is there a way that I can exclude those non-located resources?

@pilor

**Comment by pilor** [comment]
Setting the policy definition's mode to "indexed" will cause it to only evaluate against resources that support tags and location.

https://docs.microsoft.com/en-us/azure/azure-policy/policy-definition#mode

I recommend using the built-in policies related to location if they work for you.  They have mode set to "indexed" already.  However, if you are writing a custom policy you can set the mode to indexed via Powershell, CLI, or REST.  We don't expose the "mode" property in the Portal.

**Comment by thuansoldier** [comment]
Hi @pilor 

You'd misunderstand the question. In Azure, not all resources have location indicated, for example a NSG rule in NSG doesn't have location, only NSG has. Or Job in Azure Automation doesn't really have location but it is still considered Azure resource. My attempt is to list all resources deployed in non-approved locations, but the compliance results many resources whose location is **null**.
