### ISSUE TITLE
Allow TLS1.2 only for app services

### ISSUE THREAD

**Issue by darshankumarys** [Azure/azure-policy#119]
Hi,

AM using below template to deny app service creation if TLS is not 1.2 but when i tried creating via portal, it got created with TLS1.0 ,  kindly suggest.

{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Web/sites/config"
      },
      {
        "field": "Microsoft.Web/sites/config/minTlsVersion",
        "notEquals": "1.2"
      }
    ]
  },
  "then": {
    "effect": "[parameters('effect')]"
  }
}

**Comment by thuansoldier** [comment]
Use this one `Microsoft.Web/sites/config/minTlsVersion` 

Refer to this one https://github.com/Azure/azure-policy/issues/54

**Comment by pilor** [comment]
Unfortunately the creation of the initial default config is done behind the scenes by the app service so you cannot deny the initial creation.  I don't believe you are given a choice of minTlsVersion during initial app service resource creation.  What your policy will do, however, is flag any app service not using TLS1.2 as non-compliant and prevent users from changing back to 1.0 once an app service is set to 1.2.

This type of scenario is something we hope to improve in the future.
