### ISSUE TITLE
Wildcard support for resource provider?

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#120]
I have a policy which audits resource types deployed in some specific regions. There are some resource providers I'd like to exclude from the policy. I've tried to use wildcard as follows but this way seems not to be correct

```
{
	"field": "type",
	"in": [
		"Microsoft.Compute/*",
		"Microsoft.Network/*"
	]
},
```

I also use `Microsoft.Compute/(*)` but not successful.  I'd not like to explicitly specify resource type such as `Microsoft.Compute/virtualMachine`. 

@pilor

**Comment by pilor** [comment]
"Like" is the only operator that supports wildcards.  We don't currently have support for wildcards inside of "in" and "notIn" arrays.

To accomplish what you are looking for you'd have to write something like:
```
"anyOf": [
            {
               "field": "type",
               "like": "Microsoft.Compute/*"
            },
            {
               "field": "type",
               "like": "Microsoft.Network/*"
            }
         ]
```
