### ISSUE TITLE
Counting digit or letter of "match" name pattern

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#121]
Hi @pilor 

Do I need to specify number of digit and letter in my name pattern? Saying I'd like the following name to be audited?

- contoso-a-rg

- contoso-ab-rg

- contoso-abc-rg

Do I need three conditions correspondingly:

- contoso-?-rg

- contoso-??-rg

- contoso-???-rg

Is there a way to cover all of three conditions in a single one? e.g. `contoso-{some_thing_here}-rg`.

**Comment by pilor** [comment]
You would need three conditions.  I know this isn't very usable.  Its something we hope to improve in the future.

**Comment by ToMakeSense** [comment]
@pilor 
any updates on this? If we could get regular expression like functionality integrated, it will be helpful. `#` to match a digit, `?` for a letter, `.` to match all character, that's so weak in functionality for **match** series conditions.
