### ISSUE TITLE
Parent resource Policy support

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#122]
Beyond resource type, is there a plan or somewhat about parent resource policy support? There is a case in which subnets from some specific virtual networks need to be scanned. 

If not, it would be great to add a filtering functionality in Compliance resource so I can filter parent resource. Currently I can only filter resource type.

@pilor

**Comment by pilor** [comment]
There isn't a plan right now.  What kind of conditions would you want to perform on the parent resource?

Today we expose the name of the parent resource (combined with the name of the child) in the "fullName" field.  We'll also inherit the tags and location from the parent resource for evaluation in some cases (if the child does not support tags + location of its own).

**Comment by thuansoldier** [comment]
@pilor  Saying I want to audit subnet under virtual network. I'd like to (from Azure Policy Compliance result) to filter virtual network.

**Comment by pilor** [comment]
@thuansoldier We are looking into some changes in this area now.  What kind of filtering do you want to do based on the parent virtual network?  I.e. do you need to inspect properties on that VM or is the filtering only based on the Resource Group and/or name of the VNet?

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
