### ISSUE TITLE
Latest version of Azure Policy schema validation

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#123]
This one seems not to be working https://schema.management.azure.com/schemas/2016-12-01/policyDefinition.json

I got the message **The property '#/if' of type object did not match any of the required schemas** when validating a simple policy which I successfully deployed with PowerShell.

Is there a newer version which I can test?

@pilor

**Comment by pilor** [comment]
Can you provide the policy that didn't validate?  I am successfully using that schema to validate my own policies during authoring.

**Comment by thuansoldier** [comment]
@pilor Sometimes it doesn't work well. I don't know and still under the investigation.

**Comment by pilor** [comment]
I'll close this in the meantime.  If you have a repro please re-activate.
