### ISSUE TITLE
Assign/Enforce RBAC roles to management groups via policy definitions

### ISSUE THREAD

**Issue by mschulz531** [Azure/azure-policy#124]
Is there a way to assign/ensure RBAC roles to a Management Group via a Policy Definition?
Similar to the Enforce Tag and Value policy but for RBAC roles?
Our requirement is to ensure certain custom roles (for managing resources) are assigned to every subscription.  I would prefer not to assign these roles at the subscription level if possible.

**Comment by thuansoldier** [comment]
This is one of my requests here https://github.com/Azure/azure-policy/issues/99 and @pilor  said there was not such a backlog. Not sure if any update now.

**Comment by mschulz531** [comment]
ok thanks, I tried to search the open issues before I posted, sorry I missed that one.

**Comment by pilor** [comment]
You can write a policy that will audit the presence of roleAssignments for certain roleDefinitions or principals at the subscription level.  It will successfully pick up the inherited permissions from the parent Management Groups and show compliant if the required roleAssignments were inherited.

It would be an [auditIfNotExists](https://docs.microsoft.com/en-us/azure/azure-policy/policy-effects#auditifnotexists) policy with the IF portion testing "type"=="Microsoft.Resources/subscriptions", and  ifNotExists details of (type="Microsoft.Authorization/roleAssignments", existenceCondition=<whatever you want to test on each roleAssignment>).

However, deployIfNotExists policies can't be used to create resources on management groups.  They use template deployments to perform actions and template deployments do not allow you to create resources at the management group level.
