### ISSUE TITLE
Tagging capability or Version Control

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#125]
Is there a tagging capability to be added in list of backlogs? With tagging I can tag policy version. Or if not, it would be good to have version capability every time I update my policy (e.g. adding more rules, deleting an assignment parameter).

@LizMS  @pilor

**Comment by vascofernandes** [comment]
Looking for the same. We should be able to version our policies.

**Comment by vascofernandes** [comment]
I tested with the REST API by adding a "version" to the Metadata in the Properties and it does work.
I create the policy definition and then read it back and the version is still present.

So, even though versioning is not baked in, one can work around it.

**Comment by thuansoldier** [comment]
@vascofernandes  yes adding a custom **property** under metadata **element** is a workaround. Every time when we make change we need to update that metadata as well.  I wish every time when we deploy a new change (as long as there is a baseline like Microsoft Word version), my version gets increased.

**Comment by pilor** [comment]
Yes, metadata is a place you can store extra information like this.  We should not be mutating anything you put in there (if we are its a bug).

First-class versioning is something that may come in the future but I don't have a concrete timeline to share.
