### ISSUE TITLE
Azure Update Manager policies do not support Red Hat 9

### ISSUE THREAD

**Issue by neok-g** [Azure/azure-policy#1258]
According to the [documentation](https://learn.microsoft.com/en-us/azure/update-manager/support-matrix?tabs=azurevm%2Cazurevm-os) Azure Update Manager supports Red Hat: RHEL 7,8,9
Unfortunately the following Azure Update Manager policies do not support Red Hat 9 and do not take it into the policy evaluation:
- [Machines should be configured to periodically check for missing system updates](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Azure%20Update%20Manager/AzUpdateMgmtCenter_AutoAssessmentMode_Audit.json)
- [Schedule recurring updates using Azure Update Manager](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Azure%20Update%20Manager/AzUpdateMgmtCenter_ScheduledPatching_Deploy.json)
- [Configure periodic checking for missing system updates on azure virtual machines](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Azure%20Update%20Manager/AzUpdateMgmtCenter_CRP_AutoAssessmentMode_Modify.json)

Of course I can create custom policies but when will these policy definitions be updated?

**Comment by neok-g** [comment]
Anyone?

**Comment by neok-g** [comment]
OK the policies seem to be updated without any notice on this issue.

**Comment by eehret** [comment]
Why does this policy grant 'Contributor' now??
