### ISSUE TITLE
'Mode: Indexed' policy is being evaluated against resources that don't support tags

### ISSUE THREAD

**Issue by markjgardner** [Azure/azure-policy#126]
I have defined the following custom policy for enforcing the existence (but not value) of certain tags on all resources within a subscription.

```json
{
  "if": {
    "not": {
      "containsKey": "project",
      "field": "tags"
    }
  },
  "then": {
    "effect": "audit"
  }
}
```

According to the [documentation](https://docs.microsoft.com/en-us/azure/azure-policy/policy-definition#mode) policy definitions with ```Mode = Indexed``` should only be applied to resources which support tags and locations. Unfortunately this policy is marking some "special" resources as noncompliant. For example, the master database on Sql Server instances (microsoft.sql/servers/databases) is coming up as non-compliant. However, it is impossible to apply tags to a master database:

```powershell
Set-AzureRmResource -Tag $tags -ResourceId "/subscriptions/$subscriptionId/resourcegroups/$resourceGroupName/providers/microsoft.sql/servers/$serverName/databases/master" -Force

Error Output: "Set-AzureRmResource : PatchResourceNotFound : The resource 
'https://management.azure.com/subscriptions/xxx/resourcegroups/xxx/providers/microsoft.sql/servers/xxx/databases/master?api-version=2015-01-01' was not found when 
performing the PATCH operation."
```
Another example of this behavior is application insights alerts (microsoft.insights/alertrules). 

It also appears as if Application Service Environments (microsoft.web/hostingenvironments) always report as non-compliant even when they have the required tags.

I would expect these resources to be excluded by the indexed mode since they do not support tags.

**Comment by thuansoldier** [comment]
This seems to be a bug for '**tag**'. With '**location**' it's fine.

**Comment by markjgardner** [comment]
@pilor and @thuansoldier Is this issue going anywhere?

**Comment by pilor** [comment]
The master DB in SQL is a special case that we are aware of.  It is of a normal resource type that DOES support tags but the resource itself is special in that SQL doesn't let you change it.

Microsoft.Insights/alertRules do support tags.  Unfortunately, not everyone exposes tag selection in the UX or makes it easy to apply tags through CLI/PS.  I just attempted to set a tag on a Microsoft.Insights/alertRules resource using the REST API and was successful.

Microsoft.Web/hostingEnvironments is a bug in the subscription level GET collection API for that resource type.  I will report it to the team and hopefully get a public fix soon.

**Comment by markjgardner** [comment]
@pilor Are you working on a solution for master databases? If so, can we keep this issue open until you have addressed that special case in order to reflect the true state of the issue and so that I'll know when it has been addressed?

**Comment by pilor** [comment]
There is a bug open to determine if there is a reasonable way to deal with special resources like that.  I will reopen this until the bug is resolved in one way or another.

It may be a while until it is addressed.  In the meantime if you are using custom policies you can exclude that specific resource type & name from your policy rule.

**Comment by pilor** [comment]
The "master" SQL DB is now excluded from compliance scans for all policies.  It is a special resource that users have no control over.  Therefore, it should not be evaluated against user policies.
