### ISSUE TITLE
Alias Request: Microsoft.Security/logCollection

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#127]
Scenario - Audit that Data Collection is enabled in Security Center at a subscription level
Definition - If Security Center data collection is off, audit as non-compliant
Example;

{
    "if": {
        "field": "type",
        "equals": "Microsoft.Security"
    },
    "then": {
        "effect": "AuditIfNotExists",
        "details": {
            "type": "Microsoft.Security/logCollection",
            "name": "default",
            "existenceCondition": {
                "allOf": [{
                        "field": "Microsoft.Security/logCollection",
                        "equals": "On"
                    }
                ]
            }
        }
    }
}

**Comment by eladperets** [comment]
There's no 'logCollection' resource, I assume you mean the logCollection property within Microsoft.Security/policies resource type

**Comment by eladperets** [comment]
Done
