### ISSUE TITLE
Alias Request: Microsoft.Security/Policies

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#129]
Scenario - Need to audit the Security Center policy settings required for CIS benchmark 2.3 to 2.19. https://www.cisecurity.org/benchmark/azure/
Definition - All settings under Microsoft.Security/policies/properties.recommendations and Microsoft.Security/policies/properties.securityContactConfiguration

Example:

{
    "if": {
        "field": "type",
        "equals": "Microsoft.Security"
    },
    "then": {
        "effect": "AuditIfNotExists",
        "details": {
            "type": "Microsoft.Security/policies/properties",
            "name": "default",
            "existenceCondition": {
                "allOf": [{
                        "field": "Microsoft.Security/policies/properties.recommendations.patch",
                        "equals": "On"
                    }
                ]
            }
        }
    }
}

**Comment by eladperets** [comment]
Done
