### ISSUE TITLE
Policy not being enforced

### ISSUE THREAD

**Issue by tperry-boopa** [Azure/azure-policy#13]
Hi guys,

I've created the policy definition and assigned to my VS Pro subscription.
However, I am still able to create a Resource Group without fail.
I have tried changed the resource type from "Microsoft.Resources/subscriptions/resourceGroups" to "Microsoft.Resources/resourceGroups" wondering if it was an issue with that. But that didn't work either.

Wondering if I'm missing something?

Cheers,
Tim

**Comment by krnese** [comment]
Hi Tim. This should be deployed and available shortly. Please give it a try by the end of the week, and let us know how it goes. Thx!

**Comment by tperry-boopa** [comment]
Thanks for the prompt response Kristian! Will give it a try in a few days!

**Comment by migrande** [comment]
I'm having the same issue.  Did this start working for you @tperry-boopa?  I tried using the enforce-resourceGroup-tags example, as well as building my own similar policy, but it doesn't seem to affect tags on resource groups.  I can create new ones that violate the policy, and the compliance blade shows 0 violations, even though there should be plenty.

**Comment by tperry-boopa** [comment]
Hi @migrande  - yep it's working for us now - just tested then!

**Comment by krnese** [comment]
@migrande - can you confirm if this work for you too now?
thx!

**Comment by migrande** [comment]
It seems to mostly work.  It does prevent me from creating new RGs that don't have the tags required by the policy, but it does not show existing RGs that are missing tags as non-compliant.

I'm not sure if this is the best forum to go into that.  Is there a way to contact the team - or should I create a new issue on here?

**Comment by migrande** [comment]
Ping @krnese - see my above comment.

**Comment by krnese** [comment]
Thanks - we'll look into this.

**Comment by krnese** [comment]
Adding @cyl3392207. Mike, is resource groups type not surfaced in the compliance overview?

**Comment by pilor** [comment]
Resource groups (and all other resource types) should be exposed correctly in the compliance views.  If you believe you are still not seeing the correct results please open a new issue or contact support.

**Comment by portizbai** [comment]
for me, the compliance works (sometimes), but the policy doesn't enforce anythiing
