### ISSUE TITLE
Alias Request: Microsoft.Sql/securityAlertPolicies.NotificationRecipientsEmails

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#130]
Scenario - Audit that SQL server and database level Threat Protection 'Send alerts to' field (NotificationRecipientsEmails) is populated an not empty. 
This is required as part of Azure CIS Benchmark 4.1.4 and 4.2.4

{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.SQL/servers"
      }
    ]
  },
  "then": {
    "effect": "AuditIfNotExists",
    "details": {
      "type": "Microsoft.SQL/servers/securityAlertPolicies", // or /servers/databases/securityAlertPolicies
      "name": "default",
      "existenceCondition": {
        "allOf": [
          {
            "field": "Microsoft.Sql/securityAlertPolicies.NotificationRecipientsEmails",
            "notEquals": ""
          }
        ]
      }
    }
  }
}

**Comment by eladperets** [comment]
Added for following securityAlertPolicies related aliases:

Microsoft.Sql/servers/securityAlertPolicies/disabledAlerts
Microsoft.Sql/servers/securityAlertPolicies/emailAccountAdmins
Microsoft.Sql/servers/securityAlertPolicies/emailAddresses
Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]
Microsoft.Sql/servers/securityAlertPolicies/retentionDays
Microsoft.Sql/servers/securityAlertPolicies/state
Microsoft.Sql/servers/securityAlertPolicies/storageEndpoint

Microsoft.Sql/servers/databases/securityAlertPolicies/disabledAlerts
Microsoft.Sql/servers/databases/securityAlertPolicies/emailAccountAdmins
Microsoft.Sql/servers/databases/securityAlertPolicies/emailAddresses
Microsoft.Sql/servers/databases/securityAlertPolicies/retentionDays
Microsoft.Sql/servers/databases/securityAlertPolicies/state
Microsoft.Sql/servers/databases/securityAlertPolicies/storageEndpoint

Note that the emailAddresses object is different between servers and databases (one is an array, the other a string)

Elad

**Comment by klawrie** [comment]
Hi Elad, i'm having difficulty getting the below working
Microsoft.Sql/servers/securityAlertPolicies/emailAddresses and
Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]

For mt test Get-AzureRmSqlServerThreatDetectionPolicy returns NotificationRecipientsEmails as empty

I have tried the below policies with no success, all incorrectly return compliant.

{
  "if": {
    "field": "type",
    "equals": "Microsoft.Sql/servers"
  },
  "then": {
    "effect": "AuditIfNotExists",
    "details": {
      "type": "Microsoft.Sql/servers/securityAlertPolicies",
      "existenceCondition": {
        "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses",
        "exists": "true"
} }}}

{
  "if": {
    "field": "type",
    "equals": "Microsoft.Sql/servers"
  },
  "then": {
    "effect": "AuditIfNotExists",
    "details": {
      "type": "Microsoft.Sql/servers/securityAlertPolicies",
      "existenceCondition": {
        "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses",
        "contains": "@"
  }}}}

{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Sql/servers"
      },
      {
        "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses",
        "notContains": "@"
      }]},
  "then": {
    "effect": "Audit"
}}

{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Sql/servers"
      },
      {
        "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]",
        "notContains": "@"
      }] },
  "then": {
    "effect": "Audit"
}}

**Comment by eladperets** [comment]
Hi,
There's only one 'securityAlertPolicies' resource called 'default' for each server.
You need to make sure that policy is targeting just this resource and not trying to evaluate all resources of type 'securityAlertPolicies' (because the SQL resource provider doesn't support it).

To do that, modify your auditIfNotExists polices to also include a name constraint as described here:
https://docs.microsoft.com/en-us/azure/azure-policy/policy-effects#auditifnotexists

For example:
{
"if": {
"field": "type",
"equals": "Microsoft.Sql/servers"
},
"then": {
"effect": "AuditIfNotExists",
"details": {
"type": "Microsoft.Sql/servers/securityAlertPolicies",
**"name": "default",**
"existenceCondition": {
"field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses",
"exists": "true"
} }}}

Please let me know if this works.
Elad.

**Comment by klawrie** [comment]
Hi again,
I have got this working for 'Microsoft.Sql/servers/databases/securityAlertPolicies/emailAddresses'
But can't get it working for Microsoft.Sql/servers/securityAlertPolicies/emailAddresses.

I have tested with the example above, and tried with these variations;

      "existenceCondition": {
        "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]",
        "contains": "@"
      }

      "existenceCondition": {
        "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses",
        "contains": "@"
      }

      "existenceCondition": {
        "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]",
        "contains": "."
      }
      "existenceCondition": {
        "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]",
        "notEquals": ""
      }

All report non-compliant, and don't change to compliant.
I'm using Get-AzureRmSqlServerThreatDetectionPolicy or the console to verify compliance.

**Comment by klawrie** [comment]
Just noticed that some of these have become compliant but it took 3 hours after the resource was changed.
I have noticed this latency occur often and can take 5-6 hours or overnight. This is in an account with minimal resources deployed. Is there any kind of policy evaluation throttling occurring?

**Comment by eladperets** [comment]
I suspect that this is related to the way the SQL resource provider works and that the resources are being evaluated only when we detect a 'write' operations to the security alert policy resource.

Can you please share the policy definition that you are using? 

Elad

**Comment by klawrie** [comment]
The working policies are:
-Audit that SQL server Threat Protection 'Send alerts to' field is populated:
"policyRule": {
    "if": {
        "field": "type",
        "equals": "Microsoft.Sql/servers"
    },
    "then": {
        "effect": "AuditIfNotExists",
        "details": {
            "type": "Microsoft.Sql/servers/securityAlertPolicies",
            "name": "default",
            "existenceCondition": {
                "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]",
                "notEquals": ""
 }}}}
-Audit that SQL database Threat Protection 'Send alerts to' field is populated:
"policyRule": {
    "if": {
        "allOf": [{
                "field": "type",
                "equals": "Microsoft.Sql/servers/databases"
            },{
                "field": "Microsoft.Sql/servers/databases/requestedServiceObjectiveName",
                "notLike": "System*"
            }]
    },
    "then": {
        "effect": "AuditIfNotExists",
        "details": {
            "type": "Microsoft.Sql/servers/databases/securityAlertPolicies",
            "name": "default",
            "existenceCondition": {
                "field": "Microsoft.Sql/servers/databases/securityAlertPolicies/emailAddresses",
                "notEquals": ""
    }}}}

**Comment by eladperets** [comment]
Thanks, I'll reach out to the SQL resource provider and see if they can fix this. Will update.

Elad

**Comment by klawrie** [comment]
Hi Elad, I have doing some Azure Policy testing today, and I have update latency issues with these SQL aliases;
Microsoft.SQL/servers/securityAlertPolicies
Microsoft.Sql/servers/securityAlertPolicies/retentionDays
Microsoft.Sql/securityAlertPolicies.disabledAlerts
Microsoft.Sql/servers/databases/securityAlertPolicies/emailAddresses
Microsoft.Sql/servers/databases/auditingSettings/retentionDays
Microsoft.Sql/servers/databases/securityAlertPolicies/retentionDays

All have been over 5 hours so far, in a test environment will minimal resources deployed.

**Comment by eladperets** [comment]
Closing this issue since it'l not related to the aliases and already being investigated as a support ticket.

Elad
