### ISSUE TITLE
Alias Request: Microsoft.Keyvault/vaults/networkAcls.defaultAction

### ISSUE THREAD

**Issue by travisnielsen** [Azure/azure-policy#132]
**Scenario**
Ensure Key Vault is not accessible from outside Azure

**Definition**
```
{
  "properties": {
    "displayName": "Key Vault - networking - default deny ACL",
    "description": "Equal to ensuring VNET Service Endpoint enabled",
  },
  "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Keyvault/vaults"
          },
          {
            "not": {
              "field": "Microsoft.Keyvault/vaults/networkAcls.defaultAction",
              "equals": "Deny"
            }
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
   }
 }
```

**Comment by eladperets** [comment]
The following Microsoft.KeyVault aliases were added:

Microsoft.KeyVault/vaults/enabledForDeployment
Microsoft.KeyVault/vaults/enabledForDiskEncryption
Microsoft.KeyVault/vaults/enabledForTemplateDeployment
Microsoft.KeyVault/vaults/enablePurgeProtection
Microsoft.KeyVault/vaults/enableSoftDelete
Microsoft.KeyVault/vaults/networkAcls.defaultAction
Microsoft.KeyVault/vaults/networkAcls.ipRules
Microsoft.KeyVault/vaults/networkAcls.ipRules[*]
Microsoft.KeyVault/vaults/networkAcls.ipRules[*].value
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules[*]
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules[*].id
Microsoft.KeyVault/vaults/sku.family
Microsoft.KeyVault/vaults/sku.name
Microsoft.KeyVault/vaults/secrets/attributes
Microsoft.KeyVault/vaults/secrets/attributes.created
Microsoft.KeyVault/vaults/secrets/attributes.enabled
Microsoft.KeyVault/vaults/secrets/attributes.exp
Microsoft.KeyVault/vaults/secrets/attributes.nbf
Microsoft.KeyVault/vaults/secrets/attributes.updated

Elad
