### ISSUE TITLE
Alias Request: Microsoft.Keyvault/vaults/networkAcls.ipRules

### ISSUE THREAD

**Issue by travisnielsen** [Azure/azure-policy#133]
**Scenario**
Prevent a Key Vault administrator from opening network access to unapproved IP addresses

**Definition**
```
{
  "properties": {
    "displayName": "Key Vault - networking - restricted IP addresses",
    "description": "Ensure only approved IP addresses for Key Vault access",
    "parameters": {
      "approvedIps": {
        "type": "Array",
        "metadata": { "description": "list of approved external IP addresses for high securty Key Vaults" }
      },
    }
  },
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Keyvault/vaults"
        },
        {
          "not": {
            "field": "Microsoft.Keyvault/vaults/networkAcls.ipRules[*].value",
            "in": "[parameters('approvedIPs')]"
          }      
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }
}
```

**Comment by eladperets** [comment]
The following Microsoft.KeyVault aliases were added:

Microsoft.KeyVault/vaults/enabledForDeployment
Microsoft.KeyVault/vaults/enabledForDiskEncryption
Microsoft.KeyVault/vaults/enabledForTemplateDeployment
Microsoft.KeyVault/vaults/enablePurgeProtection
Microsoft.KeyVault/vaults/enableSoftDelete
Microsoft.KeyVault/vaults/networkAcls.defaultAction
Microsoft.KeyVault/vaults/networkAcls.ipRules
Microsoft.KeyVault/vaults/networkAcls.ipRules[*]
Microsoft.KeyVault/vaults/networkAcls.ipRules[*].value
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules[*]
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules[*].id
Microsoft.KeyVault/vaults/sku.family
Microsoft.KeyVault/vaults/sku.name
Microsoft.KeyVault/vaults/secrets/attributes
Microsoft.KeyVault/vaults/secrets/attributes.created
Microsoft.KeyVault/vaults/secrets/attributes.enabled
Microsoft.KeyVault/vaults/secrets/attributes.exp
Microsoft.KeyVault/vaults/secrets/attributes.nbf
Microsoft.KeyVault/vaults/secrets/attributes.updated

Elad
