### ISSUE TITLE
Alias Request: Microsoft.Keyvault/vaults/networkAcls.virtualNetworkRules

### ISSUE THREAD

**Issue by travisnielsen** [Azure/azure-policy#134]
**Scenario**
Ensure Key Vault is only accessible to approved VNETs (VNET service endpoints)

**Definition**
```
{
  "properties": {
    "displayName": "Key Vault - networking - default deny ACL",
    "description": "Equal to ensuring VNET Service Endpoint enabled",
    "parameters": {
      "approvedVNETs": {
          "type": "Array",
          "metadata": { "description": "list of approved VNETs for high securty Key Vaults" }
      }
    }
  },
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Keyvault/vaults"
        },
        {
          "not": {
            "field": "Microsoft.Keyvault/vaults/networkAcls.virtualNetworkRules[*].id",
            "in": "[parameters('approvedVNETs')]"
          }
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }
}
```

**Comment by eladperets** [comment]
The following Microsoft.KeyVault aliases were added:

Microsoft.KeyVault/vaults/enabledForDeployment
Microsoft.KeyVault/vaults/enabledForDiskEncryption
Microsoft.KeyVault/vaults/enabledForTemplateDeployment
Microsoft.KeyVault/vaults/enablePurgeProtection
Microsoft.KeyVault/vaults/enableSoftDelete
Microsoft.KeyVault/vaults/networkAcls.defaultAction
Microsoft.KeyVault/vaults/networkAcls.ipRules
Microsoft.KeyVault/vaults/networkAcls.ipRules[*]
Microsoft.KeyVault/vaults/networkAcls.ipRules[*].value
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules[*]
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules[*].id
Microsoft.KeyVault/vaults/sku.family
Microsoft.KeyVault/vaults/sku.name
Microsoft.KeyVault/vaults/secrets/attributes
Microsoft.KeyVault/vaults/secrets/attributes.created
Microsoft.KeyVault/vaults/secrets/attributes.enabled
Microsoft.KeyVault/vaults/secrets/attributes.exp
Microsoft.KeyVault/vaults/secrets/attributes.nbf
Microsoft.KeyVault/vaults/secrets/attributes.updated

Elad
