### ISSUE TITLE
Alias Request: Microsoft.Sql/servers/virtualNetworkRules

### ISSUE THREAD

**Issue by travisnielsen** [Azure/azure-policy#135]
**Scenario**
Restrict access to an Azure SQL DB Server to specific, approved VNETs via VNET Service Endpoints

**Definition**
```
{
    "properties": {
      "displayName": "Azure SQL DB - VNET Service Endoints - Allow approved VNETs only",
      "description": "Restrict access to approved VNETs",
      "parameters": {
        "approvedVnetIDs": {
          "type": "Array",
          "metadata": { "description": "list of VNET IDs" }
        }
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Sql/servers/virtualNetworkRules"
          },
          {
            "not": {
              "field": "Microsoft.Sql/servers/virtualNetworkRules.virtualNetworkSubnetId",
              "in": "[parameters('approvedVnetIDs')]"
            }
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }
  }
```

**Comment by eladperets** [comment]
The following Microsoft.KeyVault aliases were added:

Microsoft.KeyVault/vaults/enabledForDeployment
Microsoft.KeyVault/vaults/enabledForDiskEncryption
Microsoft.KeyVault/vaults/enabledForTemplateDeployment
Microsoft.KeyVault/vaults/enablePurgeProtection
Microsoft.KeyVault/vaults/enableSoftDelete
Microsoft.KeyVault/vaults/networkAcls.defaultAction
Microsoft.KeyVault/vaults/networkAcls.ipRules
Microsoft.KeyVault/vaults/networkAcls.ipRules[*]
Microsoft.KeyVault/vaults/networkAcls.ipRules[*].value
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules[*]
Microsoft.KeyVault/vaults/networkAcls.virtualNetworkRules[*].id
Microsoft.KeyVault/vaults/sku.family
Microsoft.KeyVault/vaults/sku.name
Microsoft.KeyVault/vaults/secrets/attributes
Microsoft.KeyVault/vaults/secrets/attributes.created
Microsoft.KeyVault/vaults/secrets/attributes.enabled
Microsoft.KeyVault/vaults/secrets/attributes.exp
Microsoft.KeyVault/vaults/secrets/attributes.nbf
Microsoft.KeyVault/vaults/secrets/attributes.updated

Elad
