### ISSUE TITLE
Alias request: Microsoft.Compute/virtualMachines/storageProfile.osDisk.EncryptionSettings

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#136]
Scenario : Need to audit that all Virtual Macine OS Disks are encrypted.
Definition :

{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Compute/virtualMachines"
      },
      {
        "field": "Microsoft.Compute/virtualMachines/storageProfile.osDisk.EncryptionSettings",
        "equals": ""
      }
    ]
  },
  "then": {
    "effect": "audit"
  }
}

**Comment by eladperets** [comment]
The following aliases were added:
Microsoft.Compute/virtualMachines/storageProfile.osDisk.encryptionSettings
 Microsoft.Compute/virtualMachines/storageProfile.osDisk.encryptionSettings.enabled

Elad
