### ISSUE TITLE
Alias Request: Microsoft.Compute/virtualMachines/osProfile.linuxConfiguration/AuthenticationType

### ISSUE THREAD

**Issue by swathikamsala** [Azure/azure-policy#137]
Scenario: Need to use azure policy to deny creation of linux VM wih password authentication, should enforce user to create VM with SSH public key authentication.

Definition:

{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Compute/virtualMachines"
        },
        {
          "field": "type",
          "equals": "Microsoft.Compute/virtualMachines/osProfile.linuxConfiguration"
        },
        {
          "field": "Microsoft.Compute/virtualMachines/osProfile.linuxConfiguration/AuthenticationType",
          "equals": "Password"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  },
  "parameters": {},
  "metadata": {
    "category": "Compute"
  }
}

**Comment by eladperets** [comment]
There's already an alias for Microsoft.Compute/virtualMachines/osProfile.linuxConfiguration.disablePasswordAuthentication.
I don't see any 'AuthenticationType' in the API spec:
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get#linuxconfiguration

Elad
