### ISSUE TITLE
Alias Request: Microsoft.KeyVault/vaultkeys/key.expires

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#138]
Scenario: Need to audit if any KeyVault keys do not have an expiry set. Required for CIS Benchmark section 8.1
{
  "properties": {
    "displayName": "Audit KeyVault key expiry",
    "description": "Audits KeyVault keys that don't have an expiry data set.",
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.KeyVault/vaultkeys"
          },
          {
            "not": {
              "field": "Microsoft.KeyVault/vaultkeys/key.expires",
              "equals": ""
            }
          }
        ]
      },
      "then": {
        "effect": "audit"
      }
    }
  }
}

**Comment by eladperets** [comment]
Unfortunately it looks like the key expiration is not exposed as part of an Azure resource and therefore can't be governed by policy.
See [this](https://docs.microsoft.com/en-us/rest/api/keyvault/getkey/getkey) for details.

**Comment by eladperets** [comment]
KV team confirmed that the keys are not Azure Resources and therefore they can't be supported by policy.

Elad

**Comment by abhijay5** [comment]
@klawrie  I have tried to create the same policy as you mentioned above for the CIS 8.1 but i am getting the error stating Alian doesnt exists, i am not sure how did it worked for you.
