### ISSUE TITLE
Feature Request: Policy support for Microsoft.KeyVault/vaultsecrets/secrets*

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#139]
Scenario: Need to audit if any KeyVault secrets do not have an expiry date set. Required for CIS Benchmark section 8.2
{
"properties": {
"displayName": "Audit KeyVault secret expiry",
"description": "Audits KeyVault secrets that don't have an expiry data set.",
"policyRule": {
"if": {
"allOf": [
{
"field": "type",
"equals": "Microsoft.KeyVault/vaultsecrets"
},
{
"not": {
"field": "Microsoft.KeyVault/vaultsecrets/secrets.expires",
"equals": ""
}
}
]
},
"then": {
"effect": "audit"
}
}
}
}

**Comment by eladperets** [comment]
The following alias was added:
Microsoft.KeyVault/vaults/secrets/attributes.exp

Elad

**Comment by abhijay5** [comment]
@eladperets i have created a policy with this provided attribute (Microsoft.KeyVault/vaults/secrets/attributes.exp) and the same policy format mentioned above but the policy is showing compliant , but it's not at all taking any effect while i have defined the Expiry to one and key and haven't defined to another one. Please provide any feedback if you have created anything.

**Comment by eladperets** [comment]
Hi, I'll have a look

**Comment by abhijay5** [comment]
@eladperets that's great thank you , i would be waiting. below one policy which i have created.
{
  "properties": {
    "displayName": "Audit if Key Vault secret key has no expery defined",
    "description": "Audits Key Vault vaults if the secret Key Inside the key vault doesn't have the expery defined on it",
    "mode": "Indexed",
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.KeyVault/vaults"
          },
          {
            "anyOf": [
              {
                "field": "Microsoft.KeyVault/vaults/secrets/attributes.enabled",
                "equals": "true"
              },
              {
                "field": "Microsoft.KeyVault/vaults/secrets/attributes.exp",
                "notequals": ""
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }
  }
}

**Comment by eladperets** [comment]
@abhijay5, your policy is referring to resource of type Microsoft.KeyVault/vaults instead of Microsoft.KeyVault/vaults/**secrets**, this can be the reason for the issue you're having.
If this doesn't work, can you please describe what are you trying to do with that policy?

Elad

**Comment by eladperets** [comment]
@abhijay5, turns out that there're limitations for what policy can do with this resource type. Deny policies, for example, won't always work because you can also add secrets directly to KV without going through ARM (and policy check). So please let me know what you're trying to achieve and i'll try to help.

Elad

**Comment by abhijay5** [comment]
@eladperets Well i have tried all with and without the path and also other parameters encluding (Microsoft.KeyVault/vaults/secrets). 
i have a requirement to create a policy for CIS Document task number  8.2 | Ensure that the   expiry date is set on all Secrets (Scored)
-- | --

**Comment by abhijay5** [comment]
@eladperets Thank you for helping, i am trying to create an audit policy but that doesn't seems to be working hence i have tried to create a policy with Deny statement but turned out that nothing is working at all for the Secret Key vault key expiry. 

Requirement is to create a policy which will audit all the secret key which doesn't have the expiry defined on it.

**Comment by eladperets** [comment]
@abhijay5,
It's currently impossible fully cover this scenario with Azure Policy:
1. We only evaluate this type of resource upon creation (i.e. PUT request sent to ARM). Our periodic compliance checks skip this resource type because of issues we have with this resource provider.
2. You can create secrets by calling KV directly. Since our periodic scans don't cover these resources, we have no way to 'catch' and evaluated these secrets.

I'll start an internal discussion to see what we can do about it and update.

Elad

**Comment by Obiwan72** [comment]
Any news when this issue is going to be fixed? We also would like to be able to use this policy.

**Comment by eladperets** [comment]
Sorry for the late response.
Unfortunately we're unable to support this resource type at the moment. The ARM API for Microsoft.KeyVault/vaults/secrets is intentionally limited in a way that makes in impossible to be fully covered by policy.

We have long term plans to support data-plane policies for specific RPs (including KV). Using these policies may be able to achieve what you need, but I can't tell when it'll be available.

**Comment by FedeBenitez** [comment]
@eladperets thanks for for information, I was also having the same results while trying to use alias Microsoft.KeyVault/vaults/secrets/attributes.exp but now i'm trying to use this [policy ](https://docs.microsoft.com/en-us/azure/governance/policy/samples/keyvault-no-vnet-rules) and i'm seeing the same behavior. Could this be related to what you already explained?

**Comment by eladperets** [comment]
@FedeBenitez, the policy in the example won't be effected by the issue described here because it's not referring to the problematic Microsoft.KeyVault/vaults/secrets resource type.
Feel free to open new issue\support ticket and we'll be happy to help.

**Comment by ns4ever** [comment]
hi

**Comment by KevinBrooke** [comment]
@eladperets Can this be re-opened please, as the issue still persists. 
It would seem that a standard best practice deployment of Azure Key Vault would include policies that ensure Keys and Secrets are only created if they have an expiry set.

**Comment by ryanmaclean** [comment]
@eladperets can this please be re-opened?

**Comment by eladperets** [comment]
Re-opening issue since it's a popular ask.
Current status is that this can't be achieved today using regular policies because of the limitation of the KV API. There are plans to support it in the future, but no ETA.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
