### ISSUE TITLE
Having difficulty with audit of NSG inbound ports

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#140]
I am trying to create a policy to audit Network Security Group TCP ports from the internet. So if RDP is inbound, allowed, no source app group and no restricted source address, it will audit it.

The first 5 filters work correctly, however it needs to check that the 'sourceAddressPrefix' is set to '*' if it is a restricted IP or tag group, this field will be populated.

I have tried using equals \*, contains * and match * but all are failing to recognise the * and audit regardless of the field contents.
{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Network/networkSecurityGroups/securityRules"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange",
          "equals": "3389"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules/access",
          "equals": "Allow"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules/direction",
          "equals": "Inbound"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceApplicationSecurityGroups[*]",
          "notContainsKey": "Id"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefixes[\*]",
          "equals": "*"
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {},
  "metadata": {}
}

**Comment by klawrie** [comment]
Fixed by changing Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefixes[*]
to
Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix

**Comment by klawrie** [comment]
This has been resolved, here is the final working policy;
{
    "policyRule": {
        "if": {
            "allOf": [{
                    "field": "type",
                    "equals": "Microsoft.Network/networkSecurityGroups/securityRules"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange",
                    "equals": "3389"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules/access",
                    "equals": "Allow"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules/direction",
                    "equals": "Inbound"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceApplicationSecurityGroups[*]",
                    "notContainsKey": "Id"
                },
                {
                    "anyOf": [{
                            "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix",
                            "equals": "*"
                        },
                        {
                            "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix",
                            "equals": "Internet"
                        }
                    ]
                }
            ]
        },
        "then": {
            "effect": "audit"
        }
    }
}

**Comment by nconder** [comment]
@klawrie thank you for posting the solution!
