### ISSUE TITLE
Alias Request

### ISSUE THREAD

**Issue by swathikamsala** [Azure/azure-policy#141]
Alias : Microsoft.Compute/virtualMachines/osProfile.linuxConfiguration.sshauthentication or 
Microsoft.Compute/virtualMachines/osProfile.linuxConfiguration.disablesshauthentication or
Microsoft.Compute/virtualMachines/osProfile.linuxConfiguration.passwordauthentication

to disallow user from creating linux VM if selected authentication type is password authentication.

**Comment by eladperets** [comment]
Microsoft.Compute/virtualMachines/osProfile.linuxConfiguration.disablePasswordAuthentication already exists.

Elad
