### ISSUE TITLE
Microsoft.Web/sites/httpsOnly - what is the behavior?

### ISSUE THREAD

**Issue by nilanjandas79** [Azure/azure-policy#142]
Hi @pilor ,

What is the expected behavior of the alias Microsoft.Web/sites/httpsOnly ?

When I check "exists" : "true" , I expect no should be able to provision any App Service without https enabled. But the actual behavior is different. It only check if the property is present in the ARM or not, does not ensure if it is set to "true" or not. Is the field type boolean?

Please help to understand the expected behavior.

**Comment by pilor** [comment]
"exists" only checks to see if the property exists in the resource.  You want to use "equals": "true" to validate that the value of the property equals true.

**Comment by nilanjandas79** [comment]
@pilor , We tried with "equals" : "true" but it is wrongly reporting in Compliance Report. App Services with HTTPS enabled are getting reported as Non-Compliant
