### ISSUE TITLE
Alias  Request: "Microsoft.Network/virtualNetworks/virtualNetworkPeerings/useRemoteGateways"

### ISSUE THREAD

**Issue by znrk** [Azure/azure-policy#144]
**Scenario**

Can not use Remote Gateway in spoke vnet.
This Alias is avoid routing trouble in sharing ER Circuit on Hybrid Networking.

**Definition**

    {
        "properties": {
            "displayName": "Can not use Remote Gateway in spoke vnet.",
            "description": "Can not use Remote Gateway in spoke vnet."
            "parameters": {},
         },
         "policyRule": {
                "if": {
                    "allOf": [
                        {
                            "field": "type",
                            "equals": "Microsoft.Network/virtualNetworks/virtualNetworkPeerings"
                        },
                        {
                            "field": "Microsoft.Network/virtualNetworks/virtualNetworkPeerings/useRemoteGateways",
                            "equals": "True"

                        }
                    ]
                },
                "then": {
                    "effect": "deny"
                }
            }
        }
    }

**Comment by mentat9** [comment]
This alias has been added: please give it a try.
