### ISSUE TITLE
Are all VM extensions supported?

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#147]
@pilor are all VM extensions supported followed by this sample https://github.com/Azure/azure-policy/tree/master/samples/Compute/audit-vm-extension

And how do I list all VM extensions?

**Comment by pilor** [comment]
Yes, all VM extensions should be auditable using that policy.

Looks like they have some programmatic means to list all possible VM extensions:
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/features-windows#discover-vm-extensions
