### ISSUE TITLE
Alias request: Microsoft.Insights/logprofiles/name

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#149]
Scenario: Need to audit if Azure Activity log has 'Export Activity Log' enabled in the subscription.
Definition: 
               "policyRule": {
                   "if": {
                                "field": "Microsoft.Insights/logprofiles/default",
                                 "exists": "false"
                            }
                    },
                    "then": {
                        "effect": "audit"
                    }
                }

**Comment by eladperets** [comment]
Not sure what you mean here. Can you please refer me to the exact setting?

**Comment by eladperets** [comment]
Got it, I'll just add aliases to all properties in the logProfile resource: https://docs.microsoft.com/en-us/rest/api/monitor/logprofiles/update

**Comment by eladperets** [comment]
Done
