### ISSUE TITLE
Alias request: Microsoft.Insights/logprofiles[*].retentionPolicy.enabled

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#150]
Scenario: Need to audit if default log profile isn't enabled or retention is less than one year
Definition:
    "policyRule": {
        "if": {
            "allOf": [{
                    "field": "type",
                    "equals": "Microsoft.Insights/logprofiles/default"
                },
                {
                "anyOf": [{ 
                
                    "field": "Microsoft.Insights/logprofiles/default/retentionPolicy.enabled",
                    "equals": "false"
                },
                {
                    "field": "Microsoft.Insights/logprofiles[*].retentionPolicy.days",
                    "lessThan": "365"
                }
            ]
        }
    ]
    }
},
"then": {
    "effect": "audit"
}

**Comment by eladperets** [comment]
Aliases added

**Comment by abhijay5** [comment]
i have created a below policy with reference of your policy, whereby the requirement is to set retention period more then 90 days, but i am sure how to processed further with this. can you please help me here. 
{
  "mode": "all",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Sql/servers/auditingSettings"
        },
        {
          "allOf": [
            {
              "field": "Microsoft.Sql/auditingSettings.state",
              "equals": "Enabled"
            },
            {
              "field": "Microsoft.Sql/servers/auditingSettings/retentionDays",
              "equals": 90
            }
          ]
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  },
  "parameters": {}
}{
  "mode": "all",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Sql/servers/auditingSettings"
        },
        {
          "allOf": [
            {
              "field": "Microsoft.Sql/auditingSettings.state",
              "equals": "Enabled"
            },
            {
              "field": "Microsoft.Sql/servers/auditingSettings/retentionDays",
              "equals": 90
            }
          ]
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  },
  "parameters": {}
}

**Comment by klawrie** [comment]
The way I did it was this;
If it's 0, it's compliant, as this means unlimited retention.
If it starts with 9 and is 2 characters, its compliant
If it's any number that includes 3 characters it's compliant.
If it's any number that includes 4 characters it's compliant.

This one is just an audit policy, could be changed to deny as you have it above.

                    "if": {
                        "field": "type",
                        "equals": "Microsoft.Sql/servers"
                    },
                    "then": {
                        "effect": "AuditIfNotExists",
                        "details": {
                            "type": "Microsoft.Sql/servers/auditingSettings",
                            "name": "default",
                            "existenceCondition": {
                                "anyOf": [{
                                        "field": "Microsoft.Sql/servers/auditingSettings/retentionDays",
                                        "match": "0"
                                    },
                                    {
                                        "field": "Microsoft.Sql/servers/auditingSettings/retentionDays",
                                        "match": "9#"
                                    },
                                    {
                                        "field": "Microsoft.Sql/servers/auditingSettings/retentionDays",
                                        "match": "###"
                                    },
                                    {
                                        "field": "Microsoft.Sql/servers/auditingSettings/retentionDays",
                                        "match": "####"
                       }]}}}},

**Comment by abhijay5** [comment]
@klawrie , I have tried the same but i am getting this below error with the same policy which you have created. 

readyState: 4
responseText: {"error":{"code":"InvalidPolicyRule","message":"Failed to parse policy rule: 'Could not find member 'lessThan' on object of type 'LeafExpression'. Path 'lessThan'.'."}}
status: 400
statusText: Bad Request

Policy 



{
	"policyRule": {
		"if": {
			"allOf": [{
					"field": "type",
					"equals": "Microsoft.Insights/logprofiles/default"
				},
				{
					"anyOf": [{

							"field": "Microsoft.Insights/logprofiles/default/retentionPolicy.enabled",
							"equals": "false"
						},
						{
							"field": "Microsoft.Insights/logprofiles[*].retentionPolicy.days",
							"lessThan": "365"
						}
					]
				}
			]
		}
	},
	"then": {
		"effect": "audit"
	}
}

**Comment by abhijay5** [comment]
Can you please share the your policy if you have created any for the same on the email ID abhi_jay5@yahoo.co.in

. 
Bunches of thanks for your help
