### ISSUE TITLE
Alias request: Microsoft.Insights/ActivityLogAlerts

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#151]
Scenario: Need to make sure that activity log alerts remain in place and enabled.
This is required for Azure CIS benchmark section 5
Would need the following;
Microsoft.Insights/ActivityLogAlerts.name
Microsoft.Insights/ActivityLogAlerts[*].enabled
Microsoft.Insights/ActivityLogAlerts[*].allOfcondition.field
Microsoft.Insights/ActivityLogAlerts[*].allOfcondition.equals
Definition:

{
    "policyRule": {
        "if": {
            "allOf": [{
                    "field": "type",
                    "equals": "Microsoft.Insights/ActivityLogAlerts"
                },
                {
                    "field": "Microsoft.Insights/ActivityLogAlerts.name",
                    "equals": "nsgAudit"
                }
            ]
        },
        "then": {
            "effect": "AuditIfNotExists",
            "details": {
                "type": "Microsoft.Insights/ActivityLogAlerts",
                "existenceCondition": {
                    "allOf": [{
                            "field": "Microsoft.Insights/ActivityLogAlerts.allOfcondition.field",
                            "equals": "resourceType"
                        },
                        {
                            "field": "Microsoft.Insights/ActivityLogAlerts.allOfcondition.equals",
                            "equals": "microsoft.network/networksecuritygroups"
                        },
                        {
                            "field": "Microsoft.Insights/ActivityLogAlerts.enabled",
                            "equals": "true"
                        }
      ]}}}}}

**Comment by eladperets** [comment]
Aliases added.

**Comment by abhijay5** [comment]
@klawrie @eladperets , i have the same requirement to follow CIS 5 topics and i have tried to create a same policy mentioned above and i am getting below error. 
readyState: 4
responseText: {"error":{"code":"InvalidPolicyAlias","message":"The policy definition 'e781b9a6-1b65-408f-9c63-d9f9229c4112' rule is invalid. The 'field' property 'Microsoft.Insights/ActivityLogAlerts.name' of the policy rule does not exist as an alias under provider 'Microsoft.Insights'. Please see https://github.com/Azure/azure-policy/blob/master/1-contribution-guide/request-alias.md to request new aliases."}}
status: 400
statusText: Bad Request

**Comment by abhijay5** [comment]
@eladperets Can you please share the alias name , for the above policy. as i am unable to locate the same.

**Comment by eladperets** [comment]
Name is a top-level property that doesn't require an alias. You can access it in the following way:
{
"field": "name",
"equals": "nsgAudit"
}

Elad

**Comment by abhijay5** [comment]
@eladperets , first of Bunches of thanks for your reply. i am not able to created a policy as you have mentioned above, can you please share an example if you have created and which is worked for you.
