### ISSUE TITLE
Alias request: Microsoft.Web/sites/config/httpsOnly

### ISSUE THREAD

**Issue by rikunjpatel** [Azure/azure-policy#152]
**Scenario:**

Need to use Azure Policy to deny creation of WebApp with HTTP only.
WebApp should always be HTTPSONLY, Deny changing to HTTP. 

**Definition:**

{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "field": "name",
          "equals": "web"
        },
        {
          "anyOf": [
            {
              "field": "Microsoft.Web/sites/config/httpsOnly",
              "notEquals": "true"
            }
          ]
        }
      ]
    },
    "then": {
      "effect": "[parameters('effect')]"
    }
  },
  "parameters": {
    "effect": {
      "type": "String",
      "metadata": {
        "displayName": "Effect",
        "description": "Enable or disable the execution of the policy"
      },
      "allowedValues": [
        "Audit",
        "deny",
        "Disabled"
      ],
      "defaultValue": "deny"
    }
  },
  "metadata": {
    "category": "App Service"
  }
}

**Comment by eladperets** [comment]
Can't you use the site's httpsOnly property to achieve this? you can use the following alias: Microsoft.Web/sites/httpsOnly

Elad
