### ISSUE TITLE
Alias Request: Microsoft.ContainerService/managedClusters

### ISSUE THREAD

**Issue by Jath1024** [Azure/azure-policy#153]
Scenario:
Block the creation of AKS cluster:

Definition:
{
    "policyRule": {
        "if": {
                    "field": "type",
                    "in": ["Microsoft.ContainerService/managedClusters"]
        },
        "then": {
            "effect": "deny"
        }
    }
}

**Comment by mentat9** [comment]
Aliases for Microsoft.ContainerService/managedClusters have been added. Note the above policy should work without the aliases anyway, since it's just testing the type field.
