### ISSUE TITLE
Can I write policy on operations like delete resource?

### ISSUE THREAD

**Issue by Maqsoodp** [Azure/azure-policy#156]
Can I write policy on operations like delete resource?

I want to have policy similar to locks to avoid deleting some of my prod resource groups at the same time it should allow me to delete deployment resources which has a hard limit of 800 deployments you have per resource group.

Locks has a issue of applying locks to deployment resource as well. Not letting me delete deployments resouce.

**Comment by pilor** [comment]
Policy is only evaluated on /write operations.  Locks and RBAC are typically the answer to prevent users from performing certain operations all up.  However, I understand what you are describing and why locks might not be a good solution.

We don't have plans to expand policy to /delete at this time but if that changes I'll make sure our documentation gets updated appropriately.

**Comment by taliesins** [comment]
@pilor I think it would be really useful to be able to evaluate policy on delete. Not being able to stop people from deleting something that has been added with an append restricts the usefulness of policies.

Could we please re-open this issue.

**Comment by pilor** [comment]
The best forum for feature requests is the Azure Governance feedback site here:
https://feedback.azure.com/forums/915958-azure-governance

Please open an item there if it doesn't already exist.  If it does exist please upvote it.
