### ISSUE TITLE
Alias Request: Microsoft.Web/serverfarms/aspcount

### ISSUE THREAD

**Issue by arvindmits** [Azure/azure-policy#160]
I want to implement and control ase environment through number of app service plan allowed for particular App service hosting environment. i want to achieve through azure policy

**Comment by mentat9** [comment]
Azure Policy is only able to apply rules to existing properties. There isn't currently any way to perform more complex logic operations during policy evaluation. I'm not able to find a property that counts the number of service plans, so I don't see a way to control this through policy.
