### ISSUE TITLE
Azure policy not re-evaluating policies

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#161]
I am seeing an issue where Azure Policy is not re-evaluating policies when a resource changes. This is in the australiasoutheast region.

I have the below policy that checks for NSG ports open to the internet. The policy correctly reports non-compliant, but on removing the incoming rule, it has failed to re-evaluate for 3 hours so far with no policy related events in the activity log.

The NSG changes are in the activity log, with the correct resource types, e.g ;
    "resourceType": {
        "value": "Microsoft.Network/networkSecurityGroups/securityRules",

Rule:
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Network/networkSecurityGroups/securityRules"
      },{
        "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange",
        "equals": "1433"
      },{
        "field": "Microsoft.Network/networkSecurityGroups/securityRules/access",
        "equals": "Allow"
      },{
        "field": "Microsoft.Network/networkSecurityGroups/securityRules/direction",
        "equals": "Inbound"
      },{
        "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceApplicationSecurityGroups[*]",
        "notContainsKey": "Id"
      },{
        "anyOf": [
          {
            "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix",
            "equals": "*"
          },{
            "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix",
            "equals": "Internet"
          }]}]},
  "then": {
    "effect": "audit"
  }}

**Comment by klawrie** [comment]
The problem also exists with configuration changes to 'Microsoft.Compute/virtualMachines/extensions', and 'Microsoft.Network/virtualNetworks'. I expect that the 24 hour policy re-scan will pick them up, but changes are not being identified before then.

**Comment by cemheren** [comment]
Hi, can you please share the Policy Assignment Id and a timestamp that you've altered the assignment/definition?

**Comment by klawrie** [comment]
Hi, 'initiative' assignment ID for these NSG rules is;  '/subscriptions/a7a50bed-20a1-4a15-8035-ef88c8860092/providers/Microsoft.Authorization/policyAssignments/CISFoundation-6Networking-assignment'

One of the associated policy definition IDs is; /subscriptions/a7a50bed-20a1-4a15-8035-ef88c8860092/providers/Microsoft.Authorization/policyDefinitions/cis-level1-audit-601-def

This was updated to be compliant at 10:42am '2018-08-13T00:42:53.0876043Z', with the deletion of 3 incoming NSG rules.

These Azure Policy rules did become compliant sometime between 5 and 7 hours later.

**Comment by cemheren** [comment]
So the problem is not appearing anymore? 5-7 might be normal depending on your subscription size. Processing all the items take time.

**Comment by klawrie** [comment]
This specific issue has gone away and these policies are now being evaluated immediately and compliance/non-compliance displayed correctly after 1 hour. Event Grid and Activity log were not functioning correctly around this time, so this may have been related.
