### ISSUE TITLE
Using Azure SQL DB networking aliases

### ISSUE THREAD

**Issue by travisnielsen** [Azure/azure-policy#162]
The following aliases have recently been created for controlling networking options for Azure SQL DB:
```
Microsoft.Sql/servers/virtualNetworkRules/virtualNetworkSubnetId
Microsoft.Sql/servers/virtualNetworkRules/ignoreMissingVnetServiceEndpoint
Microsoft.Sql/servers/firewallRules/startIpAddress
Microsoft.Sql/servers/firewallRules/endIpAddress
```
I'm looking for guidance on how these can actually be used in a scenario where:
- Network access is restricted to a specific subnet(s) in a VNET
- Access from certain IP addresses must be whitelisted (default deny)

The structure of the network ACL aliases and in the ARM API is very different than other services like Azure Storage and Key Vault. Also, none of the aliases seem to include support for arrays: [*].

I'm looking to understand how these aliases are intended to be used.

**Comment by pilor** [comment]
These articles cover how [virtualNetworkRules](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-vnet-service-endpoint-rule-overview) and [firewallRules](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-firewall-configure) are used in SQL.

Everything is deny by default for SQL so you don't have to worry about enforcing that through policy.

What would work well through policy is auditing if a certain vnet rule (or firewall rule) does not exist to ensure expected incoming traffic will function correctly.  I've created two sample policies that achieve that:
https://github.com/Azure/azure-policy/tree/master/samples/SQL/audit-sql-server-firewall-rule
https://github.com/Azure/azure-policy/tree/master/samples/SQL/audit-sql-server-vnet-rule

**Comment by jabbera** [comment]
@pilor What if I have a list of single addresses I need to add and want to ensure that no other addresses are added? I can't seem to determine how to do that.
