### ISSUE TITLE
Policies failing when deployed to multi-subscription tenant. 

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#166]
Hi,
I have created a deployment with 92 Azure Policy definitions, 9 definition sets, and 9 assignments.
These policies work as expected when I deploy to my test tenant which has one subscription.
But when I deploy the same ARM template to the development environment, that has two subscriptions, some policies work and others don't.

Policies that work correctly evaluate tags on resource types 'Microsoft.Storage/storageAccounts', Microsoft.Compute/virtualMachines, and 'Microsoft.Network/networkSecurityGroups' work correctly

The policies that don't work, and there are 35 of them, evaluate tags on resource groups;
{"policyRule": {
      "if": {
        "allOf": [ {
            "field": "type",
            "equals": "Microsoft.Resources/subscriptions/resourceGroups"
          },{
            "field": "tags.tcs:extensions:compliance:cis:v1_0_0:section:2",
            "contains": "02.02.00"
          }]},
      "then": {
        "effect": "audit"
      } },
    "parameters": {},
    "mode": "all",
    "metadata": {
      "category": "Section2"
    } }

When changing these resource group tags, the Activity log correctly shows the evaluation with an 'Update resource group' event, that has a 'Audit' child event, with properties.policies correctly listing all of the tags based policies that should be turned to non-compliant. 

But event after 24 hours, all policies like the one above incorrectly remain compliant.

With the built-in policies created by Security-Centre, there are 134 policies in the subscription.

**Comment by cemheren** [comment]
Hi, can you please share the subscription Id?

**Comment by klawrie** [comment]
Subscription Id is;

a7a50bed-20a1-4a15-8035-ef88c8860092

On 18 Aug 2018, at 8:09 am, Akif Cem Heren <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, can you please share the subscription Id?

**Comment by cemheren** [comment]
This is odd, but your subscription seems so be not registered for Microsoft.Resources. 
Can you try manually registering it? 

Here is the related documentation: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-supported-services

**Comment by klawrie** [comment]
I have tried to register Microsoft.Resources in the subscription portal under resource providers. I get a 'Register' event with operation type 'microsoft.resources/register/action' in the Activity log with status 'Succeeded'
But Microsoft.Resources s still unregistered after 30 minutes.
I tried in powershell - 'Register-AzureRmResourceProvider -ProviderNamespace Microsof
t.Resources -Debug'

 There is quite a bit or output that looks successful, no error messages, but the last line of the output is;
  "registrationState": "NotRegistered"

**Comment by cemheren** [comment]
Update, we found the source of the problem, but the fix might take some time. It's related to the Quota that your subscription belongs to. (I'm deliberately refraining from giving more details since this is public). Short term you may change your Quota so something else, or use another subscription. 

If you don't know how to change the subscription Quota please create an Azure ticket and they can help.

**Comment by cemheren** [comment]
Closing the issue since we moved to internal discussion.
