### ISSUE TITLE
Alias request: Microsoft.Network/applicationGateways/webApplicationFirewallConfiguration.ruleSetVersion

### ISSUE THREAD

**Issue by simarley** [Azure/azure-policy#167]
Scenario

Need policy to check the version of the WAF rule set used

{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Network/applicationGateways"
        },
        {
          "field": "Microsoft.Network/applicationGateways/webApplicationFirewallConfiguration.ruleSetVersion",
          "notEquals": "3.0"
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  }

**Comment by mentat9** [comment]
This alias has been added: please give it a try.
