### ISSUE TITLE
Alias request: Microsoft.Network/applicationGateways/SslPolicy.PolicyName

### ISSUE THREAD

**Issue by simarley** [Azure/azure-policy#168]
Scenario

Policy to audit Application Gateway SslPolicy.PolicyName

Definition

"policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Network/applicationGateways"
        },
        {
          "field": "Microsoft.Network/applicationGateways/SslPolicy.PolicyName",
          "notEquals": "AppGwSslPolicy20170401"
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  }

**Comment by aarsan** [comment]
Any updates on this? Is this on the roadmap?

**Comment by eladperets** [comment]
Hi, This is still WIP. Adding aliases to network resources takes longer that other resource providers. I'll try to expedite it, but I can't give an ETA.

Elad

**Comment by mentat9** [comment]
This alias has been added: please give it a try.
