### ISSUE TITLE
Alias request: Microsoft.Storage/storageAccounts/kind

### ISSUE THREAD

**Issue by kse001** [Azure/azure-policy#169]
**Scenario**

Want to be able to require storage accounts to be V2 when deployed

**Definition**

{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Storage/storageAccounts"
        },
        {
          "field": "Microsoft.Storage/storageAccounts/kind",
          "notEquals": "StorageV2"
        }
      ]
    },
    "then": {
      "effect": "Deny"
    }
  }
}

**Comment by mentat9** [comment]
You can already write such a rule. Try this:
```
{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Storage/storageAccounts"
        },
        {
          "field": "kind",
          "notEquals": "StorageV2"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }
}
```
