### ISSUE TITLE
Alias request: Microsoft.Compute/virtualMachines/storageProfile.osDisk.managedDisk.storageAccountType

### ISSUE THREAD

**Issue by vijaynar** [Azure/azure-policy#171]
Scenario : Need to audit that all Virtual Machine OS Disks are using premium disk.
Definition :
{
"if": {
"allOf": [
{
"field": "type",
"equals": "Microsoft.Compute/virtualMachines"
},
{
"field": "Microsoft.Compute/virtualMachines/storageProfile.osDisk.managedDisk.storageAccountType",
"equals": ""
}
]
},
"then": {
"effect": "audit"
}
}

**Comment by eladperets** [comment]
Added Microsoft.Compute/virtualMachines/storageProfile.osDisk.managedDisk.storageAccountType.

Elad
