### ISSUE TITLE
Alias support to limit disk size

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-policy#181]
**Scenario**
Suppose a service needs a P10 disk. That's $21.51 per month, no problem. But a P50 disk is $540.68 per month, and it absolutely *IS* a problem to leave that kind of usage unchecked.

This kind of scenario is of course exactly what Azure Policy is for. However, I can't find a way to restrict the disk size using Azure Policy. Looking at the results of az provider show --namespace Microsoft.Compute --expand "resourceTypes/aliases" --query "resourceTypes[].aliases[].name", the only Managed Disk property I can apply policy to is the sku.name, which doesn't help me.

I would like to be able to restrict a subscription or RG to a max P10 disk (say). This should apply to both standalone disks and disks created implicitly when creating a VM.

**Definition**
Microsoft--you're the Azure experts, so I trust you will validate exactly what aliases are required to meet the scenario. It's a little complicated, given the various places disk size might be specified (in the disk, or in the VM when creating either OS disks or data disks implicitly, and also considering VM Scale Sets).

I _think_ we need aliases for:

- Microsoft.Compute/disks/properties.diskSizeGB
- Microsoft.Compute/virtualMachines/properties.storageProfile.osDisk.diskSizeGB
- Microsoft.Compute/virtualMachines/properties.storageProfile.dataDisks.diskSizeGB
- Microsoft.Compute/virtualMachineScaleSets/properties.virtualMachineProfile.storageProfile.dataDisks.diskSizeGB
- Microsoft.Compute/virtualMachineScaleSets/virtualMachines/properties.storageProfile.osDisk.diskSizeGB
- Microsoft.Compute/virtualMachineScaleSets/virtualMachines/properties.storageProfile.dataDisks.diskSizeGB

Please check I didn't miss anything!

Given the complexity, an example policy or built-in policy showing correct usage would also be very useful.

**Comment by lpassig** [comment]
Hi @satyavel, we also need this alias! We need to enforce gonvernance/compliance for a customer to reduce a potential blast radius, finacially speaking. If some malicous admin or hacker sets up multiple P80   Disks its getting pricy real quick.
