### ISSUE TITLE
Alias request: "Microsoft.Resources/links/id"

### ISSUE THREAD

**Issue by vijaynar** [Azure/azure-policy#183]
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Compute/virtualMachines"
      },
      {
        "field": "Microsoft.Compute/virtualMachines/osDisk.uri",
        "exists": "False"
      },
      {
        "field": "name",
        "equals": "policy-3"
      }
    ]
  },
  "then": {
    "effect": "deployIfNotExists",
    "details": {
      "resourceGroupName": "[parameters('targetResourceGroupName')]",
      "type": "Microsoft.Resources/links",
      "existenceScope": "Subscription",
      "existenceCondition": {
        "field": "id",
        "like": "ASR-Protect-*"
      },

**Comment by mentat9** [comment]
You can access the link id without an alias. Microsoft.Resources/links only has sourceId, targetId and notes properties. All three of those have been added. Please give your scenario a try.
