### ISSUE TITLE
Alias request: Microsoft.Web/sites/config/ftpsState

### ISSUE THREAD

**Issue by YuHe18** [Azure/azure-policy#190]
****Scenario****
We need to use Azure Policy to deny app services with both FTP and FTPS enabled. We want users only to be able to choose between FTPS Only and Disable.
****Definition****
{
  "parameters": {},
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "field": "Microsoft.Web/sites/config/ftpsState",
          "equals": "AllAllowed"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }
}

**Comment by mkpkmkpk** [comment]
+1

**Comment by simarley** [comment]
+1

**Comment by mentat9** [comment]
The alias for this property has been added (along with the rest of Microsoft.Web/sites/config/*). Please give it a try.

**Comment by mentat9** [comment]
Hi @YuHe18:

That behavior is somewhat unexpected, since normally an append policy would not work to modify an existing property. It appears to work in this case because Microsoft.Web accepts partial PUTs and the clients use this. The PUT used to create a new site does not include the config/ftpsState property, so policy is ineffective.

I've outlined an approach here that should do what you want. Let me know if you get it working. Unfortunately, it's a little complex and requires 3 policies. The append and deny policies don't conflict: the policy engine evaluates the append policy first, then the deny policy.

This append policy covers the case where an existing site has the wrong value.
```
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Web/sites/config"
      },
      {
        "field": "Microsoft.Web/sites/config/ftpsState",
        "exists": "False"
      }
    ]
  },
  "then": {
    "effect": "append",
    "details": [
      {
        "field": "Microsoft.Web/sites/config/ftpsState",
        "value": "FtpsOnly"
      }
    ]
  }
}
```
This one prevents someone updating an existing site config to set the undesired value:
```
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Web/sites/config"
      },
      {
        "anyOf": [
          {
            "field": "Microsoft.Web/sites/config/ftpsState",
            "exists": "False"
          },
          {
            "field": "Microsoft.Web/sites/config/ftpsState",
            "equals": "AllAllowed"
          }
        ]
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}
```
Finally, a deployIfNotExists policy is needed to ensure a newly created site gets the right config value as it's created. I don't have a working sample for you, but this is a working auditIfNotExists policy.
```
{
  "if": {
    "field": "type",
    "equals": "Microsoft.Web/sites"
  },
  "then": {
    "effect": "auditIfNotExists",
    "details": {
      "type": "Microsoft.Web/sites/config",
      "name": "web",
      "existenceCondition": {
        "anyOf": [
          {
            "field": "Microsoft.Web/sites/config/ftpsState",
            "exists": "True"
          },
          {
            "field": "Microsoft.Web/sites/config/ftpsState",
            "equals": "ftpsOnly"
          }
        ],
        "allOf": [
          {
            "field": "Microsoft.Web/sites/config/ftpsState",
            "exists": "True"
          },
          {
            "field": "Microsoft.Web/sites/config/ftpsState",
            "equals": "ftpsOnly"
          }
        ]
      }
    }
  }
}
```
If you convert this to a deployIfNotExists policy, it should force the property to have the correct value.

**Comment by darkweb-123** [comment]
I have used the same policy for an azure function app to update to FTPS . not working @mentat9  @YuHe18  any idea on this. pasting my policy here
"policyRule": {
      "if": {
        "anyOf": [
          {
            "allOf": [
              {
                "field": "type",
                "equals": "Microsoft.Web/sites/config"
              },
              {
                "field": "Microsoft.Web/sites/config/ftpsState",
                "exists": "False"
              }
            ]
          },
          {
            "allOf": [
              {
                "field": "type",
                "equals": "Microsoft.Web/sites/config"
              },
              {
                "field": "Microsoft.Web/sites/config/ftpsState",
                "equals": "AllAllowed"
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "append",
        "details": [
          {
            "field": "Microsoft.Web/sites/config/ftpsState",
            "value": "FtpsOnly"
          }
        ]
      }
    }
  }

**Comment by CodeThePlanet** [comment]
@darkweb-123  working on something similar and made some progress here. Instead of "Microsoft.Web/sites/config/ftpState" use "Microsoft.Web/sites/siteConfig.ftpState". 

The append policy seems to be working as long as ftpState isn't already set. But that could be more about my parameters. I'll update if I make more progress.

**Comment by darkweb-123** [comment]
@CodeThePlanet  i have created a policy which would do the same . have a look in to this and let me knw if this is not working .

    "policyRule": {
      "if": {
        "field": "type",
        "equals": "Microsoft.Web/sites"
      },
      "then": {
        "effect": "deployIfNotExists",
        "details": {
          "type": "Microsoft.Web/sites/config",
          "existenceCondition": {
            "field": "Microsoft.Web/sites/config/ftpsState",
            "in": [
              "FtpsOnly",
              "Disabled"
            ]
          },
          "deployment": {
            "properties": {
              "mode": "incremental",
              "template": {
                "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                "contentVersion": "1.0.0.0",
                "parameters": {
                  "sitename": {
                    "type": "string"
                  }
                },
                "resources": [
                  {
                    "type": "Microsoft.Web/sites/config",
                    "name": "[concat(parameters('sitename'), '/web')]",
                    "apiVersion": "2018-11-01",
                    "properties": {
                      "ftpsState": "FtpsOnly"
                    }
                  }
                ]
              },
              "parameters": {
                "sitename": {
                  "value": "[field('name')]"
                }
              }
            }
          }
        }
      }
    }
  }

**Comment by CodeThePlanet** [comment]
@darkweb-123 so far it works like a charm! Thanks for the reply!

**Comment by darkweb-123** [comment]
@CodeThePlanet - Any idea on how to create an policy which would update web app http to https .
I'm stuck here . Not sure why is my policy not working properly.

{
  "policyType": "Custom",
  "mode": "All",
  "displayName": "UPDATE WEB APP HTTP - HTTPS",
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Web/sites"
    },
    "then": {
      "effect": "deployIfNotExists",
      "details": {
        "type": "Microsoft.Web/sites",
        "name": "web",
        "existenceCondition": {
          "field": "Microsoft.Web/sites/httpsOnly",
          "equals": "true"
        },
        "deployment": {
          "properties": {
            "mode": "incremental",
            "template": {
              "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
              "contentVersion": "1.0.0.0",
              "parameters": {
                "sitename": {
                  "type": "string"
                }
              },
              "resources": [
                {
                  "type": "Microsoft.Web/sites",
                  "name": "[concat(parameters('sitename'), '/web')]",
                  "apiVersion": "2018-11-01",
                  "properties": {
                    "httpsOnly": "true"
                  }
                }
              ]
            },
            "parameters": {
              "sitename": {
                "value": "[field('name')]"
              }
            }
          }
        }

**Comment by wendlandreas** [comment]
> @CodeThePlanet - Any idea on how to create an policy which would update web app http to https . I'm stuck here . Not sure why is my policy not working properly.
> 
> { "policyType": "Custom", "mode": "All", "displayName": "UPDATE WEB APP HTTP - HTTPS", "policyRule": { "if": { "field": "type", "equals": "Microsoft.Web/sites" }, "then": { "effect": "deployIfNotExists", "details": { "type": "Microsoft.Web/sites", "name": "web", "existenceCondition": { "field": "Microsoft.Web/sites/httpsOnly", "equals": "true" }, "deployment": { "properties": { "mode": "incremental", "template": { "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#", "contentVersion": "1.0.0.0", "parameters": { "sitename": { "type": "string" } }, "resources": [ { "type": "Microsoft.Web/sites", "name": "[concat(parameters('sitename'), '/web')]", "apiVersion": "2018-11-01", "properties": { "httpsOnly": "true" } } ] }, "parameters": { "sitename": { "value": "[field('name')]" } } } }

The "name" of the resource in the deployment template should be
`"name": "[parameters('sitename')]",` (without the '/web'.

**Comment by wendlandreas** [comment]
@mentat9 I am facing the following issue:
I have 2 "deployIfNotExists" policies, one that sets Microsoft.Web/sites/httpsOnly to true ("incremental" deployment), the other sets Microsoft.Web/sites/config/minTlsVersion to 1.2.
The first rule for httpsOnly works fine, anytime someone sets this httpsOnly to false it is changed back to true by the policy a couple of minutes later.
The second policy for minTlsVersion is giving me some troubles. When I manually create a remediation task it works fine and sets the property to 1.2. However, when I manually change it to 1.0 or 1.1 the deployment is never triggered.
Funnily, when additionally I set httpsOnly to false both deployments are triggered.

Is it possible that changes to Microsoft.Web/sites/config don't trigger the policy deployments?

**Comment by lm-gh-01** [comment]
HI 
How to apply same to the slots 
what type expression should be?
