### ISSUE TITLE
Alias request: Microsoft.Web/sites/slots/httpsOnly

### ISSUE THREAD

**Issue by YuHe18** [Azure/azure-policy#191]
****Scenario****
We need to use Azure Policy to deny slots of app services with HTTPS Only off. We want all the slots in the subscription with HTTPS Only turned on. The current supported alias of HTTPS Only for web/sites does not cover the slots.
****Definition****
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Web/sites/slots"
      },
      {
        "field": "Microsoft.Web/sites/slots/httpsOnly",
        "equals": "false"
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}

**Comment by mkpkmkpk** [comment]
+1

**Comment by simarley** [comment]
+1

**Comment by trolleyboy** [comment]
+1

**Comment by mentat9** [comment]
Alias has been added. Please give it a try.
