### ISSUE TITLE
Alias request: Microsoft.Web/sites/slots/config/minTlsVersion

### ISSUE THREAD

**Issue by YuHe18** [Azure/azure-policy#192]
****Scenario****
We need to use Azure Policy to deny slots of app services with TLS version less than 1.2. The current supported alias of minTlsVersion for web/sites does not cover the slots.
****Definition****
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Web/sites/slots/config"
      },
      {
        "field": "Microsoft.Web/sites/slots/config/minTlsVersion",
        "notEquals": "1.2"
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}

**Comment by simarley** [comment]
Also waiting for this one.

**Comment by trolleyboy** [comment]
+1

**Comment by mentat9** [comment]
Alias has been added: please try it out.

**Comment by YuHe18** [comment]
> Alias has been added: please try it out.
Hi, was the alias given a new name? I found six alias added for web slots and there is no one named minTlsVersion or ftpsState(this alias was requested in #193 ). The ones I found are: Microsoft.Web/sites/slots/availabilityState,  Microsoft.Web/sites/slots/clientCertEnabled, Microsoft.Web/sites/slots/hostNames[*], Microsoft.Web/sites/slots/hostNameSslStates[*].name, Microsoft.Web/sites/slots/httpsOnly,  Microsoft.Web/sites/slots/serverFarmId, Microsoft.Web/sites/slots/usageState.

**Comment by mentat9** [comment]
Sorry, this was closed by mistake. Alias has not been added yet.

**Comment by mentat9** [comment]
Alias has now been added: please give your scenario a try.
