### ISSUE TITLE
Alias request: Microsoft.Web/sites/slots/config/ftpsState

### ISSUE THREAD

**Issue by YuHe18** [Azure/azure-policy#193]
****Scenario****
We need to use Azure Policy to deny slots of app services with both FTP and FTPS enabled. We want users only to be able to choose between FTPS Only and Disable.
****Definition****
{
  "parameters": {},
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/slots/config"
        },
        {
          "field": "Microsoft.Web/sites/slots/config/ftpsState",
          "equals": "AllAllowed"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }
}

**Comment by trolleyboy** [comment]
+1

**Comment by mentat9** [comment]
Alias has been added: please try it out.

**Comment by mentat9** [comment]
Sorry, this was closed by mistake. Alias has not been added yet.

**Comment by mentat9** [comment]
Alias has now been added: please give your scenario a try.
