### ISSUE TITLE
Alias request: Microsoft.Compute/disks/encryptionSettings

### ISSUE THREAD

**Issue by cleibl** [Azure/azure-policy#195]
**Scenario**
We need to use Azure Policy to deny creating data disks without encryption.  I see an alias has already been created for OS disk on VMs.   

"Microsoft.Compute/virtualMachines/storageProfile.osDisk.encryptionSettings",
"Microsoft.Compute/virtualMachines/storageProfile.osDisk.encryptionSettings.enabled",

**Definition**
{
"parameters": {},
"policyRule": {
"if": {
"allOf": [
{
"field": "type",
"equals": "Microsoft.Compute/disks"
},
{
"field": "Microsoft.Compute/disks/encryptionSettings.enabled",
"notequals": "true"
}
]
},
"then": {
"effect": "deny"
}
}
}

**Comment by mentat9** [comment]
These aliases have been added. Please give them a try.
