### ISSUE TITLE
Alias Request: Microsoft.Cache/Redis/subnetID

### ISSUE THREAD

**Issue by cleibl** [Azure/azure-policy#199]
### Scenario

We need the ability to enforce that a Redis Cache be created in a VNET/Subnet

### Definition
{
   "if": {
     "allOf": [
           {
            "field": "type",
            "equals": "Microsoft.Cache/Redis"
           },
           {
            "field": "Microsoft.Cache/Redis/subnetID",
            "exists": false
           }
         ]
       },
   "then": {
      "effect": "deny"
   }
}

**Comment by mentat9** [comment]
All aliases for Microsoft.Cache/Redis have been added. Please give these a try.
