### ISSUE TITLE
The policy 'effect' property value cannot be 'DeployIfNotExists'.

### ISSUE THREAD

**Issue by averkinderen** [Azure/azure-policy#20]
Deploy if not exist doesnt work with the given example for network watcher

New-AzureRmPolicyDefinition : InvalidPolicyRuleEffect : The policy definition 'deploy-NW-in-vnet-regions' rule is invalid. The policy 'effect' property value cannot be 'DeployIfNotExists'.
At line:1 char:15
+ ... efinition = New-AzureRmPolicyDefinition -Name "deploy-NW-in-vnet-regi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmPolicyDefinition], ErrorResponseMessageException
    + FullyQualifiedErrorId : InvalidPolicyRuleEffect,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzurePolicyDefinitionCmdlet

Any idea what to do ?

**Comment by krnese** [comment]
We currently don't support "deployIfNotExists" for custom policies, only built-in policies provided by Microsoft directly.

**Comment by nicholasmhughes** [comment]
@krnese is there a timeline for support of this effect in custom policies?

**Comment by DCtheGeek** [comment]
For anyone finding this old issue via search, **deployIfNotExists** for custom policies has been supported for a while: https://docs.microsoft.com/azure/governance/policy/concepts/effects#deployifnotexists
