### ISSUE TITLE
The deploy-network-watcher-in-vnet-regions policy does not deploy

### ISSUE THREAD

**Issue by jcwrights** [Azure/azure-policy#201]
When I attempt to deploy this policy through the Azure portal or through the CLI, I first get this error message:

**readyState: 4
responseText: {"error":{"code":"InvalidPolicyRuleEffect","message":"The policy definition '443ea2ce-b09f-4225-bd68-97706398f051' rule is invalid. The policy 'effect' property value cannot be 'deployIfNotExists'."}}
status: 400
statusText: Bad Request**

If I change the 'deployIfNotExists' property to something else, such as 'append', I then get the following error:

**readyState: 4
responseText: {"error":{"code":"InvalidPolicyRule","message":"Failed to parse policy rule: 'Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'Microsoft.WindowsAzure.ResourceStack.Providers.Authorization.Data.Schema.AppendDetails[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath 'type'.'."}}
status: 400
statusText: Bad Request**

Please let me know what I am missing.  Thanks.

**Comment by pilor** [comment]
deployIfNotExists policies are not available for custom policy definitions yet.  They are only supported in built-in policy definitions (that example is already a built-in policy that you should see in your environment).

This will be changing very soon (~2 weeks) at which point you will be able to create your own custom deployIfNotExists policies.  Look for documentation updates here when that happens:
https://docs.microsoft.com/en-us/azure/azure-policy/policy-effects#deployifnotexists
