### ISSUE TITLE
Alias Request: Microsoft.DataLakeStore/accounts/newTier

### ISSUE THREAD

**Issue by franzoir** [Azure/azure-policy#203]
Scenario: 
We want to use Azure Policy to deny creation of specific Data Lake Store tiers. 
Ex. Deny all tiers except for "Consumption", "Commitment_1TB"

Definition: 
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "Microsoft.DataLakeStore/accounts"
            },
            {
                "not": {
                    "field": "Microsoft.DataLakeStore/accounts/newTier.sku",
                    "in": [
                        "Consumption",
                        "Commitment_1TB"
                    ]
                }
            }
        ]
    },
    "then": {
        "effect": "deny"
    }

**Comment by mentat9** [comment]
I've added the ```Microsoft.DataLakeStore/accounts/newTier``` alias. There isn't actually a newTier.sku field. The newTier field itself is an enum that allows the various values, so you can test it directly.

**Comment by franzoir** [comment]
> I've added the `Microsoft.DataLakeStore/accounts/newTier` alias. There isn't actually a newTier.sku field. The newTier field itself is an enum that allows the various values, so you can test it directly.

thank you !
