### ISSUE TITLE
Feature request: Need to be able to manage "Microsoft.Web/sites/config/authSettings"

### ISSUE THREAD

**Issue by haschdl** [Azure/azure-policy#207]
**Scenario**
We have a large number of app services and we would like to audit instances without Azure Authentication enabled. 

**Note** this is not the same as `Microsoft.Web/sites/config/siteAuthEnabled`, which gives only if authentication is enable for the app service, and not what kind of authentication method is used.

**Definition**

``` JSON

{
  "mode": "all",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "not": {
            "field": "Microsoft.Web/sites/config/authSettings.defaultProvider",
            "equals": "AzureActiveDirectory"
          }
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {}
}

```

**Comment by mkpkmkpk** [comment]
+1

**Comment by haschdl** [comment]
Hello @mentat9 I’m aware this is not supported, this is why the issue was open in the first place, to request the feature. Why is the issue closed?

**Comment by mentat9** [comment]
Sorry about that. This shouldn't stay open as an alias request. I closed it because we don't create aliases for fields that can't be managed by policy. I'll reopen it and change it to a feature request.

**Comment by mentat9** [comment]
For reference, this is the same issue as https://github.com/Azure/azure-policy/issues/264.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
