### ISSUE TITLE
New Alias "Microsoft.Resources/subscriptions/resourceGroups.id"

### ISSUE THREAD

**Issue by spmsaj** [Azure/azure-policy#208]
ex:
if": {     
                "allOf": [
                    {   
                        "field": "type", 
                        "equals": "Microsoft.Resources/subscriptions/resourceGroups"
                    },  
                    {   
                        "field": "Microsoft.Resources/subscriptions/resourceGroups.id",
                        "contains": "some value to search"
                    }
                 
                ]
    }

**Comment by pilor** [comment]
what part of the ID are you trying to search?  The name and type are already exposed so the only thing not present would be the subscription ID itself.

**Comment by spmsaj** [comment]
Hi, If you look at the subject line, I am looking for resourcegroups.id alias (not subscription id). Which is not present in the alias list when I did a az cli search. If I am wrong, please show me the command to display aliases that contains this. In fact I do not see anything associated with resourceGroups.
Also, if resourcegroup name is exposed, what is the alias I should use for it and please provide a rest api command where I can query the alias to display name.
Sandhya Job
Cloud Services (Automation)
214-529-3252

**Comment by pilor** [comment]
There are a set of fields (including "name" and "type") that are exposed on every resource.  They don't require aliases for you to access them.  The list is in our documentation here:
https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#fields

An example policy that would deny the creation of any resource group that didn't have a name starting with "rgPrefix" is:
```
{
   "mode": "All",
   "policyRule": {
      "if": {
         "allOf": [
            {
               "field": "type",
               "equals": "Microsoft.Resources/subscriptions/resourceGroups"
            },
            {
               "field": "name",
               "notLike": "rgPrefix*"
            }
         ]
      },
      "then": {
         "effect": "deny"
      }
   }
}
```

**Comment by spmsaj** [comment]
Ok, thank you, My question had nothing to do with name, but with id. Is there an alias for id for resourcegroup?

But nevertheless, let me try this one on a test policy. Please do not close the github issue before your customers verify it.

Sandhya Job
Cloud Services (Automation)
214-529-3252
