### ISSUE TITLE
Alias request Microsoft.Compute/VirtualMachines/identity.type

### ISSUE THREAD

**Issue by wilfriedwoivre** [Azure/azure-policy#211]
**Scenario**

Enforce usage of Managed Service Identity for all virtual machines
    
**Definition** 

```json
 "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Compute/virtualMachines"
        },
        {
          "not": {
            "field": "Microsoft.Compute/virtualMachines/identity.type",
            "equals": "SystemAssigned"
          }
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
```

**Comment by pilor** [comment]
You can use "field": "identity.type" for this.  Managed Service Identity is a top-level property that is present on a number of resource types so it is treated as a first-class field similar to "name" and "type".

**Comment by arvindshmicrosoft** [comment]
@pilor could you please clarify how to set (in an 'append' effect) the identity.type only for a VM? I tried using identity.type and unfortunately it ended up getting applied to things like OS Disks which do not support MSI (this therefore ended up failing my VM creation). In other words, in append effect, how do specifically only set the SystemAssigned identity.type? Functionally the equivalent of the below:

 "then": {
            "effect": "append",
            "details": [
               {
                  "field": "Microsoft.Compute/virtualMachines/identity.type",
                  "value": "SystemAssigned"
               }
            ]
         }

**Comment by pilor** [comment]
Your IF statement should contain conditions that define what resources should get the "append" applied to them.

```
"if": 
   {
      "field": "type",
      "equals": "Microsoft.Compute/virtualMachines"
    }
```
