### ISSUE TITLE
Alias Request: Microsoft.Sql/servers/databases/DatabaseProperties.licenseType

### ISSUE THREAD

**Issue by simarley** [Azure/azure-policy#216]
Scenario:

Need to audit/deny usage of Azure SQL Database where the LicenseType is not "LicenseIncluded".

Definition:

{
  "mode": "all",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "in": [
            "Microsoft.Sql/servers/databases"
          ]
        },
        {
          "field": "Microsoft.Sql/servers/databases/DatabaseProperties.licenseType",
          "notEquals": "LicenseIncluded"
        }
      ]
    },
    "then": {
      "effect": "[parameters('effect')]"
    }
  },
  "parameters": {
    "effect": {
      "type": "String",
      "metadata": {
        "displayName": "Effect",
        "description": "The action of the policy"
      },
      "allowedValues": [
        "Audit",
        "Deny"
      ],
      "defaultValue": "Audit"
    }
  }
}

**Comment by mentat9** [comment]
This alias has previously been added. Use it like this: ```Microsoft.Sql/servers/databases/licenseType```. Note: you can use the Get-AzureRmPolicyAlias Powershell cmdlet to query the details of existing aliases.
