### ISSUE TITLE
Alias Request: Microsoft.Sql/managedInstances/ManagedInstanceProperties.licenseType

### ISSUE THREAD

**Issue by simarley** [Azure/azure-policy#217]
Scenario:

Need to audit/deny usage of Azure SQL Managed Instances where the LicenseType is not "LicenseIncluded".

Definition:

{
"mode": "all",
"policyRule": {
"if": {
"allOf": [
{
"field": "type",
"in": [
"Microsoft.Sql/managedInstances"
]
},
{
"field": "Microsoft.Sql/managedInstances/ManagedInstanceProperties.licenseType",
"notEquals": "LicenseIncluded"
}
]
},
"then": {
"effect": "[parameters('effect')]"
}
},
"parameters": {
"effect": {
"type": "String",
"metadata": {
"displayName": "Effect",
"description": "The action of the policy"
},
"allowedValues": [
"Audit",
"Deny"
],
"defaultValue": "Audit"
}
}
}

**Comment by mentat9** [comment]
This alias has been added. Use it like this: ```Microsoft.Sql/managedInstances/licenseType```.
