### ISSUE TITLE
Alias Request: Microsoft.Sql/servers/databases.Name

### ISSUE THREAD

**Issue by simarley** [Azure/azure-policy#218]
Scenario:

Currently the built-in policy definition "Audit transparent data encryption status" does not exclude the master database which can't have TDE enabled on. This puts all the master databases out of compliance. Suggest adding this to the policy but to enable this the alias needs adding.

Definition:

{
  "mode": "indexed",
  "policyRule": {
    "if": {
     "allOf": [
    {
      "field": "type",
      "equals": "Microsoft.Sql/servers/databases"
    },
    {
      "field": "Microsoft.Sql/servers/databases.Name",
      "notEquals": "master"
    }
     ]
    },
    "then": {
      "effect": "AuditIfNotExists",
      "details": {
        "type": "Microsoft.Sql/servers/databases/transparentDataEncryption",
        "name": "current",
        "existenceCondition": {
          "allOf": [
            {
              "field": "Microsoft.Sql/transparentDataEncryption.status",
              "equals": "enabled"
            }
          ]
        }
      }
    }
  },
  "parameters": {}
}

**Comment by pilor** [comment]
"name" is a top-level field that can be accessed directly.  You can write your policy using:

```
{
"field": "name",
"notEquals": "master"
}
```
