### ISSUE TITLE
Policy Initiative Assignment created from PowerShell cannot be edited in the Portal

### ISSUE THREAD

**Issue by laughtonsm** [Azure/azure-policy#22]
I am using the examples to create a policy initiative, and then assign this to a subscription.  Upon doing so, I am able to view the configuration using Powershell, however, when viewing in the portal, you get a 'broken' Azure blade (Dark cloud with raindrop).  If I create the same assignment via the portal, this works fine.  I can see that by using powershell, there are some properties missing - i.e. metadata, and notScopes (the latter is actually an array with a count of zero in the configuration via the portal)

Any ideas why this might be?

**Comment by bennbatt8112** [comment]
Hey laughtonsm,

This is not necessarily a solution, but _could_ be a short term fix if you're experiencing GUI Issues.
Sometimes when working with preview features, I've run into random rain clouds and apparent bugs. 
You should have something in your URL like:
https://portal.azure.com/#resource/subscriptions/...
 
As a test you can change the URL to the following:
https://portal.azure.com/?feature.customportal=false/#resource/subscription/...

This has gotten me around a handful of issues in the past and is worth a try. Doesn't speak much to the root issue though.

**Comment by cyl33922072** [comment]
Which UI is broken? Do you go the new policy center?

**Comment by pilor** [comment]
The legacy policy experience in the Resource Group and Subscription blades has been replaced with the new Policy Portal experience.  You should now be able to interact with your initiatives (and all other policy resources) correctly regardless of where you enter the policy experience in the UX.
