### ISSUE TITLE
The built-in Azure Policy "Audit transparent data encryption status" doesn't exclude the master database

### ISSUE THREAD

**Issue by GaryStrange** [Azure/azure-policy#220]
Hi,

I've kind of assumed that the engineers maintaining this repo are also responsible for the Azure built-in policies.

We have assigned "Audit transparent data encryption status" to our subscriptions and the reports include many instances of the master database non-compliances. Can you fix the built-in policy to exclude checking the master database? I'm aware exclusions are possible at assignment time. However, I don't see the option to exclude all databases called master.

Thanks,
Gary

**Comment by simarley** [comment]
It may not be obvious by the title but I have referenced this in #218 and this was the reason for requesting the alias for the database name, so we can filter out master dbs not only in the defaults but in custom policies as required. Thanks!

**Comment by pilor** [comment]
The SQL DB built-ins have been updated to exclude the "master" DB.

**Comment by GaryStrange** [comment]
Thanks
