### ISSUE TITLE
Policies that apply to NSG Rules can be circumvented by deploying the NSG Rules as part of an NSG

### ISSUE THREAD

**Issue by koppek** [Azure/azure-policy#222]
I have the following policy that denies NSG Rules that have the destination port set to 22 or * from source *.
{
  "mode": "all",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Network/networkSecurityGroups/securityRules"
        },
        {
          "allOf": [
            {
              "anyOf": [
                {
                  "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange",
                  "in": [
                    "*",
                    "22"
                  ]
                },
                {
                  "not": {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]",
                    "notEquals": "*"
                  }
                }
              ]
            },
            {
              "field": "Microsoft.Network/networkSecurityGroups/securityRules/access",
              "equals": "Allow"
            },
            {
              "anyOf": [
                {
                  "field": "Microsoft.Network/networkSecurityGroups/securityRules/direction",
                  "equals": "Outbound"
                },
                {
                  "field": "Microsoft.Network/networkSecurityGroups/securityRules/direction",
                  "equals": "Inbound"
                }
              ]
            }
          ]
        }
      ]
    },
    "then": {
      "effect": "[parameters('effect')]"
    }
  },
  "parameters": {
    "effect": {
      "type": "String",
      "metadata": {
        "displayName": "Effect",
        "description": "The effect for this policy."
      }
    }
  }
}

**Issue**
While this Policy does ensure that noncompliant NSG Rules aren't created on existing NSGs, it does _not_ ensure that new NSGs aren't created with noncompliant NSG Rules.

**Comment by pilor** [comment]
Networking APIs are more complex than most.  SecurityRules are exposed as a child resource under an NSG as well as an array of rule inside the NSG resource itself.  They can be modified in both places.

Your rule, as you've stated, only covers manipulation of securityRules via their child resource representation.  There are equivalent aliases that let you inspect these values in the [securityRules array within the NSG resource](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networksecuritygroups/networksecuritygroups_createorupdate) (i.e. "Microsoft.Network/networkSecurityGroups/securityRules[*].destinationPortRange").  However, the language will run each clause against the elements in the array individually.  For example, if you have a clause that checks "destinationPortRange" and a clause that checks "direction" they will work but they will independently compare their values against every securityRule in the array.  There isn't currently a way to specify you only want to return true if a single element in the array has both conditions.  

Improvements to handling of these array aliases (anything with [*]) are in the pipeline but may still be a few months out.
