### ISSUE TITLE
Alias request: Microsoft.Cache/Redis/minimumTlsVersion

### ISSUE THREAD

**Issue by chudsonwr** [Azure/azure-policy#226]
**Scenario**

Need to enforce TLS version settings in the policy

**Definition**

{
	"properties": {
		"mode": "all",
		"displayName": "Enforce security settings for Redis cache instances",
		"description": "Ensures SSL is enabled",
		"policyRule": {
			"if": {
				"anyOf": [{
					"allOf": [{
							"field": "type",
							"equals": "Microsoft.Cache/Redis"
						},
						{
							"not": {
								"field": "Microsoft.Cache/Redis/minimumTlsVersion",
								"equals": "1.2"
							}
						}
					]
				}]
			},
			"then": {
				"effect": "deny"
			}
		}
	}
}

**Comment by mentat9** [comment]
All aliases for ```Microsoft.Cache/Redis``` have been added. Please give these a try.
