### ISSUE TITLE
Alias request: "Microsoft.Network/applicationGateways/gatewayIPConfigurations[*].subnet.id

### ISSUE THREAD

**Issue by mike-westaway** [Azure/azure-policy#228]
Create policy statements that ensure application gateways are only created in specific subnets.

**Comment by tcsatheesh** [comment]
I think there is another alias required here for the frontend publicipaddress id.
Definition
{
	"if": {
	   "allOf": [
		  {
			 "field": "type",
			 "equals": "Microsoft.Network/applicationGateways"
		  },
		  {
			 "not": {
				"field": "Microsoft.Network/applicationGateways/frontendIPConfigurations[*].publicIpAddress.id",
				"exists": false
			 }
		  },
		  {
			 "not": {
				"field": "Microsoft.Network/applicationGateways/gatewayIPConfigurations[*].subnet.id",
				"in": "[parameters('subnetIds')]"
			 }
		  }
	   ]
	},
	"then": {
	   "effect": "deny"
	}
 }

**Comment by mentat9** [comment]
This alias has been added: please give it a try.
