### ISSUE TITLE
Alias Request: Microsoft.Authorization/Locks.Level

### ISSUE THREAD

**Issue by AErmie** [Azure/azure-policy#229]
**Scenario**
Enable the ability to create a Policy to audit if Resource Groups labelled with a specific Tag (i.e. "Env:PROD") has a Resource Lock applied to it. 

The challenge with creating a definition for this is that the Resource Lock has a custom name, so we need a wildcard placeholder. 

The [ARM template](https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/locks) shows the Level referenced within the Properties object, but the example of how to use [Aliases in Policies](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#understanding-the--alias) by using the wildcard.property (i.e. [*].property) is not accepted in the Policy.

**Definition**
```
{
  "mode": "all",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Resources/subscriptions/resourceGroups"
        },
        {
          "field": "[concat('tags[', parameters('tagName'), ']')]",
          "equals": "[parameters('tagValue')]"
        },
        {
          "field": "Microsoft.Authorization/locks/[*]/level",
          "equals": "CanNotDelete"
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {
    "tagName": {
      "type": "String",
      "metadata": {
        "displayName": "Tag Name",
        "description": "The Tag namne to audit against (i.e. Environment, CostCenter, etc.)"
      }
    },
    "tagValue": {
      "type": "String",
      "metadata": {
        "displayName": "Tag Value",
        "description": "Value of the tag to audit against (i.e. Prod/UAT/TEST, 12345, etc.)"
      }
    }
  }
}
```

**Comment by abhijay5** [comment]
@AErmie i have tried to create a same policy but i am getting error on the filed (Microsoft.Authorization/locks/[*]/level",)stating that alias doesn't exists . can you please help

**Comment by AErmie** [comment]
Yeah, my approach was wrong. The Azure Policy team helped me out with the correct method to audit the Resource Lock. 
This Alias Request can be closed.

**Comment by abhijay5** [comment]
@AErmie , it would be great help if you can help me or guide me or share your policy on abhi_jay5@yahoo.co.in

**Comment by AErmie** [comment]
Sure. Actually, I have a post coming out on Monday on my blog ([https://adinermie.com/](https://adinermie.com/)) that goes into exactly this (including the code for the policy).

**Comment by abhijay5** [comment]
@AErmie Many Thanks for replying and sharing the information, i will wait for your post on coming Monday.

**Comment by pilor** [comment]
For other's reference the alias for lock level is:
`Microsoft.Authorization/locks/level`
