### ISSUE TITLE
Alias request: Microsoft.Network/networkInterfaces/Primary

### ISSUE THREAD

**Issue by klawrie** [Azure/azure-policy#230]
**Scenario**
We need to be able to audit virtual machines that have secondary network interfaces attached. To do this through PowerShell, the following command achieves this and returns the virtual machine Id.

`Get-AzureRmNetworkInterface | where {$_.Primary -eq $false} | select {$_.VirtualMachine.Id}`

**Definition**
"if": {
      "allOf": [
        {  
          "field": "type",
         "equals": "Microsoft.Network/networkInterfaces"
        },{
          "field": "Microsoft.Network/networkInterfaces/Primary",
          "equals": "False"
       }]
    },
    "then": {
      "effect": "audit"
    }

**Comment by mentat9** [comment]
This alias is now deployed. Please give it a try.
