### ISSUE TITLE
Alias request: Microsoft.Insights/logprofiles/retentionPolicy.enabled

### ISSUE THREAD

**Issue by abhijay5** [Azure/azure-policy#234]
I have tried the same but i am getting this below error with the same policy which you have created.

readyState: 4
responseText: {"error":{"code":"InvalidPolicyRule","message":"Failed to parse policy rule: 'Could not find member 'lessThan' on object of type 'LeafExpression'. Path 'lessThan'.'."}}
status: 400
statusText: Bad Request

Policy

{
"policyRule": {
"if": {
"allOf": [{
"field": "type",
"equals": "Microsoft.Insights/logprofiles/default"
},
{
"anyOf": [{

						"field": "Microsoft.Insights/logprofiles/default/retentionPolicy.enabled",
						"equals": "false"
					},
					{
						"field": "Microsoft.Insights/logprofiles[*].retentionPolicy.days",
						"lessThan": "365"
					}
				]
			}
		]
	}
},
"then": {
	"effect": "audit"
}

**Comment by camillemarie** [comment]
"lessThan" is not supported in policy rules at this time. 

Your rule should work with "notEquals"

**Comment by abhijay5** [comment]
@camillemarie , i have tried this many rules, Equals , contain, match,notMatch, mot equals. as well as mentioned below. but nothing worked, can you please share the sample if you have created any and this is working.  
{
  "mode": "indexed",
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Insights/logprofiles"
    },
    "then": {
      "effect": "[parameters('effect')]",
      "details": {
        "type": "Microsoft.Insights/logprofiles",
        "existenceCondition": {
          "allOf": [
            {
              "field": "Microsoft.Insights/logprofiles/retentionPolicy.enabled",
              "equals": "true"
            },
            {
              "field": "Microsoft.Insights/logprofiles/retentionPolicy.days",
              "equals": "[parameters('requiredRetentionDays')]"
            }
          ]
        }
      }
    }
  },
  "parameters": {
    "effect": {
      "type": "String",
      "metadata": {
        "displayName": "Effect",
        "description": "Enable or disable the execution of the policy"
      },
      "allowedValues": [
        "AuditIfNotExists",
        "Disabled"
      ],
      "defaultValue": "AuditIfNotExists"
    },
    "requiredRetentionDays": {
      "type": "String",
      "metadata": {
        "displayName": "Required retention (days)",
        "description": "The required diagnostic logs retention in days"
      },
      "defaultValue": "365"
    }
  }
}
