### ISSUE TITLE
Alias request: Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientIpsecPolicies/ipsecIntegrity

### ISSUE THREAD

**Issue by brisneyland** [Azure/azure-policy#244]
**Scenario**

Australian Govt Information Security has several levels of security: Unclassified, Protected, Secret, TopSecret. The Internet Security Manual documents controls which must be implemented to comply with the Australian standards for a specific level of security. For any communication outside a government “Protected’ environment, the connection must have a minimum level of encryption and integrity.

We want to ensure that any vpnGateway connection between the Azure Central regions and government on-premises datacenters comply with the options outlined in the ISM

We need to able to customization the options for different types of connection – i.e. ipsecIntegrity = SHA256 or GCMAES256

**Definition**

{
    "properties": {
        "mode": "all",
        "displayName": "S2S VPN Gateway AU Protected",
        "description": "This policy enables you to restrict the site-to-site vpn gateways to attributes which comply with Australian ISM 2017 requirements for Protected status",
        "parameters": {
            "ipsecEncryption": {
                "type": "String",
                "allowedValues": [
                    "AES256",
                    "GCMAES256"
                ],
                "metadata": {
                    "displayName": "IPsec Encryption"
                }
            },
            "ipsecIntegrity": {
                "type": "String",
                "allowedValues": [
                    "SHA256",
                    "GCMAES256"
                ],
                "metadata": {
                    "displayName": "IPsec Integrity"
                }
            },
            "ikeEncryption": {
                "type": "String",
                "allowedValues": [
                    "AES256",
                    "GCMAES256"
                ],
                "metadata": {
                    "displayName": "IKE Encryption"
                }
            },
            "ikeIntegrity": {
                "type": "String",
                "allowedValues": [
                    "SHA256",
                    "GCMAES256"
                ],
                "metadata": {
                    "displayName": "IKE Integrity"
                }
            },
            "dhGroup": {
                "type": "String",
                "allowedValues": [
                    "DHGroup2",
                    "DHGroup14",
                    "DHGroup24",
                    "ECP256",
                    "ECP384"
                ],
                "metadata": {
                    "displayName": "DH Group"
                }
            },
            "pfsGroup": {
                "type": "String",
                "allowedValues": [
                    "PFS2048",
                    "PFS24",
                    "ECP256",
                    "ECP384"
                ],
                "metadata": {
                    "displayName": "pfs Group"
                }
            }
        },
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.Network/virtualNetworkGateways"
                    },
                    {
                        "field": "Microsoft.Network/virtualNetworkGateways/gatewayType",
                        "equals": "VPN"
                    },
                    { "anyOf": [{ 
                            "field": "Microsoft.Network/virtualNetworkGateways/vpnType",
                            "in": "RouteBased"
                        },
                        {
                            "field": "Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientProtocols",
                            "notIn": "IkeV2"
                        },
                        {"not": 
                            {
                                "field": "Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientIpsecPolicies/saLifeTimeSeconds",
                                "exists": "bool"
                            }
                        },
                        {"not":
                            {
                                "field": "Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientIpsecPolicies/saDataSizeKilobytes",
                                "exists": "bool"
                            }
                        },
                        {
                            "field": "Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientIpsecPolicies/ipsecEncryption",
                            "notIn": "[parameters('ipsecEncryption')]"
                        },
                        {
                            "field": "Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientIpsecPolicies/ipsecIntegrity",
                            "notIn": "[parameters('ipsecEncryption')]"
                        },
                        {
                            "field": "Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientIpsecPolicies/ikeEncryptions",
                            "notIn": "[parameters('ipsecIntegrity')]"
                        },
                        {
                            "field": "Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientIpsecPolicies/ikeIntegrity",
                            "notIn": "[parameters('ikeIntegrity')]"
                        },
                        {
                            "field": "Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientIpsecPolicies/dhGroup",
                            "notIn": "[parameters('dhGroup')]"
                        },
                        {
                            "field": "Microsoft.Network/virtualNetworkGateways/vpnClientConfiguration[*]/vpnClientIpsecPolicies/pfsGroup",
                            "notIn": "[parameters('pfsGroup')]"
                        }
                    ]
                    }
                ]
            },
            "then": {
                "effect": "Deny"
            }
        }
    }
}

**Comment by mentat9** [comment]
This alias is now deployed. Please give it a try.
