### ISSUE TITLE
NSG Policy: Deny Any Single IP or CIDR Ranges in Source:IP Addresses with public IP

### ISSUE THREAD

**Issue by nconder** [Azure/azure-policy#249]
I need to deny any public inbound traffic on defined destination ports from the internet. When users specify an IP or CIDR range it circumvents the Internet Service tag or Source Any policies. 

What is the best way to deny any NSG rule with a Single IP and or CIDR Ranges in the 'Source: IP Addresses' field with a public IP with policy?

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
