### ISSUE TITLE
Why Chef or Puppet agents are used for Guest Configurations on Linux

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-policy#252]
Hi,
I would like to know the reason why Chef or Puppet clients are needed. If this is Azure service I would expect that the code that is deployed will be related to Microsoft. The main problem is that if we use Azure services like Log Analytics, Azure Automation, etc. we should ultimately end up with less agents that we need to use and all of them are supported by Microsoft. It is not clear what happens if you have problem with Azure policy guest configuration. Do you turn to Microsoft or to Chef? Documentation does not provide such information.

**Comment by mgreenegit** [comment]
We plan to support customer-provided content in the future where we will be open to customers using the tools/languages of their choice.  Support for Azure solutions is provided by Microsoft.  If issues are found in open source tools, we would work with the maintainers to find a resolution.

Does this text address the question?  If so I will submit it to the documentation.

As part of supporting multiple tools/languages, we plan to include options for DSC in Linux which would be a "single maintainer" scenario.

**Comment by slavizh** [comment]
Thanks Michael! Yes that answers my question. Great to hear that. Also cannot wait that Azure Automation start using new DSC. I think that will help me a lot convincing management that we should start using Azure Automation DSC for configuration management. I am closing the issue.
