### ISSUE TITLE
Feature Request: deny Microsoft.Network/virtualNetworks by resourcegroup

### ISSUE THREAD

**Issue by mzack1985** [Azure/azure-policy#254]
Alias Request Microsoft.Network/virtualNetworks/resourcegroup.name

Scenario
Deny creating VNets outside a specified Resource Group

{
  "mode": "all",
  "policyRule": {
    "if": {
      "anyof":[{
       
        "field":"Microsoft.Resources/subscriptions/resourceGroup.name",
        "in":[
          "Network-dev-rg",
          "Network-prod-rg"

        ]},
      {
      "field": "type",
      "in": [
        "Microsoft.Network/virtualNetworks",
        "Microsoft.Network/virtualNetworkGateways"
      ]
      }
      ]
    },
    "then": {
      "effect": "Deny"
    }
  },
  "parameters": {}
}

**Comment by pilor** [comment]
The resource group that contains the resource being evaluated is exposed to all policies via the ["[resourceGroup().name]" language expression](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#resourcegroup).

However, the policy language today doesn't let you perform a comparison against a function result.  We will be expanding the language to support that in the next few months via something similar to:

```
"value": "[resourceGroup().name]",
"in": [ "Network-dev-rg", "Network-prod-rg" ] 
```

That isn't an immediate help to you.  There are some hacky things you could do to get similar behavior today but they would involve multiple policies.  One example would be to use an "append" policy to dynamically append the resource group's name as a tag to your virtualNetwork resources:

```
"effect": "append",
"details": [{
   "field": "tags.rgName",
   "value": "[resourceGroup().name]"
}]
```

You could then inspect "field": "tags.rgName" in your deny policy to see if it is one of the allowed or invalid resource groups.  The append will occur before your deny is evaluated.

**Comment by mzack1985** [comment]
thanks for the help and information

**Comment by mentat9** [comment]
This capability is now available. Details are available here: https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure. You can now use syntax like this in your if:
```
{
  "value": "[resourceGroup().name]",
  "equals": "SomeResourceGroup"
}
```
