### ISSUE TITLE
Alias request: Microsoft.Insights/ActivityLogAlerts

### ISSUE THREAD

**Issue by abhijay5** [Azure/azure-policy#261]
Scenario: Need to make sure that activity log alerts remain in place and enabled.
This is required for Azure CIS benchmark section 5
Would need the following;
Microsoft.Insights/ActivityLogAlerts.name
Microsoft.Insights/ActivityLogAlerts[].enabled
Microsoft.Insights/ActivityLogAlerts[].allOfcondition.field
Microsoft.Insights/ActivityLogAlerts[*].allOfcondition.equals
Definition:

{
"policyRule": {
"if": {
"allOf": [{
"field": "type",
"equals": "Microsoft.Insights/ActivityLogAlerts"
},
{
"field": "Microsoft.Insights/ActivityLogAlerts.name",
"equals": "nsgAudit"
}
]
},
"then": {
"effect": "AuditIfNotExists",
"details": {
"type": "Microsoft.Insights/ActivityLogAlerts",
"existenceCondition": {
"allOf": [{
"field": "Microsoft.Insights/ActivityLogAlerts.allOfcondition.field",
"equals": "resourceType"
},
{
"field": "Microsoft.Insights/ActivityLogAlerts.allOfcondition.equals",
"equals": "microsoft.network/networksecuritygroups"
},
{
"field": "Microsoft.Insights/ActivityLogAlerts.enabled",
"equals": "true"
}
]}}}}}

**Comment by camillemarie** [comment]
All of these aliases exist already (with slightly different names).

In the future, please use the Get-AzureRmPolicyAlias cmdlet to check for existing aliases before opening an alias request. 

For example:
` Get-AzureRmPolicyAlias -NamespaceMatch Insights -ResourceTypeMatch activityLogAlerts | select -expand aliases | select name -expand paths`

Returns:

Name                                                               | Path                                     | ApiVersions
-------------------------------------------------------------------|------------------------------------------|------------
Microsoft.Insights/ActivityLogAlerts/scopes                        | properties.scopes                        | {2018-09-01, 2017-03-01-preview, 2017-04-01}
Microsoft.Insights/ActivityLogAlerts/scopes[*]                     | properties.scopes[*]                     | {2018-09-01, 2017-03-01-preview, 2017-04-01}
Microsoft.Insights/ActivityLogAlerts/condition                     | properties.condition                     | {2018-09-01, 2017-03-01-preview, 2017-04-01}
Microsoft.Insights/ActivityLogAlerts/condition.allOf               | properties.condition.allOf               | {2018-09-01, 2017-03-01-preview, 2017-04-01}
Microsoft.Insights/ActivityLogAlerts/condition.allOf[*]            | properties.condition.allOf[*]            | {2018-09-01, 2017-03-01-preview, 2017-04-01}
Microsoft.Insights/ActivityLogAlerts/condition.allOf[*].field      | properties.condition.allOf[*].field      | {2018-09-01, 2017-03-01-preview, 2017-04-01}
Microsoft.Insights/ActivityLogAlerts/condition.allOf[*].equals     | properties.condition.allOf[*].equals     | {2018-09-01, 2017-03-01-preview, 2017-04-01}
Microsoft.Insights/ActivityLogAlerts/condition.allOf[*].containsAny| properties.condition.allOf[*].containsAny| {2018-09-01, 2017-03-01-preview, 2017-04-01}
Microsoft.Insights/ActivityLogAlerts/enabled                       | properties.enabled                       | {2018-09-01, 2017-03-01-preview, 2017-04-01}

For further reference:
[Policy fields](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#fields)
[Policy aliases](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#fields)

**Comment by abhijay5** [comment]
@camillemarie First of all thank you for replying, i am aware about the alias name, i have created many test policy with different sets of parameters by using the above alias names. which is doesn't seems to be working at all. 
Can you please check it by yourself or share the policy if you have created and that works for you. 

Bunches of thanks in advance for your reply and time.

**Comment by abhijay5** [comment]
@camillemarie i have re-checked the the policy alias after going through your inputs, but name alias doesn't available which will help to full fill the requirement of following CIS docs Needs. 
5.1
--
5.2
5.3
5.4
5.5
5.6
5.7
5.8
5.9
5.1
5.11
5.12
it would be highly appreciated if you can at-least  help us with one sample policy for the above TASK number mentioned. once again tank you in advancefor your reply.

**Comment by camillemarie** [comment]
@abhijay5 _name_ is a supported field for all resources. You do not need an alias.

More generally: This repository is not a support channel. If you include a full policy definition and error message to describe what "isn't working" we may be able to help you troubleshoot, but there is no SLA on such requests. If you need dedicated assistance in implementing policies in your environment, you should [contact Microsoft Support.](https://support.microsoft.com/en-us/gp/contactus81?forceorigin=esmc&Audience=Commercial)
