### ISSUE TITLE
Alias request: Microsoft.Insights/logprofiles[*].retentionPolicy.enabled

### ISSUE THREAD

**Issue by abhijay5** [Azure/azure-policy#262]
Scenario: Need to audit if default log profile isn't enabled or retention is less than one year
Definition:
"policyRule": {
"if": {
"allOf": [{
"field": "type",
"equals": "Microsoft.Insights/logprofiles/default"
},
{
"anyOf": [{

                "field": "Microsoft.Insights/logprofiles/default/retentionPolicy.enabled",
                "equals": "false"
            },
            {
                "field": "Microsoft.Insights/logprofiles[*].retentionPolicy.days",
                "lessThan": "365"
            }
        ]
    }
]
}
},
"then": {
"effect": "audit"
}

**Comment by camillemarie** [comment]
The aliases you want exist already. They are:

```
Microsoft.Insights/logProfiles/retentionPolicy.enabled
Microsoft.Insights/logProfiles/retentionPolicy.days
```

In the future, please use the Get-AzureRmPolicyAlias cmdlet to check for existing aliases before opening an alias request. 

**For example:**

`Get-AzureRmPolicyAlias -NamespaceMatch Insights -ResourceTypeMatch logProfiles | select -expand aliases | select name -expand paths`

**Returns:**

Name                                                  | Path                              | ApiVersions
------------------------------------------------------|-----------------------------------|------------
Microsoft.Insights/logProfiles/storageAccountId       | properties.storageAccountId       | {2016-03-01}
Microsoft.Insights/logProfiles/serviceBusRuleId       | properties.serviceBusRuleId       | {2016-03-01}
Microsoft.Insights/logProfiles/locations              | properties.locations              | {2016-03-01}
Microsoft.Insights/logProfiles/locations[*]           | properties.locations[*]           | {2016-03-01}
Microsoft.Insights/logProfiles/categories             | properties.categories             | {2016-03-01}
Microsoft.Insights/logProfiles/categories[*]          | properties.categories[*]          | {2016-03-01}
Microsoft.Insights/logProfiles/retentionPolicy        | properties.retentionPolicy        | {2016-03-01}
Microsoft.Insights/logProfiles/retentionPolicy.enabled| properties.retentionPolicy.enabled| {2016-03-01}
Microsoft.Insights/logProfiles/retentionPolicy.days   | properties.retentionPolicy.days   | {2016-03-01}


**For further reference:**
[Policy fields](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#fields)
[Policy aliases](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#fields)
