### ISSUE TITLE
Alias Request: Microsoft.DocumentDB/databaseAccounts/enableMultipleWriteLocations

### ISSUE THREAD

**Issue by SotKarras** [Azure/azure-policy#263]
Scenario
We need to use Azure Policy to audit all CosmosDB account that do not have Multi-Master enabled. In the ARM template this is controlled by the enableMultipleWriteLocations flag. The policy would be something like the following:

Definition
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.DocumentDB/databaseAccounts"
      },
      {
        "field": "Microsoft.DocumentDB/databaseAccounts/enableMultipleWriteLocations",
        "equals": "false"
      }
    ]
  },
  "then": {
    "effect": "audit"
  }
}

**Comment by mentat9** [comment]
This alias has been added: give it a try.
