### ISSUE TITLE
Microsoft.Web/sites/config/siteAuthSettings.* aliases are not valid

### ISSUE THREAD

**Issue by anwather** [Azure/azure-policy#264]
Just a question about what this and the siteauthsettings.isAadAutoProvisioned - I have created a web app and enabled App Service Authentication with AAD as the default provider and configured the service principal etc. A policy testing for siteauthEnabled is working correctly. However the policy below is showing as non-compliant. 

```
{
  "if": {
    "allOf": [
      {
        "field": "Microsoft.Web/sites/config/siteAuthSettings.enabled",
        "equals": "false"
      }
    ]
  },
  "then": {
    "effect": "audit"
  }
}
```
If I check resource explorer - I can see that in the config view it shows ```.enabled``` as being ```false``` but if I check the authsettings resource it shows ```enabled``` as being ```true```.

*Resource Explorer Config*
```
"value": [
    {
      "id": "/subscriptions/subguid/resourceGroups/resourcegroupname/providers/Microsoft.Web/sites/sitename/config/web",
      "name": "mySite",
      "type": "Microsoft.Web/sites/config",
      "location": "South Central US",
      "properties": {
        "numberOfWorkers": 1,
<<snip>>
        "vnetName": "",
        "siteAuthEnabled": true,
        "siteAuthSettings": {
          "enabled": null,
          "unauthenticatedClientAction": null,
          "tokenStoreEnabled": null,
          "allowedExternalRedirectUrls": null,
          "defaultProvider": null,
          "clientId": "65185236-cdf2-452c-9aea-xxxxxxxxdb680",
          "clientSecret": null,
          "clientSecretCertificateThumbprint": null,
          "issuer": "https://sts.windows.net/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/",
          "allowedAudiences": null,
          "additionalLoginParams": null,
          "isAadAutoProvisioned": false,
          "googleClientId": null,
          "googleClientSecret": null,
```
*Resource Explorer AuthSettings*
```
{
  "id": "/subscriptions/subguid/resourceGroups/resourcegroupname/providers/Microsoft.Web/sites/sitename/config/authsettings",
  "name": "authsettings",
  "type": "Microsoft.Web/sites/config",
  "location": "South Central US",
  "properties": {
    "enabled": true,
    "runtimeVersion": "1.0.0",
    "unauthenticatedClientAction": "RedirectToLoginPage",
    "tokenStoreEnabled": true,
    "allowedExternalRedirectUrls": null,
    "defaultProvider": "AzureActiveDirectory",
    "clientId": "65185236-cdf2-452c-9aea-xxxxxxxxx680",
    "clientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "clientSecretCertificateThumbprint": null,
    "issuer": "https://sts.windows.net/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/",
    "allowedAudiences": [
      "https://MySite.azurewebsites.net/.auth/login/aad/callback"
    ],
    "additionalLoginParams": null,
    "isAadAutoProvisioned": true,
    "googleClientId": null,
    "googleClientSecret": null,
```
Where does the alias point to - I'm not sure which resource page I'm targeting.

**Comment by camillemarie** [comment]
**Generally speaking...**

You can use the [Get-AzureRmPolicyAlias cmdlet](https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/get-azurermpolicyalias?view=azurermps-6.13.0) to learn more about how a given alias maps to resource properties.

For example:
`Get-AzureRmPolicyAlias -AliasMatch "Microsoft.Web/sites/config/siteAuthSettings.enabled" | select resourcetype -expand aliases | where {$_.Name -eq "Microsoft.Web/sites/config/siteAuthSettings.enabled"} | select resourcetype,name -expand paths`

Returns:

ResourceType| Name                                               | Path                               | ApiVersions
------------|----------------------------------------------------|------------------------------------|------------
sites/config| Microsoft.Web/sites/config/siteAuthSettings.enabled| properties.siteAuthSettings.enabled| {2014-04-01, 2014-04-01-preview, 2014-06-01, 2014-11-01...}

This means that the _Microsoft.Web/sites/config/siteAuthSettings.enabled_ alias will select the _properties.siteAuthSettings.enabled_ property from any resource of type _sites/config_ (and it will return empty string if the property is not present).

---------------
**Re: your policy**
Which resource is showing up as Non-Compliant? The _web_ config you included above is the only one with the _properties.siteAuthSettings.enabled_ property, and it is null, not "false", so I wouldn't expect it be be flagged by your policy.

**Comment by camillemarie** [comment]
This version of your policy will **always** flag resources as compliant (because null != "null"):

```
 {
  "if": {
    "allOf": [
      {
        "field": "Microsoft.Web/sites/config/siteAuthSettings.enabled",
        "equals": "null"
      }
    ]
  },
  "then": {
    "effect": "audit"
  }
}
```

This policy you originally posted should have worked:
```
{
  "if": {
    "allOf": [
      {
        "field": "Microsoft.Web/sites/config/siteAuthSettings.enabled",
        "equals": "false"
      }
    ]
  },
  "then": {
    "effect": "audit"
  }
}
```

Did you have a prior version of the policy definition before that, or did you enable App Service Authentication after the policy was put in place? It can take some time for compliance results to update after a change (especially if only the policy definition was changed, and not the assignment), and I have a feeling that you were seeing stale results.

**Comment by camillemarie** [comment]
OK, bad news:

**authSettings** cannot be managed via policy at this time. In the interest of hiding secrets from users in the default Reader role, this resource provider doesn't expose secrets via GET calls (hence the _null_ in /config/web, and lack of GET support for /config/authSettings). 

This means that the existing Microsoft.Web/sites/config/siteAuthSettings.* aliases are invalid. We'll look into removing these, but we don't have a good deprecation story at the moment.
 
--------
For your specific policy:
_Microsoft.Web/sites/config/siteAuthSettings.enabled_ is identical to _Microsoft.Web/sites/config/siteAuthEnabled_. I have not seen a case where the value for `properties.siteAuthEnabled` in /config/web mismatches the value for `properties.enabled` in /config/authSettings.

So you can use a policy like this instead:
 ```
{
  "if": {
    "field": "Microsoft.Web/sites/config/siteAuthEnabled",
    "equals": "false"
  },
  "then": {
    "effect": "audit"
  }
}
```

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
