### ISSUE TITLE
Dead link in Readme.md

### ISSUE THREAD

**Issue by towerbe** [Azure/azure-policy#266]
In the primary readme, in the "other" section there is a link for Exploring Azure Policy (Hands-on Labs).  This link does not work.  It appears that this hands-on lab no longer exists.  I've searched the entire hands-on labs site to the best of my abilities, but cannot find any classes on Azure Policy.  Can you either remove the reference, or remove it, please. (I would really like to have a link to this lab if it is still available).

**Comment by camillemarie** [comment]
Removed the link: #267 

A new lab is in the works but it is not publicly available at this time.

**Comment by towerbe** [comment]
Do you have an ETA for the new lab, or need a beta tester?  I represent a
major Fortune 100 client of Microsoft with a substantial Azure investment.
