### ISSUE TITLE
Alias Request : Enable MSI on App service 

### ISSUE THREAD

**Issue by sonalikaroy** [Azure/azure-policy#271]
### Scenario

What are you trying to achieve using Azure Policy?

### Alias

Include details about the alias being requested. Details on aliases are available [**here**](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases).
- What resource provider and resource type is involved?
- What property on that resource type do you wish to expose?

### Example policy definition

Please include a sample policy definition that shows how you would like to use this new alias.

**Comment by pilor** [comment]
You can use `"field": "identity.type"` to inspect the state of MSI on a resource
