### ISSUE TITLE
Feature request: enforce that storage shared access signature tokens expire within an hour

### ISSUE THREAD

**Issue by abhijay5** [Azure/azure-policy#276]
CIS document task number 3.4 Ensure that shared access signature tokens expire within an hour
3.5  Ensure   that shared access signature tokens are allowed only over https. 

Have tried to use AZSK to retrieve the information but that is also doesn't scan for the above settings and not helpful. 

    Thank you for contributing!

    ISSUE TITLE: Alias request: "Microsoft.Compute/storageAccounts/SAS"

    ISSUE DESCRIPTION: CIS document task number 3.4 Ensure that shared access signature tokens expire within an hour & 3.5  Ensure   that shared access signature tokens are allowed only over https. 

Have tried to use AZSK to retrieve the information but that is also doesn't scan for the above settings and not helpful.

**Comment by abhijay5** [comment]
CIS document task number 3.4 Ensure that shared access signature tokens expire within an hour
3.5  Ensure   that shared access signature tokens are allowed only over https. 

Have tried to use AZSK to retrieve the information but that is also doesn't scan for the above settings and not helpful.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
