### ISSUE TITLE
activity log

### ISSUE THREAD

**Issue by darshankumarys** [Azure/azure-policy#277]
Activity logs are not visible in Azure Policies. Is there anything in your backlog ?

we need to know who and when has created polices and when the policies are updated. 

If you provide some information on this, it would be great.

**Comment by pilor** [comment]
You will see activity logs related to azure policy if the policy is operated on at subscription scope or below.  Management group operations aren't exposed to activity logs yet (for any resource).  The management group team is actively working on that but I don't believe they have a github presence to route the issue to.  If you want updates on that work please submit a support request through the Azure Portal.
