### ISSUE TITLE
Alias request: Microsoft.Sql/servers/databases/sku.name

### ISSUE THREAD

**Issue by pvvdurgaprasad** [Azure/azure-policy#278]
Alias request: Microsoft.Sql/servers/databases/sku.name

Scenario
Verify that all databases are in desired pricing tier for DTU based single database

Alias
RP: Microsoft.Sql
Resource Type: servers/databases
Property: sku.name
Example policy definition
 ```
   {
        "properties": {
            "displayName": "Audit database is in Basic tier",
            "description": "Audit database is in Basic tier",

            "policyRule": {
                "if": {
                {
				"allOf": [
					{
					"field": "type",
					"equals": "Microsoft.Sql/servers/databases"
					}, 			  
					{
					"not": {
						"anyOf": [
							{
							"allOf": [
								{
								"field": "name",
								"equals": "inf995sqlserver/samplebasicdb"
								},
								{
								"field": "Microsoft.Sql/servers/databases/sku.name",
								"equals": "Basic"
								}
							]
							}
						]
					}
					}
				]
				}
                },
                "then": {
                    "effect": "audit"
                }
            }
        }
    }
```

**Comment by mentat9** [comment]
I believe you are looking for Microsoft.Sql/servers/databases/currentSku. You can already manage Microsoft.Sql/servers/databases/sku in policy without an alias, since it's not part of the root level property bag. The following aliases have been added, please give them a try: 

```Microsoft.Sql/servers/databases/currentSku```, 
```Microsoft.Sql/servers/databases/currentSku.capacity```, 
```Microsoft.Sql/servers/databases/currentSku.family```, 
```Microsoft.Sql/servers/databases/currentSku.size```, 
```Microsoft.Sql/servers/databases/currentSku.tier```, 
```Microsoft.Sql/servers/databases/currentSku.name```
