### ISSUE TITLE
Alias request: Microsoft.KeyVault/accessPolicies

### ISSUE THREAD

**Issue by pshelton-skype** [Azure/azure-policy#280]
### Scenario

We would like to enforce and audit access permissions for keys, secrets, and certificates in Key Vault via Azure Policy, including some of the following scenarios:

#### Enforce Reader Permissions

In order to enable company-wide auditing of which certificates are stored in which subscriptions, what storage connection strings haven't recently been rotated, or what teams have expiring certificates, for example, enforce by policy that all Key Vaults have a particular AAD Application ID enabled for List permissions on all Key Vaults, perhaps using a policy like:

```
{
  "properties": {
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.KeyVault/accessPolicies"
          },
          {
            "not": {
              "allOf": [
                {
                  "field": "objectId",
                  "equals": "00000000-0000-0000-0000-000000000000"
                },
                {
                  "field": "Microsoft.KeyVault/accessPolicies/permissions/keys/",
                  "contains": "List"
                },
                {
                  "field": "Microsoft.KeyVault/accessPolicies/permissions/secrets/",
                  "contains": "List"
                },
                {
                  "field": "Microsoft.KeyVault/accessPolicies/permissions/certificates/",
                  "contains": "List"
                }
              ]
            }
          }
        ]
      },
      "then": {
        "effect": "deployIfNotExists"
      }
    }
  }
}
```

#### Deny Non-Production Applications Permission on Production Key Vaults

Some production subscriptions may require that certain test applications are not given permissions to access Key Vaults hosted within them. In order to prevent incorrect permissions from being assigned, deny the assignment of permissions to a particular AAD Application ID, perhaps using a policy like:

```
{
  "properties": {
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.KeyVault/accessPolicies"
          },
          {
              "field": "objectId",
              "equals": "00000000-0000-0000-0000-000000000000"
            }
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }
  }
}
```

#### Audit Overly-Expansive Permissions

Some deployments happen via VSTS RM, though a Service Principal granted permissions on a subscription and read-only permissions to secrets in a Key Vault. In order to prevent secrets being created or destroyed through a deployment, audit all Key Vaults that have permissions granted to a particular AAD Application ID and ensure that the permissions are restricted to only Get and List, perhaps using a policy like:

```
{
  "properties": {
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.KeyVault/accessPolicies"
          },
          {
            "anyOf": [
              {
                "allOf": [
                  {
                    "field": "objectId",
                    "equals": "00000000-0000-0000-0000-000000000000"
                  },
                  {
                    "field": "Microsoft.KeyVault/accessPolicies/permissions/secrets/",
                    "contains": "Delete"
                  }
                ],
                "allOf": [
                  {
                    "field": "objectId",
                    "equals": "00000000-0000-0000-0000-000000000000"
                  },
                  {
                    "field": "Microsoft.KeyVault/accessPolicies/permissions/secrets/",
                    "contains": "Import"
                  }
                ]
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "audit"
      }
    }
  }
}
```

### Alias

Include details about the alias being requested. Details on aliases are available [**here**](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases).

- What resource provider and resource type is involved?
Microsoft.KeyVault

- What property on that resource type do you wish to expose?
- accessPolicies and all of its sub-properties:
  - tenantId
  - objectId
  - permissions and all of its sub-properties
    - keys
    - secrets
    - certificates
    - storage

### Example policy definition

See scenarios outlined above. This is my first time writing sample policies, so the exact syntax may not be correct, but I hope the intention is.

**Comment by Obiwan72** [comment]
Any news when this issue is going to be fixed? We also would like to be able to use this policy.

**Comment by hrboyceiii** [comment]
Would love to see this as well. Having a DINE policy for ensuring proper access across apps.

**Comment by mentat9** [comment]
Aliases for all Keyvault fields have been published. Please give them a try.

**Comment by hrboyceiii** [comment]
So awesome that these are now available!!! My immediate scenario is for deploy if not exists policies as this is a pain point for my customer.  Would it be possible for an example implementation to be posted here for such a policy??

Thank you!!!
