### ISSUE TITLE
Alias request: Microsoft.Network/routeTables/properties.disableBgpRoutePropagation

### ISSUE THREAD

**Issue by blthomas** [Azure/azure-policy#282]
### Scenario

We need an Azure policy to deny creating any Route Tables with BGP route propagation enabled. The policy would be something like the following:

### Example policy definition

{
  "mode": "all",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Network/routeTables"
        },
        {
          "field": "Microsoft.Network/routeTables/properties.disableBgpRoutePropagation",
          "equals": "False"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }

}

**Comment by mentat9** [comment]
This alias has been added. Please give it a try.
