### ISSUE TITLE
Alias Request: ApplicationGateways/FrontendPort/properties.port

### ISSUE THREAD

**Issue by FireDrunk** [Azure/azure-policy#283]
### Scenario

What are you trying to achieve using Azure Policy?
Limit available ports in Microsoft.Network/ApplicationGateways/FrontendPort/properties.port

### Alias

Include details about the alias being requested. Details on aliases are available [**here**](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases).
- What resource provider and resource type is involved?
Microsoft.Network/ApplicationGateways/FrontendPort
- What property on that resource type do you wish to expose?
Port

### Example policy definition

Please include a sample policy definition that shows how you would like to use this new alias.
```
{
  "policyRule": {
    "if": {
      "allOf":[
        {
          "field": "type",
          "equals": "Microsoft.Network/applicationGateways"
        },
        {
          "field": "Microsoft.Network/applicationGateways/frontendPorts[*].port",
          "notEquals": "80"
        },
        {
          "field": "Microsoft.Network/applicationGateways/frontendPorts[*].port",
          "notEquals": "443"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }
}
```
Deny anything but 80 and 443 (additionally we want to require HTTPS on port 443, but that's a different policy)

**Comment by mentat9** [comment]
This alias has been added. Please give it a try.
