### ISSUE TITLE
Alias request: Microsoft.Web/sites/config/cors[*]

### ISSUE THREAD

**Issue by mpapas** [Azure/azure-policy#285]
### Scenario

Ensure that a Web or Function App’s CORS settings contain a specific list of mandatory allowed origins.

For example, deny a Function App if the CORS settings are configured and none of the CORS settings include each of the mandatory origin URL’s provided.

### Alias

Add [*] alias to already existing "Microsoft.Web/sites/config/cors" alias in order to enumerate individual values.

RP: Microsoft.Web
Resource Type: sites
Property/alias: Microsoft.Web/sites/config/cors[*]

### Example policy definition
```
{
  "properties": {
    "displayName":"Audit CORS Policy for Web App",
    "description":"Audits that a Web App contains the specified CORS policy",
    "mode": "All",
    "parameters": {
      "listOfAllowedOrigins": {
          "type": "Array",
          "metadata": {
              "displayName": "Allowed Origins",
              "description": ""
          }
      }
    },
    "policyRule": {
      "if": {
        "allOf": [{
                "field": "Microsoft.Web/sites/config/cors",
                "exists": "true"
            },
            {
                "field": "Microsoft.Web/sites/config/cors[*].value",
                "notIn": "[parameters('listOfAllowedOrigins')]"
            }
        ]
    },
    "then": {
        "effect": "audit"
    }
  }
}
}
```

**Comment by mentat9** [comment]
Unfortunately, these fields cannot be managed by Azure Policy. Please see https://github.com/Azure/azure-policy/issues/264 for details.
