### ISSUE TITLE
Alias request: Microsoft.Compute/virtualMachines/extensions[*].VirtualMachineExtensionType

### ISSUE THREAD

**Issue by punit1396** [Azure/azure-policy#286]
### Scenario

We are trying to make a policy that should not run on encrypted VMs. 
There is an alias exposed to check if the VM is encrypted (Microsoft.Compute/virtualMachines/storageProfile.osDisk.encryptionSettings.enabled).
But this is not sufficient as the ADE (Azure Disk Encryption) team has introduced single pass encryption. The encryption details are no longer stored in the storageProfile but are visible in the instance view.
Hence, checking for the existence of the encryption extension.

### Alias

RP: Microsoft.Compute
Resource Type: virtualMachines/extensions
Property/alias: Microsoft.Compute/virtualMachines/extensions[*].VirtualMachineExtensionType

### Example policy definition

{
    "properties": {
        "displayName": "Audit VMs that are not encrypted",
        "description": "Audit VMs that are not encrypted",
        "parameters": {},
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.Compute/virtualMachines"
                    },
                    {
                        "field": "Microsoft.Compute/virtualMachines/extensions[*].VirtualMachineExtensionType",
                        "notContains": "AzureDiskEncryption"
                    }
                ]
            },
            "then": {
                "effect": "Audit"
            }
        }
    }
}

**Comment by mentat9** [comment]
This property isn't one that can be managed by policy. Policy only manages properties that are present both in the PUT request body and the GET response. You might be able to do what you need using 
```Microsoft.Compute/disks/encryptionSettings``` which already has an alias.
