### ISSUE TITLE
Alias request: Microsoft.RecoveryServices/vaults/replicationFabrics[*].FabricSpecificDetails.Location

### ISSUE THREAD

**Issue by punit1396** [Azure/azure-policy#287]
### Scenario

Trying to create a policy that checks if a replication fabric exists for a certain location else deploy one. So, need the replication fabric location exposed through an alias.

### Alias

RP: Microsoft.RecoveryServices
Resource Type: vaults/replicationFabrics
Property/alias: Microsoft.RecoveryServices/vaults/replicationFabrics[*].FabricSpecificDetails.Location

### Example policy definition

{
    "properties": {
        "displayName": "Audit Recovery Services Vaults if fabric for given location does not exist",
        "description": "Audit Recovery Services Vaults if fabric for given location does not exist",
        "parameters": {
            "location": {
                "type": "String",
                "metadata": {
                "displayName": "location",
                "description": null
                },
                "defaultValue": "eastus"
            }
        },
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.RecoveryServices/vaults"
                    },
                    {
                        "field": "Microsoft.RecoveryServices/vaults/replicationFabrics[*].FabricSpecificDetails.Location",
                        "notEquals": "[parameters('location')]"
                    }
                ]
            },
            "then": {
                "effect": "Audit"
            }
        }
    }
}

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.RecoveryServices has been published. Note that collection gets against a resource type like Microsoft.RecoveryServices/vaults/replicationFabrics can't be managed via array aliases. You will need to write policies that target instances.
