### ISSUE TITLE
Alias request: Microsoft.Compute/virtualMachines/zones

### ISSUE THREAD

**Issue by punit1396** [Azure/azure-policy#288]
### Scenario

We are trying to create a policy that should not run on zone-redundant VMs. Hence, need to check for the existence of this field.

### Alias

RP: Microsoft.Compute
Resource Type: virtualMachines
Property: zones

### Example policy definition
{
    "properties": {
        "displayName": "Audit VMs that are not zone redundant",
        "description": "Audit VMs that are not zone redundant",
        "parameters": {},
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.Compute/virtualMachines"
                    },
                    {
                        "field": "Microsoft.Compute/virtualMachines/zones",
                        "exists": "false"
                    }
                ]
            },
            "then": {
                "effect": "Audit"
            }
        }
    }
}

**Comment by mentat9** [comment]
Turns out zones alias is special, and requires code changes before it can be used in policy. In the meantime, I've removed them to avoid confusion.

**Comment by ChendrayanV** [comment]
@mentat9 Thanks for the confirmation. Any tentative date for completion? Thanks in advance!

**Comment by mentat9** [comment]
If things go well, the soonest it could be is 2-3 weeks from now. Sorry I can't make it go any faster: the timing isn't under my control.

**Comment by mentat9** [comment]
This request is now complete. I did a full refresh of Microsoft.Compute, and Zones and Zones[*] aliases are now published for ```Microsoft.Compute/virtualMachines```, ```Microsoft.Compute/disks```, ```Microsoft.Compute/virtualMachineScaleSets```, and ```Microsoft.Compute/virtualMachineScaleSets/virtualMachines```.

**Comment by ChendrayanV** [comment]
Thanks a lot!
