### ISSUE TITLE
Alias Request: Microsoft.Sql/servers/databases/dataMaskingPolicies

### ISSUE THREAD

**Issue by CtrlDot** [Azure/azure-policy#289]
### Scenario

What are you trying to achieve using Azure Policy?

I am trying to enforce/ensure that Azure SQL databases are set up with masking rules in place, and also to watch for when/if these masking rules are changed/deleted.

### Alias

Include details about the alias being requested. Details on aliases are available [**here**](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases).
- What resource provider and resource type is involved?
Microsoft.Sql/servers/databases/dataMaskingPolicies

- What property on that resource type do you wish to expose?
dataMaskingState
exemptPrincipals

### Example policy definition

Please include a sample policy definition that shows how you would like to use this new alias.

{
    "if":{
        "allOf":[
            {
                "field":"type",
                "equals":"Microsoft.Sql/servers/databases"
            },
            {
                "field":"Microsoft.sql/servers/databases/dataMaskingPolicy/exemptPrincipals",
                "notEquals":"DataAdmins"
            }
        ]
    },
    "then":{
        "effect":"audit"
    }
}

**Comment by mentat9** [comment]
Aliases for all Microsoft.Sql fields have been published. Please give them a try.
