### ISSUE TITLE
Alias request: Microsoft.RecoveryServices/vaults/replicationPolicies[*].Name

### ISSUE THREAD

**Issue by punit1396** [Azure/azure-policy#290]
### Scenario

Trying to create a policy that checks if a replication policy with a particular name exists in a vault else deploy one. So, need the replication policy name exposed through an alias.

### Alias

RP: Microsoft.RecoveryServices
Resource Type: vaults/replicationPolicies
Property/alias: Microsoft.RecoveryServices/vaults/replicationPolicies[*].Name

### Example policy definition
{
    "properties": {
        "displayName": "Audit Recovery Services Vaults if it does not have a replication policy with given name",
        "description": "Audit Recovery Services Vaults if it does not have a replication policy with given name",
        "parameters": {
            "policyName": {
                "type": "String",
                "metadata": {
                "displayName": "policyName",
                "description": null
                },
                "defaultValue": "24-hour-retention-policy"
            }
        },
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.RecoveryServices/vaults"
                    },
                    {
                        "field": "Microsoft.RecoveryServices/vaults/replicationPolicies[*].Name",
                        "notEquals": "[parameters('policyName')]"
                    }
                ]
            },
            "then": {
                "effect": "Audit"
            }
        }
    }
}

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.RecoveryServices has been published. Unfortunately, no fields in vaults/replicationPolicies can be managed by policy, because there are no fields common to get and put requests.
