### ISSUE TITLE
Alias request: Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers[*].Name

### ISSUE THREAD

**Issue by punit1396** [Azure/azure-policy#291]
### Scenario

Trying to create a policy that checks if a protection container with a particular name exists under a replication fabric else deploy one. So, need the protection container name exposed through an alias.

### Alias

RP: Microsoft.RecoveryServices
Resource Type: vaults/replicationFabrics/replicationProtectionContainers
Property/alias: Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers[*].Name

### Example policy definition
{
    "properties": {
        "displayName": "Audit Recovery Services Vaults if it does not have a protection container with given name in any of its fabrics",
        "description": "Audit Recovery Services Vaults if it does not have a protection container with given name in any of its fabrics",
        "parameters": {
            "containerName": {
                "type": "String",
                "metadata": {
                "displayName": "containerName",
                "description": null
                },
                "defaultValue": "asr-a2a-default-container"
            }
        },
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.RecoveryServices/vaults"
                    },
                    {
                        "field": "Microsoft.RecoveryServices/vaults/replicationPolicies[*].Name",
                        "notEquals": "[parameters('containerName')]"
                    }
                ]
            },
            "then": {
                "effect": "Audit"
            }
        }
    }
}

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.RecoveryServices has been published. Unfortunately, no fields in resource type ```vaults/replicationFabrics/replicationProtectionContainers``` can be managed by policy, because there are no fields common to get and put requests.
