### ISSUE TITLE
Alias request: Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectionContainerMappings[*].Name

### ISSUE THREAD

**Issue by punit1396** [Azure/azure-policy#292]
### Scenario

Trying to create a policy that checks if a protection container mapping  with a particular name (fixed format) exists under a protection container else deploy one. So, need the protection container mapping name exposed through an alias.

### Alias

RP: Microsoft.RecoveryServices
Resource Type: vaults/replicationFabrics/replicationProtectionContainers/replicationProtectionContainerMappings
Property/alias: Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectionContainerMappings[*].Name

### Example policy definition

{
    "properties": {
        "displayName": "Audit Recovery Services Vaults if it does not have a protection container mapping with given name",
        "description": "Audit Recovery Services Vaults if it does not have a protection container mapping with given name",
        "parameters": {
            "mappingName": {
                "type": "String",
                "metadata": {
                "displayName": "mappingName",
                "description": null
                },
                "defaultValue": "scus-ncus-24-hour-retention-policy"
            }
        },
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.RecoveryServices/vaults"
                    },
                    {
                        "field": "Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/repli            cationProtectionContainerMappings[*].Name",
                        "notEquals": "[parameters('mappingName')]"
                    }
                ]
            },
            "then": {
                "effect": "Audit"
            }
        }
    }
}

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.RecoveryServices has been published. Note that collection gets against a resource type like Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectionContainerMappings can't be managed via array aliases. You will need to write policies that target instances.
