### ISSUE TITLE
Alias request: Microsoft.KeyVault/vaults/providers/diagnosticsettings "eventHubName" and "eventHubAuthorizationRuleId" properties

### ISSUE THREAD

**Issue by pshelton-skype** [Azure/azure-policy#294]
### Scenario

Audit and enforce proper configuration to stream Key Vault audit log to Event Hub(s). Determining audit logs are written to storage is supported with the `Microsoft.Insights/logProfiles/storageAccountId` alias, but no such support appears to exist for Event Hubs per `Get-AzureRmPolicyAlias -NamespaceMatch Insights -ResourceTypeMatch logProfiles`.

### Alias

- What resource provider and resource type is involved?

providers/microsoft.insights/diagnosticSettings/

- What property on that resource type do you wish to expose?

eventHubAuthorizationRuleId
eventHubName

See https://docs.microsoft.com/en-us/rest/api/monitor/diagnosticsettings/createorupdate and https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-logs-stream-template#non-compute-resource-template.

### Example policy definition

```
"policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.KeyVault/vaults"
    },
    "then": {
      "effect": "AuditIfNotExists",
      "details":{
        "type": "Microsoft.Insights/diagnosticSettings",
        "existenceCondition": {
          "allOf": [
            {
              "field": "Microsoft.Insights/diagnosticSettings/logs[*].retentionPolicy.enabled",
              "equals": "true"
            },
            {
              "field": "Microsoft.Insights/diagnosticSettings/logs[*].retentionPolicy.days",
              "equals": "[parameters('requiredRetentionDays')]"
            },
            {
              "field": "Microsoft.Insights/diagnosticSettings/logs[*].category”,
              "equals": "AuditEvent"
            },
            {
              "field": "Microsoft.Insights/diagnosticSettings/eventHubName”,
              "equals": "[parameters('mySecurityEventHub')]"
            }
          ]
        }
      }
    }
}
```

**Comment by mentat9** [comment]
You can use the Microsoft.Insights/diagnosticSettings aliases for this scenario.
