### ISSUE TITLE
Alias request: Microsoft.Compute/virtualMachines/ProvisioningState

### ISSUE THREAD

**Issue by punit1396** [Azure/azure-policy#301]
### Scenario

Trying to create a policy that runs on a VM only if it's provisiong state is 'succeeded'.

### Alias

RP: Microsoft.Compute
Resource Type: virtualMachines
Property: ProvisioningState

### Example policy definition

{
    "properties": {
        "displayName": "Audit VMs if provisiong state is not 'succeeded'",
        "description": "Audit VMs if provisiong state is not 'succeeded'",
        "parameters": {
        },
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.Compute/virtualMachines"
                    },
                    {
                        "field": "Microsoft.Compute/virtualMachines/ProvisioningState",
                        "notEquals": "Succeeded"
                    }
                ]
            },
            "then": {
                "effect": "Audit"
            }
        }
        }
    }
}

**Comment by mentat9** [comment]
This alias has been added.
