### ISSUE TITLE
Need to be able to find Network Interfaces which are not attached to VM

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-policy#302]
### Scenario

Trying to audit use of non-attached VMs (similar how `Microsoft.Compute/disks/diskState` property can be used to find disks which are not attached

### Alias

- What resource provider and resource type is involved?
`Microsoft.Network/networkInterfaces/`
- What property on that resource type do you wish to expose?
`AttachedState`

### Example policy definition

```
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Network/networkInterfaces"
      },
      {
        "field": "Microsoft.Network/networkInterfaces/Attached",
        "equals": "Unattached"
      }
    ]
  },
  "then": {
    "effect": "audit"
  }
}
```

**Comment by mentat9** [comment]
Policy only manages fields present both in PUT request body and GET response body. This field doesn't fit that category. However, take a look at https://github.com/Azure/azure-policy/issues/257. This might provide a way of doing what you need. Note that alias is not yet available, but the network team is in the process of rolling out their new manifests, so it should be available soon. You can use the Get-AzureRmPolicyAlias Powershell cmdlet to quickly query for existing aliases.
