### ISSUE TITLE
Microsoft.ContainerRegistry/registries/sku.name

### ISSUE THREAD

**Issue by sonalikaroy** [Azure/azure-policy#303]
Hi,

Can you please help in creating a sku alias for container registry?We want to limit to use only primary sku.

{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.ContainerRegistry/registries"
        },
        {
          "not": {
            "field": "Microsoft.ContainerRegistry/registries/sku.name",
            "equals": "premium"
          }
        }
      ]
    },
    "then": {
      "effect": "Deny"
    }
  },
  "parameters": {
  }
}

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.ContainerRegistry, including sku* are now published. Give these a try.
