### ISSUE TITLE
NSG Policy avoidance through Marketplace deployments

### ISSUE THREAD

**Issue by nconder** [Azure/azure-policy#305]
NSG Policy avoidance through ARM Templates or Marketplace deployments

Problem Example:
- A VM is being deployed from the Azure Marketplace with an NSG rule allow XYZ port.
- An NSG rule policy exist to deny XYZ port.
- The result is that the deployment is successful and the NSG is deployed with the XYZ port rule that is directly opposed to the policy. 
- The policy is not being evaluated. 

Solution:
- Properly evaluate the entire deployment against all policies if in conflict deny the entire deployment.
- OR properly evaluate the entire deployment against all policies if in conflict deny the NSG deployment or particular deployment of the out of compliance resource.
- Add additional alias in policy to deny conflicting deployments at the VM or network levels.

**Comment by pilor** [comment]
Can you share your policy?  NSG rules can be edited in two places.  Directly on the [NSG resource](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networksecuritygroups/createorupdate) in the securityRules array and as child ["securityRules" resources](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/securityrules/createorupdate) to the NSG.

Restrictions on NSG rules need to target both cases if you want to fully restrict the scenario.

**Comment by nconder** [comment]
@pilor you have actually addressed this in a MS ticket 118112621002828 as this not being possible unless we could have a block on creating an NSG but that this is not possible. Please feel free to email me from that ticket if you need to in case the correct information was not properly conveyed to me from the ticket owner.

My point of opening this in github was to put this in the backlog to address or get ideas from the community on ways to accomplish this.

I also have a feature request in for [extending locks to NSG rules](https://feedback.azure.com/forums/217313-networking/suggestions/36321688-extend-locks-to-individual-azure-nsg-rules). 

But here is the example, we need to block NSG rule 'allow 3389 inbound from internet' from VM Marketplace deployments or any ARM template deployment with policy. How could this be accomplished with a deny policy? We have a DiNE policy to allow 3389 from VNET so access to the VM is available. 

`{
    "properties": {
        "mode": "All",
        "parameters": {},
        "displayName": "Deny RDP open to the internet.",
        "description": "Deny RDP open to the internet.",
        "metadata": {
            "category": "InfoSec Compliance"
        },
        "policyRule": {
            "if": {
                "allOf": [{
                        "field": "type",
                        "equals": "Microsoft.Network/networkSecurityGroups/securityRules"
                    },
                    {
                        "allOf": [{
                                "field": "Microsoft.Network/networkSecurityGroups/securityRules/access",
                                "equals": "Allow"
                            },
                            {
                                "field": "Microsoft.Network/networkSecurityGroups/securityRules/direction",
                                "equals": "Inbound"
                            },
                            {
                                "anyOf": [{
                                        "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange",
                                        "equals": "3389"
                                    },
                                    {
                                        "not": {
                                            "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]",
                                            "notEquals": "3389"
                                        }
                                    }
                                ]
                            },
                            {
                                "anyOf": [{
                                        "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix",
                                        "in": [
                                            "*",
                                            "Internet"
                                        ]
                                    },
                                    {
                                        "not": {
                                            "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefixes[*]",
                                            "notIn": [
                                                "*",
                                                "Internet"
                                            ]
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            "then": {
                "effect": "deny"
            }
        }
    }
}`

**Comment by pilor** [comment]
Ah, I see.  This is dependent on planned work to improve array field handling in policy.  Once you can evaluate multiple conditions against each element in the NSG securityRules array (within the NSG resource) then this scenario can be accomplished solely with "deny" policies.  

Today your only option is to have each condition evaluated against all items in the array independently which doesn't allow you to look for "port": 3389 and "access": "deny", etc...

**Comment by nconder** [comment]
Yes, although I yield to you on the best way to handle this situation due to your expertise with Policy and think what you have suggested is on target.

**Comment by nconder** [comment]
@pilor would it be possible to evaluate a deployment with policy once it is in Accepted or Running state for NSG rules then [cancel](https://docs.microsoft.com/en-us/rest/api/resources/deployments/cancel) if an NSG rule condition is matched?

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
