### ISSUE TITLE
`Audit enabling of diagnostic logs in App Services` applies to Function Apps

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-policy#308]
#### Details of the scenario you tried and the problem that is occurring
Policy shipped with Azure Security Center called `Audit enabling of diagnostic logs in App Services` incorrectly identifies Function Apps as failing audit even though it's impossible to enable diagnostic logging for such.

https://github.com/Azure/azure-policy/tree/master/samples/Monitoring/app-service-audit-diagnostic-logs

Function apps do not have Diagnostics Logs Option 

![image](https://user-images.githubusercontent.com/13176884/52084515-e11acd00-2567-11e9-9580-c9295e0cfa14.png)

**Comment by pilor** [comment]
Thank you.  I will get in touch with Azure Security Center and come back with an update

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
