### ISSUE TITLE
Alias request: Microsoft.Network/routeTables/routes[*].nextHopIpAddress

### ISSUE THREAD

**Issue by frenky29a** [Azure/azure-policy#309]
### Scenario

We are trying to define policy which ensures that no User Defined Route in a Route Table can bypass a central network appliance (firewall) in HUB subscription.

### Alias

Microsoft.Network/routeTables/routes[*].nextHopIpAddress
Microsoft.Network/routeTables/routes.nextHopIpAddress

### Example policy definition

{
    "type": "Microsoft.Authorization/policyDefinitions",
    "properties": {
        "mode": "All",
        "parameters": {},
        "displayName": "Every UDR in RT must target NW appliance / FW",
        "description": "Every UDR in RT must target NW appliance / FW",
        "policyRule": {
            "if": {

                        "allOf": [
                            {
                                "field": "type",
                                "equals": "Microsoft.Network/routeTables"
                            },
                            {
                                "field": "Microsoft.Network/routeTables/routes[*].nextHopIpAddress",
                                "notEquals": "10.0.0.100"
                            }
                        ]

            },
            "then": {
                "effect": "deny"
            }
        }
    }
}

**Comment by bridgjr** [comment]
+1
Would like to do something similar - perhaps also exposing other fields within the route table e.g. addressprefix to enforce routing.

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.Network/routeTables have been published to public cloud. This is a milestone: the first time the policy team has published auto-generated Microsoft.Network aliases. We will be adding aliases for more resource types over the coming weeks. Thank-you for your patience everyone!
