### ISSUE TITLE
Compliance Report's Overall resource compliance is inaccurate / misleading

### ISSUE THREAD

**Issue by JamesDuggan** [Azure/azure-policy#310]
ISSUE TITLE:
The summary section of a Policy's compliance report is misleading / inaccurate.

ISSUE DESCRIPTION:
I have assigned a policy to a resource group with three Azure SQL Server resources. Only two of these resources have firewall rules defined. The compliance report suggests 35 of 37 resources passed, Given the policy only tests the type Microsoft.Sql/servers/firewallRules and since only two of the servers have firewall rules defined, then I would expect the report to state 0 of 2 resources passed, and similarly that 2 of 2 failed,

Please see image attached. 
![image](https://user-images.githubusercontent.com/4933801/52276673-b5725b00-294a-11e9-941b-543d56d9a1e4.png)

**Comment by JamesDuggan** [comment]
Hi,

the subscription is 89ee9a69-4694-4629-834c-95fcd30ccf68

The policy is assigned to resource group "resources-arm-euw" and is
named "Audit
servers_firewallRules exist"

Policy is attached.

To understand why I find the compliance summary for this policy
misleading/inaccurate, please look at the following policies that are more
specific versions of the above.

Audit servers_firewallRules named AllowAllWindowsAzureIps exist
Audit servers_firewallRules with ip 0_0_0_0 exist

Many Thanks

James

**Comment by camillemarie** [comment]
The Audit servers_firewallRules exist policy only has one condition:
```
{
    "field": "type",
    "equals": "Microsoft.Sql/servers/firewallRules"
}
```

In this case, all resources within the scope of the assignment will be considered for compliance by design. If we used the condition for both applicability and compliance, it would be impossible for any resource to ever become "compliant". 

When there are more conditions (as in the other two policy rules), then the "type" condition would be used to determine applicability.

**Comment by JamesDuggan** [comment]
That seems odd given one would expect the order to be applicability (by type if exists) then compliance. Granted that preventing a specific resource type is leaning towards edge case, notwithstanding, the purpose of the compliance summary should be to inform the number of resources that are not compliant and the total number of resources based on the type when it exists.

**Comment by camillemarie** [comment]
Compliance percentage is a bit of a subjective thing. Another person could write that same policy rule with the intent of growing it to a larger list of disallowed resource types, and would want to see all of their allowed resources flagged as compliant (Consider the "Allowed resource types" builtin policy). The policy engine errs on the side of caution and doesn't restrict applicability when a policy rule only contains type conditions.

You can still "trick" the engine into being more restrictive by adding a sham condition to your policy rule, like so: 

```
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Sql/servers/firewallRules"
      },
      {
        "field": "name",
        "notEquals": "////"
      }
    ]
  }
```


If you still have suggestions for how applicability should be improved (the more specific, the better), please raise it on [UserVoice](https://feedback.azure.com/forums/915958-azure-governance/category/345055-azure-policy), where it's easier for us to gauge support.

**Comment by JamesDuggan** [comment]
I strongly disagree. The lack of documentation and therefore clarity on how the logic of a rule is implemented and impacts compliance reporting should be perfectly clear and unambiguous. If the type is included then clearly the policy's author is interested in resources of the specified type.

Given that Azure Policy scans all resources in "all" mode and only those that can be tagged or have location in "indexed" mode, as implemented there is even more ambiguity on what the compliance summary means. 

Finally, given this is about compliance, subjectivity is the last thing that is needed.
