### ISSUE TITLE
Alias request: Microsoft.Security/advancedThreatProtectionSettings.isEnabled

### ISSUE THREAD

**Issue by DdenBraver** [Azure/azure-policy#311]
### Scenario

I would like to audit against Storage Accounts, if they have ATP enabled.
If they are not enabled I would like to use a deployIfNotExists to enable this.

currently we can use the REST-API endpoint to meet our goal, however Azure Policy is preferred.
`
Invoke-RestMethod -Uri "https://management.azure.com$($SubscriptionId)/resourceGroups/$($StorageAccountResourceGroupName)/providers/Microsoft.Storage/storageAccounts/$($StorageAccountName)/providers/microsoft.security/advancedThreatProtectionSettings/current?api-version=2017-08-01-preview" -Headers $Headers -Method Get
`

### Alias
Microsoft.Security/advancedThreatProtectionSettings
Microsoft.Security/advancedThreatProtectionSettings.isEnabled

### Example policy definition
`

        "if": {
            "allOf": [
                {
                    "field": "type",
                    "equals": "Microsoft.Storage/storageAccounts"
                },
                {
                    "field": "Microsoft.Security/advancedThreatProtectionSettings.isEnabled",
                    "equals": "false"
                }
            ]
        },
        "then": {
            "effect": "deployIfNotExists",
            "details": {
                "type": "Microsoft.Storage/storageAccounts",
                "name": "Default",
                "existenceCondition": {
                    "field": "Microsoft.Security/advancedThreatProtectionSettings.isEnabled",
                    "equals": "true"
                },
                "roleDefinitionIds": [
                    "/providers/microsoft.authorization/roleDefinitions/17d1049b-9a84-46fb-8f53-869881c3d3ab"
                ],
                "deployment": {
                    "properties": {
                        "mode": "incremental",
                        "parameters": {
                            "storageAccountName": {
                                "value": "[field('name')]"
                            },
                            "location": {
                                "value": "[field('location')]"
                            }
                        },
                        "template": {
                            "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                            "contentVersion": "1.0.0.0",
                            "parameters": {
                                "storageAccountName": {
                                    "type": "string"
                                },
                                "location": {
                                    "type": "string"
                                },
                                "kind": {
                                    "type": "string"
                                }
                            },
                            "resources": [
                                {
                                    "apiVersion": "2017-08-01-preview",
                                    "type": "Microsoft.Storage/storageAccounts",
                                    "name": "[parameters('storageAccountName')]",
                                    "location": "[parameters('location')]",
                                    "kind": "[parameters('kind')]",
                                    "resources": {
                                        "type": "Microsoft.Security",
                                        "name": "current",
                                        "apiVersion": "2017-08-01-preview",
                                        "properties": {
                                            "isEnabled": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }

`

**Comment by mentat9** [comment]
This alias has been published. Please give it a try.
