### ISSUE TITLE
Alias request: Microsoft.EventHub/namespaces/networkruleset/virtualNetworkRules

### ISSUE THREAD

**Issue by JohnnyB85** [Azure/azure-policy#312]
### Scenario

Restrict access to an Azure Event Hub to specific, approved VNETs via VNET Service Endpoints

### Alias

Microsoft.EventHub/namespaces/networkruleset/virtualNetworkRules[*].subnet.id

### Example policy definition

{
    "properties": {
      "displayName": "Azure Event Hub - VNET Service Endoints - Allow approved VNETs only",
      "description": "Restrict access to approved VNETs",
      "parameters": {
        "approvedVnetIDs": {
          "type": "Array",
          "metadata": { "description": "list of VNET IDs" }
        }
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.EventHub/namespaces/networkruleset/virtualNetworkRules"
          },
          {
            "not": {
              "field": "Microsoft.EventHub/namespaces/networkruleset/virtualNetworkRules[*].subnet.id",
              "in": "[parameters('approvedVnetIDs')]"
            }
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }
  }

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.EventHub has been published, including this one. Please try it out.

**Comment by mikaelsnavy** [comment]
Hi @JohnnyB85 - were you ever to get your Event Hub VNET policy to work? I can't seem to get the Policy alias to work!

**Comment by mentat9** [comment]
@mikaelsnavy can you elaborate on what's not working?

**Comment by mikaelsnavy** [comment]
Hi @mentat9, I'm trying to write a Policy against the alias ```Microsoft.EventHub/namespaces/networkRuleSets/default.defaultAction``` and I cannot get any Policy to have a true evaluation against this field. I was hoping to gain insight from the virtualNetworkRules alias. :smile: 

Here is my policy I'm working with (I have the ```like``` condition in the policy as a temporary measure until I can get anything to trigger of the defaultAction field).
```
"policyRule": {
      "if": {
        "allOf": [
          {
            "field": "Microsoft.EventHub/namespaces/networkRuleSets/default.defaultAction",
            "equals": "Allow"
          },
          {
            "field": "type",
            "like": "Microsoft.EventHub/*"
          }
        ]
      },
      "then": {
        "effect": "audit"
      }
    }
``` 
Here is the json output from ```az resource show``` for the resource that I feel should be picked by my Policy however there are 0 compliant and 0 non-compliant resources.
![image](https://user-images.githubusercontent.com/753437/58221309-f2c6e280-7cc6-11e9-88b2-7e79148be7c8.png)

Am I missing something obvious?? 

Thanks so much for responding!
Mikael

**Comment by mikaelsnavy** [comment]
Hey @mentat9 I was playing with this tonight and realized I need to be using the field `Microsoft.EventHub/namespaces/networkRuleSet/default.defaultAction`not `Microsoft.EventHub/namespaces/networkRuleSets/default.defaultAction`. Looks like it's working now!

**Comment by mentat9** [comment]
Thanks for the update @mikaelsnavy. Glad it's working for you now. We have discovered that the way the event hub team published these resource types has resulted in some policy features not working. We created both sets of aliases to try and work around some earlier issues, but some others remain. I don't think you will see compliance checks work for this resource type unfortunately. We are working with the event hub team to try and get the issues corrected so policies can fully work. Sorry for the inconvenience! Also, fair warning: there is a similar set of issues for Microsoft.ServiceBus/namespaces/networkRuleSet[s] resource types.

**Comment by mikaelsnavy** [comment]
That makes sense @mentat9, thanks for the update. I was able to get a Policy evaluation to trigger once, but not again (even with no modifications to the Policy, assignment, or resource). I'm definitely still seeing issues. :disappointed: Would it be helpful to open another issue? Also, if so, is this a good place to surface similar issues we're experiencing with Policy? Thanks!

**Comment by mentat9** [comment]
If you are having difficulties getting policies working and don't see any previous issues that appear to address it, then open a new issue here. Of course, if you are dealing with a livesite issue, open a CSS ticket.

As far as whether you should move this one to a new issue, it's up to you: it won't affect our work either way (we track comments on closed issues as well). I don't plan to reopen this issue, since its original point has been resolved, but I also slightly prefer to not fork the follow-up to a new issue. I think search results are usually better from conversations that haven't been split up.
