### ISSUE TITLE
Azure sql firewall policy(allowallazureservices) is working for only while creating the server.I can still go and update firewall.

### ISSUE THREAD

**Issue by sonalikaroy** [Azure/azure-policy#314]
Azure sql firewall policy(allowallazureservices) is working for only while creating the server.I can still go and update firewall.

{
  "if": {
    "anyof": [
      {
        "allOf": [
          {
            "field": "Microsoft.Sql/servers/firewallRules/startIpAddress",
            "equals": "0.0.0.0"
          },
          {
            "field": "Microsoft.Sql/servers/firewallRules/endIpAddress",
            "equals": "0.0.0.0"
          }
        ]
      },
      {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Sql/servers/firewallRules"
          },
          {
            "field": "Microsoft.Sql/servers/firewallRules/startIpAddress",
            "equals": "0.0.0.0"
          },
          {
            "field": "Microsoft.Sql/servers/firewallRules/endIpAddress",
            "equals": "0.0.0.0"
          }
        ]
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
