### ISSUE TITLE
Policy to restrict Microsoft.Network/publicIPAddresses by subscription and resource group

### ISSUE THREAD

**Issue by ztbrumbaugh** [Azure/azure-policy#315]
I'd like to access the id field of a publicIPAddresses resource. I think should actually be one of the direct fields accessed in policy, and not an alias and available across all resource types similar to "location", but that does not appear to be the case. By checking against the id, I could determine if the resource matches a naming convention or which subscriptions and resource groups are approved to use the publicIPAddresses resource.

Example policy definition

Direct Field
```json
  {
    "if": {
      "field": "id",
      "contains": "{subscriptionID}/{resourceGroupName}"
    },
    "then": {
      "effect" : "deny"
    }
  }
```

Alias
```json
  {
    "if": {
      "field": "Microsoft.Network/publicIPAddresses/id",
      "contains": "{subscriptionID}/{resourceGroupName}"
    },
    "then": {
      "effect" : "deny"
    }
  }
```

**Comment by mentat9** [comment]
You are correct that id is not a field we create aliases for, but it also is not available to use directly. Would something like this work for you?
```
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Network/publicIPAddresses"
        },
        {
          "value": "[resourceGroup().name]",
          "equals": "{SomeResourceGroup}"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  },
```

To restrict by subscription, you would assign the policy to a [set of] subscription[s] or management group[s]. You could also use "like" instead of "equals" on the value to do wildcard pattern matching.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
