### ISSUE TITLE
Need Alias to Audit / Enforce the collation for SQL database

### ISSUE THREAD

**Issue by PeterSkoglund** [Azure/azure-policy#316]
I'd like to access the collation field of a Microsoft.Sql/servers/databases resource.  By checking against the collation , I could determine if the resource matches a enforrced collation convention.

Example policy definition

{
  "properties": {
    "displayName": "Audit If collation is wrong",
    "description": "Audit If collation is not Finnish_Swedish_CI_AS this database",
    "parameters": {

    },
    "policyRule": {
        "if": {
          "allOf": [
            {
              "not": {
                "equals": "Finnish_Swedish_CI_AS",
                "field": "Microsoft.Sql/servers/databases.collation"
              }
            },
              {
                "equals": "Microsoft.Sql/servers/databases",
                "field": "type"
              }
   
          ]
        },
        "then": {
          "effect": "audit"
        }
      }
    }
}

**Comment by mentat9** [comment]
The full set of aliases for Microsoft.Sql have been published. The one you are looking for is ```Microsoft.Sql/managedInstances/databases/collation```. Please give it a try.
