### ISSUE TITLE
Alias request: Microsoft.Network/trafficManager/endpoints.type

### ISSUE THREAD

**Issue by NickFadz** [Azure/azure-policy#318]
I am attempting to limit the endpoint types allowed on my traffic manager to exclude External Endpoints.

"if": {
  "field": "Microsoft.Netowrk/trafficManagerProflies/endpoints.type",
  "equals": "Microsoft.Network/trafficManagerProfiles/externalEndpoints"
},
"then": {
  "effect": "deny"
}

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.Network/trafficManagerProfiles has been published, including endpoints[*].type.
