### ISSUE TITLE
How do you find deallocated machines for certain amount of time?

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-policy#319]
There seems to be no clean way to find out how long VM has been in deallocated state. I imagine it shall be pretty common requirement to audit wasted resources by auditing machines which are deallocated for certain amount of time. Neither Azure Advisor or policy exists to address this issue.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
