### ISSUE TITLE
Microsoft.OperationalInsights/workspaces

### ISSUE THREAD

**Issue by brakelee** [Azure/azure-policy#321]
### Scenario

What are you trying to achieve using Azure Policy?
After the automatic deployment of a subscription an OMS workspace has to be created automatically via a policy.

### Alias

- What resource provider and resource type is involved?
Microsoft.OperationalInsights
- What property on that resource type do you wish to expose?
workspace
### Example policy definition
"Properties": {
        "displayName": "4.1.2-deploy-loganalyticsworkspace",
        "policyType": "Custom",
        "mode": "indexed",
        "description": "This policy ensures that every new subscription has a default workspace",
        "metadata": {
            "category": "LogAnalytics-workspace"
        },
        "parameters": {},
        "variables": {
            "name": "Workspace",
            "location": "westeurope",
            "sku": "pernode",
            "searchVersion": "1"
        },
        "policyRule": {
            "if": {
                "field": "type",
                "equals": "Microsoft.OperationalInsights/workspaces"
            },
            "then": {
                "effect": "DeployIfNotExists",
                "details": {
                    "type": "Microsoft.OperationalInsights/workspaces",
                    "name": "Default",
                    "existenceCondition": {
                        "field": "Microsoft.OperationalInsights/workspaces",
                        "equals": "Enabled"
                    },
                    "roleDefinitionIds": [
                        "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20w2342dd24c"
                    ],
                    "deployment": {
                        "properties": {
                            "mode": "incremental",
                            "template": {
                                "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                                "contentVersion": "1.0.0.0",
                                "resources": [
                                    {
                                        "type": "Microsoft.OperationalInsights/workspaces",
                                        "name": "[variables('name')]",
                                        "apiVersion": "2017-03-15-preview",
                                        "location": "[variables('location')]",
                                        "properties": {
                                            "sku": {
                                                "name": "[variables('sku')]"
                                            },
                                            "features": {
                                                "searchVersion": "[variables('searchVersion')]"
                                            }
                                        }
                                    }
                                ]
                            },
                            "parameters": {
                                "serverName": {
                                    "value": "[field('name')]"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "PolicyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/e7dec1f7-ace5-48df-b4be-462f516fb412"
}

**Comment by krnese** [comment]
This doesn't require an alias, but must be a subscription level template deployment for deployIfNotExists. Is that what you are looking for?

**Comment by mentat9** [comment]
Full set of aliases has been generated for Microsoft.OperationalInsights, including the requested ones, so I'm closing this request. @brakelee, feel free to open another issue, or continue this thread if you have difficulty getting your scenario working.
