### ISSUE TITLE
Alias request: Microsoft.Network/applicationGateways/backendHttpSettings[*]

### ISSUE THREAD

**Issue by tcanelas** [Azure/azure-policy#322]
### Scenario

Enforce backendHttpSettings ports and protocols

### Alias
* Resource Provider: `Microsoft.Network`
* Resource Type: `applicationGateways`
* Property: `backendHttpsSettings[*].properties.port`, `backendHttpsSettings[*].properties.protocol`

### Example policy definition

```
{
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "Microsoft.Network/applicationGateways"
            },
            {
                "not":{
                    "field": "Microsoft.Network/applicationGateways/backendHttpSettings[*].port",
                    "Equals": "443"
                }
            },
            {
                "not":{
                    "field": "Microsoft.Network/applicationGateways/backendHttpSettings[*].protocol",
                    "Equals": "https"
                }
            }
        ]
    },
    "then": {
        "effect": "Deny"
    }
}
```

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.Network/applicationGateways has been published in public cloud, including ```Microsoft.Network/applicationGateways/backendHttpSettingsCollection[*]```.
