### ISSUE TITLE
Alias bug: Microsoft.Network/applicationgateways/frontendPorts[*].ports

### ISSUE THREAD

**Issue by tcanelas** [Azure/azure-policy#324]
#### Details of the scenario you tried and the problem that is occurring
Using this policy:
policy1
```
{
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "Microsoft.Network/applicationGateways"
            },
            {
                "not":{
                    "field": "Microsoft.Network/applicationGateways/frontendPorts[*].port",
                    "equals": "443"
                }
            }
        ]
    },
    "then": {
        "effect": "Deny"
    }
}
```
**Expected Result** : 
It should deny when any of the frontendPorts.port is not 443
not(443=443 && 80=443) = not(true && false) = not(false) = true then deny
**Actual Result**:
It denies when any of the frontendPorts is 443
It does the Expected result using this policy:
policy2
```
{
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "Microsoft.Network/applicationGateways"
            },
            {
                "not":{
                    "field": "Microsoft.Network/applicationGateways/frontendPorts[*].port",
                    "notequals": "443"
                }
            }
        ]
    },
    "then": {
        "effect": "Deny"
    }
}
```
Which is not logic as it works in a reverse way compared to other policies
**To reproduce the issue** : 
Assign policy1
Create an application gateway with frontend port 443 --> It will be denied by policy1
#### If policy is Guest Configuration - details about target node
Target is to deny the creation of application gateways using anything else than port 443 in any frontend configuration

**Comment by camillemarie** [comment]
@mentat9 This looks like a bug in the Microsoft.Network/applicationGateways/frontendPorts[*].port alias

The path for alias Microsoft.Network/applicationGateways/frontendPorts[*].port is incorrect.

It is:     
    `properties.frontendPorts[*].port`
It should be:    
    `properties.frontendPorts[*].properties.port`


----------------------------
## Details

#### Results of Get-AzureRmPolicyAlias cmdlet

`Get-AzureRmPolicyAlias -AliasMatch "frontendPorts" | select -expand Aliases |select Name -expand Paths`

returns:

Name                                                         | Path                            
------------------------------------------------------------ | --------------------------------
Microsoft.Network/applicationGateways/frontendPorts[*].port  | properties.frontendPorts[*].port

#### Sample resource
```
{
  "type": "Microsoft.Network/applicationGateways",
  "location": "eastus",
  "properties": {
    "frontendPorts": [
      {
        "name": "appGatewayFrontendPort",
        "properties": {
          "Port": 443
        }
      }
    ]
  }
}
```
See [ApplicationGateways](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2018-10-01/applicationgateways).

**Comment by mentat9** [comment]
Yes, thanks @tcanelas for the report and @camillemarie for the spot-on investigation. I've fixed the alias manifest. Given that it's Microsoft.Network, I can't deploy it myself, but I've queued it up with the NRP team at high priority. Sorry for the inconvenience: I'll update this issue when it's deployed.

**Comment by mentat9** [comment]
This alias has been fixed, although it may take a day or so to propagate to all ARM caches in all regions. Please give it a try.
