### ISSUE TITLE
Microsoft.Web/hostingEnvironments/internalLoadBalancingMode

### ISSUE THREAD

**Issue by fboukezzoula** [Azure/azure-policy#325]
**Microsoft.Web/hostingEnvironments/internalLoadBalancingMode**

We want to be sure that the ASE is using an internalLoadBalancing before any deployment (effect : Deny)

Microsoft.Web/hostingEnvironments/internalLoadBalancingMode = "None" for VIP Public

**Comment by mentat9** [comment]
The full set of aliases for Microsoft.Web, including this one has been published. Please give it a try.
