### ISSUE TITLE
Incorrect URL for deploy-sql-server-auditing PowerShell Deployment

### ISSUE THREAD

**Issue by RichShillingtonMSFT** [Azure/azure-policy#327]
The URL for deploy-sql-server-auditing PowerShell Deployment has a typo.
Is: https://raw.githubusercontent.com/Azure/azure-policy/master/samples/SQL/deploysql-server-auditing/azurepolicy.rules.json

Should be: https://raw.githubusercontent.com/Azure/azure-policy/master/samples/SQL/deploy-sql-server-auditing/azurepolicy.rules.json

Issue: It is missing the - between deploy and sql. deploysql vs deploy-sql

**Comment by DCtheGeek** [comment]
Thanks @RichShillingtonMSFT. I also noticed that **[Preview]** has been removed from the built-in in the portal, so also updated that in the PR.
