### ISSUE TITLE
Alias Request: Microsoft.Compute/VirtualMachines/availabilityZone.id

### ISSUE THREAD

**Issue by ChendrayanV** [Azure/azure-policy#330]
### Scenario

What are you trying to achieve using Azure Policy?
We need end users to choose availability options (Availability Zone / Availability Set) - Users can opt the one as per the requirement and support availability. For availability set we have alias so policy enforced works as expected. Adding the alias **_Microsoft.Compute/VirtualMachines/availabilityZone.id_** will solve our requirement

### Alias

- What resource provider and resource type is involved? **Microsoft.Compute/VirtualMachines**
- What property on that resource type do you wish to expose? **AvailabilityZone**

### Example policy definition

```JSON
{
    "mode": "indexed",
    "policyRule": {
        "if": {
            "allOf": [
                {
                    "field": "type",
                    "equals": "Microsoft.Compute/virtualMachines"
                },
                {
                    "not": {
                        "field": "Microsoft.Compute/virtualMachines/availabilityZone.id",
                        "exists": "true"
                    }
                }
            ]
        },
        "then": {
            "effect": "deny"
        }
    },
    "parameters": {}
}
```

**Comment by mentat9** [comment]
It looks like the field you want to manage is not published in the Azure Open APIs. Azure Policy only supports policies that manage published fields present both in GET and PUT requests, so we can't add the above aliases. However, it sounds like the ```zones``` alias might be an alternative for you. That has already been requested here: https://github.com/Azure/azure-policy/issues/288, and the work to add it is under way.
