### ISSUE TITLE
KeyVault AccessPolicies: The operation 'Read' is disallowed on resource type vaults/accessPolicies

### ISSUE THREAD

**Issue by hrboyceiii** [Azure/azure-policy#333]
#### Details of the scenario you tried and the problem that is occurring
I am trying to use the new KeyVault aliases for accessPolicies (see issue #280) to append/replace accessPolicy entries on vaults using the following `deployIfNotExists` policy:

```json
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.KeyVault/vaults"
      },
      {
        "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId",
        "notIn": "[parameters('allowedObjectIds')]"
      }
    ]
  },
  "then": {
    "effect": "deployIfNotExists",
    "details": {
      "type": "Microsoft.Authorization/policyAssignments",
      "name": "DoesNotExist101a",
      "roleDefinitionIds": [
        "/providers/Microsoft.Authorization/roleDefinitions/f25e0fa2-a7c8-4377-a976-54943a77a395",
        "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
      ],
      "deployment": {
        "properties": {
          "mode": "Incremental",
          "template": {
            "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
            "contentVersion": "1.0.0.0",
            "parameters": {
              "vaultName": {
                "type": "string"
              },
              "objectIds": {
                "type": "array"
              },
              "applicationIds": {
                "type": "array",
                "defaultValue": [
                  1
                ]
              }
            },
            "variables": {
              "vaultResourceId": "[resourceId('Microsoft.KeyVault/vaults', parameters('vaultName'))]",
              "getVaultDeploymentName": "[concat('getVaultName-', parameters('vaultName'))]",
              "getVaultTransformedAccessPolicies": "[concat('getVaultName-', parameters('vaultName'), 'transformedAPs')]",
              "accessPolicies": {
                "copy": [
                  {
                    "name": "objects",
                    "count": "[length(parameters('objectIds'))]",
                    "input": {
                      "tenantId": "[subscription().tenantId]",
                      "objectId": "[parameters('objectIds')[copyIndex('objects')]]",
                      "permissions": {
                        "keys": [
                          "get",
                          "list"
                        ],
                        "certificates": [
                          "get",
                          "list"
                        ],
                        "secrets": [
                          "get",
                          "list"
                        ],
                        "storage": [
                          "get",
                          "list"
                        ]
                      }
                    }
                  },
                  {
                    "name": "applications",
                    "count": "[length(parameters('applicationIds'))]",
                    "input": {
                      "tenantId": "[subscription().tenantId]",
                      "applicationId": "[parameters('applicationIds')[copyIndex('applications')]]",
                      "permissions": {
                        "keys": [
                          "get",
                          "list"
                        ],
                        "certificates": [],
                        "secrets": [],
                        "storage": []
                      }
                    }
                  }
                ]
              },
              "transformedAccessPolicies": {
                "accessPolicies": "[concat(variables('accessPolicies').objects, variables('accessPolicies').applications)]"
              }
            },
            "resources": [
              {
                "apiVersion": "2018-02-01",
                "type": "Microsoft.Resources/deployments",
                "name": "[variables('getVaultDeploymentName')]",
                "properties": {
                  "mode": "Incremental",
                  "template": {
                    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "resources": [],
                    "outputs": {
                      "vaultProperties": {
                        "type": "object",
                        "value": "[reference(variables('vaultResourceId'), '2018-02-14', 'Full')]"
                      }
                    }
                  }
                }
              },
              {
                "apiVersion": "2018-02-01",
                "type": "Microsoft.Resources/deployments",
                "name": "[variables('getVaultTransformedAccessPolicies')]",
                "properties": {
                  "mode": "Incremental",
                  "template": {
                    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "resources": [],
                    "outputs": {
                      "transformedAccessPolicies": {
                        "type": "object",
                        "value": {
                          "properties": {
                            "accessPolicies": "[concat(reference(variables('vaultResourceId'), '2018-02-14', 'Full').properties.accessPolicies, variables('accessPolicies').objects)]"
                          }
                        }
                      }
                    }
                  }
                }
              },
              {
                "name": "[concat(parameters('vaultName'), '/replace')]",
                "type": "Microsoft.KeyVault/vaults/accessPolicies",
                "apiVersion": "2018-02-14",
                "properties": {
                  "accessPolicies": "[reference(variables('getVaultTransformedAccessPolicies')).outputs.transformedAccessPolicies.value.properties.accessPolicies]"
                }
              }
            ]
          },
          "parameters": {
            "vaultName": {
              "value": "[field('name')]"
            },
            "objectIds": {
              "value": "[parameters('allowedObjectIds')]"
            }
          }
        }
      }
    }
  }
}
```

The policy successfully identifies existing non-compliant resources and marks the as not compliant.  Trying to remediate the resources using a remediation task fails; new resources created while the policy is active also fail automatic remediation with the same error.

Policy defines both Contributor and KeyVault Contributor RBAC permissions.  I thought Contributor might be necessary for the read permission/operation mentioned in the error, however, that does not resolve the issue

#### Verbose logs showing the problem
"The attempt to retrieve resources of type 'Microsoft.KeyVault/vaults/accessPolicies' for the 'DeployIfNotExists' policy resulted in a BadRequest response with error '{\"error\":{\"code\":\"DisallowedResourceOperation\",\"message\":\"The operation 'read' on resource type 'vaults/accessPolicies' is disallowed.\"}}'."

Region is East US 2.

Can provide sub and tenant IDs at request if useful

#### Suggested solution to the issue
Remediation tasks and auto-remediation deployments should succeed.

**Comment by stefangordon** [comment]
I am able to reproduce the same issue and am also blocked by it.   

In my case I was attempting to add a new policy

```
{
    "policyRule": {
      "if": {
          "field": "type",
          "equals": "Microsoft.KeyVault/vaults"
      },
      "then": {
          "effect": "DeployIfNotExists",
          "details": {
              "type": "Microsoft.KeyVault/vaults/accessPolicies",
              "name": "current",
              "roleDefinitionIds": [
                  "/providers/Microsoft.Authorization/roleDefinitions/f25e0fa2-a7c8-4377-a976-54943a77a395"
              ],
              "existenceCondition": {
                  "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId",
                  "equals": "[parameters('userObjectId')]"
              },
              "deployment": {
                  "properties": {
                      "mode": "incremental",
                      "template": {
                          "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                          "contentVersion": "1.0.0.0",
                          "parameters": {
                                "objectId": {
                                  "type": "string"
                                },
                                "keyVaultName": {
                                  "type": "string"
                                },
                                "secretsPermissions": {
                                    "type": "array",
                                    "defaultValue": [
                                      "list"
                                    ]
                                }
                          },
                          "resources": [
                            {
                              "type": "Microsoft.KeyVault/vaults/accessPolicies",
                              "name": "[concat(parameters('keyVaultName'), '/add')]",
                              "apiVersion": "2018-02-14",
                              "properties": {
                                "accessPolicies": [
                                  {
                                    "tenantId": "[parameters('tenantId')]",
                                    "objectId": "[parameters('objectId')]",
                                    "permissions": {
                                      "secrets": "[parameters('secretsPermissions')]"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                      },
                      "parameters": {
                          "objectId": {
                              "value": "[parameters('userObjectId')]"
                          },
                          "tenantId": {
                            "value": "[field('Microsoft.Keyvault/vaults/tenantId')]"
                          },
                          "keyVaultName": {
                            "value": "[field('name')]"
                          }
                      }
                  }
              }
          }
      }
    },
    "parameters": {
      "userObjectId": {
        "type": "String",
        "metadata": {
          "description": "The GUID for the user which should have access",
          "displayName": "User Object ID"
        }
      }
    }
  }
```

**Comment by stefangordon** [comment]
@hrboyceiii I think we may have the type wrong, it wasn't clear admittedly.   We both used the type from the template which isn't how it works I believe.

So `Microsoft.KeyVault/vaults/accessPolicies` is wrong.

try:
```
      "then": {
          "effect": "DeployIfNotExists",
          "details": {
              "type": "Microsoft.KeyVault/vaults",
```

It takes forever to test this, so I haven't confirmed a successful creation yet, but it did eliminate that error.

**Comment by stefangordon** [comment]
I have not been able to find any way to do this successfully, but it has been a very common request.  Hopefully we can get some feedback from the Policy team.

**Comment by hrboyceiii** [comment]
I concur with @stefangordon -- I've tried a different policy, referencing the /accessPolicies alias in the existanceCondition and that yields the same 'Read' operation error.

Thoughts on workarounds or fixes for this issue?

**Comment by mentat9** [comment]
OK, the basic issue (Read operation disallowed) is due to referencing type Microsoft.Keyvault/vaults/accessPolicies. The first policy got the error by using it in the deployment template. The second policy got in the same error, but due to using that type in the policy if condition. Since it's not actually a resource type, a failure is not entirely unexpected, although the fact that the Keyvault RP disallows retrieving that particular path is a little unexpected. In any case, referencing that path in policy just won't work.

Unfortunately, without being able to specify that path as a type, it's not possible to specify the incremental syntax in the template to add an access policy (PUT to …/add) that appears to be special to Keyvault. Even though it works with a straight ARM deployment, it does not work with a DeployIfNotExist policy, because the policy engine attempts to retrieve the resource type specified in the template prior to submitting the deployment job, and stops when it gets the failure.

So we've worked out a different approach for this scenario. You should be able to extend this policy as needed. This policy operates at the vault level by checking whether the given access policy already exists and if not, deploys the vault with the access policy added, which turns into an update to add the new access policy:

```
{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.KeyVault/vaults"
        },
        {
          "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId",
          "notEquals": "[parameters('userObjectId')]"
        }
      ]
    },
    "then": {
      "effect": "DeployIfNotExists",
      "details": {
        "type": "Microsoft.KeyVault/vaults",
        "name": "current",
        "roleDefinitionIds": [
          "/providers/Microsoft.Authorization/roleDefinitions/f25e0fa2-a7c8-4377-a976-54943a77a395"
        ],
        "deployment": {
          "properties": {
            "mode": "incremental",
            "template": {
              "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
              "contentVersion": "1.0.0.0",
              "parameters": {
                "objectId": {
                  "type": "string"
                },
                "keyVaultName": {
                  "type": "string"
                },
                "secretsPermissions": {
                  "type": "array",
                  "defaultValue": [
                    "list"
                  ]
                },
                "tenantId": {
                  "type": "string"
                },
                "location": {
                  "type": "string"
                },
                "sku": {
                  "type": "object"
                },
                "existingAccessPolicies": {
                  "type": "array",
                  "defaultValue": []
                }
              },
              "variables": {
                "accessPolicies": [
                  {
                    "tenantId": "[parameters('tenantId')]",
                    "objectId": "[parameters('objectId')]",
                    "permissions": {
                      "secrets": "[parameters('secretsPermissions')]"
                    }
                  }
                ]
              },
              "resources": [
                {
                  "type": "Microsoft.KeyVault/vaults",
                  "name": "[parameters('keyVaultName')]",
                  "location": "[parameters('location')]",
                  "apiVersion": "2018-02-14",
                  "properties": {
                    "sku": "[parameters('sku')]",
                    "tenantId": "[parameters('tenantId')]",
                    "accessPolicies": "[concat(parameters('existingAccessPolicies'), variables('accessPolicies'))]"
                  }
                }
              ]
            },
            "parameters": {
              "objectId": {
                "value": "[parameters('userObjectId')]"
              },
              "tenantId": {
                "value": "[field('Microsoft.Keyvault/vaults/tenantId')]"
              },
              "keyVaultName": {
                "value": "[field('name')]"
              },
              "location": {
                "value": "[field('location')]"
              },
              "sku": {
                "value": "[field('Microsoft.Keyvault/vaults/sku')]"
              },
              "existingAccessPolicies": {
                "value": "[field('Microsoft.Keyvault/vaults/accessPolicies')]"
              }
            }
          }
        }
      }
    }
  },
  "parameters": {
    "userObjectId": {
      "type": "String",
      "metadata": {
        "displayName": "User Object ID",
        "description": "The GUID for the user which should have access"
      }
    }
  }
}
```

**Comment by rnielsenwiz** [comment]
``Here is what I put together that appears to meet the criteria. 
`{
  "properties": {
    "displayName": "Key Vault access policy should exist",
    "policyType": "Custom",
    "mode": "All",
    "description": "This policy checks for the existence of the Key Vault access policy and remediates during the creation of a new Key Vault",
    "metadata": {
      "category": "Key Vault",
      "createdBy": "56817a7a-b281-4822-b6d9-e125a438bef5",
      "createdOn": "2023-03-09T14:58:46.6401486Z",
      "updatedBy": "56817a7a-b281-4822-b6d9-e125a438bef5",
      "updatedOn": "2023-03-09T16:13:08.4332977Z"
    },
    "parameters": {
      "effect": {
        "type": "String",
        "metadata": {
          "displayName": "Effect",
          "description": "Enable or disable the execution of the policy"
        },
        "allowedValues": [
          "DeployIfNotExists",
          "Disabled",
          "AuditIfNotExists"
        ],
        "defaultValue": "DeployIfNotExists"
      },
      "AadObjectId": {
        "type": "String",
        "metadata": {
          "displayName": "AAD Object ID",
          "description": "The objectId of the principal to ensure access for."
        }
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.KeyVault/vaults"
          },
          {
            "field": "Microsoft.KeyVault/vaults/enableRbacAuthorization",
            "equals": "false"
          }
        ]
      },
      "then": {
        "effect": "[parameters('effect')]",
        "details": {
          "type": "Microsoft.KeyVault/vaults",
          "name": "[field('name')]",
          "existenceCondition": {
            "count": {
              "field": "Microsoft.Keyvault/vaults/accessPolicies[*]",
              "where": {
                "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId",
                "equals": "[parameters('AadObjectId')]"
              }
            },
            "greater": 0
          },
          "roleDefinitionIds": [
            "/subscriptions/8cf7ee65-5ae1-48af-85c1-dc96f2b83741/providers/Microsoft.Authorization/roleDefinitions/f25e0fa2-a7c8-4377-a976-54943a77a395"
          ],
          "evaluationDelay": "AfterProvisioning",
          "deployment": {
            "properties": {
              "mode": "incremental",
              "template": {
                "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
                "contentVersion": "1.0.0.0",
                "parameters": {
                  "vaultName": {
                    "type": "string"
                  },
                  "principalObjectId": {
                    "type": "string"
                  }
                },
                "resources": [
                  {
                    "type": "Microsoft.KeyVault/vaults/accessPolicies",
                    "name": "[concat(parameters('vaultName'), '/add')]",
                    "apiVersion": "2019-09-01",
                    "properties": {
                      "accessPolicies": [
                        {
                          "tenantId": "[subscription().tenantId]",
                          "objectId": "[parameters('principalObjectId')]",
                          "permissions": {
                            "keys": [
                              "list"
                            ],
                            "secrets": [
                              "list"
                            ],
                            "certificates": [
                              "list",
                              "listissuers"
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              },
              "parameters": {
                "vaultName": {
                  "value": "[field('name')]"
                },
                "principalObjectId": {
                  "value": "[parameters('AadObjectId')]"
                }
              }
            }
          }
        }
      }
    }
  },
 `
