### ISSUE TITLE
Azure Policy for type Microsoft.Web/hostingEnvironments and field tags not working as expected

### ISSUE THREAD

**Issue by atul-contino** [Azure/azure-policy#334]
Below is the policy rule,

"if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Web/hostingEnvironments"
          },
          {
            "field": "tags.compliance:STD:v1_0_0",
            "contains": "NON-ILB-ASE"
          }
        ]
      },
      "then": {
        "effect": "audit"
      }

**Comment by atul-contino** [comment]
Do we have any update on this?

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
