### ISSUE TITLE
Alias request: microsoft.devtestlab/schedules/targetResourceId

### ISSUE THREAD

**Issue by joranm** [Azure/azure-policy#336]
### Scenario

We would like to create an Azure Policy which allow us to perform an auditIfNotExists or deployIfNotExist if a virtual machine is not configured with autoshutdown. We need to check if the virtual machines within a specific (dev/test) subscription are part of an microsoft.devtestlab/schedules/taskType auto shutdown schedule and registered in microsoft.devtestlab/schedules/targetResourceId

### Alias
RP: microsoft.devtestlab
RT: /schedules
properties: taskType and targetResourceId

### Example policy definition
{
  "mode": "all",
  "parameters": { },
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Compute/virtualMachines"
        }
      ]
    },
    "then": {
      "effect": "auditIfNotExists",
      "details": {
        "type": "microsoft.devtestlab/schedules",
        "existenceCondition": {
          "allOf": [
            {
              "field": "taskType",
              "like": "ComputeVmShutdownTask"
            },
            {
              "field": "targetResourceId",
              "like": "[field('name')]"
            }
          ]
        }
      }
    }
  }
}

**Comment by mentat9** [comment]
The full set of Microsoft.DevTestLab aliases has been published, including this one. Please try it out.
