### ISSUE TITLE
Alias request: Microsoft.Security/policies/securityContactConfiguration

### ISSUE THREAD

**Issue by VOVELEE** [Azure/azure-policy#338]
### Scenario
Ensure Proper security contact configuration is applied amongst all subscriptions under a tenant. Currently exposed alias Microsoft.Security/policies doesn't prevent changing security contacts details. See below in "Example of non-working deny assignment"

### Alias

**- What resource provider and resource type is involved?**
Microsoft.Security
**- What property on that resource type do you wish to expose?**
Microsoft.Security/policies/properties.securityContactConfiguration

### Example policy definition

``` JSON
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Security/securityContactConfiguration"
      },
      {
        "not": {
          "field": "Microsoft.Security/securityContactConfiguration/sendToAdminOn",
          "equals": "true"
        }
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}
```

### Example of non-working deny assignment of current exposed aliases
The policy below correctly recognizes non-compliant resources but doesn't prevent changing to incorrect setting
```JSON 
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Security/policies"
      },
      {
        "allOf": [
          {
            "field": "Microsoft.Security/policies/policyLevel",
            "equals": "Subscription"
          },
          {
            "not": {
              "field": "Microsoft.Security/policies/securityContactConfiguration.areNotificationsOn",
              "equals": "true"
            }
          }
        ]
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}
```

**Comment by dorpo** [comment]
Hey,

We're working on deprecating this alias (since the API behind it is under a derprecation process).

The security contact configuration is also available through a slimmer API (Microsoft.Security/securityContacts) and we'll provide an alias to that in the next few days.

I'll reply on this thread as soon as it's available.

**Comment by VOVELEE** [comment]
Sounds good :)
Looking forward for the aliases

**Comment by dorpo** [comment]
Hi,

According to the example you presented I'll supply an equivalent with going through "Microsoft.Security/policies/".
In general, it's good to avoid this API and its corresponding aliases, as it will be deprecated soon.

`{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Security/securityContacts"
      },
      {
        "not": {
          "field": "Microsoft.Security/securityContacts/alertsToAdmins",
          "equals": "true"
        }
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}`

Explained:

"Microsoft.Security/securityContactConfiguration" -> should be transitioned to 
"Microsoft.Security/securityContacts"

"Microsoft.Security/securityContactConfiguration/sendToAdminOn" -> should be transitioned to 
"Microsoft.Security/securityContacts/alertToAdmins"

The previous API (policies), held a single member called securityContactConfiguration with all the content of security contacts. The recent API (securityContacts), treats each element in the response as a contact.

Small Discalimer, 
This prevents modifying a security contact with the "securityContacts" API, not the policies one (it's deprecated very soon, so this is not a big issue). Azure Security Center graphic ui calls the "securityContacts" API, so this policy covers you for any changes applied via the UI.

**Comment by mentat9** [comment]
Closing this request since the fields requested are deprecated.
