### ISSUE TITLE
Microsoft.Compute	disks alias in 

### ISSUE THREAD

**Issue by RichShillingtonMSFT** [Azure/azure-policy#339]
### Scenario

I am trying to create Azure Policy to manage storage. Specifically disk encryption,  which is no longer stored in the storageProfile but are visible in the instance view.

AzureCloud contains the following aliases however they are not available in Azure US Government. These need to be made available for use with Azure Policy in Azure Sovereign Clouds.

### Alias
Microsoft.Compute/disks/accountType
Microsoft.Compute/disks/osType
Microsoft.Compute/disks/creationData
Microsoft.Compute/disks/creationData.createOption
Microsoft.Compute/disks/creationData.imageReference
Microsoft.Compute/disks/creationData.imageReference.id
Microsoft.Compute/disks/diskSizeGB
Microsoft.Compute/disks/encryptionSettings
Microsoft.Compute/disks/encryptionSettings.enabled
Microsoft.Compute/disks/encryptionSettings.diskEncryptionKey
Microsoft.Compute/disks/encryptionSettings.diskEncryptionKey.sourceVault
Microsoft.Compute/disks/encryptionSettings.diskEncryptionKey.sourceVault.id
Microsoft.Compute/disks/encryptionSettings.diskEncryptionKey.secretUrl
Microsoft.Compute/disks/encryptionSettings.keyEncryptionKey
Microsoft.Compute/disks/encryptionSettings.keyEncryptionKey.sourceVault
Microsoft.Compute/disks/encryptionSettings.keyEncryptionKey.sourceVault.id
Microsoft.Compute/disks/encryptionSettings.keyEncryptionKey.keyUrl
Microsoft.Compute/disks/timeCreated
Microsoft.Compute/disks/provisioningState
Microsoft.Compute/disks/diskState
Microsoft.Compute/disks/sku.tier
Microsoft.Compute/disks/creationData.storageAccountId
Microsoft.Compute/disks/creationData.imageReference.lun
Microsoft.Compute/disks/creationData.sourceUri
Microsoft.Compute/disks/creationData.sourceResourceId
Microsoft.Compute/disks/ownerId
Microsoft.Compute/disks/managedBy
Microsoft.Compute/disks/sku
Microsoft.Compute/disks/diskIOPSReadWrite
Microsoft.Compute/disks/diskMBpsReadWrite

.

**Comment by mentat9** [comment]
The Microsoft.Compute aliases have been replicated to the Government cloud.
