### ISSUE TITLE
Policy to Audit Storage Blobs with no Threat Detection enabled

### ISSUE THREAD

**Issue by mcuison** [Azure/azure-policy#341]
Is there a policy similar to the "SQL DB/Server deny policy for auditing/TDE/threat detection? #29" issue for auditing Storage Blobs with no Threat Detection enabled?

**Comment by mentat9** [comment]
There doesn't appear to be a field like that defined in the Azure OpenApi specs for Microsoft.Storage. If you can make a more specific query, we can give you a more definitive answer. Maybe you can provide a specific API field/property you have in mind to manage via policy.

**Comment by mcuison** [comment]
Hi,

Thanks for the reply.

I’m trying to use policy to audit storage accounts that do not have Threat Protection enabled.  The property can be verified using PowerShell or REST - https://docs.microsoft.com/en-us/rest/api/securitycenter/advancedthreatprotection/get<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Frest%2Fapi%2Fsecuritycenter%2Fadvancedthreatprotection%2Fget&data=02%7C01%7CMichael.Cuison%40microsoft.com%7C0e6cb867392e404dfcf608d6ad63754e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636887040015735523&sdata=lHEYNxSAuYiDLO66y0N2Xc8ZmUhue2Oq94b0KEHwwl0%3D&reserved=0>

**Comment by mentat9** [comment]
@mcuison, those properties can be managed through the Microsoft.Security aliases.
