### ISSUE TITLE
Microsoft.Web/sites.properties.minTlsVersion

### ISSUE THREAD

**Issue by kwill-MSFT** [Azure/azure-policy#342]
### Scenario

Prevent Web Apps from having minTlsVersion != 1.2

### Alias

The current minTlsVersion aliases on Microsoft.Web/sites/config and Microsoft.Web/sites/slots/config work correctly when one of these resource types are explicitly created.  However, you can also specify minTlsVersion when creating a Microsoft.Web/sites resource by specifying "siteConfig" in the resource properties.

Using this ARM template, Policy can't evaluate the minTlsVersion property.
{
	"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {},
	"variables": {},
	"resources": [
		{
			"name": "TLSPolicyTest",
			"type": "Microsoft.Web/sites",
			"apiVersion": "2018-02-01",
			"location": "northeurope",
			"tags": {},
			"properties": {
				"enabled": true,
				"siteConfig": {
					"appSettings": [
						{
							"Name": "SettingName1",
							"Value": "TestAppSetting1"
						}
					],
					"minTlsVersion": "1.1"
				},
				"httpsOnly": true,
				"serverFarmId": "/subscriptions/1377f4d2-3dce-4b96-ad95-677f764e8a24/resourceGroups/rgtest/providers/Microsoft.Web/serverFarms/ServicePland112edcb-9376"
			},
			"resources": []
		}
	],
	"outputs": {}
}

### Example policy definition

Need to add something like Microsoft.Web/sites.siteConfig.minTlsVersion to the below:

    "policyRule": {
        "if": {
            "allOf": [
                {
                    "anyOf": [
                        {
                            "field": "type",
                            "equals": "Microsoft.Web/sites/config"
                        },
                        {
                            "field": "type",
                            "equals": "Microsoft.Web/sites/slots/config"
                        }
                    ]
                },
                {
                    "anyOf": [
                        {
                            "allOf": [
                                {
                                    "field": "Microsoft.Web/sites/config/minTlsVersion",
                                    "exists": "true"
                                },
                                {
                                    "field": "Microsoft.Web/sites/config/minTlsVersion",
                                    "notEquals": "1.2"
                                }
                            ]
                        },
                        {
                            "allOf": [
                                {
                                    "field": "Microsoft.Web/sites/slots/config/minTlsVersion",
                                    "exists": "true"
                                },
                                {
                                    "field": "Microsoft.Web/sites/slotsconfig/minTlsVersion",
                                    "notEquals": "1.2"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        "then": {
            "effect": "deny"
        }
    },

**Comment by idatum** [comment]
We engaged the Microsoft.Web RP team, and are working with them to add the OpenAPI specs changes needed to support this alias.

**Comment by mentat9** [comment]
This has been added. The alias is ```Microsoft.Web/sites/siteConfig.minTlsVersion```.

**Comment by BoscoJohnson07** [comment]
Expected Value: 'siteConfig.minTlsVersion' should be 1.2
 Actual Value: 'siteConfig.minTlsVersion' is undefined
 Issue Type: MissingAttribute
 
 in the function apps throwing vulnerability
