### ISSUE TITLE
Policy That Verifies Activity Log Export is Enabled for Subscription

### ISSUE THREAD

**Issue by SpencerLN** [Azure/azure-policy#344]
I am attempting to find a way to create a policy that checks if a subscription is exporting the Activity Log to an Event Hub via a Log Profile (https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-logs-stream-event-hubs). I want to check both that a Microsoft.Insights/logProfiles with a specific name (default) exists in a subscription and that the default logProfile is configured to export to the correct Event Hub. If both of these conditions are not true, then I would like to Policy to show as non-compliant for that subscription.

I was able to create a policy that audits if a LogProfile is sending data to the correct Event Hub, but have been unable to create a policy that audits if the LogProfile exists at all for a given subscription. 
`{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Insights/logProfiles"
        },
        {
          "field": "Microsoft.Insights/logProfiles/serviceBusRuleId",
          "notEquals": "[parameters('serviceBusRuleId')]"
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {
    "serviceBusRuleId": {
      "type": "String",
      "metadata": {
        "displayName": "serviceBusRuleId",
        "description": "Event Hub Shared Access Policy"
      }
    }
  }
}`

Is this something that is possible? If so, could you help point me in the correct direction?

**Comment by jstarnes88** [comment]
I'm actually looking to do the exact same thing. I am not able to figure out how to verify that the logProfile exists at all using policy.

Could someone help here?

**Comment by ns4ever** [comment]
{
  "mode": "All",
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Resources/subscriptions"
    },
    "then": {
      "effect": "auditIfNotExists",
      "details": {
        "type": "Microsoft.Insights/logProfiles",
        "name": "default",
        "existenceScope": "subscription",
        "existenceCondition": {
          "allOf": [
            {
              "field": "Microsoft.Insights/logProfiles/retentionPolicy",
              "notEquals": ""
            },
            {
              "field": "Microsoft.Insights/logProfiles/serviceBusRuleId",
              "notEquals": ""
            }
          ]
        }
      }
    }
  },
  "parameters": {}
}

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
