### ISSUE TITLE
Alias request: "Microsoft.Solutions/applications" or "managedBy"

### ISSUE THREAD

**Issue by krowlandson** [Azure/azure-policy#345]
## Scenario

Trying to create an Azure Policy which allows me to exclude deployments performed by a Managed Application (Provider = Microsoft.Solutions/applications).

To use a specific example, we have a policy to enforce tagging policies on Resource Groups. When trying to deploy a Managed Application, the deployment fails as the Managed Application provides no mechanism by which to specify the required tags.

Looking at the Activity Log, there appears to be a way to identify that the deployment was initiated by a Managed Application using the "managedBy" field in "properties.requestbody" with a condition set against the value (if present).

An example of a deployment containing this field is as follows:

```
{

… <redacted for brevity> …

    "properties": {
        "requestbody": "{\"location\":\"westeurope\",\"managedBy\":\"/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Solutions/applications/<applicationId>\"}"
    },

… <redacted for brevity> …

}
```

## Alias

I believe there may be two ways we could achieve this if support for the relevant alias is provided.

- Option 1: Support "managedBy" as a field to assess
- Option 2: Support "Microsoft.Solutions/applications" as an alias

The preferred solution would depend wholly on which method would achieve the desired outcome but I suspect Option 1 would be the better way.

### Option 1: Support "managedBy" as a field to assess
```
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "not": {
            "field": "managedBy",
            "contains": "/Microsoft.Solutions/applications"
          }
        },
        {
          "field": "type",
          "in": "[parameters('arrayOfResourceTypes')]"
        },
        {
          "not": {
            "field": "[concat('tags[',parameters('tagName'), ']')]",
            "match": "[parameters('tagValuePattern')]"
          }
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }
}
```
### Option 2: Support "Microsoft.Solutions/applications" as an alias
```
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "not": {
            "field": "/Microsoft.Solutions/applications",
            "exists": "true"
          }
        },
        {
          "field": "type",
          "in": "[parameters('arrayOfResourceTypes')]"
        },
        {
          "not": {
            "field": "[concat('tags[',parameters('tagName'), ']')]",
            "match": "[parameters('tagValuePattern')]"
          }
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }
}
```

**Comment by mentat9** [comment]
Full set of aliases for ```Microsoft.Solutions``` has been published. You should be able to try your scenario using the ```managedBy``` alias. I'm not sure about the other approach, since ```Microsoft.Solutions/applications``` is a resource type rather than a field. ```Microsoft.Solutions/applications/applicationDefinitionIds``` also looks like it might be helpful. In any case, all aliases that are manageable by policy are now published.

**Comment by krowlandson** [comment]
Thank you for the super quick response on this.

I've had a good dig through the possible options this morning and unfortunately the Alias approach doesn't appear to allow us to achieve the desired outcome. Looking at the available aliases for "Microsoft.Solutions/applications/*", I believe these will only be of use when trying to deploy a Resource of type "Microsoft.Solutions/applications" and not when a Managed Application is trying to deploy the Resources defined within the Managed Application (as defined by the publisher).

The issue I'm facing is that I still cannot use "managedBy" as a "field" value, and there are no Resource Group aliases available, including "managedBy".

My belief is that if we can support "managedBy" as a supported "[Field](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#fields)" type, we can then use this for any request that contains "managedBy" in the "requestbody" as identified above.

If there's an alternative way you can suggest that allows us to identify whether a deployment was requested by a Managed Application and exclude that from the Policy, I'm open to suggestions.

**Comment by mentat9** [comment]
I don't think it will be a general option to support managedBy using "field": "managedBy". Only a tiny handful of resource providers actually have a managedBy field, so it's not something we can surface through policy. It's fine as a per-provider alias, but there won't be any aliases for resource groups, because they are internal ARM constructs, not resource types controlled by resource providers. There currently isn't a way of identifying and taking action based on the requestor of a deployment, which is what would be needed to enforce this kind of policy. I don't think this is a scenario we can support at this point, sorry.

**Comment by krowlandson** [comment]
Just a quick update relating to the above. We've discovered another scenario where it would be useful to have the above supported.

We've just been diagnosing an issue with Azure Backup, whereby the backup of a new VM was failing with the following error:

```
An invalid policy is configured on the VM which is preventing Snapshot operation.
Please correct the policy and retry the operation.
```

Looking at the Activity Log we could see that the "Microsoft.RecoveryServices" provider was trying to create a new Resource Group to store the Recovery Point. This was failing due to the Azure Policy which required specific Tags to be provided.

As you can see in this snippet from the Activity Log, the request once again included the "managedBy" field:

```
"properties": {
        "requestbody": "{\"location\":\"westeurope\",\"managedBy\":\"subscriptions/<subscriptionId>/providers/Microsoft.RecoveryServices/\"}"
}
```

While I appreciate this may not be used by all providers, this doesn't decrease the usefulness of having this supported by Azure Policy so we can better control granularity of our policy conditions.

**Comment by mentat9** [comment]
@krowlandson, I haven't heard anything new on this, but you can give additional help to the cause by adding an idea (or upvoting an existing one) at [Azure User Voice](https://feedback.azure.com/forums/915958-azure-governance). These submissions are monitored, prioritized, and acted upon.
