### ISSUE TITLE
Ability to include a 'description' property for each policy definition added to a policy initiative.

### ISSUE THREAD

**Issue by oliveirt** [Azure/azure-policy#348]
At present when creating a policy initiative it is not possible to include a description for each policy definition that is included in the initiative. This would be useful in situations where the same policy is included multiple times within a single policy initiative but with differing parameter values (but this would also be useful for simply allowing additional information to be provided). At present when looking at policy compliance in the portal there is no visibility of which of the policies has actually failed, as only the policy name is displayed.

In addition when the individual policy item is selected in the portal to view non-compliant resources, it is the description of the policy initiative / policy initiative assignment which is displayed. This could be replaced with the description of the actual policy rule within the initiative (if it were possible to add one).

In comparison when an assignment is created for a single policy definition a meaningful description can easily be provided that provides some insight into the parameter values that have been supplied and what is expected to meet compliance. For example for the 'Allowed locations' policy details of the permitted locations can be included in the description, as visibility of the supplied parameter values is difficult to locate (which is a wider issue).

**Comment by rohit-bh** [comment]
We have plans to allow the user to provide their own policy names (policyDefinitionReference Id) when creating initiatives through the UX. This is already possible through the API.

We will also surface the policyDefinitionReference in the compliance views. This will enable differentiation when the same policy is used multiple times in an initiative. (Ex - the allowed location can be specified via policyDefinitionReference in the initiative).

**Comment by oliveirt** [comment]
Thanks. I can see the 'policyDefinitionReferenceId' in existing policy definitions and have successfully defined it to a friendlier value via the API. But would be nice to have this added to the documentation.

https://docs.microsoft.com/en-us/rest/api/resources/policysetdefinitions/createorupdate#policydefinitionreference

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
