### ISSUE TITLE
DeployIfNotExist policy help please!

### ISSUE THREAD

**Issue by moonchest** [Azure/azure-policy#349]
Hi guys,

I wanted to write an Azure policy that auto-remedy/deploy a routeTable, if the routeTable named "route" is not found for any subnets.

Here is where I am up to, please weigh in, thanks a lot!

Cheers,

Ken

[AutoRemedyRouteTable.txt](https://github.com/Azure/azure-policy/files/3012918/AutoRemedyRouteTable.txt)

**Comment by rohit-bh** [comment]
I tried using this template deployment and it doesn't work for me. You should validate the template deployment before trying this via Azure policy. See https://docs.microsoft.com/en-us/rest/api/resources/deployments for more details.

Once you have a valid template, we can work on a DeployIfNotExists policy.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
