### ISSUE TITLE
Alias request: Microsoft.DataLakeStore/accounts/virtualNetworkRules

### ISSUE THREAD

**Issue by JohnnyB85** [Azure/azure-policy#350]
### Scenario

Audit unrestricted network access to Azure Data Lake instances

### Alias

RP: Microsoft.DataLakeStore
Resource Type: Microsoft.DataLakeStore/accounts
Property: properties.virtualNetworkRules.properties[*].subnetId

### Example policy definition

{
	"properties": {
		"displayName": "Azure Data Lake - VNET Service Endoints - Allow approved VNETs only",
		"description": "Restrict access to approved VNETs",
		"parameters": {
			"approvedVnetIDs": {
				"type": "Array",
				"metadata": { 
					"description": "list of VNET IDs" 
				}
			}
		}
	},
	"policyRule": {
		"if": {
			"allOf": [
				{
					"field": "type",
					"equals": "Microsoft.DataLakeStore/accounts/virtualNetworkRules"
				},
				{
					"not": {
						"field": "Microsoft.DataLakeStore/accounts/virtualNetworkRules.properties[*].subnetId",
						"in": "[parameters('approvedVnetIDs')]"
					}
				}
			]
		},
		"then": {
			"effect": "deny"
		}
	}
}

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.DataLakeStore has been published including the ones requested above.
