### ISSUE TITLE
Alias request: Microsoft.ServiceBus/namespaces/networkruleset/virtualNetworkRules

### ISSUE THREAD

**Issue by JohnnyB85** [Azure/azure-policy#352]
### Scenario

Audit unrestricted network access to Service Bus instances

### Alias

RP: Microsoft.ServiceBus
Resource Type: Microsoft.ServiceBus/namespaces/networkruleset
Property: properties.virtualNetworkRules.subnet.id

### Example policy definition

{
	"properties": {
		"displayName": "Service Bus - VNET Service Endoints - Allow approved VNETs only",
		"description": "Restrict access to approved VNETs",
		"parameters": {
			"approvedVnetIDs": {
				"type": "Array",
				"metadata": { 
					"description": "list of VNET IDs" 
				}
			}
		}
	},
	"policyRule": {
		"if": {
			"allOf": [
				{
					"field": "type",
					"equals": "Microsoft.ServiceBus/namespaces/networkruleset"
				},
				{
					"not": {
						"field": "Microsoft.ServiceBus/namespaces/networkruleset.virtualNetworkRules.subnet[*].id",
						"in": "[parameters('approvedVnetIDs')]"
					}
				}
			]
		},
		"then": {
			"effect": "deny"
		}
	}
}

**Comment by CtrlDot** [comment]
+1

**Comment by mentat9** [comment]
The full set of aliases for Microsoft.ServiceBus have been published and are available to use in policies. We have reports that they are not appearing in the output of Get-AzPolicyAlias, but that is a problem with Get-AzPolicyAlias, not a problem with the aliases themselves.
