### ISSUE TITLE
Alias request: Microsoft.Network/routeTables/routes[*].nextHopType

### ISSUE THREAD

**Issue by KevinBrooke** [Azure/azure-policy#353]
### Scenario

Ensure all traffic remains in a private space by blocking users from creating routes with the next hop type set to "internet".

### Alias

`Microsoft.Network/routeTables/routes[*].nextHopType
`
### Example policy definition

```
{
    "if": {
        "allOf": [
            {
                "field": "type",
                "contains": "Microsoft.Network/routeTables"
            },
            {
                "field": "Microsoft.Network/routeTables/routes[*].nextHopType",
                "equals": "Internet"
            }
        ]
    },
    "then": {
        "effect": "deny"
    }
}
```

**Comment by markmabe** [comment]
This is policy is also very important to our organization. We would greatly appreciate consideration to support that.

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.Network/routeTables, including nextHopType have been published to public cloud.
