### ISSUE TITLE
Alias Request: Microsoft.Sql/servers/databases/securityAlertPolicies/disabledAlerts[*]

### ISSUE THREAD

**Issue by mylameaccount** [Azure/azure-policy#358]
I am requesting that a wildcard alias ([*]) be created for SQL Databases SecurityAlertPolices that matches the SQL Database server's SecurityAlertPolices

The scenario we are looking to audit for is for any disabled threat protection types or specific ones being disabled.

- Resource Provider: Microsoft.Sql
- Resource Type: servers/databases/securityAlertPolicies
- Property: properties.disabledAlerts[*]
- Alias Name: Microsoft.Sql/servers/databases/securityAlertPolicies/disabledAlerts[*]

### Example policy definition

{
  "if": {
    "field": "type",
    "equals": "Microsoft.Sql/servers/databases"
  },
  "then": {
    "effect": "[parameters('effect')]",
    "details": {
      "type": "Microsoft.Sql/servers/databases/securityAlertPolicies",
      "existenceCondition": {
        "anyOf": [
          {
            "field": "Microsoft.Sql/servers/databases/securityAlertPolicies/disabledAlerts[*]",
            "equals": "Sql_Injection"
          }
        ]
      }
    }
  }
}

**Comment by mentat9** [comment]
This alias has been added: give it a try.

**Comment by mylameaccount** [comment]
That worked for me. Thank you very much.
