### ISSUE TITLE
Alias request: Microsoft.ContainerService/managedClusters/enablePodSecurityPolicy

### ISSUE THREAD

**Issue by nawolfin** [Azure/azure-policy#359]
**Scenario**

Add alias for the "enablePodSecurityPolicy" property that available in the new API of Azure Kubernets Service
This policy will be used in a new built-in policy under Security Center category, this new policy will validate that users are using Pod Security Policy in Kubernets clusters.

**Alias**

Resource Provider: "Microsoft.ContainerService"
Resource Type: "ManagedClusters"
Property name: "enablePodSecurityPolicy"
available in API VERSION: "2019-02-01"

**Example Policy**
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.ContainerService/enablePodSecurityPolicy"
      },
      {
        "anyOf": [
          {
            "field": "Microsoft.ContainerService/managedClusters/enablePodSecurityPolicy",
            "exists": "false"
          },
          {
            "field": "Microsoft.ContainerService/managedClusters/enablePodSecurityPolicy",
            "equals": "false"
          }
        ]
      }
    ]
  },
  "then": {
    "effect": "audit"
  }
}

**Comment by nawolfin** [comment]
I want to add another alias for the same provider and resource type (property: "apiServerAuthorizedIPRanges") let me know if you want me to create another alias request or we can use this one for both cases.

Thanks!

**Comment by mentat9** [comment]
No need to create another issue. We will update the entire resource type (or namespace) when we get to it.

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.ContainerService has been published, including the ones requested here.

**Comment by nawolfin** [comment]
This is great! thank you!
