### ISSUE TITLE
Array Parameter

### ISSUE THREAD

**Issue by sonalikaroy** [Azure/azure-policy#360]
Hi,

I am trying to create a policy to append our default subnet ids and ip address to storage account when it is created.The default value within the policy works but when I pass in value as parameter, it gives invalid json when it tries to perform the append action.

Policy :
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Storage/storageAccounts"
        },
        {
          "field": "Microsoft.Storage/storageAccounts/networkAcls.defaultAction",
          "notequals": "Deny"
        },
        {
          "field": "Microsoft.Storage/storageAccounts/networkAcls.defaultAction",
          "exists": "false"
        }
      ]
    },
    "then": {
      "effect": "append",
      "details": [
        {
          "field": "Microsoft.Storage/storageAccounts/networkAcls.defaultAction",
          "value": "Deny"
        },
        {
          "field": "Microsoft.Storage/storageAccounts/networkAcls.bypass",
          "value": "AzureServices"
        },
        {
          "field": "Microsoft.Storage/storageAccounts/networkAcls.virtualNetworkRules",
          "value": "[parameters('VirtualNetworkId')]"
        },
        {
          "field": "Microsoft.Storage/storageAccounts/networkAcls.ipRules",
          "value": "[parameters('FirewallIPs')]"
        }
      ]
    }
  },
  "parameters": {
    "VirtualNetworkId": {
      "type": "Array",
      "metadata": {
        "displayName": "Virtual Network Subnet Ids",
        "description": "Add it in a specific format "
      },
      "defaultValue": [
        {
          "id": "********",
          "action": "Allow",
          "state": "Succeeded"
        }
      ]
    },
    "FirewallIPs": {
      "type": "Array",
      "metadata": {
        "displayName": "Firewall IPs",
        "description": "Add it in a specific format "
      },
      "defaultValue": [
        {
          "value": "**********",
          "action": "Allow"
        }
      ]
    }
  }
}

Passing Value  as parameter 

{ 
"id": "********************",
"action": "Allow",
"state": "Succeeded"
}

Am i doing anything wrong?

**Comment by camillemarie** [comment]
Could you please provide (1)  the json for the policy assignment (where you passed the virtualNetworkId as a parameter), and (2) the full error message?

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
