### ISSUE TITLE
Microsoft.DBforMariaDB/servers/sslEnforcement

### ISSUE THREAD

**Issue by cloudignition** [Azure/azure-policy#361]
### Scenario

What are you trying to achieve using Azure Policy?

Enforce the use of TLS/SSL for MariaDB

### Alias

Include details about the alias being requested. Details on aliases are available [**here**](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases).
- What resource provider and resource type is involved?

Microsoft.DBforMariaDB

- What property on that resource type do you wish to expose?

sslEnforcement  - Enforcing the use of SSL/TLS for communication with the service

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.DBforMariaDB including the requested alias has been published.
