### ISSUE TITLE
Alias Request: Microsoft.ServiceFabric/clusters/properties/upgradeMode

### ISSUE THREAD

**Issue by CtrlDot** [Azure/azure-policy#364]
### Scenario

I want to ensure that all my clusters are set to auto-upgrade (make sure I don't have to do anything manual to keep up with security updates, etc)

### Alias

Include details about the alias being requested. Details on aliases are available [**here**](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases).
- What resource provider and resource type is involved?
- What property on that resource type do you wish to expose?

Microsoft.ServiceFabric/clusters/properties/upgradeMode

### Example policy definition

Please include a sample policy definition that shows how you would like to use this new alias.

      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.ServiceFabric/clusters"
          },
          {
            "not": {
              "field": "Microsoft.ServiceFabric/clusters/upgradeMode",
              "equals": Automatic
            }
          }
        ]
      },
      "then": {
        "effect": "audit"
      }

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.ServiceFabric have been published including the requested alias above.

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.ServiceFabric including the requested alias has been published.
