### ISSUE TITLE
Policy alias httpLoggingEnabled not working if there is a log settings

### ISSUE THREAD

**Issue by skbar50** [Azure/azure-policy#368]
#### Verbose logs 
New-AzResourceGroupDeployment : 11:32:22 AM - Error: Code=InvalidTemplateDeployment; Message=The template deployment failed because of policy violation. Please see details for more information.
At line:10 char:1
+ New-AzResourceGroupDeployment `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
 
New-AzResourceGroupDeployment : 11:32:46 AM - Error: Code=RequestDisallowedByPolicy; Message=Resource 'cat-skbtest-dev-webapp/logs' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"WebApps_http_Logging_Enabled","id":"/subscriptio
ns/29907ea6-8205-4f72-9525-9cf6138caafb/resourceGroups/val-policytest/providers/Microsoft.Authorization/policyAssignments/d99775625e8a404eb2c0c5ba"},"policyDefinition":{"name":"WebApps_http_Logging_Enabled","id":"/subscriptions/29907ea6-8205-4f72-9525-9cf61
38caafb/providers/Microsoft.Authorization/policyDefinitions/fc61fea6-e5ba-4749-a116-4bbc9696961f"}}]'.
At line:10 char:1
+ New-AzResourceGroupDeployment `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
 
New-AzResourceGroupDeployment : The deployment validation failed
At line:10 char:1
+ New-AzResourceGroupDeployment `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResourceGroupDeployment], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by mentat9** [comment]
Please post the policy (or policies) that were assigned and the template you used when getting these results.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) settion in the readme for details and Azure Policy support information.
