### ISSUE TITLE
Alias Request: webApplicationFirewallConfiguration.firewallMode

### ISSUE THREAD

**Issue by jgarverick** [Azure/azure-policy#37]
**Scenario**
Use Azure Policy to check/enforce the WAF firewall mode.
**Definition**
{
  "properties": {
    "displayName": "Allowed Application Gateway WAF Mode",
    "description": "This policy enables you to detect if the WAF is in detection or prevention mode.",
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Network/applicationGateways"
          },
          {
            "not": {
              "field": "Microsoft.Network/applicationGateways/webApplicationFirewallConfiguration.firewallMode",
              "equals": "Prevention"
            }
          }
        ]
      },
      "then": {
        "effect": "Deny"
      }
    }
  }
}

**Comment by pilor** [comment]
This is in progress.  Deployment of aliases for Microsoft.Network resources can take a few weeks.

**Comment by pilor** [comment]
`Microsoft.Network/applicationGateways/webApplicationFirewallConfiguration.firewallMode` is now available.  Sorry for the extended wait.

**Comment by simarley** [comment]
Thank you Chris and team!
