### ISSUE TITLE
Issue: Unable to Audit ResourceType "Microsoft.Storage/storageAccounts/blobServices/containers"

### ISSUE THREAD

**Issue by mylameaccount** [Azure/azure-policy#377]
I am trying to audit the Alias "Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess" however I am finding no way to get to the resourceType "Microsoft.Storage/storageAccounts/blobServices/containers".

It seems that there are some missing relationships. This is what I am observing so far:

- "Microsoft.Storage/storageAccounts/blobServices/containers" does not seem to exist as a standalone resourceType.

- "Microsoft.Storage/storageAccounts" doesn't seem to have a related resourceType of "Microsoft.Storage/storageAccounts/blobServices/containers"

- "Microsoft.Storage/storageAccounts/blobServices" doesn't seem to exists as a standalone resourceType.

- "Microsoft.Storage/storageAccounts" doesn't seem to have a related resourceType of "Microsoft.Storage/storageAccounts/blobServices"

I would expect to have seen some sort of relationship between the resourceTypes.  Is there a relationship between them?

- "storageAccounts" <--> "blobServices"
- "blobServices" <--> "containers"
- "storageAccounts" <--> "containers"

This is an example of a policyRule I would like to be able to do but it does not work at this time. Please recommend the appropriate appoach to get to the alias "Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess" for auditing:
```

    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Storage/storageAccounts"
          }
        ]
      },
      "then": {
        "effect": "[parameters('effect')]",
        "details": {
          "type": "Microsoft.Storage/storageAccounts/blobServices/containers",
          "existenceCondition": {
            "allOf": [
              {
                "field": "Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess",
                "equals": "Private"
              }
            ]
          }
        }
      }
    }

```

This is the resulting compliance details output from the rule above:
```

Reason for non-compliance
No related resources match the effect details in the policy definition.
EXISTENCE CONDITION
Type
Microsoft.Storage/storageAccounts/blobServices/containers


```

**Comment by rohit-bh** [comment]
If you try _{scope}/providers/Microsoft.Storage/storageAccounts/{SA_name}/blobServices_, this will fail with a "HttpResourceNotFound". This is because blobServices contains a singleton of name 'default'. 
_{scope}/providers/Microsoft.Storage/storageAccounts/{SA_name}/blobServices/default_ will work and list this instance.

To list the containers, you can use _{scope}/providers/Microsoft.Storage/storageAccounts/{SA_name}/blobServices/default/containers_ 

As for the policy you are trying to write, there are a few issues which I will outline below. This policy is not possible today.
**1. In the case of applying the policy when an applicable resource is changed**:
Whenever _Microsoft.Storage/storageAccounts/blobServices/containers_ are created/updated, the policy will be evaluated. During evaluation we know the exact resource that is being changed and will evaluate against it. This should work just fine. However, it is possible to create containers via data plane operations. In this case, the policy **will not** be evaluated. This is a known gap which the storage team plans to address in the coming months.

If the container is created through the Azure Portal, it first tries to create it via the control plane. If this fails (which it will if your policy was a 'deny'), the portal tries to create the container via a data plane operation which will succeed.

**2. In the case of compliance checks on existing resources in your environment**:
Let's say we have existing containers in your environment which are non-compliant with the policy.  We scan subscriptions by listing all resource types in _Microsoft.Storage_ namespace. Unfortunately, Microsoft.Storage does not list the _Microsoft.Storage/storageAccounts/blobServices/containers_ resource type. Due to this, we don't know about it which is why you see "No related resources match the effect details in the policy definition."

For this policy to work, the following changes are needed:
- _Microsoft.Storage_ needs to support collection GET on _{scope}/providers/Microsoft.Storage/storageAccounts/{SA_name}/blobServices
- _Microsoft.Storage_ needs to list _Microsoft.Storage/storageAccounts/blobServices/containers_ resource type.
- _Microsoft.Storage_ needs to support collection GET on _Microsoft.Storage/storageAccounts/blobServices/containers_. I believe this is possible today, but does not return all containers which is a problem.

**Comment by stephenfrichardson** [comment]
This is bad

**Comment by mylameaccount** [comment]
This is helpful information and I also appreciate how you outlined the reasons why it doesn't work.  It appears that all of the following do not work as well:

- Microsoft.Storage/storageAccounts/blobServices/containers
- Microsoft.Storage/storageAccounts/blobServices
- Microsoft.Storage/storageAccounts/queueServices
- Microsoft.Storage/storageAccounts/fileServices
- Microsoft.Storage/storageAccounts/tableServices

It may be on creation that some of these will audit however that disappear on their own eventually and are never seen again as you pointed out will happen. I tried some tests with Deny however as you said this won't work if provisioned via the portal but it didn't deny no matter how I triggered the creation. Portal, Powershell, Rest, template. Its possible I did something wrong there but it appears not to have worked.

The most frustrating part of this at this time is that there are so many aliases that don't seem to work for one reason or another throughout Azure Policy.  I appreciate aliases being created however creating and testing of some of these policies takes a lot of time. If they don't work the assumption is that its on the policy definition authors side.  To find out these are issues with Azure Policy is frustrating.

Each Alias published MUST be working and return useful data. This should be required for publishing. I found one alias that returns an object that is unusable in Azure Policy. We are wasting time with non-functioning aliases trying to get them working and no knowing they are broken.

Storage Aliases must work! There are storage settings that we need to audit for.  Storage Accounts are a huge risk for us all.

I have clients that are talking about creating home grown auditing rules engines and leaving Azure Policy out of the picture.  Please fix this as having a consistent tool for helping with governance across all clients is important to me and others.

**Comment by ashimabdul** [comment]
PG Team, is there a ETA for this? If not for the feature please remove the non-working alias which saves a lot of time for everyone who are trying to consume

**Comment by mentat9** [comment]
Storage team will provide an update this week.

**Comment by fhryo-msft** [comment]
The Azure Policy works on container for governance on public access. You can see the following sample. However, we don't recommend you to use it for now as it only audits and governs for changes with ARM operations. When customers change it with Storage SDKs (data plane), Azure Policy can't detect. It's known gap that Storage team is actively working with Azure Policy team to address. We don't have ETA yet.

The good news is that Storage is developing an new account property to prevent container public access. And you can use Azure Policy to enforce it just like other properties in storage account. The ETA is Q3 CY19.

Azure Policy team will remove the policy alias on container to avoid confusion soon. @LizMS can provide ETA.

Sample policy for container public access (Working in management plane but not recommended):
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Storage/storageAccounts/blobServices/containers"
      },
      {
        "not": {
          "field":"Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess",
          "equals": "None"
        }
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}

**Comment by mentat9** [comment]
All aliases for this resource type have been removed. Details on this and a few other problematic resource types are documented in a new Known Issues section of the readme: https://github.com/Azure/azure-policy#known-issues.

**Comment by pbillany** [comment]
> The good news is that Storage is developing an new account property to prevent container public access. And you can use Azure Policy to enforce it just like other properties in storage account. The ETA is Q3 CY19.

@LizMs,  @mentat9 - Any updates on this one? Thanks

**Comment by mentat9** [comment]
Last I heard it is expected to be available around the end of September. @fhryo-msft, is that still looking like a good ETA?

**Comment by fhryo-msft** [comment]
Yes, the ETA stays unchanged.

**Comment by pbillany** [comment]
Okay - thanks for the prompt update!

**Comment by pbillany** [comment]
Hi, has this property been released yet? Thanks.

**Comment by fhryo-msft** [comment]
Unfortunately, the property will be shipped later than this month. We will look for latest estimate and update.

**Comment by jhawrysz** [comment]
Hi, is there an updated estimate for this?

**Comment by Benoit-Gaumard** [comment]
Hi, is there an updated estimate for this?

Any chance to solve this problem ?

The following solutions are not working ...

Microsoft.Storage/storageAccounts/blobServices/containers.publicAccess
Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess

**Comment by fhryo-msft** [comment]
Please not use container public access alias in the policy. It's not working as expected.

The new estimate is Jun 2020 to ship new storage account property for public access enforcement.

**Comment by Benoit-Gaumard** [comment]
June 2020 ? Thank you.

**Comment by JoelCBennett** [comment]
Dang... June?

**Comment by fzavalloni** [comment]
Yes. It is already June and is not working.

**Comment by ashimabdul** [comment]
Dear Microsoft, did you mean June 2021 or is this never going to happen? I see total lack of process or commitment to customer. Will this happen in near future or should we just stop following this thread with 0 hope?

**Comment by fhryo-msft** [comment]
Storage team is releasing public access setting on storage account towards Jun 30 2020. Customers can use it to control the public access on all containers in the storage account. After it's released on storage, we will work with Azure Policy team to integrate the setting with Azure Policy so customers can us Azure Policy to audit and govern public access across storage accounts.

We work the best to ship above features and capabilities as early as possible. However, please understand the ETA is subject to change based on latest progress and issues.

**Comment by fhryo-msft** [comment]
As I clarified, it would be extra work to get Storage public access setting available on Azure Policy. It should be sometime between Jul and Sep 2020. We will work with Azure Policy team to estimate a better timeline for the integration. Please stay tuned.

**Comment by jrhalasz** [comment]
> As I clarified, it would be extra work to get Storage public access setting available on Azure Policy. It should be sometime between Jul and Sep 2020. We will work with Azure Policy team to estimate a better timeline for the integration. Please stay tuned.

@fhryo-msft -  
Will this be available by September?

**Comment by JoelCBennett** [comment]
> As I clarified, it would be extra work to get Storage public access setting available on Azure Policy. It should be sometime between Jul and Sep 2020. We will work with Azure Policy team to estimate a better timeline for the integration. Please stay tuned.

It appears that the policy definition below actually works.  Is this supported:

"policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Storage/storageAccounts"
          },
          {
            "anyOf": [
              {
                "field": "Microsoft.Storage/storageAccounts/allowBlobPublicAccess",
                "exists": "false"
              },
              {
                "field": "Microsoft.Storage/storageAccounts/allowBlobPublicAccess",
                "equals": "true"
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }
  },

**Comment by fhryo-msft** [comment]
Yes, it works practically now but it's not official yet as we are updating the doc.

**Comment by fhryo-msft** [comment]
To audit or enforce blob public access on the entire storage account, please refer to: https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-prevent

**Comment by sadewale3** [comment]
This thread is very interesting. i am currently having similar issue with meeting my use case. Right now thee capability provided with the currently policy setting allows audit of the storage account for public access. I would like to audit the individual containers and blob for public access. 

It seems the following resource type does not exist anymore: Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess
