### ISSUE TITLE
VM should have latest OS version installed

### ISSUE THREAD

**Issue by sprilutsky01** [Azure/azure-policy#383]
<!--
    Thank you for contributing!

    ISSUE TITLE:
     "Alias request: "Microsoft.Compute/virtualMachines"

    ISSUE DESCRIPTION (this template):

Being on   the latest OS version significantly reduces risks from security design issues   and security bugs that may be present in older versions.

### Scenario
What are you trying to achieve using Azure Policy?

Being on   the latest OS version significantly reduces risks from security design issues   and security bugs that may be present in older versions.

### Alias

Include details about the alias being requested. Details on aliases are available [**here**](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases).
- What resource provider and resource type is involved?
   Microsoft.Compute/virtualMachines/Windows
   Microsoft.Compute/virtualMachines/Linux

- What property on that resource type do you wish to expose?
  Microsoft.Compute/virtualMachines/Windows/Latest.OS.Version
  Microsoft.Compute/virtualMachines/Linux/Latest.OS.Version

### Example policy definition

{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Compute/virtualMachines"
        },
        {
          "field": "Microsoft.Compute/virtualMachines/Windows/Latest.OS.Version",
          "equals": "true"
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {}
}

**Comment by camillemarie** [comment]
Duplicate of #376
