### ISSUE TITLE
Do not leave management ports open on VMs

### ISSUE THREAD

**Issue by sprilutsky01** [Azure/azure-policy#384]
Do   not leave management ports open on VMs, force to use JIT on Azure
--

### Scenario

What are you trying to achieve using Azure Policy?

### Alias

Include details about the alias being requested. Details on aliases are available [**here**](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases).
- What resource provider and resource type is involved?
     Do   not leave management ports open on VMs
- What property on that resource type do you wish to expose?
     
### Example policy definition
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Compute/virtualMachines"
        },
        {
          "field": "Microsoft.Compute/virtualMachines/Management.Ports.Off",
          "equals": "true"
        }
      ]
    },
    "then": {
      "effect": "audit/deny"
    }
  },
  "parameters": {}
}

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
