### ISSUE TITLE
Issue - https://docs.microsoft.com/en-us/azure/governance/policy/samples/allow-custom-vm-image

### ISSUE THREAD

**Issue by jayaakshayan** [Azure/azure-policy#387]
<!--
    Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:
    Policy Name : Allow custom VM image from a resource group
 https://docs.microsoft.com/en-us/azure/governance/policy/samples/allowed-custom-images

   Short description of my issue : post assignment of this policy, not able to update VM tag.

  ISSUE DESCRIPTION (this template):  Allow custom image from a resource group
Link :  https://docs.microsoft.com/en-us/azure/governance/policy/samples/allowed-custom-images

I have assigned this policy to my subscription. The policy is working good as expected.

At the same time, this policy blocks the VM tag assignment and it pops up error " Access unauthorized, please correct any errors and try again".

When i look in to the activity log, this policy denies the tag creation, update and deletion for only VM.

The policy intention is to only allow custom images, but it is getting reverse effect as blocking tag to VM. Could you please rewrite the policy and post in the Microsoft KB.

**Comment by DCtheGeek** [comment]
@jayaakshayan Can you provide some details as to the issue with that sample?

**Comment by jayaakshayan** [comment]
Here is the details:-
Policy:-
{
    "type": "Microsoft.Authorization/policyDefinitions",
    "name": "custom-image-from-rg",
    "properties": {
        "displayName": "Allow custom VM image from a Resoruce Group",
        "description": "This policy allows only usage of images from a resource group",
        "parameters": {
            "resourceGroupName":{
                "type":"String",
                "metadata":{
                    "displayName": "Resource Group Name",
                    "strongType": "ExistingResourceGroups"
                }
            }
        },
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.Compute/virtualMachines"
                    },
                    {
                        "not": {
                            "field": "Microsoft.Compute/imageId",
                            "contains": "[concat('resourceGroups/',parameters('resourceGroupName'))]"
                        }
                    }
                ]
            },
            "then": {
                "effect": "deny"
            }
        }
    }
}

![Activitylog](https://user-images.githubusercontent.com/42839520/57388232-68b25080-71d5-11e9-8f4a-5f474482161d.jpg)
![error](https://user-images.githubusercontent.com/42839520/57388241-6c45d780-71d5-11e9-9f0a-1baa0bcdf033.jpg)

**Comment by DCtheGeek** [comment]
Might be confusing two different policy definition samples.  You included a screenshot of a tag, but this policy doesn't test for a tag. It tests that the custom image (by imageId property) used to create the virtual machine is from a specific resource group, the name of which is provided as a parameter during policy assignment.

**Comment by jayaakshayan** [comment]
Yes the policy purpose is to create virtual machine from only a specific group custom images and it does the job very well.

But the policy gets reverse effect. When ever this policy assigned, we could not able to update the VM tag and it throws error.

Can you please assign this policy to your test subscription, post assignment please check whether you can able to update the VM tag.

**Comment by DCtheGeek** [comment]
The error above for the VM tag doesn't indicate a policy, it indicates that you don't have permission to set a tag on the VM.  Are you saying that if the policy isn't assigned, you can add the tag you are shown as being denied in the screenshot? If that's the case, this is more a support incident and you should open a ticket.

**Comment by jayaakshayan** [comment]
Yes right, iam the owner for the subcription. If the policy is unassigned then the tag is working fine.

This is more of bug, the policy is making reverse effect. I am not sure weather i need to open a support ticket for this. If yes, can you please help me how to raise support ticket to inform this bug to Microsoft.

**Comment by camillemarie** [comment]
@jayaakshayan Once you assign the policy, you won't be able to update any non-compliant VM, by design. This includes changing the tags.

There is a bug which is causing the Tags UI to show "Access Unauthorized" for policy failures right now, but if you check the activity log or F12, you will see the policy error.

**Comment by jayaakshayan** [comment]
Thanks for the input, i am closing this issue.
