### ISSUE TITLE
Get-date within policy

### ISSUE THREAD

**Issue by sonalikaroy** [Azure/azure-policy#388]
Is it possible to get date within the policy?

**Comment by DCtheGeek** [comment]
Yes.  Use the function`utcNow()` to get the full date/time. You can also use `addDays(dateTime, numberOfDaysToAdd)` to do a calculation, such as in a value accessor.  I've got an action item to get these doc'ed. :)

**Comment by sonalikaroy** [comment]
Thanks for quick reply.so for value in tag , i can just say :

"value": utcNow() ?

**Comment by DCtheGeek** [comment]
"value": "[utcNow()]" since it's a function.  Are you trying to append this in a tag?  If the tag name already exists, append won't update it, but will error.  And this will only append the tag to newly created resources.  Is that your use-case?

**Comment by sonalikaroy** [comment]
ys , we need to add it for new resources if that tag name doesnot exist.Thanks again :)

**Comment by scr8er** [comment]
> Yes. Use the function`utcNow()` to get the full date/time. You can also use `addDays(dateTime, numberOfDaysToAdd)` to do a calculation, such as in a value accessor. I've got an action item to get these doc'ed. :)

Thats exactly what i was looking for to set creation and expiration date to dev resources
tyvm
