### ISSUE TITLE
Alias Request: webApplicationFirewallConfiguration.disabledRuleGroups

### ISSUE THREAD

**Issue by jgarverick** [Azure/azure-policy#39]
**Scenario**
Use Azure Policy to audit the existence of any disabled OWASP rule groups.  This may require the addition of a `count` property to query if there are any items in the collection, as I think the property will always exist regardless of its contents.
**Definition**
```
{
  "properties": {
    "displayName": "Disabled Application Gateway WAF Rules",
    "description": "This policy allows you to detect if any of the OWASP rule sets used in the WAF are disabled.",
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Network/applicationGateways"
          },
          {
            "field": "Microsoft.Network/applicationGateways/webApplicationFirewallConfiguration.disabledRuleGroups",
            "exists": "true"
          }
        ]
      },
      "then": {
        "effect": "Audit"
      }
    }
  }
}
```

**Comment by pilor** [comment]
This is in progress.  Deployment of aliases for Microsoft.Network resources can take a few weeks.

**Comment by pilor** [comment]
For your specific example you can workaround the current lack of a count operator by using the following to flag any inclusion of disabledRuleGroups (once the alias is available):

```
"not": {
   "field": "Microsoft.Network/applicationGateways/webApplicationFirewallConfiguration.disabledRuleGroups[*].ruleGroupName",
   "notLike": "*"
}
```

**Comment by pilor** [comment]
`Microsoft.Network/applicationGateways/webApplicationFirewallConfiguration.disabledRuleGroups[*].ruleGroupName`  is now available.  Sorry for the extended wait.
