### ISSUE TITLE
Alias Request: "Microsoft.CDN/profiles/endpoints/originHostHeader"

### ISSUE THREAD

**Issue by mylameaccount** [Azure/azure-policy#390]
I am requesting that an alias be created for the “originHostHeader” property of the “Microsoft.CDN/profiles/endpoints” resource type.

The scenario we are looking to audit for is for any CND Profile resource that use specific origin types (Web Apps, Blob Storage, and Cloud Services) by inspecting the Origin Host Header.  _Note: We prefer to have the "Origin Host Name" but not sure if that is possible. Another request will be made for this._

Resource Provider: Microsoft.CDN/profiles
Resource Type: profiles/endpoints
Property: “originHostHeader”
Alias Name: : Microsoft.CDN/profiles/endpoints/originHostHeader"

Example policy definition
 ```
   "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.CDN/profiles"
          }
        ]
      },
      "then": {
    "effect": "[parameters('effect')]",
    "details": {
      "type": "Microsoft.CDN/profiles/endpoints",
      "existenceCondition": {
        "allOf": [
          {
            "field": "Microsoft.CDN/profiles/endpoints/originHostHeader",
            "notContains": "blob"
          }
        ]
      }
    }
```

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.Cdn has been published, including ```Microsoft.Cdn/profiles/endpoints/originHostHeader```. Please try it out.
