### ISSUE TITLE
How does policy work on port ranges

### ISSUE THREAD

**Issue by mpchen** [Azure/azure-policy#392]
Problem - so I want to block people creating NSGs that open up Internet access to some ports (22, 3389, etc.). I can create a policy to block the specific port, e.g., 

"allOf": [
                    {
                        "field": "Microsoft.Network/networkSecurityGroups/securityRules/access",
                        "equals": "Allow"
                    },
                    {
                        "field": "Microsoft.Network/networkSecurityGroups/securityRules/direction",
                        "equals": "Inbound"
                    },
                    {
                        "anyOf": [
                            {
                                "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange",
                                "equals": "22"
                            },
                            {
                                "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange",
                                "equals": "3389"
                            },
]

This will block creation of NSGs if the specific port is used in the security rules. But it can be bypassed if someone create a NSG rules that allows port ranges (such as 3300-3400).

Wondering how policy deals with port ranges and what the best way is in this case.

**Comment by mpchen** [comment]
I tried destinationPortRanges[*] array but it does not work.

 "not": {
        "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]",
          "Equals": "22"
}

**Comment by nconder** [comment]
@mpchen port range evaluation does not work at this time. But I have heard this feature is in the works.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.

**Comment by keanesf** [comment]
For anyone that stumbles on this answer like I did. There now appears to be an example in this repo that solves this issue

https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Network/NetworkSecurityGroup_RDPAccess_Audit.json

https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Network/NetworkSecurityGroup_SSHAccess_Audit.json

**Comment by rudolphjacksonm** [comment]
The policy linked above is deprecated and I can't find it anywhere in the portal 😞 is there a new built-in policy that does the same?

**Comment by nehakulkarni123** [comment]
Hi @rudolphjacksonm, you can also choose to create a custom policy definition with this logic if you'd like. [Here](https://docs.microsoft.com/azure/governance/policy/tutorials/create-custom-policy-definition) is more information on how to do that. 

In the meantime, I will check with the Networking team to see if they have any plans to introduce new policy definitions with this scenario.

**Comment by rudolphjacksonm** [comment]
Cool, thanks @nehakulkarni123 !

**Comment by avbanks** [comment]
If anyone is struggling the snippet below should help out


   "parameters": {
      "blockedports": {
        "type": "array",
        "metadata": {
          "description": "Array of blocked management ports",
          "displayName": "Blocked_Ports"
        },
        "defaultValue": [
          22,
          23,
          135,
          445,
          1433,
          2222,
          3389,
          5985,
          5986,
          7474,
          7473,
          7687
        ]
      },
      "effect": {
        "type": "String",
        "metadata": {
          "description": "Enable or disable the execution of the policy",
          "displayName": "Effect"
        },
        "allowedValues": [
          "Audit",
          "Deny",
          "Disabled"
        ],
        "defaultValue": "Audit"
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "equals": "Microsoft.Network/networkSecurityGroups/securityRules",
            "field": "type"
          },
          {
            "allOf": [
              {
                "equals": "Allow",
                "field": "Microsoft.Network/networkSecurityGroups/securityRules/access"
              },
              {
                "equals": "Inbound",
                "field": "Microsoft.Network/networkSecurityGroups/securityRules/direction"
              },
              {
                "anyOf": [
                  {
                    "equals": "*",
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange"
                  },
                  {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange",
                    "in": "[parameters('blockedports')]"
                  },
                  {
                    "equals": "true",
                    "value": "[and(and(not(empty(field('Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange'))), contains(field('Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange'),'-')), greater(length(intersection(range(int(first(split(field('Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange'), '-'))), sub(int(last(split(field('Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange'), '-'))), int(first(split(field('Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange'), '-'))))), parameters('blockedports'))),0))]"
                  },
                  {
                    "count": {
                      "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]",
                      "where": {
                        "equals": "true",
                        "value": "[and(not(empty(first(field('Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]')))), greater(length(intersection(range(int(first(split(first(field('Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]')), '-'))), sub(int(last(split(first(field('Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]')), '-'))), int(first(split(first(field('Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]')), '-'))))), parameters('blockedports'))),0))]"
                      }
                    },
                    "greater": 0
                  },
                  {
                    "not": {
                      "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]",
                      "notEquals": "*"
                    }
                  },
                  {
                    "not": {
                      "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRanges[*]",
                      "notIn": "[parameters('blockedports')]"
                    }
                  }
                ]
              },
              {
                "anyOf": [
                  {
                    "equals": "*",
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix"
                  },
                  {
                    "equals": "Internet",
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix"
                  },
                  {
                    "not": {
                      "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefixes[*]",
                      "notEquals": "*"
                    }
                  },
                  {
                    "not": {
                      "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefixes[*]",
                      "notEquals": "Internet"
                    }
                  }
                ]
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "[parameters('effect')]"
      }
    }
  }
}
