### ISSUE TITLE
Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by sprilutsky01** [Azure/azure-policy#393]

**Comment by mentat9** [comment]
@sprilutsky01, I can't tell what you are asking. Can you provide some more information?

**Comment by sprilutsky01** [comment]
Hi Chris,

There are now aliases available for Azure SQL DataWarehouse. Some of the Microsoft.SQL/server/database/... aliases work for SQL DataWarehouse, but not all. Asking to have separate aliases for Azure SQL DataWarehouse.

Things like:

  *   Ensure that 'Auditing' is set to 'On' SQL DW
  *   Ensure that 'Auditing' Retention is 'greater than 90 days'
  *   Ensure that 'Advanced Data Security' on a SQL DW is set to 'On'
  *   Ensure that 'Transparent Data encryption' is set to 'On' on a SQL DW
  *   In a SQL Server with multiple databases, setup firewall rules also at the database level SQL Server High
  *   Client-side encryption should be used where appropriate SQL DW
  *   Review the Data Masking policy for SQL Database sensitive data columns if in use.
  *   Enable SQL DW threat detection with email admins option. Do not exclude any detection types
  *   Do not use SQL Authentication. Use AAD-authentication instead
  *   Access to SQL Servers and DBs must be granted in accordance with the principle of least privilege
  *   Enable SQL Server audit with selected event types and retention period of minimum 365 days
  *   Enable SQL Database audit with selected event types and retention period of minimum 365 days
  *   Logs should be reviewed routinely
  *   Review the Data Masking policy for SQL Database sensitive data columns if in use.
  *   Use the 'Allow access to Azure services' flag only if required.

Regards,
   Sergey Prilutsky


________________________________

**Comment by mentat9** [comment]
@sprilutsky01, this behavior appears to be under control of the Microsoft.Sql resource provider, not policy. From the policy side, aliases provide an api-version independent REST path to a field in the GET response/PUT request, but the field and its behavior is controlled by the resource provider. In the case you are talking about here, it appears that the paths to the fields you are referring to are the same whether it's a DB or DW. If DWs are actually created and modified on different REST paths than DBs, I wasn't able to find them. Unless there is a way to distinguish them by resource type or namespace as declared in the Open Api specs, policy has no way of making or distinguishing separate aliases. I'd suggest contacting the SQL team to see if they will support those fields on DWs.

**Comment by mentat9** [comment]
Closing this, since it's not actionable by Azure Policy. This request requires new support from Microsoft.Sql resource provider. Please open a support ticket for the SQL team at https://azure.microsoft.com/support/create-ticket/, or submit a request through User Voice: https://feedback.azure.com/forums/307516-sql-data-warehouse
