### ISSUE TITLE
Support request: Custom DeployIfNotExists policy for App Service logs is not evaluating

### ISSUE THREAD

**Issue by jim102978429347** [Azure/azure-policy#394]
DeployIfNotExists policy is not evaluating for App Service. The policy should deploy a template if the _Microsoft.Web/sites/config/logs.httpLogs.fileSystem_ alias is not enabled.

**Policy Definition**
`{
  "mode": "All",
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Web/sites"
    },
    "then": {
      "effect": "deployIfNotExists",
      "details": {
        "type": "Microsoft.Web/sites/config",
        "name": "logs",
        "roleDefinitionIds": [
          "/providers/Microsoft.Authorization/roleDefinitions/56d4fsg564-6180-58sd7f-ab88-a6sd4f65asd4f"
        ],
        "existenceCondition": {
          "not": {
            "field": "Microsoft.Web/sites/config/logs.httpLogs.fileSystem",
            "equals": "enabled"
          }
        },
        "deployment": {
          "properties": {
            "mode": "incremental",
            "template": {
              "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
              "contentVersion": "1.0.0.0",
              "parameters": {
                "appServiceName": {
                  "type": "string"
                },
                "appServiceLocation": {
                  "type": "string"
                }
              },
              "resources": [
                {
                  "apiVersion": "2018-02-01",
                  "name": "[parameters('appServiceName')]",
                  "type": "Microsoft.Web/sites",
                  "location": "[parameters('appServiceLocation')]",
                  "properties": {},
                  "resources": [
                    {
                      "name": "logs",
                      "type": "config",
                      "apiVersion": "2018-02-01",
                      "dependsOn": [
                        "[resourceId('Microsoft.Web/sites/', parameters('appServiceName'))]"
                      ],
                      "properties": {
                        "httpLogs": {
                          "fileSystem": {
                            "retentionInMb": 35,
                            "retentionInDays": 101,
                            "enabled": true
                          }
                        }
                      }
                    }
                  ]
                }
              ]
            },
            "parameters": {
              "appServiceName": {
                "value": "[field('fullName')]"
              },
              "appServiceLocation": {
                "value": "[field('location')]"
              }
            }
          }
        }
      }
    }
  },
  "parameters": {}
}`

I have reviewed every log that I can think of but I cannot see that the policy is every triggered or evaluated even though there are multiple App Services within the scope of the policy's assignment. Is there a way to to debug these?

I have tested the arm template and it is working as expected. Looking for someone with deeper knowledge to help point me in the right direction.

**Comment by camillemarie** [comment]
Couple of things: 

1. The existenceCondition won't work
    - `not` isn't needed here. In `ifNotExists` conditions you want to match the resources that would make the policy compliant.
    - The `Microsoft.Web/sites/config/logs.httpLogs.fileSystem` alias will grab the entire properties.httpLogs.fileSystem object. Since you just care about the "enabled" property, you should use the  `Microsoft.Web/sites/config/logs.httpLogs.fileSystem.enabled` alias.
       - Use Get-AzPolicyAlias to explore alias paths.
`Get-AzPolicyAlias -AliasMatch "Microsoft.Web/sites/config/logs.httpLogs.fileSystem" | select resourcetype -expand aliases | where name -clike "*fileSystem*" | select resourcetype,name -expand paths`
       - Use resources.azure.com to explore resource json bodies.

   It should be:

   ```
   "existenceCondition": {
  	   "field": "Microsoft.Web/sites/config/logs.httpLogs.fileSystem.enabled",
	   "equals": "true"
    }
   ```

2. That role definition id doesn't look familiar. Make sure you're using the correct id - read [here ](https://docs.microsoft.com/en-us/azure/templates/)for more info.
