### ISSUE TITLE
Firewall Policy for Redis

### ISSUE THREAD

**Issue by nagstor** [Azure/azure-policy#397]
Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:
    Unable to create a working policy to for Firewall Rules for Azure Redis

    ISSUE DESCRIPTION (this template):

   I am trying to create a Azure Policy to prevent users from creating a Standard tier Redis cache without Firewall rules. I tried multiple options, but none or working.  Can you please let me know how to go about setting this policy.
One of the policies I tried is as below:

{
  "properties": {
    "displayName": "Redis-PricingRestriction-Std",
    "policyType": "Custom",
    "mode": "All",
    "description": " Enforce Restrictions by Pricing Tier:\n\n1. Enforce Firewall Rules on Standard Tier",
    "metadata": {
      "category": "Cache",
      "createdBy": "",
      "createdOn": "",
      "updatedBy": "",
      "updatedOn": ""
    },
    "parameters": {},
    "policyRule": {
      "if": {
        "anyOf": [
          {
            "allOf": [
              {
                "field": "type",
                "equals": "Microsoft.Cache/Redis"
              },
              {
                "field": "Microsoft.Cache/Redis/sku.name",
                "equals": "Standard"
              },
              {
                "field": "type",
                "equals": "Microsoft.Cache/Redis/firewallrules"
              },
              {
                "anyOf": [
                  {
                    "not": {
                      "field": "Microsoft.Cache/Redis/firewallrules/startIP",
                      "match": "^(?!\\s*$).+"
                    }
                  },
                  {
                    "not": {
                      "field": "Microsoft.Cache/Redis/firewallrules/endIP",
                      "match": "^(?!\\s*$).+"
                    }
                  }
                ]
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "deny",
        "details": {
          "type": "Microsoft.Cache/Redis/firewallrules",
          "existenceCondition": {
            "anyOf": [
              {
                "not": {
                  "field": "Microsoft.Cache/Redis/firewallrules/startIP",
                  "match": "^(?!\\s*$).+"
                }
              },
              {
                "not": {
                  "field": "Microsoft.Cache/Redis/firewallrules/endIP",
                  "match": "(?!\\s*$).+"
                }
              }
            ]
          }
        }
      }
    }
  },
 }

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
