### ISSUE TITLE
Kubernetes Policies

### ISSUE THREAD

**Issue by marian-craciunescu** [Azure/azure-policy#404]
The documentation regarding the applying the new .rego policies is not very expletive.
How can be applied ? What are the precoditions except to have the opt-in for them.

Also maybe you can add some related documentation regarding on how to write new one or extend them.

**Comment by camillemarie** [comment]
@RamyasreeChakka to comment on AKS policies.

**Comment by RamyasreeChakka** [comment]
@LizMS Can you please comment on AKS policies?

**Comment by marian-craciunescu** [comment]
@LizMS  do you have any information on how to apply .rego policy ?
From Portal I was not able to create a new policy definition (because it requires a valid JSON format)
Same applies for the `New-AzPolicyDefinition` powershell method.

**Comment by marian-craciunescu** [comment]
should I do something like this ?
https://www.openpolicyagent.org/docs/latest/deployments/#kubernetes

**Comment by marian-craciunescu** [comment]
I will close this issue since I was able to get in touch with people from Microsoft.
This feature is in alpha so no documentation will be found until it is released.
The policy from here should appear in the Category= `Kubernetes Data plane` in Azure portal once the preview is enabled and Microsoft is able to give green light.
I recommend to get in touch via Slack channel from OPA if there are still questions.

No possibility to extend right now.
