### ISSUE TITLE
New Policy Parameter: the account info when applying the azure-policy, not defining that.

### ISSUE THREAD

**Issue by endurancetest20380119** [Azure/azure-policy#406]
### Description

I want the account info parameter, ex. mail address, when applying the azure-policy, not defining that.

### Use case
Someone creates the resource group and enforce to do tagging that dynamically.
https://stackoverflow.com/questions/56179756/azure-policyapply-tag-and-add-the-account-info

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
