### ISSUE TITLE
Microsoft.Sql/servers/databases/providers/diagnosticSettings/eventHubAuthorizationRuleId

### ISSUE THREAD

**Issue by aboelter** [Azure/azure-policy#407]
### Scenario
We want to be sure that events are sent to event hub on all database servers
It would be nice to have the option for log analytics as well

### Alias
- What resource provider and resource type is involved?
   - Microsoft.Sql diagnostic settings provider
- What property on that resource type do you wish to expose?
   - eventHubAuthorizationRuleId
   - eventHubName
   - loganalyticsWorkspaceID

### Example policy definition

{
  "mode": "All",
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Sql/servers"
    },
    "then": {
      "effect": "deployIfNotExists",
      "details": {
        "type": "Microsoft.Sql/servers/auditingSettings",
        "name": "Default",
        "existenceCondition": {
          "allOf": [
            {
              "field": "Microsoft.Sql/servers/auditingSettings/state",
              "equals": "Enabled"
            },
            {
              "field": "Microsoft.Sql/servers/auditingSettings/isAzureMonitorTargetEnabled",
              "equals": "true"
            },
            {
              "field": "Microsoft.Sql/servers/databases/providers/diagnosticSettings/eventHubAuthorizationRuleId",
              "equals": "[parameters('EventHubID')]"
            }
          ]
        },
        "roleDefinitionIds": [
          "/providers/microsoft.authorization/roleDefinitions/905c6fa6-630c-49f8-ab32-f7ca76d56725"
        ],
        "deployment": {
          "properties": {
            "mode": "incremental",
            "template": {
              "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
              "contentVersion": "1.0.0.0",
              "parameters": {
                "serverName": {
                  "type": "string"
                },
                "retentionDays": {
                  "type": "int"
                },
                "WorkspaceID": {
                  "type": "string"
                },
                "EventHubID": {
                  "type": "string"
                },
                "EventHubName": {
                  "type": "string"
                }
              },
              "variables": {
                "diagnosticSettingsName": "SQLSecurityAuditEvents_3d229c42-c7e7-4c97-9a99-ec0d0d8b86c1",
                "auditActions": [
                  "SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP",
                  "FAILED_DATABASE_AUTHENTICATION_GROUP"
                ]
              },
              "resources": [
                {
                  "name": "[concat(parameters('serverName'),'/master/microsoft.insights/',variables('diagnosticSettingsName'))]",
                  "type": "Microsoft.Sql/servers/databases/providers/diagnosticSettings",
                  "dependsOn": [],
                  "apiVersion": "2017-05-01-preview",
                  "properties": {
                    "name": "[variables('diagnosticSettingsName')]",
                    "eventHubAuthorizationRuleId": "[parameters('EventHubID')]",
                    "eventHubName": "[parameters('EventHubName')]",
                    "logs": [
                      {
                        "category": "SQLSecurityAuditEvents",
                        "enabled": true,
                        "retentionPolicy": {
                          "days": 0,
                          "enabled": false
                        }
                      }
                    ]
                  }
                },
                {
                  "name": "[concat(parameters('serverName'), '/Default')]",
                  "type": "Microsoft.Sql/servers/auditingSettings",
                  "apiVersion": "2017-03-01-preview",
                  "properties": {
                    "state": "Enabled",
                    "auditActionsAndGroups": "[variables('auditActions')]",
                    "isAzureMonitorTargetEnabled": true,
                    "isStorageSecondaryKeyInUse": false,
                    "retentionDays": "[parameters('retentionDays')]"
                  }
                }
              ]
            },
            "parameters": {
              "serverName": {
                "value": "[field('Name')]"
              },
              "retentionDays": {
                "value": "[parameters('retentionDays')]"
              },
              "WorkspaceID": {
                "value": "[parameters('WorkspaceID')]"
              },
              "EventHubID": {
                "value": "[parameters('EventHubID')]"
              },
              "EventHubName": {
                "value": "[parameters('EventHubName')]"
              }
            }
          }
        }
      }
    }
  },
  "parameters": {
    "retentionDays": {
      "type": "Integer",
      "metadata": {
        "displayName": "Enter the Log retention Days",
        "description": null
      },
      "defaultValue": 7
    },
    "WorkspaceID": {
      "type": "String",
      "metadata": {
        "displayName": "Enter the Workspace ID for Log Analytics",
        "description": null
      },
      "defaultValue": ""
    },
    "EventHubID": {
      "type": "String",
      "metadata": {
        "displayName": "Enter the ID for EventHub",
        "description": null
      },
      "defaultValue": ""
    },
    "EventHubName": {
      "type": "String",
      "metadata": {
        "displayName": "Enter the Name of the EventHub Namespace",
        "description": null
      },
      "defaultValue": ""
    }
  }
}

**Comment by mentat9** [comment]
Those aliases are already available, but they aren't in the Microsoft.Sql namespace. The type you need is ```Microsoft.Insights/diagnosticSettings```. The three aliases are:
```
Microsoft.Insights/diagnosticSettings/eventHubAuthorizationRuleId
Microsoft.Insights/diagnosticSettings/eventHubName
Microsoft.Insights/diagnosticSettings/workspaceId
```

**Comment by aboelter** [comment]
When I try to use that in the method that I described it does not show compliant

[cid:image001.png@01D5224B.CA084990]

Thank you,
Adam Boelter
AGT Desktop Automation
319-355-4975

**Comment by permster** [comment]
I would have to agree that this doesn't appear to work.  In the case of SQL Servers and Databases does diagnosticSettings = auditingSettings?  When doing a Get-AzureRMDiagnosticSettings against a SQL Server with Auditing turned on (Event Hub) I get no information back.  Also, when doing a Get-AzureRMSQLServerAuditing against the same SQL Server I get AuditState = Enabled but no properties or values related to the configured Event Hub.

Something is missing here but it may not be a policy issue.
