### ISSUE TITLE
DeployIfNotExist evalutes and show non compliant but do not deploy template

### ISSUE THREAD

**Issue by mjazwiecki** [Azure/azure-policy#409]
Hello, I am experiencing issue with my custom policy enforcing keeping particular User Defined Route for peered virtual network. In case the network is peered and any of UDR properties do not match with the template UDR should gets deployed automatically for both new and updated existing vNets.

The problem is, after some time, all non-compliant vnets are shown, but no deployment is made. Manual remediation works just fine, but I am aiming for fully automated solution.

Please help.
[udr-to-nva.txt](https://github.com/Azure/azure-policy/files/3251960/udr-to-nva.txt)

**Comment by jreed14** [comment]
We're experiencing the same issue. Is DeployIfNotExist still not available for custom policies?

**Comment by mjazwiecki** [comment]
To make it even more interesting, other custom policy works like a charm. I was wondering, maybe it is resource type I am covering with this one (Microsoft.Network/virtualNetworks) not supported?

**Comment by camillemarie** [comment]
1. _virtualNetworkPeerings_ are exposed both as a property on the _Microsoft.Network/virtualNetworks_ resource type, and as a child resource type:  _Microsoft.Network/virtualNetworks/virtualNetworkPeerings_.

    If the peering is added via the _virtualNetworkPeerings_ API[1], then the policy will not be triggered because the resource type being updated is _Microsoft.Network/virtualNetworks/virtualNetworkPeerings_, not _Microsoft.Network/virtualNetworks_. 

    To address this, you'd need to add a second deployIfNotExists policy targetting the _Microsoft.Network/virtualNetworks/virtualNetworkPeerings_ type:
    ```
            {
                "field": "type",
                "equals": "Microsoft.Network/virtualNetworks/virtualNetworkPeerings"
            },
    ```

     (and updating the aliases in the other conditions accordingly)
 

    [1] i.e. : `PUT /subscriptions/<subId>/resourceGroups/<rgName>/providers/Microsoft.Network/virtualNetworks/<vNetName>/virtualNetworkPeerings/<peeringName>`

2.  By any chance, are all of your resources being marked as non-compliant, even after remediation? I would expect that the aliases in the `existenceCondition` (e.g. `Microsoft.Network/virtualNetworks/subnets/routeTable.routes[*].name`) will never resolve, because they target the _Microsoft.Network/virtualNetworks/subnets_ type, but the `type` in the IfNotExists `details` is _Microsoft.Network/virtualNetworks_

**Comment by mjazwiecki** [comment]
@camillemarie Thank you for your reply! I have to admit that I considered myself pretty good at Azure Policy but the more I try to get this one work I feel I understand it less. 
Ad1. I have try adding the following, but all I got was the same result. No automatic remediation for new or updated resources.
  ```
"if": {
        "anyOf": [
            {
              "allOf": [
                  {
                      "field": "type",
                      "equals": "Microsoft.Network/virtualNetworks"
                  },
                  {
                      "field": "Microsoft.Network/virtualNetworks/VirtualNetworkPeerings[*].peeringState",
                      "equals": "Connected"
                  },
                  {
                      "field": "Microsoft.Network/virtualNetworks/VirtualNetworkPeerings[*].name",
                      "equals": "peerSpokeToHub"
                  }
              ]
            },
            {
              "allOf": [
                  {
                      "field": "type",
                      "equals": "Microsoft.Network/virtualNetworks/VirtualNetworkPeerings"
                  },
                  {
                      "field": "Microsoft.Network/virtualNetworks/virtualNetworkPeerings/remoteVirtualNetwork.id",
                      "exists": "true"
                  }
              ]
            }
        ]
      },
```

Ad2. I made suggested change, but still, after manual remediation corrected resources are shown as non-compliant. Any idea how to fix that?

```
"then": {
          "effect": "deployIfNotExists",
          "details": {
              "type": "Microsoft.Network/virtualNetworks/subnets",
              "existenceCondition": {
                  "allOf": [
                      {
                          "field": "Microsoft.Network/virtualNetworks/subnets/routeTable.id",
                          "exists": "true"
                      },
                      {
                          "field": "Microsoft.Network/virtualNetworks/subnets/routeTable.routes[*].name",
                          "equals": "toNVA"
                      },
                      {
                          "field": "Microsoft.Network/virtualNetworks/subnets/routeTable.routes[*].addressPrefix",
                          "equals": "0.0.0.0/0"
                      },
                      {
                          "field": "Microsoft.Network/virtualNetworks/subnets/routeTable.routes[*].nextHopType",
                          "equals": "VirtualAppliance"
                      },
                      {
                          "field": "Microsoft.Network/virtualNetworks/subnets/routeTable.routes[*].nextHopIpAddress",
                          "in": ["10.0.0.1", "10.0.0.2"]
                      },
                      {
                          "field": "Microsoft.Network/virtualNetworks/subnets/routeTable.routes[*].provisioningState",
                          "equals": "Succeeded"
                      }
                  ]
              },
```

**Comment by mjazwiecki** [comment]
Is there any other place this could be posted to get help?

**Comment by mentat9** [comment]
Yes, best option is to contact CSS if you aren't getting what you need here. They can help with policy questions, and will escalate if necessary to get them answered. Link to open a CSS ticket is here: https://azure.microsoft.com/en-us/support/create-ticket/

**Comment by mjazwiecki** [comment]
@mentat9 Yes, that was my first guess, I have opened the ticket some time ago, but still nothing came out of it.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
