### ISSUE TITLE
Microsoft.HDInsight/clusters/properties.clusterVersion

### ISSUE THREAD

**Issue by MuraliMaohar** [Azure/azure-policy#41]
Scenario : Allow Provisioning of HDInsight Cluster which supports Secure data transfer (https). HDInsight with version 3.6 or newer only supports secured https connection with storage accounts.

Definition: 
{
"policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.HDInsight/clusters"
                    },
                    {
                        "not": {
                            "field": "Microsoft.HDInsight/clusters/properties.clusterVersion",
                            "equals": "3.6.1000.0"
                        }
                    }
                ]
            },
            "then": {
                "effect": "audit"
            }
        }
    }

**Comment by pilor** [comment]
Acknowledged.  I'll work with the HDInsight team to get this published

**Comment by MuraliMaohar** [comment]
Thanks pilor. Appreciate your help on this. Can you give me a tentative date on when this will be published.

**Comment by pilor** [comment]
A few more days.  HDInsight didn't have any existing aliases which makes the process take longer.

**Comment by MuraliMaohar** [comment]
thanks appreciate your help.

**Comment by pilor** [comment]
`Microsoft.HDInsight/clusters/clusterVersion` is now available
