### ISSUE TITLE
Alias Request: Microsoft.ContainerService/managedClusters/addonProfiles[*] 

### ISSUE THREAD

**Issue by marian-craciunescu** [Azure/azure-policy#412]
<!--
    Thank you for contributing!

    ISSUE TITLE:
Alias Request: Microsoft.ContainerService/managedClusters/addonProfiles 

    ISSUE DESCRIPTION (this template):
  AddonProfiles must be exposed via ARM template in order to be able to check if a particular addon is deployed .For example I want to use `httpApplicationRouting` or `omsagent` just from the start 

### Scenario

What are you trying to achieve using Azure Policy?

### Alias

Include details about the alias being requested. Details on aliases are available [**here**](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases).
- What resource provider and resource type is involved?
Microsoft.ContainerService/managedClusters
- What property on that resource type do you wish to expose?
Microsoft.ContainerService/managedClusters/addonProfiles[*].
### Example policy definition
```
{
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "Microsoft.ContainerService/managedClusters"
            },
            {
                "not": {
                    "allOf": [
                        {
                            "field": "Microsoft.ContainerService/managedClusters/addonProfiles.httpApplicationRouting.enabled",
                            "equals": false
                        }
                    ]
                }
            }
        ]
    },
    "then": {
        "effect": "audit"
    }
}
```

**Comment by mentat9** [comment]
Unfortunately, this field is specified in the Open API spec as "additionalProperties". That type of specification does not provide enough schema for it to be manageable by Azure Policy.

**Comment by marian-craciunescu** [comment]
@mentat9  do you think there is a way just to audit the values that are there ?

**Comment by mentat9** [comment]
There is an alias for the add-on collection object itself. To check whether a given add-on is present you could try the containsKey() function. I don't know how/whether that works, or whether the results are able to provide the audit you need. That's the only thing I can think of that might be helpful, other than something really ugly based on strings (not sure that's even possible). Sorry we don't have any good way to support your scenario.
