### ISSUE TITLE
Policy creation issue : Functions App Trigger Values 

### ISSUE THREAD

**Issue by pbillany** [Azure/azure-policy#415]
#### Details of the scenario you tried and the problem that is occurring

Trying to return values of a trigger in a Functions App. 

Hoping to use something like:-

**"value": "[string(field('Microsoft.Web/sites/functions/config')[string('bindings')])]"**

The error back that states that I can’t use expressions that include the “[field('fieldName').property]”.  It’s the first time that I have seen that error any reference to that specific method.

This means that the approach I had in mind will not work.

Below is the output in the portal:

 
![image](https://user-images.githubusercontent.com/26569123/59449762-a2433080-8dff-11e9-96ea-3390a8c4e507.png)

#### Verbose logs showing the problem

![image](https://user-images.githubusercontent.com/26569123/59449877-e8988f80-8dff-11e9-91fe-5e36dc176745.png)

Have also tried to use "contains" string search within on config but get the following regardless of the contents of the field...-

Current value must be equal to the target value.
Field
Microsoft.Web/sites/functions/config
Path
properties.config

Current value
{"bindings":[{"name":"myTimer","type":"timerTrigger","direction":"in","schedule":"0 */5 * * * *"}],"disabled":false}
Target value

"httpTrigger"

#### Suggested solution to the issue

Is it possible to extend alias to this level or query properties as mentioned above?

@mylameaccount - FYI

**Comment by pbillany** [comment]
So trying some amendment to this query.. 

Using:-

"value": "[field('Microsoft.Web/sites/functions')]",
              "contains": "[parameters('PreApprovedTriggers')]"

I'm seeing following error:

readyState: 4

responseText: {"error":{"code":"InvalidPolicyParameters","message":"A function or parameter in policy 'FunctionApp.Binding.MustUseHttp' could not be validated. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'The policy definition 'FunctionApp.Binding.MustUseHttp' rule is invalid. The 'field' property 'Microsoft.Web/sites/functions' of the policy rule doesn't exist as an alias under provider 'Microsoft.Web' and resource type 'sites'. The supported aliases are
'Microsoft.Web/sites/serverFarmId; Microsoft.Web/sites/clientCertEnabled; Microsoft.Web/sites/hostNameSslStates[*].sslState; Microsoft.Web/sites/httpsOnly; Microsoft.Web/sites/hostNames[*]; Microsoft.Web/sites/usageState; Microsoft.Web/sites/availabilityState; Microsoft.Web/sites/name; Microsoft.Web/sites/state; Microsoft.Web/sites/hostNames; Microsoft.Web/sites/repositorySiteName; Microsoft.Web/sites/enabled; Microsoft.Web/sites/enabledHostNames[*]; Microsoft.Web/sites/enabledHostNames; Microsoft.Web/sites/hostNameSslStates[*].name; Microsoft.Web/sites/hostNameSslStates[*].virtualIP; Microsoft.Web/sites/hostNameSslStates[*].thumbprint; Microsoft.Web/sites/hostNameSslStates[*].toUpdate; Microsoft.Web/sites/hostNameSslStates[*]; Microsoft.Web/sites/hostNameSslStates; Microsoft.Web/sites/lastModifiedTimeUtc; Microsoft.Web/sites/siteConfig.id; Microsoft.Web/sites/siteConfig.name; Microsoft.Web/sites/siteConfig.kind; Microsoft.Web/sites/siteConfig.location; Microsoft.Web/sites/siteConfig.type; Microsoft.Web/sites/siteConfig.tags.additionalProperties; Microsoft.Web/sites/siteConfig.tags; Microsoft.Web/sites/siteConfig; Microsoft.Web/sites/siteConfig.numberOfWorkers; Microsoft.Web/sites/siteConfig.defaultDocuments[*]; Microsoft.Web/sites/siteConfig.defaultDocuments; Microsoft.Web/sites/siteConfig.netFrameworkVersion; Microsoft.Web/sites/siteConfig.phpVersion; Microsoft.Web/sites/siteConfig.pythonVersion; Microsoft.Web/sites/siteConfig.nodeVersion; Microsoft.Web/sites/siteConfig.requestTracingEnabled; Microsoft.Web/sites/siteConfig.requestTracingExpirationTime; Microsoft.Web/sites/siteConfig.remoteDebuggingEnabled; Microsoft.Web/sites/siteConfig.remoteDebuggingVersion; Microsoft.Web/sites/siteConfig.httpLoggingEnabled; Microsoft.Web/sites/siteConfig.logsDirectorySizeLimit; Microsoft.Web/sites/siteConfig.detailedErrorLoggingEnabled; Microsoft.Web/sites/siteConfig.publishingUsername; Microsoft.Web/sites/siteConfig.publishingPassword; Microsoft.Web/sites/siteConfig.appSettings[*].name; Microsoft.Web/sites/siteConfig.appSettings[*]; Microsoft.Web/sites/siteConfig.appSettings; Microsoft.Web/sites/siteConfig.metadata[*].name; Microsoft.Web/sites/siteConfig.metadata[*]; Microsoft.Web/sites/siteConfig.metadata; Microsoft.Web/sites/siteConfig.connectionStrings[*].name; Microsoft.Web/sites/siteConfig.connectionStrings[*].connectionString; Microsoft.Web/sites/siteConfig.connectionStrings[*].type; Microsoft.Web/sites/siteConfig.connectionStrings[*]; Microsoft.Web/sites/siteConfig.connectionStrings; Microsoft.Web/sites/siteConfig.handlerMappings[*].extension; Microsoft.Web/sites/siteConfig.handlerMappings[*].scriptProcessor; Microsoft.Web/sites/siteConfig.handlerMappings[*].arguments; Microsoft.Web/sites/siteConfig.handlerMappings[*]; Microsoft.Web/sites/siteConfig.handlerMappings; Microsoft.Web/sites/siteConfig.documentRoot; Microsoft.Web/sites/siteConfig.scmType; Microsoft.Web/sites/siteConfig.use32BitWorkerProcess; Microsoft.Web/sites/siteConfig.webSocketsEnabled; Microsoft.Web/sites/siteConfig.alwaysOn; Microsoft.Web/sites/siteConfig.javaVersion; Microsoft.Web/sites/siteConfig.javaContainer; Microsoft.Web/sites/siteConfig.javaContainerVersion; Microsoft.Web/sites/siteConfig.appCommandLine; Microsoft.Web/sites/siteConfig.managedPipelineMode; Microsoft.Web/sites/siteConfig.virtualApplications[*].virtualPath; Microsoft.Web/sites/siteConfig.virtualApplications[*].physicalPath; Microsoft.Web/sites/siteConfig.virtualApplications[*].preloadEnabled; Microsoft.Web/sites/siteConfig.virtualApplications[*].virtualDirectories[*].virtualPath; Microsoft.Web/sites/siteConfig.virtualApplications[*].virtualDirectories[*].physicalPath; Microsoft.Web/sites/siteConfig.virtualApplications[*].virtualDirectories[*]; Microsoft.Web/sites/siteConfig.virtualApplications[*].virtualDirectories; Microsoft.Web/sites/siteConfig.virtualApplications[*]; Microsoft.Web/sites/siteConfig.virtualApplications; Microsoft.Web/sites/siteConfig.loadBalancing; Microsoft.Web/sites/siteConfig.experiments.rampUpRules[*].actionHostName; Microsoft.Web/sites/siteConfig.experiments.rampUpRules[*].reroutePercentage; Microsoft.Web/sites/siteConfig.experiments.rampUpRules[*].changeStep; Microsoft.Web/sites/siteConfig.experiments.rampUpRules[*].changeIntervalInMinutes; Microsoft.Web/sites/siteConfig.experiments.rampUpRules[*].minReroutePercentage; Microsoft.Web/sites/siteConfig.experiments.rampUpRules[*].maxReroutePercentage; Microsoft.Web/sites/siteConfig.experiments.rampUpRules[*].changeDecisionCallbackUrl; Microsoft.Web/sites/siteConfig.experiments.rampUpRules[*].name; Microsoft.Web/sites/siteConfig.experiments.rampUpRules[*]; Microsoft.Web/sites/siteConfig.experiments.rampUpRules; Microsoft.Web/sites/siteConfig.experiments; Microsoft.Web/sites/siteConfig.limits.maxPercentageCpu; Microsoft.Web/sites/siteConfig.limits.maxMemoryInMb; Microsoft.Web/sites/siteConfig.limits.maxDiskSizeInMb; Microsoft.Web/sites/siteConfig.limits; Microsoft.Web/sites/siteConfig.autoHealEnabled; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.requests.count; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.requests.timeInterval; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.requests; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.privateBytesInKB; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.statusCodes[*].status; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.statusCodes[*].subStatus; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.statusCodes[*].win32Status; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.statusCodes[*].count; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.statusCodes[*].timeInterval; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.statusCodes[*]; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.statusCodes; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.slowRequests.timeTaken; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.slowRequests.count; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.slowRequests.timeInterval; Microsoft.Web/sites/siteConfig.autoHealRules.triggers.slowRequests; Microsoft.Web/sites/siteConfig.autoHealRules.triggers; Microsoft.Web/sites/siteConfig.autoHealRules.actions.actionType; Microsoft.Web/sites/siteConfig.autoHealRules.actions.customAction.exe; Microsoft.Web/sites/siteConfig.autoHealRules.actions.customAction.parameters; Microsoft.Web/sites/siteConfig.autoHealRules.actions.customAction; Microsoft.Web/sites/siteConfig.autoHealRules.actions.minProcessExecutionTime; Microsoft.Web/sites/siteConfig.autoHealRules.actions; Microsoft.Web/sites/siteConfig.autoHealRules; Microsoft.Web/sites/siteConfig.tracingOptions; Microsoft.Web/sites/siteConfig.vnetName; Microsoft.Web/sites/siteConfig.cors.allowedOrigins[*]; Microsoft.Web/sites/siteConfig.cors.allowedOrigins; Microsoft.Web/sites/siteConfig.cors; Microsoft.Web/sites/siteConfig.apiDefinition.url; Microsoft.Web/sites/siteConfig.apiDefinition; Microsoft.Web/sites/siteConfig.autoSwapSlotName; Microsoft.Web/sites/siteConfig.localMySqlEnabled; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].ipAddress; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].subnetMask; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*]; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions; Microsoft.Web/sites/trafficManagerHostNames[*]; Microsoft.Web/sites/trafficManagerHostNames; Microsoft.Web/sites/premiumAppDeployed; Microsoft.Web/sites/scmSiteAlsoStopped; Microsoft.Web/sites/targetSwapSlot; Microsoft.Web/sites/hostingEnvironmentProfile.id; Microsoft.Web/sites/hostingEnvironmentProfile.name; Microsoft.Web/sites/hostingEnvironmentProfile.type; Microsoft.Web/sites/hostingEnvironmentProfile; Microsoft.Web/sites/microService; Microsoft.Web/sites/gatewaySiteName; Microsoft.Web/sites/clientAffinityEnabled; Microsoft.Web/sites/hostNamesDisabled; Microsoft.Web/sites/outboundIpAddresses; Microsoft.Web/sites/containerSize; Microsoft.Web/sites/maxNumberOfWorkers; Microsoft.Web/sites/cloningInfo.correlationId; Microsoft.Web/sites/cloningInfo.overwrite; Microsoft.Web/sites/cloningInfo.cloneCustomHostNames; Microsoft.Web/sites/cloningInfo.cloneSourceControl; Microsoft.Web/sites/cloningInfo.sourceWebAppId; Microsoft.Web/sites/cloningInfo.hostingEnvironment; Microsoft.Web/sites/cloningInfo.appSettingsOverrides.additionalProperties; Microsoft.Web/sites/cloningInfo.appSettingsOverrides; Microsoft.Web/sites/cloningInfo.configureLoadBalancing; Microsoft.Web/sites/cloningInfo.trafficManagerProfileId; Microsoft.Web/sites/cloningInfo.trafficManagerProfileName; Microsoft.Web/sites/cloningInfo; Microsoft.Web/sites/resourceGroup; Microsoft.Web/sites/isDefaultContainer; Microsoft.Web/sites/defaultHostName; Microsoft.Web/sites/reserved; Microsoft.Web/sites/possibleOutboundIpAddresses; Microsoft.Web/sites/dailyMemoryTimeQuota; Microsoft.Web/sites/suspendedTill; Microsoft.Web/sites/snapshotInfo.id; Microsoft.Web/sites/snapshotInfo.name; Microsoft.Web/sites/snapshotInfo.kind; Microsoft.Web/sites/snapshotInfo.type; Microsoft.Web/sites/snapshotInfo; Microsoft.Web/sites/snapshotInfo.snapshotTime; Microsoft.Web/sites/snapshotInfo.recoveryTarget.location; Microsoft.Web/sites/snapshotInfo.recoveryTarget.id; Microsoft.Web/sites/snapshotInfo.recoveryTarget; Microsoft.Web/sites/snapshotInfo.overwrite; Microsoft.Web/sites/snapshotInfo.recoverConfiguration; Microsoft.Web/sites/snapshotInfo.ignoreConflictingHostNames; Microsoft.Web/sites/slotSwapStatus.timestampUtc; Microsoft.Web/sites/slotSwapStatus.sourceSlotName; Microsoft.Web/sites/slotSwapStatus.destinationSlotName; Microsoft.Web/sites/slotSwapStatus; Microsoft.Web/sites/isXenon; Microsoft.Web/sites/hyperV; Microsoft.Web/sites/clientCertExclusionPaths; Microsoft.Web/sites/redundancyMode; Microsoft.Web/sites/inProgressOperationId; Microsoft.Web/sites/geoDistributions[*].location; Microsoft.Web/sites/geoDistributions[*].numberOfWorkers; Microsoft.Web/sites/geoDistributions[*]; Microsoft.Web/sites/geoDistributions; Microsoft.Web/sites/networkConfig.virtualNetwork.subnetResourceId; Microsoft.Web/sites/networkConfig.virtualNetwork.swiftSupported; Microsoft.Web/sites/hostNameSslStates[*].hostType; Microsoft.Web/sites/siteConfig.linuxFxVersion; Microsoft.Web/sites/siteConfig.machineKey.validation; Microsoft.Web/sites/siteConfig.machineKey.validationKey; Microsoft.Web/sites/siteConfig.machineKey.decryption; Microsoft.Web/sites/siteConfig.machineKey.decryptionKey; Microsoft.Web/sites/siteConfig.machineKey; Microsoft.Web/sites/siteConfig.push.id; Microsoft.Web/sites/siteConfig.push.name; Microsoft.Web/sites/siteConfig.push.kind; Microsoft.Web/sites/siteConfig.push.type; Microsoft.Web/sites/siteConfig.push; Microsoft.Web/sites/siteConfig.push.isPushEnabled; Microsoft.Web/sites/siteConfig.push.tagWhitelistJson; Microsoft.Web/sites/siteConfig.push.tagsRequiringAuth; Microsoft.Web/sites/siteConfig.push.dynamicTagsJson; Microsoft.Web/sites/siteConfig.http20Enabled; Microsoft.Web/sites/siteConfig.minTlsVersion; Microsoft.Web/sites/cloningInfo.ignoreQuotas; Microsoft.Web/sites/siteConfig.windowsFxVersion; Microsoft.Web/sites/siteConfig.azureStorageAccounts.additionalProperties.type; Microsoft.Web/sites/siteConfig.azureStorageAccounts.additionalProperties.accountName; Microsoft.Web/sites/siteConfig.azureStorageAccounts.additionalProperties.shareName; Microsoft.Web/sites/siteConfig.azureStorageAccounts.additionalProperties.accessKey; Microsoft.Web/sites/siteConfig.azureStorageAccounts.additionalProperties.mountPath; Microsoft.Web/sites/siteConfig.azureStorageAccounts.additionalProperties.state; Microsoft.Web/sites/siteConfig.azureStorageAccounts.additionalProperties; Microsoft.Web/sites/siteConfig.azureStorageAccounts; Microsoft.Web/sites/siteConfig.cors.supportCredentials; Microsoft.Web/sites/siteConfig.managedServiceIdentityId; Microsoft.Web/sites/siteConfig.xManagedServiceIdentityId; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].vnetSubnetResourceId; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].vnetTrafficTag; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].subnetTrafficTag; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].action; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].tag; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].priority; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].name; Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].description; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].ipAddress; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].subnetMask; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].vnetSubnetResourceId; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].vnetTrafficTag; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].subnetTrafficTag; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].action; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].tag; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].priority; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].name; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*].description; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions[*]; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictions; Microsoft.Web/sites/siteConfig.scmIpSecurityRestrictionsUseMain; Microsoft.Web/sites/siteConfig.ftpsState; Microsoft.Web/sites/siteConfig.reservedInstanceCount'. Please see https://github.com/Azure/azure-policy/blob/master/1-contribution-guide/request-alias.md to request new aliases.'."}}

status: 400

statusText: error

**Comment by mentat9** [comment]
This error is expected, since Microsoft.Web/sites/functions is a resource type, not a field. That resource type does have a number of aliases (you can list them using ```Get-AzPolicyAlias -NamespaceMatch Microsoft.Web -ResourceTypeMatch 'functions' | select -ExpandProperty Aliases```).

**Comment by pbillany** [comment]
So I'm trying to get data back from the aliases mentioned above but so far I've been unsuccessful. 

Function app configuration as follows:-

{"value":
    [{"id":"/subscriptions/subID/resourceGroups/rgname/providers/Microsoft.Web/sites/btest01/functions/HttpTrigger1",
        "name":"btest01/HttpTrigger1",
        "type":"Microsoft.Web/sites/functions",
        "location":"UK South",
        "properties":{"name":"HttpTrigger1",
            "function_app_id":null,
            "script_root_path_href":"https://btest01.azurewebsites.net/admin/vfs/site/wwwroot/HttpTrigger1/",
            "script_href":"https://btest01.azurewebsites.net/admin/vfs/site/wwwroot/HttpTrigger1/run.csx",
            "config_href":"https://btest01.azurewebsites.net/admin/vfs/site/wwwroot/HttpTrigger1/function.json",
            "test_data_href":"https://btest01.azurewebsites.net/admin/vfs/data/Functions/sampledata/HttpTrigger1.dat",
            "secrets_file_href":null,
            "href":"https://btest01.azurewebsites.net/admin/functions/HttpTrigger1",
            "config":
                {"bindings":
                    [{"authLevel":"function",
                        "name":"req",
                        "type":"httpTrigger",
                        "direction":"in",
                        "methods":["get","post"]},
                            {"name":"$return",
                            "type":"http",
                            "direction":"out"}]},
          "files":null,
          "test_data":"{\r\n    \"name\": \"Azure\"\r\n}",
         "invoke_url_template":"https://btest01.azurewebsites.net/api/httptrigger1",
         "language":"CSharp"}}],
    "nextLink":null,
    "id":null}

Tried querying various properties with the variations of the following policy and I'm not getting any values back.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/26569123/59669779-bb0e6600-91b2-11e9-9d34-30b6f40870cd.png">


Is there something wrong with my policy query? Why would I not be getting any values back:-

<img width="484" alt="image" src="https://user-images.githubusercontent.com/26569123/59670822-7a175100-91b4-11e9-95b2-7f23cdb11cf3.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/26569123/59670458-e5145800-91b3-11e9-89bd-4ce261e1a8ac.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/26569123/59670485-ed6c9300-91b3-11e9-883a-a5528a762e4f.png">

Any help gratefully received.

**Comment by pbillany** [comment]
Opened new alias request #430 as I have many, many attempts to extract relevant info without success!
