### ISSUE TITLE
Custom: Deny key vault access policies with certain permissions

### ISSUE THREAD

**Issue by kutluomeroglu** [Azure/azure-policy#416]
#### Deny creation of access policies with specific permissions to keys/secrets

I am trying to achieve this by the policy below, however the keyvaults including access policies that are supposed to be uncompliant according to the rule below are actually showing compliant. I can also add new access policies from the portal, that should get denied by the policy

**Note: This happens when adding a policy when a key vault exists, creating a keyvault with a access policy that doesn't fit the azure policy rule actually gets denied. However, I can go ahead and add an uncompliant access policy once the vault is actually created** 

I believe this should be achievable as aliases were added previously for this issue:
https://github.com/Azure/azure-policy/issues/280

```
{
  "properties": {
    "displayName": "Deny selected Key Vault access policy permissions",
    "policyType": "Custom",
    "mode": "Indexed",
    "description": "Deny assigning selected permissions to access policies for Key Vaults",
    "parameters": {},
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.KeyVault/vaults"
          },
          {
            "field": "Microsoft.Keyvault/vaults/accessPolicies[*].permissions.keys[*]",
            "in": [
              "Create",
              "Delete"
            ]
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }
  },
  "type": "Microsoft.Authorization/policyDefinitions",
  "name": "deny-keyvault-policypermissions"
}
```

**Comment by mentat9** [comment]
Please see https://github.com/Azure/azure-policy/issues/333 for information that might shed light on this problem. Hopefully the guidance there for the DeployIfNotExists scenario can be adapted to your needs.

**Comment by kutluomeroglu** [comment]
Another issue I faced was, when deploying a keyvault, if a create a access policy that has ["Create","Delete","Get"] permissions for keys, it actually passes the rule below:
```
 {
            "field": "Microsoft.Keyvault/vaults/accessPolicies[*].permissions.keys[*]",
            "in": [
              "Create",
              "Delete"
            ]
          }
```
If I create the access policy with exactly the same permissions, I can make it fail. The validation error tells me more about why this request failed by showing this:
```
{
                  "result": "True",
                  "expression": "Microsoft.Keyvault/vaults/accessPolicies[*].permissions.keys[*]",
                  "path": "properties.accessPolicies[*].permissions.keys[*]",
                  "expressionValue": [
                    "Delete",
                    "Create"
                  ],
                  "targetValue": [
                    "Create",
                    "Delete"
                  ],
                  "operator": "In"
                }
```
Does that mean the alias "Microsoft.Keyvault/vaults/accessPolicies[*].permissions.keys[*]" actually returns an array?

**Comment by mentat9** [comment]
You are correct. This page has more information: https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#understanding-the--alias
