### ISSUE TITLE
CosmosDB Virtual Network Rule Append Rule

### ISSUE THREAD

**Issue by geek876** [Azure/azure-policy#417]
Hi, I am trying to run policy in 'append' mode so if the resource that is getting created does not have any virtual network endpoint, it adds one with the right subnet. Doing something like

"effect": "append",
"details": [{

{
"field": "Microsoft.DocumentDB/databaseAccounts/virtualNetworkRules[*].id",
"value": "[parameters('approvedCosmosDbSubnets')]"
}
]

My variables are like
approvedCosmosDbsubnets: subnet1

But it fails with error 'Policy is trying to append fields with different value', EVENTHOUGH i am selecting 'subnet1' when i am creating the DB. Not sure where things are going wrong ?

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
