### ISSUE TITLE
Problem with Script action alias on HDInsight

### ISSUE THREAD

**Issue by VInodKumar-N** [Azure/azure-policy#418]
Trying to check the OS-patching script action is available or not through Azure policy on HDInsight service. But couldn't able to get the expected output.

**Policy Definition**
```

"policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.HDInsight/clusters"
    },
    "then": {
      "effect": "[parameters('effect')]",
      "details": {
        "type": "Microsoft.HDInsight/clusters",
        "name": "[field('name')]",
        "existenceCondition": {
          "field": "Microsoft.HDInsight/clusters/computeProfile.roles[*].scriptActions[*].uri",
          "equals": "https://hdiconfigactions.blob.core.windows.net/linuxospatchingrebootconfigv02/os-patching-reboot-config.sh"
        }
      }
    }
  }

Reason for non-compliance :

Current value must be equal to the target value.
Field
Microsoft.HDInsight/clusters/computeProfile.roles[*].scriptActions[*].uri
Path
properties.computeProfile.roles[*].scriptActions[*].uri
Current value
 --
Target value
"https://hdiconfigactions.blob.core.windows.net/linuxospatchingrebootconfigv02/os-patching-reboot-config.sh"


```

***************************

I have already added the script action to HDInsight cluster. Still it is showing as blank. and marking the resource to be Non-Compliance.

**Comment by mentat9** [comment]
Information on this resource type is in the [**Known Issues**](https://github.com/Azure/azure-policy#known-issues) section of the readme.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the Getting Support section in the readme for details and Azure Policy support information.
