### ISSUE TITLE
Alias Request for Microsoft.Sql/servers/aadsql/administrators/activeDirectory

### ISSUE THREAD

**Issue by uday31in** [Azure/azure-policy#42]
Audit AAD SQL user for Admin.

**Comment by joshidp** [comment]
Can we have a deny policy for SQL Servers without aad admin user set?

Thanks

**Comment by pilor** [comment]
Sorry, this request isn't clear.  What resource property are you requesting to be exposed as a policy alias?

**Comment by joshidp** [comment]
Hi Chris,

This request is for below set of properties under AzureSQL Server.

"properties": {
        "administratorType": "ActiveDirectory",
        "login": "abc@xyz.com",
        "sid": "xxxx--xxxx--xxxx",
        "tenantId": "xxxx--xxxx--xxxx"
      }

Thanks  & Regards,
Deepak

**Comment by joshidp** [comment]
Thanks

**Comment by pilor** [comment]
The following aliases are now available:

Microsoft.Sql/servers/administrators/administratorType
Microsoft.Sql/servers/administrators/login
icrosoft.Sql/servers/administrators/sid
Microsoft.Sql/servers/administrators/tenantId

**Comment by hrboyceiii** [comment]
Is there a working example of this?  I have a policy defined as such:

```
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Sql/servers/administrators"
      },
      {
        "not": {
          "field": "Microsoft.Sql/servers/administrators/administratorType",
          "equals": "ActiveDirectory"
        }
      },
      {
        "not": {
          "field": "Microsoft.Sql/servers/administrators/login",
          "exists": true
        }
      },
      {
        "not": {
          "field": "Microsoft.Sql/servers/administrators/sid",
          "equals": "[parameters('administratorSid')]"
        }
      },
      {
        "not": {
          "field": "Microsoft.Sql/servers/administrators/tenantId",
          "equals": "[subscription().tenantId]"
        }
      }
    ]
  },
  "then": {
    "effect": "[parameters('effect')]"
  }
}
```

Hard coding values for Tenant and Sid do nothing; meaning, if I set effect to Deny and I run an ARM Template, call Set-AzureRMSQLServerAzureActiveDirectoryAdministrator or manipulate the AAD Settings via the Portal, nothing happens with the policy.  I don't see anything in the Activity Log on the resource group either.

Am I missing something?

**Comment by hrboyceiii** [comment]
Update: taking from the [AAD Admin sample ](https://github.com/Azure/azure-policy/tree/master/samples/SQL/audit-if-no-sql-active-directory-admin)which uses an AuditIfNotExists effct, I was able to get this to trigger non-compliance state.

Desired effect would be to enable a deny to prevent the resource from entering non-compliance.  Is this possible?

Here's the AuditIfNotExists policy rule for reference:
```
{
  "if": {
    "field": "type",
    "equals": "Microsoft.Sql/servers"
  },
  "then": {
    "effect": "auditIfNotExists",
    "details": {
      "type": "Microsoft.Sql/servers/administrators",
      "existenceCondition": {
        "allOf": [
          {
            "not": {
              "field": "Microsoft.Sql/servers/administrators/administratorType",
              "equals": "ActiveDirectory"
            }
          },
          {
            "not": {
              "field": "Microsoft.Sql/servers/administrators/login",
              "exists": true
            }
          },
          {
            "not": {
              "field": "Microsoft.Sql/servers/administrators/sid",
              "equals": "[parameters('administratorSid')]"
            }
          },
          {
            "not": {
              "field": "Microsoft.Sql/servers/administrators/tenantId",
              "equals": "[subscription().tenantId]"
            }
          }
        ]
      }
    }
  }
}
```
