### ISSUE TITLE
Custom Diagnostic Settings Application Gateway : Can't choose individual logs to audit

### ISSUE THREAD

**Issue by ruthlees** [Azure/azure-policy#420]
**Details of the scenario you tried and the problem that is occurring:**
 Want to write a policy to auditIfNotExist certain logs and metrics that I need to check that are feeding into a particular workspace that feeds to Sentinel. So for this instance, I need to check that the Application Gateway Access Log and Application Gateway Firewall Log are set to true while Application Gateway Performance log and metric are set to false when being fed to a part. However, can't seem to target the individual logs.

**Verbose logs showing the problem:**
N/A

**Suggested solution to the issue:**

Do I need to create request an alias for individual logs in diagnostic settings for various resources?

**My Custom Policy:**

{
    "properties": {
      "displayName": "Audit Application Gateway - Diagnostic Settings - oms workspace",
      "policyType": "Custom",
      "mode": "All",
      "metadata": {
        "category": "Application Gateway",
      },
      "parameters": {
        "logAnalytics": {
          "type": "String",
          "metadata": {
            "displayName": "Log Analytics workspace",
            "description": "The target Log Analytics Workspace for Azure Diagnostics",
            "strongType": "omsWorkspace"
          }
        },
        "metricsEnabled": {
          "type": "String",
          "metadata": {
            "displayName": "Enable Metrics",
            "description": "Enable Metrics - True or False"
          },
          "allowedValues": [
            "True",
            "False"
          ],
          "defaultValue": "False"
        },
        "applicationGatewayAccessLog": {
          "type": "String",
          "metadata": {
            "displayName": "Enable Application Gateway Access Log",
            "description": "Enable Logs - True or False"
          },
          "allowedValues": [
            "True",
            "False"
          ],
          "defaultValue": "True"
        },
        "applicationGatewayPerformanceLog": {
          "type": "String",
          "metadata": {
            "displayName": "Enable Application Performance Access Log",
            "description": "Enable Logs - True or False"
          },
          "allowedValues": [
            "True",
            "False"
          ],
          "defaultValue": "False"
        },
        "applicationGatewayFirewallLog": {
          "type": "String",
          "metadata": {
            "displayName": "Enable Application Firewall Access Log",
            "description": "Enable Logs - True or False"
          },
          "allowedValues": [
            "True",
            "False"
          ],
          "defaultValue": "True"
        }
      },
      "policyRule": {
        "if": {
          "field": "type",
          "equals": "Microsoft.Network/applicationGateways"
        },
        "then": {
          "effect": "auditIfNotExists",
          "details": {
            "type": "Microsoft.Insights/diagnosticSettings",
            "existenceCondition": {
              "allOf": [
                {
                  "field": "Microsoft.Insights/diagnosticSettings/logs.category",
                  "equals": "[parameters('applicationGatewayAccessLog')]"
                },
                {
                  "field": "Microsoft.Insights/diagnosticSettings/logs.category",
                  "equals": "[parameters('applicationGatewayPerformanceLog')]"
                },
                {
                  "field": "Microsoft.Insights/diagnosticSettings/logs.category",
                  "equals": "[parameters('applicationGatewayFirewallLog')]"
                },
                {
                  "field": "Microsoft.Insights/diagnosticSettings/metrics.enabled",
                  "equals": "[parameters('metricsEnabled')]"
                },
                {
                  "field": "Microsoft.Insights/diagnosticSettings/workspaceId",
                  "equals": "[parameters('logAnalytics')]"
                }
              ]
            }
          }
        }
      }
    }
  }

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
