### ISSUE TITLE
Alias Request : Microsoft.Batch/batchAccounts/pools/scaleSettings.autoScale.formula

### ISSUE THREAD

**Issue by VInodKumar-N** [Azure/azure-policy#422]
This policy is to audit if autoscale property has been enabled or not, and to check formula.
```

{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Batch/batchAccounts/pools"
        },
        {
          "field": "Microsoft.Batch/batchAccounts/pools/scaleSettings.autoScale.formula",
          "exists": "false"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }

}


```

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.Batch has been published, including the above requested alias.

**Comment by VInodKumar-N** [comment]
Hi Chris,

Thanks for looking into this. Today i got a chance to test the alias but they are not giving any results in compliance page. To test it from base i used below definition still no result. Could you please check this once. Thanks.

Policy definition :
`{
  "mode": "All",
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Batch/batchAccounts/pools"
    },
    "then": {
      "effect": "deny"
    }
  }
}`

**Comment by mentat9** [comment]
The support model for this repo has changed. Please see the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
