### ISSUE TITLE
Aliase "Microsoft.ApiManagement/service/backends/protocol" is not retrieving right value 

### ISSUE THREAD

**Issue by rchithracse** [Azure/azure-policy#423]
<!--
    Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:
    Please prefix the issue title with the policy package name, e.g.
    'PolicyName: Validating API Management Backend Protocol 

    ISSUE DESCRIPTION (this template):
    I have used this "Microsoft.ApiManagement/service/backends/protocol" aliases to audit if the backend protocol is configured to http . But it is not retrieving the value and so the policy is not working 
Here is the policy . I checked with "equal" and "like" operators but it is not working. 

Please provide me with the correct aliase to validate the API Management Backend Protocol.
    
"policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.ApiManagement/service/backends"
          },
          {
            "field": "Microsoft.ApiManagement/service/backends/protocol",
            "equals": "http"
          }
        ]
      },
      "then": {
        "effect": "audit"
      }
    }

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
