### ISSUE TITLE
Check services present in storage Account or not

### ISSUE THREAD

**Issue by rahulthescorpion** [Azure/azure-policy#425]
Need a additional data in an existing alias 

Microsoft.Storage/storageAccounts/primaryEndpoints.web; 
Microsoft.Storage/storageAccounts/primaryEndpoints.blob; 
Microsoft.Storage/storageAccounts/primaryEndpoints.queue; 
Microsoft.Storage/storageAccounts/primaryEndpoints.table; 
Microsoft.Storage/storageAccounts/primaryEndpoints.file; 

sample values : https://sqlvawit6qrn37bx2k.blob.core.windows.net/"
Need additonal info like services are present or not in LIST API itself.

**Comment by mentat9** [comment]
Policy aliases can only reference existing data already provided by the resource provider API (Microsoft.Storage in this case). This request needs to go to the storage team. You can submit or upvote ideas at Azure User Voice: https://feedback.azure.com/forums/217298-storage. You can also open a support ticket at https://azure.microsoft.com/support/create-ticket/
