### ISSUE TITLE
Hybrid benefit use policy example excludes images not created from marketplace

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-policy#426]
https://github.com/Azure/azure-policy/tree/master/samples/Compute/enforce-hybrid-use-benefit

Policy provided above verifies that VMs are using hybrid benefit but they are only good for VMs created from images created from Marketplace, so any customer images which are created by attaching disks (like ASRed or manual uploads) will not be included in results.

**Comment by artisticcheese** [comment]
Following policy shall be used instead to catch Windows machines running not created from Gallery 


```
"if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Compute/virtualMachines"
          },
          {
            "field": "Microsoft.Compute/virtualMachines/storageProfile.osDisk.osType",
            "equals": "Windows"
          },
          {
            "field": "Microsoft.Compute/licenseType",
            "notEquals": "Windows_Server"
          }
        ]
      },
```

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
