### ISSUE TITLE
Can i restrict someone from deleting a particular user access at the subscription level using policy?

### ISSUE THREAD

**Issue by sonalikaroy** [Azure/azure-policy#427]

**Comment by mrajess** [comment]
This doesn't seem like a good use for Policy. If there's a user that you want to have rights to a subscription that can't be removed via an owner of said subscription then you should consider putting that subscription inside of a management group and granting the user rights there. The subscription will inherit permissions from the MG and as long as the owner of the inheriting subscription doesn't also have rights to the MG then they won't be able to remove the users rights.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
