### ISSUE TITLE
Alias request: "Microsoft.DBforPostgreSQL/servers/configurations"

### ISSUE THREAD

**Issue by mrajess** [Azure/azure-policy#429]
# Scenario

I'm trying to create policies for CIS 1.1.

It has the following controls:

4.12 Ensure server parameter 'log_checkpoints' is set to 'ON' for PostgreSQL Database Server
4.14 Ensure server parameter 'log_connections' is set to 'ON' for PostgreSQL Database Server 
4.15 Ensure server parameter 'log_disconnections' is set to 'ON' for PostgreSQL Database Server
4.16 Ensure server parameter 'log_duration' is set to 'ON' for PostgreSQL Database Server 
4.17 Ensure server parameter 'connection_throttling' is set to 'ON' for PostgreSQL Database Server
4.18 Ensure server parameter 'log_retention_days' is greater than 3 days for PostgreSQL Database Server

These are configured via Server Parameters, which reside in "Microsoft.DBforPostgreSQL/servers/configurations".

Here's a sample out of the resource explorer:

{
  "value": [
    {
      "properties": {
        "value": "on",
        "description": "Enable input of NULL elements in arrays.",
        "defaultValue": "on",
        "dataType": "Boolean",
        "allowedValues": "on,off",
        "source": "system-default",
        "isConfigPendingRestart": "False",
        "isDynamicConfig": "True"
      },
      "id": "/subscriptions/1a0a3f26-c387-4204-891e-be296382e9d2/resourceGroups/postgresql/providers/Microsoft.DBforPostgreSQL/servers/mrajesspostgresql/configurations/array_nulls",
      "name": "array_nulls",
      "type": "Microsoft.DBforPostgreSQL/servers/configurations"
    },
    {
      "properties": {
        "value": "safe_encoding",
        "description": "Sets whether \"\\'\" is allowed in string literals.",
        "defaultValue": "safe_encoding",
        "dataType": "Enumeration",
        "allowedValues": "safe_encoding,on,off",
        "source": "system-default",
        "isConfigPendingRestart": "False",
        "isDynamicConfig": "True"
      },
      "id": "/subscriptions/1a0a3f26-c387-4204-891e-be296382e9d2/resourceGroups/postgresql/providers/Microsoft.DBforPostgreSQL/servers/mrajesspostgresql/configurations/backslash_quote",
      "name": "backslash_quote",
      "type": "Microsoft.DBforPostgreSQL/servers/configurations"
    },

### Alias

Microsoft.DBforPostgreSQL/servers/configurations/log_checkpoints.value 
Microsoft.DBforPostgreSQL/servers/configurations/log_connections.value
Microsoft.DBforPostgreSQL/servers/configurations/log_disconnections.value
Microsoft.DBforPostgreSQL/servers/configurations/log_duration.value
Microsoft.DBforPostgreSQL/servers/configurations/connection_throttling.value
Microsoft.DBforPostgreSQL/servers/configurations/log_retention_days.value

### Example policy definition

{
    "properties": {
        "displayName": "Ensure server parameter 'log_checkpoints' is set to 'ON' for PostgreSQL Database Server 4.12.",
        "description": "Enable log_checkpoints on PostgreSQL Servers.",
        "mode": "All",
        "metadata": {
            "category": "CIS"
        },
        "parameters": {
            "effect": {
                "type": "String",
                "metadata": {
                    "displayName": "Effect",
                    "description": "Enable or disable the execution of the policy"
                },
                "allowedValues": [
                    "Deny",
                    "Audit"
                ]
            }
        },
        "policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.DBforPostgreSQL/servers"
                    },
                    {
                        "field": "Microsoft.DBforMySQL/servers/configurations/log_checkpoints.value",
                        "notEquals": "on"
                    }
                ]
            },
            "then": {
                "effect": "[parameters('effect')]"
            }
        }
    }
}

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.DBforPostgreSQL have been published. However, properties for the requested aliases are not published in the Open API specs. We can only create aliases for properties that are published in the Open API specs.

**Comment by tobycouchmanmicrosoft** [comment]
@mentat9 We'd like to have deny policy on Microsoft.DBforMySQL/servers/configurations/pgaudit.log but there's no alias for that.  We were expecting the Microsoft.DBforPostgreSQL/servers/configurations/value alias to also have an array alias where we could access the sub properties and have policy on them.  I don't understand the above comment about the Open API specs - is this a request we can post somewhere else?

**Comment by mentat9** [comment]
Unfortunately, we are unable to handle requests for aliases here. Issues here are only for supporting specific policy samples published in this repo. Please refer to the readme for details and information about [getting support for Azure Policy](https://github.com/Azure/azure-policy#azure-policy-support).
