### ISSUE TITLE
Alias question for Microsoft.Cache/Redis/redisConfiguration.additionalProperties

### ISSUE THREAD

**Issue by jchomarat** [Azure/azure-policy#431]
Hello,

I want to create a policy to ensure that the redis configuration parameter rdb-backup-enabled is set to false. When I export the Microsoft.Cache/Redis aliases, I can see Microsoft.Cache/Redis/redisConfiguration.additionalProperties.

How can I set a policy with one of this object's property.
I tried different combinaison, such as:

Microsoft.Cache/Redis/redisConfiguration.additionalProperties.rdb-backup-enabled
Microsoft.Cache/Redis/redisConfiguration.additionalProperties.rdbBackupEnabled
Microsoft.Cache/Redis/redisConfiguration.additionalProperties['rdb-backup-enabled']
etc ....
with no success.

Is there a way, is it supported?

Thanks a lot
Julien

**Comment by mentat9** [comment]
Sorry, Azure Policy is not able to manage additionalProperties fields, since they are not fully schematized in the Open API specs. The alias for additionalProperties in this namespace was created due to a bug and will be removed.
