### ISSUE TITLE
Policy evaluation on /delete operation

### ISSUE THREAD

**Issue by kailashsingh** [Azure/azure-policy#434]
We were working on to enforce a specific UDR that has default route 0.0.0.0/0 to have firewall IP as nextHopIp.
To add this UDR whenever a new Route Table is created, we achieved it through a Append policy.

Now issues comes when someone deletes that route, in this as well we want a Deny policy to kick in and stop user from deleting this route. For this we created a Deny policy which always expects that particular route to be there.

Now issues comes when user deletes the route its /delete operation which does'nt lead to any policy evaluation, which leads to successful route deletion. 

I understand from documention that policy evaluation happen only in /write operation, but is above achievable without resource lock/RBAC that is through policy and is this feature is azure policy pipeline?

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the readme for details and Azure Policy support information.
