### ISSUE TITLE
Alias Request: Microsoft.SqlVirtualMachine/sqlVirtualMachine

### ISSUE THREAD

**Issue by RobbieBinnie** [Azure/azure-policy#436]
I am requesting that an alias be created for Microsoft.SqlVirtualMachine/sqlVirtualMachine, the reason I am requesting this is that I am trying to stop users from enabling the Azure Hybrid benefit for SQL once a marketplace image has been deployed. 

**Example policy:**
"policyRule": {
    "if": {
        "allOf": [
            {
                "field": "Microsoft.SqlVirtualMachine/sqlVirtualMachine/sqlServerLicenseType",
                "equals": "AHUB"
            }
        ]
    },
    "then": {
        "effect": "deny"
    }
}

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.SqlVirtualMachine has been published, including the above requested one.
