### ISSUE TITLE
copy-resourcegroup-tag policy not working as expected

### ISSUE THREAD

**Issue by bijujo** [Azure/azure-policy#439]
I have applied the policy "copy-resourcegroup-tag" to one of our subscription. It is not copying tags from resource group to resources.  Other than assigning the policy, do I need to do anything else for the functionality? Thanks.

**Comment by camillemarie** [comment]
The `copy-resourcegroup-tag` policy will only copy the tag when a resource is created or modified. It will not copy tags to any existing resources (unless they are modified). This behavior [is by-design for the append effect](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/effects#append).
