### ISSUE TITLE
'Mode: Indexed' policy is still being evaluated against resources that don't support tags

### ISSUE THREAD

**Issue by mlnrt** [Azure/azure-policy#441]
Hello,
I have similar issues as in this one: https://github.com/Azure/azure-policy/issues/126

I assigned a built-in policy "Require specified tag" to enforce a specific tag.
That built-in policy has the mode set to 'Indexed' and yet while creating resources through the portal, there are many cases where it gets denied because the resource creation interface doesn't provide the ability to add tags and so the policy is violated.

For example, I can't enable "guest level monitoring" on a VM, because the agent is created without tags and violates the policy.

And the CLI documentation for this doesn't show the --tag parameter as an option for the "az vm diagnostics" command either.

I had the same experience with many other services.

Am I doing anything wrong ?

Best Regards

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for details and Azure Policy support information.
