### ISSUE TITLE
Alias Request: Microsoft.ContainerInstance/containerGroups/ipAddress.type

### ISSUE THREAD

**Issue by pearcec** [Azure/azure-policy#444]
**Scenario**

Restrict ACI from using Public IP addresses. 

**Example**

```
{
      "if": {
         "allOf": [
            {
               "field": "type",
               "in": [
                  "Microsoft.ContainerInstance"
               ]
            },
            {
              "field": "Microsoft.ContainerInstance/containerGroups/ipAddress.type",
              "notEquals": "Private"

            }
         ]
      },
      "then": {
         "effect": "deny"
      }
   }
```

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for details and Azure Policy support information.
