### ISSUE TITLE
Alias Request: Microsoft.Kusto/TrustExternalTenant

### ISSUE THREAD

**Issue by mpchen** [Azure/azure-policy#447]
#### Details of the scenario you tried and the problem that is occurring
I'd like to write a policy to check whether Kusto (Azure Data Explorer) trusts external AAD.

I ran 
> az provider show --namespace Microsoft.Kusto --expand "resourceTypes/aliases" --query "resourceTypes[].aliases[].name

and it looks like no alias is available for Kusto yet.
""

#### Suggested solution to the issue

Request aliases to be published for Microsoft.Kusto, specially the alias for "TrustExternalTenant".

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for details and Azure Policy support information.
