### ISSUE TITLE
field fullName not working for "Microsoft.Network/virtualNetworks/subnets"

### ISSUE THREAD

**Issue by mpchen** [Azure/azure-policy#449]
So I am trying to modify the "enforce-nsg-on-subnet" sample policy to deploy an existing nsg (using deployifnotexists). Below is the "deployifnotexists" part of the policy:

"then": {
        "effect": "DeployIfNotExists",
        "details": {
          "type": "Microsoft.Network/virtualNetworks/subnets",
          "name": "current",
          "roleDefinitionIds": [
            "/providers/Microsoft.Authorization/roleDefinitions/4d97b98b-1d4f-4787-a291-c67834d212e7"
          ],
          "existenceCondition": {
            "field": "Microsoft.Network/virtualNetworks/subnets/networkSecurityGroup.id",
            "equals": "[parameters('nsgId')]"
          },
          "deployment": {
            "properties": {
              "mode": "incremental",
			  "parameters": {
			                "subnetName": {
			                  **"value": "[field('fullName')]"** 
			                }
			              },
              "template": {
                "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                "contentVersion": "1.0.0.0",
                "parameters": {
                  "subnetName": {
                    "type": "string"
                  }
                },
                "resources": [
                  {
                    "name": "[parameters('subnetName')}",
                    "type": "Microsoft.Network/virtualNetworks/subnets",
                    "apiVersion": "2018-03-01",
                    "properties": {
                      "networkSecurityGroup": {
                        "id": "[resourceId('Microsoft.Network/networkSecurityGroups', 'testnsg')]"
                      }
                    }
                  }
                ]
              },

I kept getting the " incorrect segment length" error so I change the value of subnetName from [field('name')] to [field('fullName')]. According to the documentation, fullName should include the parent resource name, which should make the segment length equal. However it does not seem to work.

So my questions are:
1. what is the value of "fullName" for a "subnet" resource;
2. If I have to concat virtualNetworkName and subnetName, how can I get the value of virtualNetworkName (in this case it is the name of the parent resource).

Thanks.

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for details and Azure Policy support information.
