### ISSUE TITLE
Policy alias in compute for acceleratednetworking

### ISSUE THREAD

**Issue by grant-flander** [Azure/azure-policy#459]
Hello. I have searched for this alias but cannot find one. I want to create a policy that limits VMs that are usable to only included VMs that support AcceleratedNetworking. AcceleratedNetworking is under Microsoft.Network/networkInterfaces/enableAcceleratedNetworking now but would be useful to have an alias that lives under Compute. 

Thank you!

**Comment by mentat9** [comment]
Closing this issue per the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for details and Azure Policy support information.

Note: policy aliases don't create new properties, they refer to existing properties. Just use the existing alias in a deny policy that prevents creation of NICs (Microsoft.Network/networkInterfaces) without accelerated networking enabled. This will block creation of VMs containing such a NIC.
