### ISSUE TITLE
Alias request for Microsoft.HDInsight/clusters/properties/securityProfile.domain and Microsoft.HDInsight/clusters/properties/securityProfile.ldapUrls

### ISSUE THREAD

**Issue by MuraliMaohar** [Azure/azure-policy#46]
{
"policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.HDInsight/clusters"
                    },
                    {
                        "not": {
                            "field": "Microsoft.HDInsight/clusters/properties/securityProfile.domain",
                            "equals": "dummy ad"
                        }
                    },
                   {
                        "not": {
                            "field": "Microsoft.HDInsight/clusters/properties/securityProfile.ldapUrls",
                            "equals": "dummy ldap"
                        }
                    }

                ]
            },
            "then": {
                "effect": "audit"
            }
        }
    }

**Comment by pilor** [comment]
```
Microsoft.HDInsight/clusters/securityProfile.directoryType
Microsoft.HDInsight/clusters/securityProfile.domain
Microsoft.HDInsight/clusters/securityProfile.ldapsUrls[*]
```

are now available

**Comment by MuraliMaohar** [comment]
Hi pilor,

this alias is not working for me. can you suggest what i am doing wrong here.

{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.HDInsight/clusters"
      },
      {
        "not": {
          "field": "Microsoft.HDInsight/clusters/securityProfile.ldapsUrls[*]",
          "contains": "ldaps://shadow.bupa.com.au:636"
        }
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}
