### ISSUE TITLE
Alias addition request- Microsoft.Web/sites/SKU

### ISSUE THREAD

**Issue by ahmichae** [Azure/azure-policy#465]
Hi,

One of the fields returned under 'properties' by the following API is SKU but for some reason this field isn't mapped as an alias. Is it possible to add it?
GET https://management.azure.com/subscriptions/SUBSCRIPTION/resourceGroups/RESOURCE-GROUP/providers/Microsoft.Web/sites?api-version=2018-11-01

Thanks!

**Comment by mentat9** [comment]
There is work underway in the Microsoft.Web resource provider to enable the sites/sku property to be managed by policy. It's not just a missing alias, there are other changes that are needed. These changes are not expected to ship before the end of the year at the soonest.

**Comment by mentat9** [comment]
Closing this issue per the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for details and Azure Policy support information.
