### ISSUE TITLE
Allowed Role Definitions: Consider adding an example of the roledefinitionid parameter

### ISSUE THREAD

**Issue by jriekse5555** [Azure/azure-policy#467]
ISSUE DESCRIPTION (this template):
    Just wanted to pass on the suggestion to add an example of a properly formatted roledefinitionid parameter. Really helpful template. It took me hours due to my inexperience sorting through logs to determine the format needed for the right format as shown below with semicolons between values:

/subscriptions/subIDGUID/providers/Microsoft.Authorization/roleDefinitions/defIDGUID

**Comment by DCtheGeek** [comment]
This information is in the docs. The doc additionally shows the format for a built-in role: https://docs.microsoft.com/azure/governance/policy/how-to/remediate-resources#configure-policy-definition

It's also in the _deployIfNotExists_ effect details and example: https://docs.microsoft.com/azure/governance/policy/concepts/effects#deployifnotexists

Where did you expect to see it in the docs and not find it or a reference?

**Comment by jriekse5555** [comment]
Thanks for the link which certainly provides the format.
