### ISSUE TITLE
Alias Request: Microsoft.Storage/storageAccounts/fileServices

### ISSUE THREAD

**Issue by petrs-x** [Azure/azure-policy#471]
I would like to request new Aliases to :

- Microsoft.Storage/storageAccounts/fileServices
- Microsoft.Storage/storageAccounts/fileServices/shares

Azure Backup for File Share is still in preview so not sure if folowing can be added as well:

- Microsoft.RecoveryServices/vaults/backupPolicies/properties/WorkloadType
- Microsoft.RecoveryServices/vaults/backupPolicies/properties/schedulePolicy
- Microsoft.RecoveryServices/vaults/backupPolicies/properties/retentionPolicy
- Microsoft.RecoveryServices/vaults/backupPolicies/properties/TimeZone

Thank you

**Comment by mentat9** [comment]
Closing this issue per the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for details and Azure Policy support information.

Note: Aliases for Microsoft.Storage and Microsoft.RecoveryServices are recently refreshed. The ones you requested in Microsoft.Storage are published. The others are not available.
