### ISSUE TITLE
Audit SQL server audit settings: Known Issues

### ISSUE THREAD

**Issue by migrande** [Azure/azure-policy#475]
#### Details of the scenario you tried and the problem that is occurring
The sample named "Audit SQL server audit settings" is using the resource type Microsoft.SQL/servers/auditingSettings.  However, the Microsoft.Sql/servers/auditingSettings type is listed in the README of this repo as having known issues.  It specifically says "The Azure Policy engine is unable to determine the compliance of any resources of such a type.".  If the sample is relying on an RP that is known to provide incomplete data, that should be noted clearly.

For me, I'm considering setting up a policy following this sample, but I need to know what the impact of the known issue is.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Note on the sample page that the RP for this type has a known issue and clarify what the known issue is with the potential ramifications.

#### If policy is Guest Configuration - details about target node
N/A

**Comment by robga** [comment]
This type "Microsoft.Sql/servers/auditingSettings" can only be used in AuditIfNotExists or DeployIfNotExists policies when specifying the name as "default". 
There are some built-in policies on this type as well: 
/providers/Microsoft.Authorization/policyDefinitions/89099bee-89e0-4b26-a5f4-165451757743
/providers/Microsoft.Authorization/policyDefinitions/7ff426e2-515f-405a-91c8-4f2333442eb5
/providers/Microsoft.Authorization/policyDefinitions/a6fb4358-5bf4-4ad7-ba82-2cd2f41ce5e9
When using this type in audit, deny, modify/append policies, the compliance scan will not work.

**Comment by migrande** [comment]
Could that be clarified in the Known Issues section of the README?  To simply say "Resource Type query results incomplete, missing, or non-standard format" without any clarification on what can or can't be done is confusing.

**Comment by migrande** [comment]
@robga or @camillemarie - any thoughts on clarifying the README?
