### ISSUE TITLE
VirtualMachines policies problem

### ISSUE THREAD

**Issue by iceyokuna** [Azure/azure-policy#488]
I would like to share you the problem that im facing about all policy related to VM image specification. The compliance status of these policy will have a problem. Because, if you use too specific image SKU in the policy like this, it can not cover all VM. When new SKUs come, you need to update the policy like ongoing maintainance. Moreover, there might be some missing SKUs in the policies.

Any idea on this, Please share.

Thank you

**Comment by mentat9** [comment]
Can you organize your images by resource group and use [this](https://github.com/Azure/azure-policy/tree/master/samples/Compute/custom-image-from-rg) approach? Then whenever you add a new image to the existing RG, it will be allowed without updating the policy or assignment.

**Comment by iceyokuna** [comment]
Will this approach cover for all subscription under management group ?
Becuase what i assign a policy to the management group level.

**Comment by mentat9** [comment]
No, that approach doesn't cover an entire organization. I don't know of a way of doing what you want.

Note that this repo is for publishing and discussion of Azure Policy sample policies, not Azure policy features, functionality, or support. The readme has more information about the correct channels for this type of query/request: https://github.com/Azure/azure-policy#azure-policy-support.

**Comment by iceyokuna** [comment]
Thank you.
