### ISSUE TITLE
issue with https traffic on all web apps

### ISSUE THREAD

**Issue by Himalayk** [Azure/azure-policy#489]
###    ISSUE TITLE:
'PolicyName: Enforce https traffic on all Web Apps' not working as expected.

  ###   ISSUE DESCRIPTION:
    

- **Issue 1:** As per policy title **Https traffic on all web app** it should deny only web app but policy deny all types of apps (for ex. function apps).

    

- **Issue 2:** I did a modification in policy effect and policy rule (as mentioned below) to auto remediate web app only using DeployIfNotExists effect.

``` 
"policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites"
        },
        {
          "field": "kind",
          "like": "app*"
        }
      ]
    } 
```
```
"then": {
        "effect": "deny"
      }
```

Added kind field with a value like an app* and effect "DeployIfNotExists". This changes working when I create a remediation task **manually** but not remediating web app automatically (existing and newly created also)

After some research on policy issue found the DeployIfNotExists action "isComplianceCheck" is showing true from the azure policy definition activity logs and this action causing skip of the remediation deployment.

![1](https://user-images.githubusercontent.com/21034366/69541703-c9f21380-0faf-11ea-9a39-611ecc82dec1.jpg)

Appreciate any help on the issues,
- Why "isComplianceCheck" is showing true
- How to meet policy aim "Enforce https traffic on all **Web Apps**(only)"

**Comment by calecarter** [comment]
The "isComplianceCheck: True" is due to the manual remediation call.  That is done as part of the remediation flow.  Can you include the full "Enforce https traffic on all Web Apps (only)" policy you created so I can look into why it is not behaving as expected.

**Comment by calecarter** [comment]
I believe the policy you are looking for is now a built-in policy that was published a couple weeks ago.  

**Name**: Web Application should only be accessible over HTTPS

**Description**: Use of HTTPS ensures server/service authentication and protects data in transit from network layer eavesdropping attacks.

**Definition Id**: /providers/Microsoft.Authorization/policyDefinitions/a4af4a39-4135-47fb-b175-47fbdf85311d

Based on this I am closing this issue.
