### ISSUE TITLE
Alias request: Microsoft.Security/complianceResults/pricings

### ISSUE THREAD

**Issue by lshade** [Azure/azure-policy#49]
** Scenario **

Need to use Azure Policy to ensure all subscriptions in a Management Group are using standard tier of Security Center

** Definition **

{
  "policyRule": {
    "if": {
      "not": {
        "field": "Microsoft.Security/complianceResults/pricings",
        "equals": "Standard"
      }
    },
    "then": {
      "effect": "deny"
    }
  }
}

**Comment by pilor** [comment]
`Microsoft.Security/pricings/pricingTier` is now available
