### ISSUE TITLE
Template function failed in Azure Policy

### ISSUE THREAD

**Issue by iceyokuna** [Azure/azure-policy#490]
I used a template function in Azure policy (substring).
                             {
                                "not": {
                                    "value": "[substring(toLower(field('tags[UpdateManagement]')),3,3)]",
                                    "in": [
                                        "mon",
                                        "tue",
                                        "wed",
                                        "thu",
                                        "fri",
                                        "sat",
                                        "sun"
                                    ]
                                }
                            }
but when the string (in "value" field) is empty or lenght is less than index parameters. The policy will not evaluate as non-compliant, but it will be fail to evaluate. So, when i try to create resource. It will not allow me to create even the policy effect is audit. 

It seem like run time error of the policy back-end.

But i still need to use that kind of template function, any suggession ?
**I think it should mark as non-compliant, not the run-time fail.**

**Comment by DCtheGeek** [comment]
A failed evaluation, often due to a template function error, becomes an **implicit deny**. The recommendation is to use the `if()` function to avoid potential errors. You can read about this approach in the docs: https://docs.microsoft.com/azure/governance/policy/concepts/definition-structure#avoiding-template-failures

**Comment by iceyokuna** [comment]
Thank you so much, i'll looking on that.
