### ISSUE TITLE
roleAssignment/principalType not working properly in deny

### ISSUE THREAD

**Issue by Oscarbralo** [Azure/azure-policy#494]
Hello, 

I am trying to create a policy that deny when you assign an Owner role to a ServicePrincipal.

`{
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "Microsoft.Authorization/roleAssignments"
            },
            {
                "field": "Microsoft.Authorization/roleAssignments/roleDefinitionId",
                "like": "*8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
            },
            {
                "field": "Microsoft.Authorization/roleAssignments/principalType",
                "equals": "ServicePrincipal"
            }
        ]
    },
    "then": {
        "effect": "deny"
    }
}`

This is the policy I have created based on the sample here about white lists, but a little bit different. 

the roleDefinitionId is the Owner. The same policy without the principalType works properly, and block when you try to assign an owner role to a servicePrincipal or User, but now, I would like to add the last part, to only block when its a servicePrincipal. The policy works and shows you everything correct or incorrect, BUT, is not blocking anything nor denying when you try to assign an owner role to a servicePrincipal. 

I don't know if this is some kind of bug, or maybe something different need to be done, I have tried some other options in the last part:

`{
                "field": "Microsoft.Authorization/roleAssignments/principalType",
                "like": "*ServicePrincipal"
}`

or even: 

`{
                "value": "Microsoft.Authorization/roleAssignments/principalType",
                "like": "*ServicePrincipal"
}`

So.. i dont know if the alias "Microsoft.Authorization/roleAssignments/principalType" is not working or not, if someone can confirm please, that would be great. 

i need to block the assignment before is done. 

Thank you

**Comment by kenieva** [comment]
Hi, 

Thanks for your feedback. If you wish to check an aliases, I would suggest using our new VSCode extenstion allows you to hover over resource properties to check for an aliases. 

I can go ahead and validate that the aliases Microsoft.Authorization/roleAssignments/principalType is valid. You said that your policy is based on another one, which is that? 

In the meantime, I will look into this for you 

-Kemley

**Comment by Oscarbralo** [comment]
Hi kenieva, 

Thanks for your quick response. Yeah, i know that the alias is valid (I checked that via az cli), and the policy works fine, the only thing that is not working is when i try to filter for that alias, trying to choose between User or ServicePrincipal.

The policy without that alias deny when I try to assign a role, but, with that alias added, is not denying. 

About policy based on another one, sorry, i was wrong, that is about another policy i am working at the moment, so, this one is not based on anything more. 

Thank you very much

**Comment by Oscarbralo** [comment]
Hi again, 

I have been checking, and yes, even Microsoft.Authorization/roleAssignments/principalType being a valid alias, is not being sent inside the response when you assign a role, so, its not a valid match if you try to check it. 

That was the reason that I couldn't do any equals, because it was not sent in a valid assigntment.

Finally, I have decided to use PrincipalId with only the list of valid ServicePrincipals to check and it worked, so, i think this is a valid a workaround. But Microsoft.Authorization/roleAssignments/principalType is not being sent, so at least for me, not working that alias.

Thank you very much

**Comment by kenieva** [comment]
Glad you found the solution, best!

**Comment by MuraliMaohar** [comment]
Hello,

Even i cannot use this alias "Microsoft.Authorization/roleAssignments/principalType". This listed as the valid alias, but when try to filter against this alias. it is not working for me.

Here is the policy definition.

{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Authorization/roleAssignments"
        },
        {
          "not": {
            "field": "Microsoft.Authorization/roleAssignments/principalType",
            "equals": "User"
          }
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  },
  "parameters": {}
}

**Comment by MuraliMaohar** [comment]
sorry i must have done some type. the above policy definition is working for me now.
