### ISSUE TITLE
Issue with Policy alias - Microsoft.Network/networkInterfaces/networkSecurityGroup.networkInterfaces[*].id

### ISSUE THREAD

**Issue by chavaravikanth** [Azure/azure-policy#495]
Hi Team,

We are implementing a policy in Azure.

Any VM which has a network security group that has more than one network interface assigned - need to be marked as Non-Compliant
and we are trying to fetch the below policy alias in the existencecondition(type of Microsoft.Network/networkInterfaces) of the "AuditIfNotExists".

Alias ID: Microsoft.Network/networkInterfaces/networkSecurityGroup.networkInterfaces[*].id -

The alias returns an entry with '--'

Can you please let me know if this alias is still valid.

"policyRule": {
"if": {
"allOf": [
{
"field": "type",
"equals": "Microsoft.Compute/virtualMachines"
}
]
},
"then": {
"effect": "auditIfNotExists",
"details": {
"type": "Microsoft.Network/networkInterfaces",
"existenceCondition": {
"allOf": [
{
"count": {
"field": "Microsoft.Network/networkInterfaces/networkSecurityGroup.networkInterfaces[*]"
},
"equals": 1
}
]
}
}
}
}

Regards,
Ravi Kanth

**Comment by mentat9** [comment]
This repo is for publishing and supporting policy samples. Please refer to the readme for details and information about [getting support for Azure Policy](https://github.com/Azure/azure-policy#azure-policy-support).
