### ISSUE TITLE
Location isn't indicated in my Allowed locations template

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#50]
I created a built-in policy Allowed location and assigned to my target resource. The policy is effective. However, when I checked definition template I didn't see location indicated.

```
{
  "if": {
    "allOf": [
      {
        "field": "location",
        "notIn": "[parameters('listOfAllowedLocations')]"
      },
      {
        "field": "location",
        "notEquals": "global"
      },
      {
        "field": "type",
        "notEquals": "Microsoft.AzureActiveDirectory/b2cDirectories"
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}
```

There must be a value inside this element `notIn": "[parameters('listOfAllowedLocations')]"` but where exactly I can find to adjust?

**Comment by pilor** [comment]
Parameter values are declared in the policyAssignment resource that assigned your definition to a particular scope (subscription, resource group, etc...).  You can see all assignments in your environment at:
https://ms.portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyMenuBlade/Assignments

**Comment by thuansoldier** [comment]
You might misunderstand my query. I'd like to know why the location is hidden in the template. To embrace DevOps culture, I don't think Azure Portal is helpful. I do know that I can see allowed locations in Azure Portal.
