### ISSUE TITLE
Issue on Network Interface built-in&Sample policy

### ISSUE THREAD

**Issue by iceyokuna** [Azure/azure-policy#501]
#### Scenario
I try to apply built-in policy to deny the network interfaces which are configured with any public IP.
The policy works as i expected, it denies any network interfaces with Public IP. However, it does not work with Azure Databricks cluster which will create the network interfaces with Public IP automatically.
Those Databricks resources are bypassed policy evaluation. But It is good that policy does not deny those Databricks resources because Databricks still requires Public IP.

The problem is that Network Interfaces of Databricks clusters are marked as non-compliant . But I dont want it to show in the non-compliant list. So, Is there any solution to write a policy that can detect and exclude the Network Interfaces which associated with a Databricks cluster(VM). And we dont want to use tags because people can put the same tag as Databricks cluster on thier resource to avoid policy. As i can see, there are no policy aliases of "Network Interfaces" that i can use to determine resource from databricks. 

#### policy definition
**Built-in policy** : "Network interfaces should not have public IPs"
**policy definition ID** : /providers/Microsoft.Authorization/policyDefinitions/83a86a26-fd1f-447c-b59d-e51f44264114

{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Network/networkInterfaces"
      },
      {
        "anyof": [
          {
            "field": "Microsoft.Network/networkInterfaces/ipconfigurations[*].publicIpAddress.id",
            "exists": true
          },
          {
            "not": {
              "field": "Microsoft.Network/networkInterfaces/ipconfigurations[*].publicIpAddress.id",
              "exists": false
            }
          }
        ]
      }
    ]
  },
  "then": {
    "effect": "deny"
  }
}

#### Suggested solution to the issue
Actually, if we can determine the image publisher of Databricks VMs with Public IP on Network Interfaces. It will be a solution for this problem. However, the current policy alises of Network Interfaces resource still can not fullfill this solution. 

**Current policy aliases that we can refer to associated VM**

- Microsoft.Network/networkInterfaces/virtualMachine
- Microsoft.Network/networkInterfaces/virtualMachine.id

**I am looking for alises that can dive into associated VM image reference:** 

- Microsoft.Network/networkInterfaces/virtualMachine.publisher
- Microsoft.Network/networkInterfaces/virtualMachine.offer
- Microsoft.Network/networkInterfaces/virtualMachine.sku

So, If we can get those 3 aliases, then this issue will be solved. Because we can write a policy to ignore Network Interfaces that associated with VM Image publisher Databricks. And it will not show in the non-compliant list.

**Comment by kenieva** [comment]
Hi, 

Thanks for your feedback. If you do not want the Databricks VMs to shown in the non-compliant list within the Policy, you can exclude the resource group which the vm is in so that the policy will not evaluate against it. Furthermore, we are looking to expand our policy enforcement on Databricks so soon the creation VMs can be denied with policy. 

Thanks!
