### ISSUE TITLE
Is there any alternative for using more than one count

### ISSUE THREAD

**Issue by piyushanshu** [Azure/azure-policy#511]
Hi,
I am trying to put two different condition for the compliance check. I am accessing array of logs twice which is causing error. Can you suggest me any alternative to this? Below is my policy.

{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.RecoveryServices/vaults"
        },
        {
          "field": "location",
          "in": "[parameters('AzureRegions')]"
        }
      ]
    },
    "then": {
      "effect": "deployIfNotExists",
      "details": {
        "type": "Microsoft.Insights/diagnosticSettings",
        "existenceCondition": {
          "anyof": [
            {
              "allof":[
              {
                "count": {
                "field": "Microsoft.Insights/diagnosticSettings/logs[*]",
                "where": {
                  "allof": [
                    {
                      "field": "Microsoft.Insights/diagnosticSettings/logs[*].Category",
                      "in": 
                      [
                        "CoreAzureBackup",
                        "AddonAzureBackupJobs",
                        "AddonAzureBackupAlerts",
                        "AddonAzureBackupPolicy",
                        "AddonAzureBackupStorage",
                        "AddonAzureBackupProtectedInstance"
                      ]
                    },
                    {
                      "field": "Microsoft.Insights/diagnosticSettings/logs[*].Enabled",
                      "equals": "True"
                    }
                  ]
                }
              },
              "Equals": 6
              },
              {
                "field": "Microsoft.Insights/diagnosticSettings/workspaceId",
                "notEquals": ""
              } 
              ]
            },            
            {
              "allof":[
                  {
                    "count": {
                    "field": "Microsoft.Insights/diagnosticSettings/logs[*]",
                    "where": {
                      "allof": [
                        {
                          "field": "Microsoft.Insights/diagnosticSettings/logs[*].Category",
                          "equals": "AzureBackupReport"
                        },
                        {
                          "field": "Microsoft.Insights/diagnosticSettings/logs[*].Enabled",
                          "equals": "True"
                        }
                      ]
                    }
                  },
                  "Equals": 1
                  },
                  {
                    "field": "Microsoft.Insights/diagnosticSettings/workspaceId",
                    "notEquals": ""
                  }
              ]
            }          
          ]
        },
        "roleDefinitionIds": [
          "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
        ],
        "deployment": {
          "properties": {
            "mode": "incremental",
            "template": {
              "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
              "contentVersion": "1.0.0.0",
              "parameters": {
                "vaultName": {
                  "type": "string"
                },
                "location": {
                  "type": "string"
                },
                "logAnalytics": {
                  "type": "string"
                },
                "metricsEnabled": {
                  "type": "string"
                },
                "logsEnabled": {
                  "type": "string"
                },
                "profileName": {
                  "type": "string"
                }
              },
              "variables": {},
              "resources": [
                {
                  "type": "Microsoft.RecoveryServices/vaults/providers/diagnosticSettings",
                  "apiVersion": "2017-05-01-preview",
                  "name": "[concat(parameters('vaultName'), '/', 'Microsoft.Insights/', parameters('profileName'))]",
                  "location": "[parameters('location')]",
                  "dependsOn": [],
                  "properties": {
                    "workspaceId": "[parameters('logAnalytics')]",
                    "logAnalyticsDestinationType": "Dedicated",
                    "metrics": [],
                    "logs": [
                      {
                        "category": "CoreAzureBackup",
                        "enabled": "true"
                      },
                      {
                        "category": "AddonAzureBackupAlerts",
                        "enabled": "true"
                      },
                      {
                        "category": "AddonAzureBackupJobs",
                        "enabled": "true"
                      },
                      {
                        "category": "AddonAzureBackupPolicy",
                        "enabled": "true"
                      },
                      {
                        "category": "AddonAzureBackupProtectedInstance",
                        "enabled": "true"
                      },
                      {
                        "category": "AddonAzureBackupStorage",
                        "enabled": "true"
                      }
                    ]
                  }
                }
              ],
              "outputs": {
                "policy": {
                  "type": "string",
                  "value": "[concat(parameters('logAnalytics'), 'configured for diagnostic logs for ', ': ', parameters('vaultName'), '/', 'Microsoft.Insights/', parameters('profileName'))]"
                }
              }
            },
            "parameters": {
              "logAnalytics": {
                "value": "[parameters('logAnalytics')]"
              },
              "location": {
                "value": "[field('location')]"
              },
              "vaultName": {
                "value": "[field('name')]"
              },
              "metricsEnabled": {
                "value": "[parameters('metricsEnabled')]"
              },
              "logsEnabled": {
                "value": "[parameters('logsEnabled')]"
              },
              "profileName": {
                "value": "[parameters('profileName')]"
              }
            }
          }
        }
      }
    }
  },
  "parameters": {
    "profileName": {
      "type": "String",
      "metadata": {
        "displayName": "Profile Name for Config",
        "description": "The profile name Azure Diagnostics"
      }
    },
    "logAnalytics": {
      "type": "String",
      "metadata": {
        "displayName": "Log Analyitcs workspace",
        "description": "The target Log Analytics Workspace for Azure Diagnostics",
        "strongType": "omsWorkspace"
      }
    },
    "azureRegions": {
      "type": "Array",
      "metadata": {
        "displayName": "Allowed Locations",
        "description": "The list of locations that can be specified when deploying resources",
        "strongType": "location"
      }
    },
    "metricsEnabled": {
      "type": "String",
      "metadata": {
        "displayName": "Enable Metrics",
        "description": "Enable Metrics - True or False"
      },
      "allowedValues": [
        "True",
        "False"
      ],
      "defaultValue": "False"
    },
    "logsEnabled": {
      "type": "String",
      "metadata": {
        "displayName": "Enable Logs",
        "description": "Enable Logs - True or False"
      },
      "allowedValues": [
        "True",
        "False"
      ],
      "defaultValue": "True"
    }
  }
}

**Comment by pilor** [comment]
Policy questions and support should go through normal support channels.  See https://github.com/Azure/azure-policy#azure-policy-support
