### ISSUE TITLE
Allow writing policy rules against field identity.userAssignedIdentities

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/azure-policy#512]
Today I am getting the errror.
```
The value of 'field' property 'identity.userAssignedIdentities' of the policy rule must be one of 'Name, Type, Location, Tags, Kind, FullName, Identity.type'
```

Enabling this capability would allow to protect a user assigned managed identity from being used with specific resource types. E.g. create a UAMI that could be used only for Azure Blueprint assignment, but cannot be assigned to a Web App.

**Comment by pilor** [comment]
Thanks.  I agree that we should support it and we will work on getting that added.  Can you please add it here as an ask?  https://feedback.azure.com/forums/915958-azure-governance
