### ISSUE TITLE
RequireTag_Deny.json expecting tags on resource that don't support them

### ISSUE THREAD

**Issue by OffColour** [Azure/azure-policy#518]
This policy is checking for tags on resources that don't support them.

For example, It's blocking the creation of DSC configurations in automation accounts as they don't have my required tag, but DSC configurations don't support tags.

In addition, it's looking for tags on things like the Log Analytics and Depndency agents which when deployed via the Azure monitor policy don't have tags.

It looks like this policy needs some built-in exceptions.

EDIT: It seems that there are many resources that support tags at the API level but this isn't reflected in the portal. DSC configurations and runbooks are the ones we've found so far.

This also applies to some Solutions, e.g. the Auto Stop start runbook solution fails as tags can't be specified.

So unsure if this is an issue with the policy, something that needs addressing in the portal and things like the Terraform provider or need to make better use of resource group tag inheritance policies might work. The inheritance policy might not work though as the deny create in this policy would likely kick in before the modify could apply to the newly created object.

**Comment by amezoii** [comment]
Hi OffColour - Are you still having issues with this? Simple question first, is your Mode set to all or indexed? 

'Indexed' will only evaluate on taggable resources whereas 'All' will evaluate on any resource. So if you are using 'All', change it to Indexed in the definition and try it again.

**Comment by OffColour** [comment]
Hi,

I'm using the default built in policy which is set to Indexed, not my own policy. My guess is that some Solutions, like the one I highlighted don't provide an option to specify a tag at creation so they get denied. So it's not the policy that's at fault, but the Solution.

There's a similar situation when creating other resources through the portal when you create a new resource group at the same time. The final screen of these give you the option of a adding a tag, but then only applies it to the specific resource you're creating and not the new resource group and therefore gets denied.

So I think you can close this as the policy is working as expected but many other things in the portal can't cope with the policy being implemented.
