### ISSUE TITLE
Alias request: "Microsoft.Web/sites/config/ipSecurityRestrictions"

### ISSUE THREAD

**Issue by alex-3sr** [Azure/azure-policy#52]
* Scenario
Permit to check that webapp are correctly compliant with IP restrictions, for allow only IP Adress allowed
* Definition

{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "field": "Microsoft.Web/sites/config/siteAuthEnabled",
          "in": ["1.2.3.4,1.2.3.5"]
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {},
  "metadata": {
    "category": "x_CustomPolicy"
  }
}

**Comment by pilor** [comment]
```
Microsoft.Web/sites/config/ipSecurityRestrictions[*].ipAddress
Microsoft.Web/sites/config/ipSecurityRestrictions[*].subnetMask
```

are now available

**Comment by singh1612** [comment]
Hi,

we try to check that all webapps are correctly compliant with IP restrictions, but without any sucsess. They are all shown as complian... any suggestions.


We are using / trying the following definitions:

-         "field": "Microsoft.Web/sites/config/ipSecurityRestrictions",
-         "notContains": "{xxx.xxx.xxx.xxx}"

-         "field": "Microsoft.Web/sites/config/ipSecurityRestrictions[*].ipAddress",
-         "contains": "xxx.xxx.xxx.xxxx"

Thx.

**Comment by singh1612** [comment]
Hi,
we try to check that all WebApps are correctly compliant with IP restrictions, but without any success. They are all shown as compliant... any suggestions.

We are using / trying the following definitions:
field": "Microsoft.Web/sites/config/ipSecurityRestrictions",
notContains": "{xxx.xxx.xxx.xxx}"
"field": "Microsoft.Web/sites/config/ipSecurityRestrictions[*].ipAddress",
"contains": "xxx.xxx.xxx.xxxx"

Thx.
