### ISSUE TITLE
NetworkSecurityGroup_SSHAccess_Audit.json fails evaluation when specifying a wide dest port range 

### ISSUE THREAD

**Issue by mpchen** [Azure/azure-policy#521]
ISSUE TITLE:
    **PolicyName: 'NetworkSecurityGroup_SSHAccess_Audit.json ' and 'NetworkSecurityGroup_RDPAccess_Audit.json'**

    ISSUE DESCRIPTION:
   **These two policies causes evaluation failure when using a wide port range in dest port. For example, creating a nsg with dest port range as 1024-65536 will cause evaluation failure.** 

   Error Msg:

> Please either fix the policy or remove the policy assignment to unblock. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'The template language function 'range' parameters are out of range: 'count' must be a positive integer no larger than 1000 and the sum of 'start index' and 'count' must be no larger than 2147483647.

**Comment by pilor** [comment]
Thanks for reporting.  We'll get it assigned to the appropriate person internally.

**Comment by pilor** [comment]
The fix for this has been released
