### ISSUE TITLE
Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings

### ISSUE THREAD

**Issue by Lithonite** [Azure/azure-policy#524]
Hello I'm thinking I need a little help. The problem is I dont now what is wrong just know it appears no resources are ever evaluated from my policy assignments. 

The following fails to match on\evaluate any resources:
`"if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings"
        },
        {
          "field": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings/default.resource.throughput",
          "greater": 1000
        }
      ]
    },
    "then": {
      "effect": "audit"
    }`

Where as when I simplify to the container object only and I see the relevant resources in compliance review. 
`"if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers"
          }
        ]
      },
      "then": {
        "effect": "audit"
      }`
In contrast I did attempt to run a policy on just "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings" and confirmed no resources appear to have been evaluated in compliance review.

I am assuming I am missing something here but I am definitely at a loss  for what that is. Hopefully someone can help me understand my gap. I did ensure the type in question appears in my arm template, and the property seems to validate on save(in terms of syntax). None the less my compliance review always shows 0 resources when written as intended to audit throughput settings.

**Comment by mentat9** [comment]
This is due to incomplete onboarding of Microsoft.DocumentDB to Azure Policy. The necessary corrections are in progress now. Barring any unforeseen issues, it should be complete within another 24 hours or so. Please try again then.
