### ISSUE TITLE
Alias request: "Microsoft.Web/sites/config/http20Enabled"

### ISSUE THREAD

**Issue by alex-3sr** [Azure/azure-policy#53]
* Scenario
Permit to check that webapp have http 2.0 Enabled

* Definition

{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "field": "Microsoft.Web/sites/config/http20Enabled",
          "equals": "true"
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {},
  "metadata": {
    "category": "x_CustomPolicy"
  }
}

**Comment by pilor** [comment]
`Microsoft.Web/sites/config/http20Enabled` is now available
