### ISSUE TITLE
Allow me to host policies outside of github

### ISSUE THREAD

**Issue by nicksc423** [Azure/azure-policy#535]
When trying to create my own policies for my AKS cluster I am hit with the error:
`String does not match the pattern of "^(https:\/\/raw\.githubusercontent\.com\/){1}(.*)(.rego){1}$"`

Why must I host my rego policies on github?  Seems silly and very limiting.

**Comment by RamyasreeChakka** [comment]
@nicksc423 Thanks for trying AKS policies. Currently for Kubernetes, we allow only built-in policies, custom policy creation is blocked.
The OPA CRD YAMLs have to be hosted on a location where Azure Policy Add-on can reach out and download the YAMLs to install on the cluster. For built-in policies, we are hosting YAMLs on GitHub and hence the above check. 
When we start supporting custom definitions, we will consider allowing locations other than GitHub.
