### ISSUE TITLE
How to build your own custom policy for guest configuration? 

### ISSUE THREAD

**Issue by skyljj** [Azure/azure-policy#536]
#### Details of the scenario you tried and the problem that is occurring
I understand we have code for guest configurations .
https://github.com/Azure/azure-policy/tree/master/samples/GuestConfiguration/package-samples/configurations/NotInstalledApplicationForLinux

and also we have built-in policy for that:
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Guest%20Configuration/GuestConfiguration_NotInstalledApp_Audit.json

but after read the document,I still don't know how to proceed, Can someone help me with that?
https://docs.microsoft.com/en-us/azure/governance/policy/how-to/guest-configuration-create

I have applied password-security guest configuration policy in azure, and it works well with chefinspec.
logs: 
" InSpec policy test failed. Test description: 'File /etc/passwd mode should cmp == "0644"'Test message: '
expected: "0644"
     got: "0666"
"

So I know the function is working , But I don't know how to make it happen, Can anyone guide me step by step to accomplish this?
Thanks in advance

**Comment by kenieva** [comment]
Hi @skyljj , we do not have exact steps in how to make a custom policy for guest config and It seems like you have all the write links. I would suggest taking in a built in policy as a template and then work to change/swamp the requirements that you need. You can also leverage our support engineers by creating a support ticket. They can help you in creating a custom policy.
