### ISSUE TITLE
Alias request: "Microsoft.Web/sites/config/minTlsVersion"

### ISSUE THREAD

**Issue by alex-3sr** [Azure/azure-policy#54]
* Scenario
Permit to check that webapp are secure by using only TLS 1.2

* Definition

{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "field": "Microsoft.Web/sites/config/minTlsVersion",
          "equals": "1.2"
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {},
  "metadata": {
    "category": "x_CustomPolicy"
  }
}

**Comment by thuansoldier** [comment]
Voted. This is one of the very common security requirements.

**Comment by thuansoldier** [comment]
I'd alo be interested in new alias for **clientCertEnabled** to ensure security confidentiality.

**Comment by pilor** [comment]
`Microsoft.Web/sites/config/minTlsVersion` is now available
