### ISSUE TITLE
HIPAA_HITRUST_audit.json:  Non-Printable character is causing issues with the policy implementation

### ISSUE THREAD

**Issue by daemel** [Azure/azure-policy#544]
#### Details of the scenario you tried and the problem that is occurring
When trying to use the HIPAA_HITRUST_audit policy it fails due to an un-recognizable character.  Possibly related to this is that the HIPAA_HITRUST_audit policy is not visible in the Azure Portal 

#### Verbose logs showing the problem
Edit RAW File (results in) - 
We’ve detected the file encoding as UTF-16LE. When you commit changes we will transcode it to UTF-8

#### Suggested solution to the issue
Re-encode the file

**Comment by DCtheGeek** [comment]
FYI @RajeevRangappa

**Comment by pilor** [comment]
This was re-encoded to UTF8 a while ago.  Forgot to close this issue.  Please re-open if you are still experiencing a problem.
