### ISSUE TITLE
ERROR - Defining Policy -New-AzPolicyAssignment - Can't use inline policy defination 

### ISSUE THREAD

**Issue by Neelkamal10** [Azure/azure-policy#546]
Encountered following error, while creating new policy defining:
![Screenshot (2)](https://user-images.githubusercontent.com/54034262/78980622-e4cabc00-7b3b-11ea-98ec-0ebd4becc964.png)

the script is here:
[t1.txt](https://github.com/Azure/azure-policy/files/4460903/t1.txt)

**Comment by pilor** [comment]
Your policy rule JSON isn't valid JSON.  You are missing the closing curly bracket after
```
{
                  "field": "type",
                  "equals": "Microsoft.Network/networkInterfaces"
```
