### ISSUE TITLE
Alias request: Microsoft.Storage/storageAccounts/blobServices/privateEndpointConnections/privateLinkServiceConnectionState.status

### ISSUE THREAD

**Issue by BadLuckNick** [Azure/azure-policy#551]
Scenario
Need to audit or block Storage Account creation without Private Link. Currently I have not found a way to do this and I suspect it has something to do with Private Link attaching to a Blob/Table/other endpoint instead of the Storage Account (therefore auditing correctly is impossible).

Required Alias:
Microsoft.Storage/storageAccounts/blobServices/privateEndpointConnections/privateLinkServiceConnectionState.status

Or ofcourse, if there is anything I've missed and there is a way to do this please tell me :).

**Comment by pilor** [comment]
Azure Support is now the appropriate channel for alias requests.  See https://github.com/Azure/azure-policy#alias-requests
