### ISSUE TITLE
Key Vault/Certificates_Expiry_ByDays.json

### ISSUE THREAD

**Issue by FeaturedWisdom** [Azure/azure-policy#555]
The policy  Key Vault/Certificates_Expiry_ByDays.json given as built-in is not evaluating any resources or certificates . Even after compliance run it says 0/0 resources compliant.

**Comment by pilor** [comment]
Please open a support request if a built-in policy is not functioning as expected.
https://github.com/Azure/azure-policy#azure-policy-support
