### ISSUE TITLE
Using the field Microsoft.DBforPostgreSQL/servers/configurations/value

### ISSUE THREAD

**Issue by FeaturedWisdom** [Azure/azure-policy#556]
Hi,
anyone was able to use the field Microsoft.DBforPostgreSQL/servers/configurations/value in policy definition. I am not able to trigger policy evaluation if i use this field
 
"if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.DBforPostgreSQL/servers/configurations"
          },
          {
            "field": "name",
            "contains": "log_retention_days"
          },
          {
            "field": "Microsoft.DBforPostgreSQL/servers/configurations/value",
            "less": 4
          }
        ]
      },
      "then": {
        "effect": "audit"
      }
    }

**Comment by kenieva** [comment]
What do you mean by "trigger policy evaluation"? Are you able to get the policy but no compliance data?

**Comment by kenieva** [comment]
We haven't gotten a response so I will close this issue. Please re-open issue when needed information is gathered.
