### ISSUE TITLE
Locations-based policy compliance fails with '--' locations

### ISSUE THREAD

**Issue by pvanroos** [Azure/azure-policy#559]
For a locations-based Azure policy, we are getting resources that have a location of '--'.  This means our compliance evaluation fails for all of them and there's alot of them.  Should we add something in the policy definition rules that ignores '--'?

**Comment by pilor** [comment]
This most likely indicates your policy is evaluating against resources that do not have a location.  Ensure your policy definition is using "mode": "indexed".  

https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#mode

**Comment by pvanroos** [comment]
@pilor Thanks.  Make sense.  

If I update a policy definition whilst already in an initiative, do I need to reassign the initiative or re-add the policy again?

**Comment by pilor** [comment]
No, the latest state of the definition will always be used.  There are caches in play so it may take up to 30 minutes to reflect changes.  You can typically sign out and sign back in to force it to refresh the definitions it is using.

**Comment by pvanroos** [comment]
Thanks again.
