### ISSUE TITLE
Events tab shows no event

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#57]
As far as my understanding, when Azure Policy scans, events are recorded and displayed in Events tab. But from what I've noticed, there is no event shown.

What does exactly **Event** mean? The tooltip seems to show a hint but still not to be clear (Events are recorded when policy effect is exercised after resource evaluation).

**Comment by LizMS** [comment]
After a policy assignment, any resource creation or change gets evaluated by the policy first. If the resource request meets the 'IF' condition of the policy definition, then the policy effect (audit/append/deny/deploy) takes place. The fact that the effect has taken place by the policy gets recorded onto the Activity Log, and then reflected onto the 'Events' tab.

**Comment by pilor** [comment]
For example, if users are getting denied by a policy you should see "deny" events show up in the events tab.  Similar for append, deploy, etc...
