### ISSUE TITLE
Policy: Register resource provider

### ISSUE THREAD

**Issue by nasarbasha** [Azure/azure-policy#573]
Hello,
I am looking for ways to enable resource providers using policy.

I want to deploy this policy via Azure Blueprints, Is it Possible?

Thanks,
Nasar

**Comment by pilor** [comment]
Template deployments register resource providers that are needed by the template.  Therefore, if you are using blueprints you should only need to include a template that contains resources for the providers you want to register.  When that runs it should register those providers to the subscription.

There is no functionality in policy to query or ensure that a resource provider is registered.

**Comment by tom-pot** [comment]
@pilor since blueprints are going to be deprecated, what is the alternative for registering RPs?

**Comment by pilor** [comment]
If you are deploying your resources using templates you shouldn't have to worry whether an RP is registered generally.  Templates register the RPs involved even when they aren't used in blueprints.
