### ISSUE TITLE
documentation mistake 

### ISSUE THREAD

**Issue by motasem13** [Azure/azure-policy#574]
checking docs here https://github.com/Azure/azure-policy 
it says that:

Below are listed the known resource types exhibiting this problem.
Microsoft.Web/sites/siteConfig

In arm microsoft.web rp there is no such resource, as
 Microsoft.Web/sites/siteConfig

![image](https://user-images.githubusercontent.com/34815091/83134322-d9801f80-a0ec-11ea-9758-ca4a878bb63c.png)

under resource providers/Microsoft.Web/sites/{Sitename} there is a property called site config but its not a resource, can you please fix this.

**Comment by mentat9** [comment]
Fixed, thanks.
