### ISSUE TITLE
question regarding Azure security baseline settings policy

### ISSUE THREAD

**Issue by bdanse** [Azure/azure-policy#579]
Hi, 

I have a question regarding all settings in **Audit Windows VMs that do not match Azure security baseline settings** policy. 

- What baseline is this based upon? CIS? Microsoft Security Compliance Toolkit?
- What OS versions are supported by this baseline?

**Comment by pilor** [comment]
OS list is here:  https://docs.microsoft.com/en-us/azure/governance/policy/concepts/guest-configuration#supported-client-types

**Comment by pilor** [comment]
I'll try to pull in someone that can answer the first question (and get it updated in the policy or docs)

**Comment by mgreenegit** [comment]
It is based on Microsoft-defined best practices, similar to the [Security and Compliance Toolkit](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-compliance-toolkit-10). Using the parameters, it should be only minor tweaks to match industry regulatory standards.
