### ISSUE TITLE
SqlServer_EnsureThreatDetectionTypes_Audit: Case sensitivity issue

### ISSUE THREAD

**Issue by EwanNoble** [Azure/azure-policy#587]
### Details of the scenario you tried and the problem that is occurring
Security center can't detect compliance for Threat Detection, our 'Microsoft.Sql/servers/securityAlertPolicies' resource is named 'Default' and the policy is looking for 'default'
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/SQL/SqlServer_EnsureThreatDetectionTypes_Audit.json#L34

#### Suggested solution to the issue
Case insensitive match on word 'Default'

#### If policy is Guest Configuration - details about target node

**Comment by pilor** [comment]
Resource names are not case sensitive in Azure Resource Manager.  If you are seeing different behavior than that please open a support case against the resource provider that is enforcing case sensitivity.
