### ISSUE TITLE
Need Alias for Microsoft.Storage/storageAccounts/networkAcls.bypass

### ISSUE THREAD

**Issue by MuraliMaohar** [Azure/azure-policy#59]
{
"policyRule": {
"if": {
"allOf": [
{
"field": "type",
"equals": "Microsoft.Storage/storageAccounts"
},
{
"not": {
"field": "Microsoft.Storage/storageAccounts/networkAcls.bypass",
"contains": "[parameters('Exceptions')]"
}
}
]
},
"then": {
"effect": "audit"
}
},
"parameters": {
"Exceptions": {
"type": "String",
"metadata": {
"displayName": "Exceptions",
"description": "Exceptions"
}
}
},
"metadata": {}
}

**Comment by mentat9** [comment]
The alias for this property (and other storageAccount properties) have been added. Please give it a try.
