### ISSUE TITLE
The template function 'field' is not valid in existenceCondition of deployIfNotExists policy

### ISSUE THREAD

**Issue by devdeer-stephan** [Azure/azure-policy#593]
I want to write a policy that automatically creates a metric alert for every app service plan. The following ARM template should do just that:
```json
{
  "$schema": "http://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "variables": {
    "cpuPolicyName": "asp-cpu-metrics-monitor"
  },
  "resources": [
    {
      "type": "Microsoft.Authorization/policyAssignments",
      "name": "[variables('cpuPolicyName')]",
      "apiVersion": "2019-06-01",
      "properties": {
        "policyType": "Custom",
        "mode": "All",
        "displayName": "[variables('cpuPolicyName')]",
        "description": "Policy to enforce metric alerts on the CPU usage of App Service Plans.",
        "policyRule": {
          "if": {
            "field": "type",
            "equals": "Microsoft.Web/serverfarms"
          },
          "then": {
            "effect": "deployIfNotExists",
            "details": {
              "type": "Microsoft.Insights/metricAlerts",
              "existanceScope": "ResourceGroup",
              "existanceCondition": {
                "field": "Microsoft.Insights/metricAlerts/name",
                "equals": "[concat('alert-', field('name'), '-cpu')]"
              },
              "deployment": {
                "properties": {
                  "mode": "incremental",
                  "template": {
                    /* removed for simplification */
                  },
                  "parameters": {
                    "resourceName": {
                      "value": "[field('name')]"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  ]
}

```
When I try to apply it from powershell, the response is `Status Message: Unable to process template language expressions for resource '/subscriptions/{{sub-id}}/providers/Microsoft.Authorization/policyAssignments/asp-cpu-metrics-monitor' at line '12' and column '9'. 'The template 'field' is not valid. Please see https://aka.ms/arm-template-expressions for usage details.' (Code:InvalidTemplate)`.
I assume the problem is the `field` usage in my `existenceCondition`, as I've seen `field` being used for parameters in mutliple documentations and samples.
Reading [the documentation](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/effects#deployifnotexists-properties) I assumed it was valid to use `field` in the `existenceCondition`. Also, I wouldn't know how to identify the correct alert otherwise. Is there maybe some syntactic error in my template, that neither I nor the vscode-extension can identify?

**Comment by pilor** [comment]
When deploying policy inside a template you need to escape any policy language expressions so the template doesn't try to evaluate them.  In this scenario that is your concat() call in "equals" and field() in "value".

See https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-expressions#escape-characters

**Comment by DCtheGeek** [comment]
Also doc'ed here: https://docs.microsoft.com/en-us/azure/governance/policy/troubleshoot/general#scenario-policy-supported-functions-processed-by-template

**Comment by carlosonunez** [comment]
I needed to add two brackets (`[`) for my deployment to succeed. I think the documentation is out of date or incomplete on this.

**Comment by placidseven** [comment]
> I needed to add two brackets (`[[`) for my deployment to succeed. So instead of it being `[[field('name')]`, for instance, it had to be `[[[field('name')]`. However, I think the documentation is out of date or incomplete on this.

Your code still wouldn't work you aren't actually using the parameter "resourceName". You can't use "field" inside the template used by the template.
