### ISSUE TITLE
Azure Policy built-in Azure Security Baseline should not require use of legacy methods for collecting Activity Logs

### ISSUE THREAD

**Issue by pacon-vib** [Azure/azure-policy#598]
Azure Policy built-in Azure Security Baseline should not require use of legacy methods for collecting Activity Logs

The built-in policy definitions are:
- "Azure Monitor log profile should collect logs for categories 'write,' 'delete,' and 'action'"
- "Azure Monitor should collect activity logs from all regions"

These policies refer to Log Profiles, which have been deprecated in favour of diagnostic settings. We are collecting subscription Activity Logs with diagnostic settings but still getting failures on the Security Baseline.

The built-in policies should refer instead to diagnostic settings.

**Comment by pilor** [comment]
Notfying the appropriate folks

**Comment by SylvainVi** [comment]
Agreed. Those policies should be flagged [Deprecated].

**Comment by kenieva** [comment]
The correct people where notified, but there hasn't been any response on this thread so I will close the issue. If the problem persist or there are updates, please re-open.

**Comment by KenBenjamin** [comment]
This issue still exists. Please re-open and keep it open until it's resolved.

**Comment by flatproject** [comment]
This issue still exists. Please re-open.

**Comment by sarab5000** [comment]
It still exists....
