### ISSUE TITLE
Alias Request: Microsoft.Network/networkSecurityGroups/subnets[*].id, Microsoft.Network/networkSecurityGroups/networkinterfaces[*].id

### ISSUE THREAD

**Issue by Welasco** [Azure/azure-policy#60]
**Scenario**
Need to use Azure Policy to audit empty Network Security Groups. NSGs that are not associated with any Interface or Subnet.

Alias:
Microsoft.Network/networkSecurityGroups/subnets[*].id
Microsoft.Network/networkSecurityGroups/subnets/id
Microsoft.Network/networkSecurityGroups/networkinterfaces[*].id
Microsoft.Network/networkSecurityGroups/networkinterfaces/id

** Definition **

{
    "type": "Microsoft.Authorization/policyDefinitions",
    "name": "audit-empty-nsg",
    "properties": {
        "displayName": "Check if the NSG is empty",
        "description": "This policy will audit any empty NSG.",
        "parameters": {
            "subnetsId": {
                    "type": "String",
                    "metadata": {
                        "description": "Resource Id of the Subnet",
                        "displayName": "NSG Id"
                    }
            },
            "interfacesId": {
                    "type": "String",
                    "metadata": {
                        "description": "Resource Id of the Interface",
                        "displayName": "NSG Id"
                    }                
            }
        },
        "policyRule": {
            "if": {
                "anyOf": [
                    {
                        "allOf": [
                            {
                                "field": "type",
                                "equals": "Microsoft.Network/networkSecurityGroups"
                            },
                            {
                                "not": {
                                    "field": "Microsoft.Network/networkSecurityGroups/subnets[*].id",
                                    "equals": "[parameters('subnetsId')]"
                                }
                            }
                        ]
                    },
                    {
                        "allOf": [
                            {
                                "field": "type",
                                "equals": "Microsoft.Network/networkSecurityGroups/subnets"
                            },
                            {
                                "not": {
                                    "field": "Microsoft.Network/networkSecurityGroups/subnets/id",
                                    "equals": "[parameters('subnetsId')]"
                                }
                            }
                        ]
                    },
                    {
                        "allOf": [
                            {
                                "field": "type",
                                "equals": "Microsoft.Network/networkSecurityGroups"
                            },
                            {
                                "not": {
                                    "field": "Microsoft.Network/networkSecurityGroups/networkinterfaces[*].id",
                                    "equals": "[parameters('interfacesId')]"
                                }
                            }
                        ]
                    },
                    {
                        "allOf": [
                            {
                                "field": "type",
                                "equals": "Microsoft.Network/networkSecurityGroups/networkinterfaces"
                            },
                            {
                                "not": {
                                    "field": "Microsoft.Network/networkSecurityGroups/networkinterfaces/id",
                                    "equals": "[parameters('interfacesId')]"
                                }
                            }
                        ]
                    }
                ]
            },
            "then": {
                "effect": "audit"
            }
        }
    }
}

**Comment by pilor** [comment]
The following aliases are now available:

```
Microsoft.Network/networkSecurityGroups/subnets[*].id
Microsoft.Network/networkSecurityGroups/networkInterfaces[*].id
```
