### ISSUE TITLE
Ensure that 'PHP version' is the latest, if used as a part of the Function app

### ISSUE THREAD

**Issue by chats14sepservian** [Azure/azure-policy#600]
#### Details of the scenario you tried and the problem that is occurring
Default version of PHP according to policy definition is 7.3 but if we don't specify PHP version in ARM template or terraform code, default version  of PHP deployed is 5.6' . Due to this, policy evaluation is coming as non compliant .
#### Verbose logs showing the problem
![Complaince failure reason](https://user-images.githubusercontent.com/67773280/86431941-7744bb00-bd39-11ea-9e16-711fef94aec8.PNG)
![Compliance result passed if default version updated to 5 6](https://user-images.githubusercontent.com/67773280/86431944-790e7e80-bd39-11ea-82e7-fb9f97c1b7eb.PNG)
![Default PHP version in Deployment template](https://user-images.githubusercontent.com/67773280/86431948-7a3fab80-bd39-11ea-9927-9cac42f5e6ed.PNG)
![Orginal azure policy from git repo fails](https://user-images.githubusercontent.com/67773280/86431949-7ad84200-bd39-11ea-8b1e-9259dec18364.PNG)
![Policy Definition updated to 5 6](https://user-images.githubusercontent.com/67773280/86431950-7ad84200-bd39-11ea-9c40-5034a98fe76d.PNG)

#### Suggested solution to the issue
Please update the default PHP version in the resource deployment to 7.3 to match with the policy definition.

**Comment by kenieva** [comment]
Hi @chats14sepservian , the built-in policy has been updated for 7.3 such (https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/App%20Service/AppService_FunctionApp_Audit_PHP_Latest.json). This might be a custom or deprecated policy.
