### ISSUE TITLE
FTP state policy for Apps should allow both Disabled and FtpsOnly

### ISSUE THREAD

**Issue by chats14sepservian** [Azure/azure-policy#601]
#### Details of the scenario you tried and the problem that is occurring
  FTP state policy for Apps should allow both Disabled and FtpsOnly, as some of the systems want FTP access to be disabled. Policies are failing if we keep the FTP state to FTPS Only.
#### Verbose logs showing the problem
![FTPSAppsState](https://user-images.githubusercontent.com/67773280/86440242-761d8900-bd4d-11ea-8e5a-7fb5b844476d.PNG)

**Comment by pilor** [comment]
From what I know of the meaning of that property I agree.  I'll start a discussion with the appropriate folks.

**Comment by Tankzor** [comment]
This would appear to be fixed now 👍 thanks!
