### ISSUE TITLE
Security Center and Azure Policy Results MisMatch

### ISSUE THREAD

**Issue by chats14sepservian** [Azure/azure-policy#603]
Azure Policy: Subnets should be associated with a Network Security Group compliance fails for some subnets with below reason: 

Reason for non-compliance
Current value must be in the target value.

Field
Microsoft.Security/complianceResults/resourceStatus

Path
properties.resourceStatus

Current value
"NotHealthy"

Target value
["NotApplicable","OffByPolicy","Healthy"]

When we browse to the Security Center to validate this policy compliance outcome for the same subnets, results shows that they are marked under "Not Applicable Section"

Also when we click on the last evaluted resource on the compliance reason failure tab, it takes us to a API error page . See. API errored out screenshot. 
![SubnetPolicyComplainceAPIError](https://user-images.githubusercontent.com/67773280/86554155-2aa6ed00-bf90-11ea-8fc1-6c1b4c73834a.PNG)
![SubnetPolicyComplainceAPILink](https://user-images.githubusercontent.com/67773280/86554156-2bd81a00-bf90-11ea-8142-83763905a464.PNG)
![SubnetPolicyComplainceFailureReason](https://user-images.githubusercontent.com/67773280/86554157-2c70b080-bf90-11ea-8b28-0628c7faab67.PNG)
![SubnetPolicyComplainceSecurityCenter](https://user-images.githubusercontent.com/67773280/86554160-2da1dd80-bf90-11ea-9d0b-ecca6ff991c5.PNG)

**Comment by pilor** [comment]
I'm OK handling simple built-in update requests via Issues in this repo. However, more general support questions (especially regarding integrations with service like Azure Security Center) should be handled through Azure Customer Support.  See https://github.com/Azure/azure-policy#getting-support
