### ISSUE TITLE
Issue with Policy: Function app has 'Client Certificates (Incoming client certificates)' set to 'On'

### ISSUE THREAD

**Issue by chats14sepservian** [Azure/azure-policy#604]
#### Details of the scenario you tried and the problem that is occurring
The policy checks for Function app has 'Client Certificates (Incoming client certificates)' set to 'On' 
             "field": "Microsoft.Web/sites/clientCertEnabled",
             "equals": "false"

    Actual value in function app resource export template.
        "clientCertEnabled": false,

   Stills the policy fails stating 
        Current value
           false
        Target value
          "false"

Seems like a potential bug in the builtIn Policy itself.
#### Verbose logs showing the problem
![PolicyCertFunctionApp](https://user-images.githubusercontent.com/67773280/86730396-d411df80-c071-11ea-97e5-2ed0872125af.PNG)

**Comment by kenieva** [comment]
Hi @chats14sepservian, what the non-compliance reason is saying is that in order to be marked compliant the value should not be equal to the target value. Hence the definition is saying if "clientCertEnabled" is marked false then it is non-compliant.
