### ISSUE TITLE
Make count or copy control flows available in the "then" section of the definition

### ISSUE THREAD

**Issue by rorieke** [Azure/azure-policy#605]
We can use "count" in the "if" element, and "copy" in a deployment on the "then" element, but these are not available in the "then" element, outside a deployment.

**Comment by kenieva** [comment]
Hi rorieke, thank you for the feature request. The best site to submit these and others is on our UserVoice: https://feedback.azure.com/forums/915958-azure-governance. You can add this feature along with benefits of implementing such and also vote on other features. Thanks!
