### ISSUE TITLE
New Diagnostic Log Categories - Leading to Policy Non-Compliance

### ISSUE THREAD

**Issue by awanarslan** [Azure/azure-policy#609]
We have policies that apply diagnostic settings to resources, but whenever new diagnostic log categories are created by MSFT, our policies then show up as NonCompliant, as obviously the new log categories are not part of our policy templates. Is there a way to manage this? Does MSFT say anywhere when/which new log categories will be developed for a resource ahead of time? For example, last week it looks like, 6 new categories were added for Data Factory, and we only see that due to the fact that all of our resources now show up as Non-Compliant although they do have diagnostic settings enabled.

**Comment by kenieva** [comment]
Hi @awanarslan, to my best knowledge there is not a way to get that information. However, this would be a question best directed to the diagnostic log team. I would recommend creating a support ticket asking for this feature and/or asking if this feature is available. Thanks
