### ISSUE TITLE
Make policy scan activities to be more transparent

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#61]
I've realized that the policy scan activities are not transparent and almost time I have nothing to know if a scan or batch of scan is done and when. 

Moreover, if I change my condition in policy definition and click Save, when does the assignment get triggered? Is it an immediate trigger?

**Comment by muratersan** [comment]
It can take up to fifteen minutes for the Azure Policy RP to detect the change. Depending on the size of the subscription that will be scanned, the time of the scan can vary. Ultimately the results will be written to a store that the RP will expose the results from. End to end the whole thing can take around 45 minutes.

**Comment by pilor** [comment]
We plan to improve the transparency of these compliance scans in the future.
