### ISSUE TITLE
Enable soft delete audit/deployifnotexists is not working

### ISSUE THREAD

**Issue by balareddy2509** [Azure/azure-policy#615]
{
"properties": {
"displayName": "Audit Data Protection on Blobs - Storage Accounts",
"policyType": "Custom",
"mode": "All",
"description": "Ensure that storage accounts created with soft delete for blobs and fileshares",
"metadata": {
"version": "1.0.0",
"category": "Storage"
},
"parameters": {
"effect": {
"type": "String",
"metadata": {
"displayName": "Effect",
"description": "The effect determines what happens when the policy rule is evaluated to match"
},
"allowedValues": [
"Audit",
"Deny",
"Disabled"
],
"defaultValue": "Audit"
}
},
"policyRule": {
"if": {
"allOf": [
{
"field": "type",
"equals": "Microsoft.Storage/storageAccounts"
},
{
"field": "Microsoft.Storage/storageAccounts/blobServices/deleteRetentionPolicy.enabled",
"exists": "true"
}
]
},
"then": {
"effect": "[parameters('effect')]"
}
}
}
}

**Comment by kenieva** [comment]
Hi @balareddy2509 if you wish to submit a custom policy, please create a pull request to this repo: https://github.com/Azure/Community-Policy
