### ISSUE TITLE
Allowed VM Disk SKU Policy Issue

### ISSUE THREAD

**Issue by abhijitkakade914** [Azure/azure-policy#621]
HI Team , 

I have created on Policy for VM with allowed SKU, Its working for me correctly. But I noticed for Virtual Machine which are Shutdown and deallocated it shows as Non-compliant because in Current value it comes '' <Blank>. 

Do you know this issue ? How can i overcome with this issue ? i want to know why shutdown vm's shows blank sku. Any other way to resolve this issue ? Please help ASAP.

 "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Compute/virtualMachines"
          },
          {
            "not": {
              "field": "Microsoft.Compute/virtualMachines/storageProfile.osDisk.managedDisk.storageAccountType",
              "in": "[parameters('listOfAllowedSKUs')]"
            }
          }
        ]
      },
      "then": {
        "effect": "[parameters('effect')]"
      }

![image](https://user-images.githubusercontent.com/46191820/90536803-d4c38880-e17c-11ea-97df-6c7a967409eb.png)

**Comment by abhijitkakade914** [comment]
Teams any updates on this ?

**Comment by VishnuGillela** [comment]
Managed disk allows changing of ``storageAccountType`` when respective VM is stopped/deallocated. 
That is the reason ``storageProfile.osDisk.managedDisk.storageAccountType`` property will be empty/not available when VM is in stopped/deallocated state.

**Comment by kenieva** [comment]
Hi @abhijitkakade914, if you need help authoring a custom policy the correct method to receive help is to file a support ticket. Thank you.
