### ISSUE TITLE
Create Policy Assignment stays non-compliant

### ISSUE THREAD

**Issue by dtoes** [Azure/azure-policy#626]
Created alert for CIS 5.2.1. Ensure that Activity Log Alert exists for Create Policy Assignment but it stays on non-compliant.

The alert works when I create a Policy assignment but it wil not change to compliant. 

Created alert for both write and delete of the policy.

Below is the Alert created for the write:

{
    "id": "/subscriptions/c03f27e6-0b28-42c1-a26a-588d20186fd6/resourceGroups/security-monitoring/providers/microsoft.insights/activityLogAlerts/Create Policy Assignment",
    "type": "Microsoft.Insights/ActivityLogAlerts",
    "name": "Create Policy Assignment",
    "location": "Global",
    "kind": null,
    "tags": {},
    "properties": {
        "scopes": [
            "/subscriptions/c03f27e6-0b28-42c1-a26a-588d20186fd6"
        ],
        "condition": {
            "allOf": [
                {
                    "field": "category",
                    "equals": "Administrative",
                    "containsAny": null,
                    "odata.type": null
                },
                {
                    "field": "operationName",
                    "equals": "Microsoft.Authorization/policyAssignments/write",
                    "containsAny": null,
                    "odata.type": null
                },
                {
                    "field": "status",
                    "equals": "started",
                    "containsAny": null,
                    "odata.type": null
                }
            ],
            "odata.type": null
        },
        "actions": {
            "actionGroups": [
                {
                    "actionGroupId": "/subscriptions/c03f27e6-0b28-42c1-a26a-588d20186fd6/resourcegroups/security-monitoring/providers/microsoft.insights/actiongroups/ag-daantest",
                    "webhookProperties": {}
                }
            ]
        },
        "enabled": true,
        "description": "Alert for creation of Policy Assignment"
    },
    "identity": null
}

C.I.S 5.2.2. through 5.2.9 are all compliant after creating the alerts. Only 5.2.1 is still not compliant. 

It looks like the monitor service used for C.I.S. 5.2.1 needs 'Activity log- Policy' instead of 'Activity log- Administrative'. In the above example the category is adnministrative because it is not possible to choose 'Acitivity log - Policy.

**Comment by kenieva** [comment]
Hi @dtoes, for help in creating a custom policy, please create an Azure support ticket. Thanks.

**Comment by alxndr13** [comment]
This is still an issue today. We added the activity log alerts for a bunch of subs through terraform. In some the policy compliance is green, in others it's still non-compliant. Compliance Reason is:

```
No related resources match the effect details in the policy definition. (Error code: InvalidResourceType)
```

Which is bs, as the resources are there and Azure Policy recognizes them in some subscriptions.
