### ISSUE TITLE
StorePasswordsUsingReversibleEncryption: Built-In Guest Config Policy expected value is incorrect (Enabled not disabled)

### ISSUE THREAD

**Issue by nawijesi** [Azure/azure-policy#630]
ISSUE TITLE: StorePasswordsUsingReversibleEncryption: Built In Guest Config Policy expected value is incorrect (Enabled not disabled)
    Please prefix the issue title with the policy sample name, e.g.
    'PolicyName: Short description of my issue'

    ISSUE DESCRIPTION (this template): When assigning this policy, the correct expected value should be to check that the policy is disabled (as per baseline). Rather the expectation is that the value should be enabled (against what security baseline recommends). The value expected is 1 not 0. 

#### Details of the scenario you tried and the problem that is occurring
Assign AzureBaseline_SecuritySettingsAccountPoicies built in Guest config policy to a Windows VM.
Check the policy compliance after it has been assigned and see that the Expected value is 1, where the actual value found in the server is 0. This is incorrect as most security baselines recommend this value to be disabled on windows machines. This leaves the policy compliance state and non-compliant.

![image](https://user-images.githubusercontent.com/67364854/91960464-d7d48200-ed01-11ea-823e-0f38566d4d21.png)

**Comment by kenieva** [comment]
Hi @nawijesi, for help in debugging compliance issues, please create an Azure support ticket so a support engineer can look into this for you.
