### ISSUE TITLE
Request RoleDefinitionName Alias

### ISSUE THREAD

**Issue by RonnieQuan** [Azure/azure-policy#636]
Currently roleDefinitionId is available, but not role name,
When we create a custom role, ID is automatically generated, when we need to drop and recreate the role, a new ID is created.
We have a similar policy like azure-policy/samples/Authorization/allowed-role-definitions/ 

Whenever the role ID changed, the policy is broken.

Is it possible to add RoleDefinitionName field? 

(Get-AzPolicyAlias -NamespaceMatch 'Microsoft.Authorization' -ResourceTypeMatch 'roleAssignments').Aliases

Name                                                     Paths                                                            
----                                                     -----                                                            
Microsoft.Authorization/roleAssignments/roleDefinitionId {Microsoft.Azure.Management.ResourceManager.Models.AliasPathType}
Microsoft.Authorization/roleAssignments/principalId      {Microsoft.Azure.Management.ResourceManager.Models.AliasPathType}
Microsoft.Authorization/roleAssignments/principalType    {Microsoft.Azure.Management.ResourceManager.Models.AliasPathType}
Microsoft.Authorization/roleAssignments/canDelegate      {}

**Comment by mentat9** [comment]
@RonnieQuan your request is reasonable, but it's nothing to do with Azure Policy or the samples published in this repo. The API that returns role assignments doesn't return the role definition name. Azure Policy only applies rules to existing GET and PUT payloads, whereas adding something to an API requires the resource provider owners to publish a new API version. You can request this kind of change at the Azure feedback page: https://feedback.azure.com/forums/34192--general-feedback, or by opening a CSS ticket here: https://azure.microsoft.com/support/create-ticket/.
