### ISSUE TITLE
ContainerAllowedPorts: doesn't work as it checks on an informative field

### ISSUE THREAD

**Issue by tvdvoorde** [Azure/azure-policy#639]
The ContainerAllowedPorts policy for Azure Kubernetes Services doesn't do anything usefull. 

It claims: **Ensure containers listen only on allowed ports in Kubernetes cluster**

It checks on the pods.spec.containers.ports which is an _informative_ field.

If the policy is applied with for example '3000' as the value, you could still run Nginx and expose (and connect to port 80, as long as you specify ports=3000 in the definition. See the text:

>  **Not specifying a port here DOES NOT prevent that port from being exposed.** 

in the explanation of the Kubernetes API

Snippet from the template:

```
          port := container.ports[_]
          format_int(port.containerPort, 10, portstr)
          satisfied := [good | allowedPort := input.parameters.allowedPorts[_]; good := (portstr == allowedPort)]
          
```

```
kubectl explain pods.spec.containers.ports
KIND:     Pod
VERSION:  v1

RESOURCE: ports <[]Object>

DESCRIPTION:
     List of ports to expose from the container. Exposing a port here gives the
     system additional information about the network connections a container
     uses, but is primarily informational. Not specifying a port here DOES NOT
     prevent that port from being exposed.
```

**Steps to reproduce**

Assign policy with value of [3000]

Deploy a pod, specify another port, it fails

```
kubectl run nginx4 --image=nginx --port=80 --restart=Never --labels=thx=1
Error from server ([denied by azurepolicy-container-allowed-ports-83bf9c5a8dfc83a926f6] Container port 80 for container nginx4 has not been allowed.): admission webhook "validation.gatekeeper.sh" denied the request: [denied by azurepolicy-container-allowed-ports-83bf9c5a8dfc83a926f6] Container port 80 for container nginx4 has not been allowed.
```

Deploy a pod, specify port 3000, it succeeds

```
kubectl run nginx4 --image=nginx --port=3000 --restart=Never --labels=thx=1
pod/nginx4 created
```

Get pods

```
kubectl get pods -o wide
NAME     READY   STATUS    RESTARTS   AGE   IP            NODE                                NOMINATED NODE   READINESS GATES
nginx4   1/1     Running   0          48s   10.244.0.21   aks-agentpool-56336909-vmss000000   <none>           <none>
```

Connecting to port 80 still works (as nginx listens on port 80

```
kubectl run test --rm -it --image=busybox:1.28 --labels=thx=1 --restart=Never /bin/sh
If you don't see a command prompt, try pressing enter.
/ # wget http://10.244.0.21:80
Connecting to 10.244.0.21:80 (10.244.0.21:80)
index.html           100% |******************************************************************************************************************************************************************|   612   0:00:00 ETA
/ #
```

And of course there is nothing listening on port 3000

```
/ # wget http://10.244.0.21:3000
Connecting to 10.244.0.21:3000 (10.244.0.21:3000)
wget: can't connect to remote host (10.244.0.21): Connection refused
```

**Comment by RamyasreeChakka** [comment]
@miwithro to look in to this.

**Comment by nehakulkarni123** [comment]
Hi @tdvoorde, [this policy](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/ContainerAllowedPorts.json) was recently deprecated since the container port is only an informative field which cannot decide the port container is actually using. The AKS team plans on releasing a new policy scenario to check on the targetPort on the service instead.  For more information, see https://aka.ms/kubepolicydoc.
