### ISSUE TITLE
Access Control (IAM) in Azure Policy

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#64]
Like other Azure services, Access Control (IAM) should be in place to see who have rights to read and create policy. It'd be good for policy access control so nobody can edit and modify policy without rights.

**Comment by krnese** [comment]
To use policies, you must be authenticated through RBAC. Specifically, your account needs the:

Microsoft.Authorization/policydefinitions/write permission to define a policy.
Microsoft.Authorization/policyassignments/write permission to assign a policy.
Microsoft.Authorization/policySetDefinitions/write permission to define an initiative.
Microsoft.Authorization/policyassignments/write permission to assign an initiative.

Is the ask to have built-in RBAC for this?

**Comment by thuansoldier** [comment]
@krnese  thank you for your response. The question would be related to UI in which the Access Control (IAM) navigation would be better to be added to the blade so Azure subscription administrator can see who has right on Azure Policy. It is like almost Azure service.

**Comment by pilor** [comment]
Noted.  Nothing to share regarding this at this point.
