### ISSUE TITLE
ASC Audit DDoS Enabled Protection Policy Marks "NotApplicable" as Non-compliant

### ISSUE THREAD

**Issue by mdtro** [Azure/azure-policy#643]
#### Details of the scenario you tried and the problem that is occurring

If a VNET is deployed with DDoS protection enabled, but does not have an Application Gateway with a public IP in one of the subnets -- this policy marks the VNET as non-compliant.

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/20070360/95374728-51810200-08a4-11eb-9fd7-ef6717db4058.png)

#### Suggested solution to the issue

Add "NotApplicable" to the allowed fields to consider the VNET compliant.

**Comment by mdtro** [comment]
I opened PR #644 to resolve this.

**Comment by kenieva** [comment]
There hasn't been any response on this thread so I will close the issue. If the problem persist or there are updates, please re-open.
