### ISSUE TITLE
Add Azure VM Boot Diag Aliases to be modifiable

### ISSUE THREAD

**Issue by husamhilal** [Azure/azure-policy#649]
Can you please add Azure VM boot diagnostics aliases to modifiable aliases? (to allow using "modify" acion)

Microsoft.Compute/virtualMachines/diagnosticsProfile.bootDiagnostics
Microsoft.Compute/virtualMachines/diagnosticsProfile.bootDiagnostics.enabled
Microsoft.Compute/virtualMachines/diagnosticsProfile.bootDiagnostics.storageUri

That would allow customer to move easily from self managed storage account to Microsoft managed storage account to store Boot Diagnostics info.

The policy will look like this:
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Compute/virtualMachines"
        }
      ]
    },
    "then": {
        "effect": "modify",
        "details": {
          "roleDefinitionIds": [
            "/providers/microsoft.authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
          ],
          "operations": [
            {
              "operation": "addOrReplace",
              "field": "Microsoft.Compute/virtualMachines/diagnosticsProfile.bootDiagnostics.enabled",
              "value": "true"
            },
            {
              "operation": "remove",
              "field": "Microsoft.Compute/virtualMachines/diagnosticsProfile.bootDiagnostics.storageUri"
            }
          ]
        }
    }
  },
  "parameters": {}
}

**Comment by nehakulkarni123** [comment]
Hello, thanks for getting in touch! We are currently exploring whether these aliases can be modifiable, and I'll be in touch with updates.

**Comment by kenieva** [comment]
@nehakulkarni123  closing this issue. Please reopen when there is an update. Thank you.

**Comment by eladperets** [comment]
@husamhilal  The aliases you requested are now modifiable

**Comment by husamhilal** [comment]
> @husamhilal The aliases you requested are now modifiable

@eladperets Thanks a lot for the update! This is really great news :)
