### ISSUE TITLE
built-in policy for ATP on storage accounts lacks permission to remediate

### ISSUE THREAD

**Issue by doug-fish** [Azure/azure-policy#660]
#### Details of the scenario you tried and the problem that is occurring
I assigned the policy /providers/Microsoft.Authorization/policyDefinitions/361c2074-3595-4e5d-8cab-4f21dffc835c to a scope that contained storage accounts without ATP enabled. They were properly flagged as non-compliant, but the remediation failed.

#### Verbose logs showing the problem
In the UI the message "The managed identity for this assignment does not have the appropriate permissions to remediate these resources. To add these permissions, go to the Edit Assignment page for this Policy and re-save it." is displayed. Remediation tasks fail.

#### Suggested solution to the issue
Probably need to give Contributor or similar access at https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Storage/StorageAdvancedThreatProtection_Deploy.json#L40

**Comment by pilor** [comment]
The role definition defined in the policy is "Security Admin" which includes the necessary permissions to execute the deployment in the policy.  The error message you are seeing in the UX indicates no permissions have been granted to your policy assignments identity.  See https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources#how-remediation-security-works for instructions on granting the appropriate permissions.

If you are still encountering issues please open a support case.
