### ISSUE TITLE
[Security Center] Multiple policies marks "NotApplicable" as non-compliant

### ISSUE THREAD

**Issue by t3mi** [Azure/azure-policy#663]
#### Details of the scenario you tried and the problem that is occurring
We are using built-in policies company wide and they give us false positives in scenarios related to AKS. Please fix following policies:
- [ASC_VmssOSVulnerabilities_Audit](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Security%20Center/ASC_VmssOSVulnerabilities_Audit.json) /providers/Microsoft.Authorization/policyDefinitions/3c735d8a-a4ba-4a3a-b7cf-db7754cf57f4
- [ASC_VmssMissingEndpointProtection_Audit](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Security%20Center/ASC_VmssMissingEndpointProtection_Audit.json) /providers/Microsoft.Authorization/policyDefinitions/26a828e1-e88f-464e-bbb3-c134a282b9de
- [ASC_VmssMissingSystemUpdates_Audit](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Security%20Center/ASC_VmssMissingSystemUpdates_Audit.json) /providers/Microsoft.Authorization/policyDefinitions/c3f317a7-a95c-4547-b7e7-11017ebdf2fe
- /providers/Microsoft.Authorization/policyDefinitions/e8cbc669-f12d-49eb-93e7-9273119e9933
This one fails with next reason: "No related resources match the effect details in the policy definition. (Error code: AssessmentNotFound)"
#### Suggested solution to the issue
Add 'NotApplicable' status to the compliant state
#### Reference
- #643

**Comment by kenieva** [comment]
Hi @t3mi, I would suggest opening an Azure support ticket to ensure that they can debug and find the root cause of the issue. Thank you.
