### ISSUE TITLE
Repo Version vs. Account Version

### ISSUE THREAD

**Issue by glsutter** [Azure/azure-policy#664]
Trying to track down some built-in policy differences between what's in our Azure commercial account and what's in the repo. Our account has a built-in policy initiative (Enable Monitoring in Azure Security Center) version 19.0.0, but in the repo I only see 17.0.0 in master. That's in policySetDefinitions/Security Center/AzureSecurityCenter.json. I didn't check all the branches, but couldn't find 19.0.0.  

I don't see 19.0.0 anywhere. Any idea where I can find that version of the initiative? In some other repo? Private, not public? Available, unavailable? Can anyone explain what's going on? 

Thanks

**Comment by pilor** [comment]
What you see in the Azure Portal and what is returned by Azure APIs is always the source of truth for built-in policies.  This repo is a mirror of that content to show the history of changes.

There was a problem with the sync that keeps this repo up to date.  Its been resolved and you should now see the latest updates represented here.
