### ISSUE TITLE
Alias request: Microsoft.Web/sites/applicationInsights

### ISSUE THREAD

**Issue by nandakiran-azure** [Azure/azure-policy#666]
Hi Team,
I am looking for an alias where we can directly check if Application Insights is enabled or disabled over Function App. I have added my sample code below. Please help me to sort this out. _

Steps to check this from UI:

1. Create Function APP
2. Go to Function APP and check for Application Insights on left side pane.
3. Verify if Application insights is enabled or disabled

 "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Web/sites"
          },
 {
            "field": "kind",
            "like": "functionapp*"
          },
          {
            "field": "Microsoft.Web/sites/applicationInsights",
            "equals": "Enabled"
          }
        ]
      },
      "then": {
        "effect": "[parameters('effect')]",
      }
    }

**Comment by kenieva** [comment]
Hi @nandakiran-azure, for help in creating custom policies, please create a support ticket. Thank you.
