### ISSUE TITLE
Least privilege for policies working with tags

### ISSUE THREAD

**Issue by t3mi** [Azure/azure-policy#668]
#### Details of the scenario you tried and the problem that is occurring
Tags related policies (for example, [InheritTag_Add_Modify](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Tags/InheritTag_Add_Modify.json#L37)) grant Contributor permission to service principal used. Is it possible to switch to Tag Contributor role?

**Comment by kenieva** [comment]
Hi @t3mi, please add in any requests to our UserVoice (https://feedback.azure.com/forums/915958-azure-governance) for triage by the team. Thank you.
