### ISSUE TITLE
Export from Azure to GitHub: error: invalid path 'initiatives/ISO_27001:2013_89c6cddc-1c73-4ac1-b19c-54d1a15a42f2/policyset.json'

### ISSUE THREAD

**Issue by p-bojkowski** [Azure/azure-policy#673]
![image](https://user-images.githubusercontent.com/74313141/100751552-c32e8580-33e7-11eb-91c6-f5e2dc0c8b7a.png)

**Comment by kenieva** [comment]
Hi @p-bojkowski , are you able to provide more context to this issue? What are you trying to accomplish and what is the issue you are facing?

**Comment by p-bojkowski** [comment]
Hi @kenieva,
I just export policies from Azure to my GitHub repo.
Exporting are working fine. But when I clone the repo I got the error message.
The problem is ':' in the path (I think ;))

![image](https://user-images.githubusercontent.com/74313141/101139672-2d2a7300-3612-11eb-8de3-908a53d61dd3.png)

**Comment by p-bojkowski** [comment]
![image](https://user-images.githubusercontent.com/74313141/101140230-fa34af00-3612-11eb-9599-3e0afe307602.png)

**Comment by kenieva** [comment]
Notifying the correct people...

**Comment by p-bojkowski** [comment]
thx! :)

**Comment by raiyanalam** [comment]
Thanks @p-bojkowski for reaching out. We have already fixed this issue and it is currently being rolled out. If all goes well, it should be available in all rings by the end of this week. 
As a workaround, can you replace the : with an _ in GitHub? The actions should work as usual with this change.
