### ISSUE TITLE
Alias request: "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]"

### ISSUE THREAD

**Issue by marktyson** [Azure/azure-policy#677]
#### Details of the scenario you tried and the problem that is occurring
I would like to use Azure Policy to audit for email addresses being set for Advanced Data Protection notifications on SQL servers. 

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Here is the proposed policy definition:

{
"properties": {
                "displayName": "Policy not working due to missing aliases - Set notification email address for Advanced Threat Protection on SQL servers",
                "policyType": "Custom",
                "mode": "all",
                "description": "Advanced Threat Protection can be configured to send alerts to one or more email addresses upon detection of anomalous activities.",
                "metadata": {
                    "securityCenter": {
                        "remediationDescription": "Add notification emails addresses to ATP settings",
                        "severity": "High"
                    }
                },
                "parameters": {
                    "effect": {
                        "type": "String",
                        "metadata": {
                            "displayName": "Effect",
                            "description": "Enable or disable the execution of the policy"
                        },
                        "allowedValues": [
                            "AuditIfNotExists",
                            "Disabled"
                        ],
                        "defaultValue": "AuditIfNotExists"
                    }
                },
                "policyRule": {
                    "if": {
                        "allOf": [
                            {
                                "field": "type",
                                "equals": "Microsoft.SQL/servers"
                            }
                        ]
                    },
                    "then": {
                        "effect": "[[parameters('effect')]",
                        "details": {
                            "type": "Microsoft.Sql/servers/securityAlertPolicies",
                            "name": "default",
                            "existenceCondition": {
                                "allOf": [
                                    {
                                        "count": {
                                            "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]"
                                        },
                                        "notEquals": 0
                                    },
                                    {
                                        "not": {
                                            "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAddresses[*]",
                                            "equals": ""
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
}

#### If policy is Guest Configuration - details about target node
N/A

**Comment by kenieva** [comment]
Hi @marktyson , to request an alias, please create an Azure support ticket so that it can be routed as needed. Thank you.
