### ISSUE TITLE
LogAnalyticsExtension_Windows built-in policy definitions should support Gen2 images

### ISSUE THREAD

**Issue by wpbrown** [Azure/azure-policy#679]
`LogAnalyticsExtension_Windows_VM_Deploy` and `LogAnalyticsExtension_Windows_VMSS_Deploy` list supported Windows image SKUs, but do not include the gen2 variants.

There doesn't seem to be any incompatibility with these images, so this omission is not necessary.

**Comment by kenieva** [comment]
Hi @wpbrown , can you clarify what you mean by gen2 variants?

**Comment by kenieva** [comment]
I will close the issue for now. If the issue arises again, please reopen the case.
