### ISSUE TITLE
Issue with Azure policy to audit App service "Access Restrictions"

### ISSUE THREAD

**Issue by devsheoran** [Azure/azure-policy#682]
Azure policy to audit App service "Access Restrictions" seems not working correctly. For example, I created below policy to audit all Azure App Services for any Deny rule. But when I apply this policy it evaluates all App Services as compliant whether there any Deny rule exists or not. Please find attached ARM template of one of App Service which doesn't have any Deny rule but policy says its compliant.
[ExportedTemplate-azsu-rg-01.zip](https://github.com/Azure/azure-policy/files/5711429/ExportedTemplate-azsu-rg-01.zip)

```
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "count": {
            "field": "Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*]",
            "where": {
              "field": "Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].action",
              "equals": "Deny"
            }
          },
          "greater": 0
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {}
}
```
This same service is also compliant against Azure policy for Allow rule (as below).

```
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "count": {
            "field": "Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*]",
            "where": {
              "field": "Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*].action",
              "equals": "Allow"
            }
          },
          "greater": 0
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {}
}
```

How can this App Service (attached ARM template) can be compliant for both these Azure policies?

Just FYI: I have to create an Azure to audit publicly accessible App Services within subscription. As first step I started writing these basic policies to play around but encountered this issue.

**Comment by devsheoran** [comment]
![Screenshot 2020-12-17 184312](https://user-images.githubusercontent.com/17984605/102529443-cb4d1d00-4097-11eb-9d85-e8c0d05d61bb.png)

**Comment by dsv591** [comment]
siteConfig is a property that only exists when the App Service is being created or updated (PUT or PATCH payload).

Once the template or PUT request is processed, the Microsoft.Web/sites/siteConfig (property) gets moved to Microsoft.Web/sites/config (which is a resource with name 'web').

Because compliance is based on a GET payload and not on a PUT, that means, siteConfig never meets the criteria for non compliance.

Therefore, to fix this policy you need to replace your Microsoft.Web/sites/siteConfig* aliases, with Microsoft.Web/sites/config/web* aliases.

For example `Microsoft.Web/sites/siteConfig.ipSecurityRestrictions[*]` should be `Microsoft.Web/sites/config/web.ipSecurityRestrictions[*]` instead

**Comment by glloyd2010f** [comment]
I was able to take this logic and work into a different policy. When I leveraged it in the original declaration it still returned that everything was compliant.

Functional Example (Doesn't Evaluate Slots)
```
{
  "mode": "All",
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Web/sites"
    },
    "then": {
      "effect": "auditIfNotExists",
      "details": {
        "type": "Microsoft.Web/sites/config",
        "existenceCondition": {
          "not": {
            "field": "Microsoft.Web/sites/config/web.ipSecurityRestrictions[*].action",
            "equals": "Allow"
          }
        }
      }
    }
  },
  "parameters": {}
}
```

Experimental Example (Hopefully will Evaluate Slots)
```
{
  "mode": "All",
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Web/sites"
    },
    "then": {
      "effect": "auditIfNotExists",
      "details": {
        "type": "Microsoft.Web/sites/config",
        "existenceCondition": {
          "anyOf": [
            {
              "not": {
                "field": "Microsoft.Web/sites/config/web.ipSecurityRestrictions[*].action",
                "equals": "Allow"
              }
            },
            {
              "not": {
                "field": "Microsoft.Web/sites/slots/config/web.ipSecurityRestrictions[*].action",
                "equals": "Allow"
              }
            }
          ]
        }
      }
    }
  },
  "parameters": {}
}
```

**Comment by glloyd2010f** [comment]
@devsheoran I was able to get an Azure Policy working that would check for ipSecurityRestrictions on Slots as well. Sadly it required that I create a second policy definition. The code for that is below.

```
{
  "displayName": "App Service Slots IP Security Restrictions Exist",
  "policyType": "Custom",
  "mode": "All",
  "description": "Checks for IP Security Restrictions on Azure App Service Slots.",
  "metadata": {
    "category": "App Service"
  },
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Web/sites/slots"
    },
    "then": {
      "effect": "[parameters('effect')]",
      "details": {
        "type": "Microsoft.Web/sites/slots/config",
        "existenceCondition": {
          "not": {
            "field": "Microsoft.Web/sites/slots/config/web.ipSecurityRestrictions[*].action",
            "equals": "Allow"
          }
        }
      }
    }
  },
  "parameters": {
    "effect": {
      "type": "String",
      "metadata": {
        "displayName": "Effect",
        "description": "'AuditIfNotExists' allows a non-compliant resource to be created, but flags it as non-compliant. 'Deny' blocks the resource creation. 'Disable' turns off the policy."
      },
      "allowedValues": [
        "AuditIfNotExists",
        "Deny",
        "Disabled"
      ],
      "defaultValue": "AuditIfNotExists"
    }
  }
}
```

**Comment by kenieva** [comment]
It seems that a policy definition solution has been provided. I will close the issue for now, if the issue arises again please reopen the issue. Thank you.
