### ISSUE TITLE
how to create a policy when creating azure blob storage without specify soft-delete?

### ISSUE THREAD

**Issue by star286** [Azure/azure-policy#683]
I want to create an azure policy, during creating an azure blob storage account, if soft-delete for blob service is not specified, it will be denied.

I use the policy as below, but it does not take effect. Every time when I create a storage account without specifying the soft-delete, the storage account still can be created.

{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Storage/storageAccounts/blobServices"
        },
        {
          "field": "Microsoft.Storage/storageAccounts/blobServices/default.deleteRetentionPolicy.enabled",
          "equals": "false"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  },
  "parameters": {}
}

I also see there is a user feedback: https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/38762671-azure-policy-to-deny-storage-account-creation-when, but not sure if it's fixed now.

**Comment by mrajess** [comment]
I can't comment on the why of it, but I can offer an alternative approach. Why Deny the creation when you could just bring the resource into compliance? 

https://github.com/Azure/Community-Policy/tree/master/Policies/Storage/deploy-soft-delete-for-containers
https://github.com/Azure/Community-Policy/blob/master/Policies/Storage/deploy-soft-delete-for-blobs

It would make for a much better user experience and would still achieve your compliance goals.

**Comment by kenieva** [comment]
I will close this issue due to lack of response. If this is still a problem, please reopen the issue.
