### ISSUE TITLE
Alias request: Microsoft.ServiceBus/namespaces/topics/subscription/filters

### ISSUE THREAD

**Issue by cannehag** [Azure/azure-policy#689]
Hello. Requesting policy alias to be able to check if topic subscriptions have any configured filters.

Scenario:
We would like to have a policy that evaluates (and remediates) that topic subscriptions should have a configured filter.

Is this possible to solve ?

**Comment by kenieva** [comment]
Hi @cannehag, please submit any alias request through an Azure support ticket. Thank you!
