### ISSUE TITLE
Alias Request: Microsoft.Storage/storageAccount/networkAcls/virtualNetworkRules

### ISSUE THREAD

**Issue by ezlbrmn** [Azure/azure-policy#69]
Scenario: we are checking compliance with following security requirement: "Azure Storage Accounts must not grant unrestricted access to all networks including Internet"
Definition: TBD

**Comment by simarley** [comment]
Also looking for this one please!

**Comment by itpropro** [comment]
This is already implemented with
"field": "Microsoft.Storage/storageAccounts/networkAcls.virtualNetworkRules[*]"

**Comment by pilor** [comment]
Also `Microsoft.Storage/storageAccounts/networkAcls.virtualNetworkRules[*].id`
