### ISSUE TITLE
Question on how to compare field with property

### ISSUE THREAD

**Issue by cannehag** [Azure/azure-policy#690]
Hi. I'm trying to write a policy checking that a healthCheckPath value on an AppService have the same value as a tag on the same resource. Is this possible to do somehow? None of my attempt have been successful :(

"existenceCondition": {
  "allOf": [
    {
      "field": "Microsoft.Web/sites/config/healthCheckPath",
       "equals": "tags('heartbeatPath')"
    }
  ]
}

**Comment by kenieva** [comment]
In order to refer tags correctly please us refer to this policy: https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Tags/InheritTag_AddOrReplace_Modify.json

Any further help with custom policies can be referred to Azure support ticketing system. Thanks!
