### ISSUE TITLE
PolicyClient demands subscription ID on management group policy deployment

### ISSUE THREAD

**Issue by survivorbat** [Azure/azure-policy#693]
Hi there,

I'm trying to deploy a set of policies to a management group that I connect to with a service principal. I have my client id, client secret and tenant id setup in an `ApplicationTokenCredentials` object. This service principal has access to the management group.

The problem I'm facing however, is that I can't instantiate a `PolicyClient` without specifying a subscription. It seems the Python SDK also has this issue: https://github.com/Azure/azure-sdk-for-python/issues/4474

In that issue, they 'fixed' it by inputting a random string. The Typescript API unfortunately does not allow this and will error while attempting to get credentials.

Is there a workaround to deploy Azure policies to a management group without having to specify a subscription?

Yours sincerely,

Survivorbat

**Comment by kenieva** [comment]
Hi @survivorbat, what command are you using?

**Comment by survivorbat** [comment]
> Hi @survivorbat, what command are you using?

Hey @kenieva, thank you for your response. Your question made me realize that I created the issue in the wrong repository, my apologies.
