### ISSUE TITLE
Missing policy parameter options for disable in HITRUST/HIPPA

### ISSUE THREAD

**Issue by ppollice** [Azure/azure-policy#694]
#### Details of the scenario you tried and the problem that is occurring

When using the Azure built in HIPAA/HITRUST Initiative, critical parameters are missing that allow the disabling of certain Policies that are not common but will still show the system as out of compliance. 

Specifically for example, 

"Vulnerabilities in container security configurations should be remediated" 
"Audit vulnerabilities in security configuration on machines with Docker installed and display as recommendations in Azure Security Center."

The ability is on the standalone policy, but not carried over into the initiative.

#### Verbose logs showing the problem

n/a

#### Suggested solution to the issue
Added these lines and modded for custom policy, but would like to be available from default..

For parameters:
        "Vulnerabilitiescontainersecurity": {
            "type": "string",
            "defaultValue": "AuditIfNotExists",
            "allowedValues": [
              "AuditIfNotExists",
              "Disabled"
            ],
and resources:

          "policyDefinitionReferenceId": "containerBenchmarkMonitoring",
          "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/e8cbc669-f12d-49eb-93e7-9273119e9933",
          "parameters": {
            "effect": {
                "value": "[parameters('Vulnerabilitiescontainersecurity')]"
              }
          },
[Hipaa.txt](https://github.com/Azure/azure-policy/files/5823684/Hipaa.txt)

**Comment by kenieva** [comment]
Hi @ppollice, 

For "Vulnerabilities in container security configurations should be remediated", disable is one of the options in the effect. You can duplicate the initiative and change the effect parameter to be disabled. 

I am not able to find the second policy within the built in initiative .

**Comment by ppollice** [comment]
right, but then the question becomes, if the built in policy is updated, will it modify the clone as well. The customer is concerned about that.

Cloning it and setting a new initiative parameter and mapping it to the policy parameter works as a bandaid

**Comment by kenieva** [comment]
If the built-in is updated, it won't modify the clone.
