### ISSUE TITLE
[Feature Request] Allow to check action in the condition

### ISSUE THREAD

**Issue by ShachafGoldstein** [Azure/azure-policy#696]
When one has a strict naming convention on a subscription, it would be great if we could allow to prevent renaming operations.

This is also useful for other cases like peering prevention and other operations that have an action involved with them.

**Comment by kenieva** [comment]
Hi @ShachafGoldstein, for proper triage of customer feedback, please log your request to: https://feedback.azure.com/forums/915958-azure-governance
