### ISSUE TITLE
'Mode: Indexed' policy is being evaluated against resources that don't support tags 

### ISSUE THREAD

**Issue by rob-wisehart-shamrock** [Azure/azure-policy#697]
I have a simple check to see if a Tag exists policy set to 'Indexed' mode and it is returning a number of various resources that do not support Tags, nor do they have valid locations.  I could create exceptions for each of these types, but I should not have to, as I understand it.

![image](https://user-images.githubusercontent.com/46359387/105099093-58550e80-5a68-11eb-835c-19102b68913b.png)

![image](https://user-images.githubusercontent.com/46359387/105099197-820e3580-5a68-11eb-939f-2021d01a23fe.png)

**Comment by kenieva** [comment]
Hi @rob-wisehart-shamrock , we are aware of this and it is logged in our Known issues in the ReadMe of this repo. We are working with the tag and resource provider teams to ensure that all indexed resources are taggable. Thanks.

**Comment by rob-wisehart-shamrock** [comment]
So, until that gets done, the "Indexed" mode of policy definitions is not usable.  If it is going to take some time to address (and it seems that it has been a significant amount of time already) the team might consider updating their documentation: https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure for example.  This document is very misleading and some might say irresponsible as it represents that the Indexed mode is for only supporting resources that support tags and location, when it doesn't and hasn't for an extended length of time.

**Comment by kenieva** [comment]
We still recommend using Indexed mode because it includes resources that are meant to be taggable. By doing mode all, you will receive more error messages and encounter more resources that are not to support tags. 

You are correct in the extended length of time. This change has to come from the resource providers so we are working with them on prioritizing this item.
