### ISSUE TITLE
PolicyAssignment: Unhelpful Error Handling in the Portal

### ISSUE THREAD

**Issue by jcbagtas** [Azure/azure-policy#700]
Unhelpful error message on Azure portal when encountering Azure Policy's ForbiddenError when adding tags.

#### Details of the scenario you tried and the problem that is occurring

1. Create a policy to require a tag with the `effect` of `deny` - `ex. require "test" tag`
2. Attach the policy to a resource group or a specific resource
3. Simulate Error via CLI:
    * `az group update -n my-rg -g my-rg --tags wrongTag=thisisforbidden`
    * Error message will be triggered:

    ```bash

    ForbiddenError: Resource 'my-rg' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Require test Tag on Resource Groups","id":"/subscriptions/xxx-xxx-xxx/providers/Microsoft.Authorization/policyAssignments/assignmentResourceGroupTestTag"},"policyDefinition":{"name":"Require test Tag on Resource Groups","id":"/subscriptions/xxx-xxx-xxx/providers/Microsoft.Authorization/policyDefinitions/resourceGroupTestTag"}}]'.

    ```

4. Simulate Error via Portal
    * Add tag via Portal:
        * ![image](https://user-images.githubusercontent.com/17738997/105316307-a64e4b80-5bfb-11eb-95e9-821c29bb7897.png)
    * Click Save
        * ![image](https://user-images.githubusercontent.com/17738997/105316269-9c2c4d00-5bfb-11eb-86ef-e5d82328374b.png)
        * Initially mistaken for an *RBAC* issue
    * Provided link does not relate to the actual error provided by the CLI. [LINK](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources)

#### Verbose logs showing the problem

```bash

ForbiddenError: Resource 'my-rg' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Require test Tag on Resource Groups","id":"/subscriptions/xxx-xxx-xxx/providers/Microsoft.Authorization/policyAssignments/assignmentResourceGroupTestTag"},"policyDefinition":{"name":"Require test Tag on Resource Groups","id":"/subscriptions/xxx-xxx-xxx/providers/Microsoft.Authorization/policyDefinitions/resourceGroupTestTag"}}]'.

```

```txt
Could not save the tags for the resource my-rg: Access unauthorized, please correct any errors and try again. More information on tags and compatible resource types can be found here.
```

#### Suggested solution to the issue

Clearer error message

#### If policy is Guest Configuration - details about target node

N/A

**Comment by nehakulkarni123** [comment]
Customers now have the ability to provide custom messaging for why a resource is non-compliant with policy (available through REST API, UI coming very soon)-- here's some documentation on it: https://docs.microsoft.com/en-us/rest/api/resources/policyassignments/create#noncompliancemessage.

**Comment by jcbagtas** [comment]
> Customers now have the ability to provide custom messaging for why a resource is non-compliant with policy (available through REST API, UI coming very soon)-- here's some documentation on it: https://docs.microsoft.com/en-us/rest/api/resources/policyassignments/create#noncompliancemessage. 

Great. Thanks I will try this out.
