### ISSUE TITLE
Policy definitions for backup: No support for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by styrup** [Azure/azure-policy#701]
#### Details of the scenario you tried and the problem that is occurring
Automatic backup on Azure Ubuntu 20.04 vm never starts.
#### Verbose logs showing the problem
N/A
#### Suggested solution to the issue
Properly around line 320-ish, something like this have to be added:
{
"field": "Microsoft.Compute/imageSKU",
 "like": "20.04*LTS"
}

#### If policy is Guest Configuration - details about target node
N/A

**Comment by kenieva** [comment]
Hi @styrup, are you able to provide more detail into this issue? What policy is it?

**Comment by styrup** [comment]
Hi, @kenieva, sure:

- https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Backup/VirtualMachineApplicationCentricBackup_Backup_Deploy_WithOutTag.json
- https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Backup/VirtualMachineApplicationCentricBackup_Backup_Deploy_WithTag.json
- https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Backup/VirtualMachineBackup_Backup_DeployIfNotExists.json
- https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Backup/VirtualMachineWithTag_Backup_Deploy.json

They are alle missing 20.04 support as I can tell.

**Comment by kenieva** [comment]
Notifying the correct team...

**Comment by kenieva** [comment]
We have notified the policy definition owners. Waiting for response...

**Comment by kenieva** [comment]
Waiting for any updates from the team....

**Comment by adityabalaji-msft** [comment]
We plan to update this policy definition to include the above OS as well. We will update this thread once the change is available (tentatively end of next week)

**Comment by sarita-msft** [comment]
Hi @styrup
Policy changes have been made, and Built-in policy on Azure Portal has been updated to include Automatic backup on Azure Ubuntu 20.04 vm.
Please try the policy and let us know.

**Comment by styrup** [comment]
Hi

I can't get it to work, I think the SKU are still worng.
This is what I have testet in my lab and it works.

"policyRule": {
"if": {
"allOf": [
{
"field":"type",
"equals":"<http://Microsoft.Compute/virtualMachines>"
},
{
"field":"location",
"equals":"[parameters('vaultLocation')]"
},
{
"anyOf": [
{
"allOf": [
{
"field":"<http://Microsoft.Compute/imagePublisher>",
"equals":"Canonical"
},
{
"field":"<http://Microsoft.Compute/imageOffer>",
"contains":"server"
},
{
"anyOf": [
{
"field":"<http://Microsoft.Compute/imageSKU>",
"like":"14.04*LTS"
},
{
"field":"<http://Microsoft.Compute/imageSKU>",
"like":"16.04*LTS"
},
{
"field":"<http://Microsoft.Compute/imageSKU>",
"equals":"20_04-lts"
}
]
}
]
}
]
}
]
},

The naming schema have changed, now its _ and image contains server

Den 8. april 2021 kl. 09.54.44 +02.00, skrev Sarita Kumari ***@***.***>:

**Comment by sarita-msft** [comment]
Hi @styrup
The policies have been updated on portal, please try them and let us know.
Thanks

**Comment by nehakulkarni123** [comment]
Hi @styrup, since the team has been updated on the portal. I will close this item. Please feel free to reach out if you have any additional issues.
