### ISSUE TITLE
New Alias Request: Microsoft.ServiceBus/Namespaces/PrivateEndpointConnections[*]

### ISSUE THREAD

**Issue by spacexii** [Azure/azure-policy#710]
Hello,

I'm making a policy that denies the creation of a ServiceBus if the user does not specify a PrivateEndpointConnection.

For policy rule I have tried
```

"policyRule": {
            "if": {
                "allOf": [
                    {
                        "field": "type",
                        "equals": "Microsoft.ServiceBus/namespaces"
                    },
                    {
                        "count": {
                            "field": "Microsoft.ServiceBus/Namespaces/PrivateEndpointConnections[*]",
                            "where": {
                                "field": "Microsoft.ServiceBus/namespaces/privateEndpointConnections[*].privateLinkServiceConnectionState.status",
                                "equals": "Approved"
                            }
                        },
                        "less": 1
                    }
                ]
            },
```

Because I have found documentation that shows an API response having these properties for Service Bus here:
https://docs.microsoft.com/en-us/rest/api/servicebus/preview/privateendpointconnections/list

![image](https://user-images.githubusercontent.com/29075086/107595273-cdd07c80-6bd9-11eb-93f7-b385eba5e5c1.png)

I'm assuming by my error (The 'field' property 'Microsoft.ServiceBus/Namespaces/sku.name[*]' of the policy rule doesn't exist as an alias under provider 'Microsoft.ServiceBus' and resource type 'Namespaces'), I need to come request this field? Thanks

**Comment by kenieva** [comment]
Hi, you can find information on how to check for aliases here: https://docs.microsoft.com/azure/governance/policy/concepts/definition-structure#aliases
If after your research it seems that the alias is not available, please create an Azure support ticket for us to investigate the creation. Thanks!
