### ISSUE TITLE
AppGateway Firewall policy reports false positive when using separate policy object

### ISSUE THREAD

**Issue by DOliana** [Azure/azure-policy#718]
In reference to the policy [WAF_AppGatewayEnabled_Audit.json](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Network/WAF_AppGatewayEnabled_Audit.json):

We are using an application gateway where the firewall is enabled but set in the arm template as referenced firewallpolicy instead of the embedded webApplicationFirewallConfiguration. This leads to a false positive in security center.

So we use
```json
{
    "type": "Microsoft.Network/applicationGateways",
    "apiVersion": "2020-07-01",
    "properties": {
        "sku": {
            "name": "WAF_v2",
            "tier": "WAF_v2"
        },
        "firewallPolicy": {
            "id": "[resourceId('Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies', variables('restApiGWFirewallPolicyName'))]"
        }
    }
}
```

**Comment by kenieva** [comment]
Notifying the correct people..

**Comment by kenieva** [comment]
This will be addressed by the WAF team. Thank you.

**Comment by DOliana** [comment]
@kanieva the issue still persists - are there any news?

**Comment by kenieva** [comment]
@TreMansdoerfer  for comment

**Comment by DOliana** [comment]
no news yet?
