### ISSUE TITLE
Alias Request: microsoft.sql/connection/servers/connectionPolicies

### ISSUE THREAD

**Issue by ezlbrmn** [Azure/azure-policy#72]
Scenario: we are checking compliance with following security requirement: To connect to Azure SQL  from outside of VNETs the usage of SQL Gateway  is mandatory 
Definition: TBD

**Comment by eladperets** [comment]
The following aliases were added:

Microsoft.Sql/servers/databases/connectionPolicies/proxyDnsName
Microsoft.Sql/servers/databases/connectionPolicies/proxyPort
Microsoft.Sql/servers/databases/connectionPolicies/redirectionState
Microsoft.Sql/servers/databases/connectionPolicies/securityEnabledAccess
Microsoft.Sql/servers/databases/connectionPolicies/state
Microsoft.Sql/servers/databases/connectionPolicies/useServerDefault
Microsoft.Sql/servers/databases/connectionPolicies/visibility

Elad
