### ISSUE TITLE
New Zealand Information Security Manual: Inclusion of built-in policy 9677b740-f641-4f3c-b9c5-466005c85278 (Advanced data security settings for SQL server should contain an email address to receive security alerts)

### ISSUE THREAD

**Issue by davidwhitenz** [Azure/azure-policy#725]
#### Details of the scenario you tried and the problem that is occurring

Currently the NZISM Initiative/PolicySet contains:
"Vulnerability Assessment settings for SQL server should contain an email address to receive scan reports"
https://github.com/Azure/azure-policy/blob/569022638bf0518edb463eff23918240faa1843a/built-in-policies/policyDefinitions/SQL/SqlServer_VulnerabilityAssessmentEmails_Audit.json
  "id": "/providers/Microsoft.Authorization/policyDefinitions/057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9",
  "name": "057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9"

![image](https://user-images.githubusercontent.com/61292861/109583462-d1b24780-7b64-11eb-8efe-8407255dd2b8.png)

Can the following be included so that the alerts email setting is also captured:
"Advanced data security settings for SQL server should contain an email address to receive security alerts"
https://github.com/Azure/azure-policy/blob/569022638bf0518edb463eff23918240faa1843a/built-in-policies/policyDefinitions/SQL/SqlServer_AdvancedDataSecurityEmails_Audit.json
  "id": "/providers/Microsoft.Authorization/policyDefinitions/9677b740-f641-4f3c-b9c5-466005c85278",
  "name": "9677b740-f641-4f3c-b9c5-466005c85278"

![image](https://user-images.githubusercontent.com/61292861/109583511-e42c8100-7b64-11eb-8282-6c9f0cf6e49f.png)

#### Verbose logs showing the problem

n/a

#### Suggested solution to the issue

Updates for NZISM Initiative/PolicySet to include additional built-in policy:
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policySetDefinitions/Regulatory%20Compliance/nz_ism.json

![image](https://user-images.githubusercontent.com/61292861/109583057-23a69d80-7b64-11eb-87a3-348fea10907d.png)

----------------
New Lines 591- 602:

      "effect-9677b740-f641-4f3c-b9c5-466005c85278": {
        "type": "String",
        "defaultValue": "AuditIfNotExists",
        "allowedValues": [
          "AuditIfNotExists",
          "Disabled"
        ],
        "metadata": {
          "displayName": "Effect for policy: Advanced data security settings for SQL server should contain an email address to receive security alerts",
          "description": "For more information about effects, visit https://aka.ms/policyeffects"
        }
      },      

----------------
New Lines 1653 - 1664:

      {
        "policyDefinitionReferenceId": "9677b740-f641-4f3c-b9c5-466005c85278",
        "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/9677b740-f641-4f3c-b9c5-466005c85278",
        "parameters": {
          "effect": {
            "value": "[parameters('effect-9677b740-f641-4f3c-b9c5-466005c85278')]"
          }
        },
        "groupNames": [
          "NZISM_Security_Benchmark_v1.0_ISM-3"
        ]
      },

----------------

**Comment by kenieva** [comment]
Notifying the correct people.

**Comment by jomolesk** [comment]
@davidwhitenz Thanks for this feedback -- we will review this policy to include in the next update to the initiative.

cc @BevanSin
