### ISSUE TITLE
Exemptions: able to exempt policies from outside my RBAC defined scope

### ISSUE THREAD

**Issue by hctrr** [Azure/azure-policy#726]
Individuals/Groups that have been granted the RBAC Contributor and Resource Policy Contributor at the subscription level can submit exemptions from policies placed at the Management Group/Root level.

This in turn allows them to bypass any corporate wide policies. 

#### Details of the scenario you tried and the problem that is occurring
MG Policy: Only allow West Region
Sub01: Allows HRLead to manage their own policies by granting them Policy Contributor

HRLeads can now create an Exception to by pass the MG policy of only allowing West Region locations.

#### Suggested solution to the issue
Only allow exemptions to the scope where the individual has access to.
In the scenario above - HRLeads would not be allowed to create exemption to the MG Policy. They would only be allowed to submit exemptions to policies scoped at the Sub01.

If HRLeads require exemption from the MG Policy, they would require the team that created the MG Policy submit that exemption.

**Comment by robga** [comment]
@hctrr , when the user create an exemption, we check whether user has /exempt/action on the corresponding assignment. We do linked access check on the policyAssignmentId property of the exemption.  
If the users ONLY has contributor/resource policy contributor at subscription level, they cannot create exemptions for the assignment at MG level. The user should see an error like "The client 'XXX' with object id 'XXX' has permission to perform action 'Microsoft.Authorization/policyExemptions/write' on scope '/subscriptions/XXX'; however, it does not have permission to perform action 'exempt/action' on the linked scope(s) '/providers/Microsoft.Management/managementGroups/XXX/providers/Microsoft.Authorization/policyAssignments/XXX' or the linked scope(s) are invalid."
If it didn't work like this, please create a support ticket. We will investigate it.

**Comment by hctrr** [comment]
We can disregard the contributor role (that added more complexity to the example).

At root MG
- Enterprise Policy to only allow US regions is allowed.
At Subscription (Sub01)
- IAM – HRLead is added with the Policy Contributor role to further lock down their sub

In the example above, the HRLead is able to create an exemption to the root policy (Policy placed in root MG) even though they only have Policy Contributor access at the Sub01. 

This experience would mean local users/groups with Policy Contributor to just their sub are allowed to bypass Enterprise wide policies.

**Comment by robga** [comment]
@hctrr , could you please create a support ticket? We can help you troubleshoot. 
If the policy assignment is at the root MG where the HRLead has no Resource Policy Contributor permissions. The HRLead should not be able to create exemption on Sub01 or lower level.
