### ISSUE TITLE
Deploy - Configure diagnostic settings for storage accounts to Log Analytics workspace

### ISSUE THREAD

**Issue by pkorolo** [Azure/azure-policy#727]
![Capture6](https://user-images.githubusercontent.com/60117125/110138891-20691700-7ddb-11eb-8cf2-684ee3853007.JPG)
![Capture7](https://user-images.githubusercontent.com/60117125/110138903-23640780-7ddb-11eb-9e7f-c91d563d6494.JPG)

#### Details of the scenario you tried and the problem that is occurring

"Deploy - Configure diagnostic settings for storage accounts to Log Analytics workspace" policy never gets compliant and remediation fails. This policy is part of "Deploy-Resource-Diag" ESLZ initiative, so its failure to come compliant takes down the compliance of the whole ESLZ initiative. Nevertheless, this is a built-in policy, so not a part of the ESLZ team work (not a custom policy). In further detail, this policy is trying to enable not only "transaction", but also "read", "write" and "delete" in all levels, the top (storage account itself) level included. At the storage account level, nothing can be configured, except "transaction"; the other three configuration options, can be set at lower levels (file, blob, etc.). This misconfiguration is obvious also from the failure log of the remediation task.

#### Verbose logs showing the problem

when someone remediates the non-compliant policy, the remediation fails with the following:

•	Error code: BadRequest
•	Message: Category 'StorageRead' is not supported

coming from the erratic storage-account-level configuration that the policy is trying to do.
![Capture5](https://user-images.githubusercontent.com/60117125/110138610-d2541380-7dda-11eb-9ba1-23fb9f5e9a67.JPG)

#### Suggested solution to the issue

Policy clearly needs to by re-authored.

**Comment by kenieva** [comment]
Hi @pkorolo , I am unable to find this policy in our built-in list. Can you provide me the definition ID?

**Comment by pkorolo** [comment]
"id": "/providers/Microsoft.Authorization/policyDefinitions/6f8f98a4-f108-47cb-8e98-91a0d85cd474",

**Comment by pkorolo** [comment]
it is in the "storage" category, not in the "monitoring" as one would expect.

**Comment by kenieva** [comment]
A fix for this is in the process of being deployed.
