### ISSUE TITLE
Police "Private endpoint should be configured for Key Vault" block when using private endpoint option

### ISSUE THREAD

**Issue by mpenhalver** [Azure/azure-policy#730]
-->
#### Details of the scenario you tried and the problem that is occurring
I am trying to use the police "Private endpoint should be configured for Key Vault" in my subscription to block key vault creations without private endpoint.
The problem is that even if I choose the private endpoint option and create a private endpoint in the same region during the Key Vault setup in Azure portal, it still show me a validation error pointing to the police "Private endpoint should be configured for Key Vault".

#### Verbose logs showing the problem

code": "InvalidTemplateDeployment",
  "message": "The template deployment failed because of policy violation. Please see details for more information.",
  "details": [
    {
      "code": "RequestDisallowedByPolicy",
      "target": "akvtst003",
      "message": "Resource 'akvtst003' was disallowed by policy. Reasons: 'Esse Key Vault foi configurado sem a opção de Private endpoint habilitada. Favor ajustar essa configuração na etapa de implantação.'. See error details for policy resource IDs.",
      "additionalInfo": [
        {
          "type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "[Preview]: Private endpoint should be configured for Key Vault",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "True",
                  "expressionKind": "Field",
                  "expression": "type",
                  "path": "type",
                  "expressionValue": "Microsoft.KeyVault/vaults",
                  "targetValue": "Microsoft.KeyVault/vaults",
                  "operator": "Equals"
                },
                {
                  "result": "True",
                  "expressionKind": "Field",
                  "expression": "Microsoft.KeyVault/vaults/privateEndpointConnections",
                  "path": "properties.privateEndpointConnections",
                  "targetValue": "false",
                  "operator": "Exists"
                }
              ],
              "reason": "Esse Key Vault foi configurado sem a opção de Private endpoint habilitada. Favor ajustar essa configuração na etapa de implantação."
            },
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/XXXXXXX",
            "policyDefinitionName": "XXXXXXXXXXXXXXXXXX",
            "policyDefinitionEffect": "Deny",
            "policyAssignmentId": "/providers/Microsoft.Management/managementGroups/XXXXXX/providers/Microsoft.Authorization/policyAssignments/XXXXXXXXXXXXXXX",
            "policyAssignmentName": "XXXXXXXXXXXXXX",
            "policyAssignmentDisplayName": "[SECOPS] - Key Vault - Private endpoint should be configured for Key Vault",
            "policyAssignmentScope": "/providers/Microsoft.Management/managementGroups/XXXXXXXXXXXXX",
            "policyAssignmentParameters": {
              "effect": {
                "value": "Deny"
              }
            }
          }
        }
      ]
    }
  ]
}

#### Suggested solution to the issue
N/A

#### If policy is Guest Configuration - details about target node
N/A

**Comment by mpenhalver** [comment]
> @mpenhalver , just to confirm, you are following the steps laid out here: https://docs.microsoft.com/en-us/azure/key-vault/general/private-link-service?tabs=portal?
> 
> 1. Find your Key Vault resource in the portal, 2. Navigate to the Networking tab, 3. Select the "Private Endpoint Connections" Tab, 4. Click "+ Private endpoint" to configure.

Yes. I am following this steps.

**Comment by kenieva** [comment]
Thank you for confirming. I have notified the Key Vault team of the issue. They did communicate with me that there are some changes coming down the pipeline to update this policy due to some known issues. I will wait for any other response as they look into your case.

**Comment by kenieva** [comment]
Still waiting for updates from the team....

**Comment by nehakulkarni123** [comment]
Key Vault team has communicated that this policy is in the process of being deprecated. Instead, they request customers to use the following built-in policy instead: [[Preview]: Azure Key Vaults should use private link ](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Key%20Vault/AzureKeyVaultPrivateEndpointEnabled_Audit.json),
