### ISSUE TITLE
[Preview] Deploy Dependency agent to Windows Azure Arc machines - remediation fails

### ISSUE THREAD

**Issue by richeney** [Azure/azure-policy#733]
<https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Monitoring/DependencyAgentExtension_Linux_HybridVM_Deploy.json> remediation fails.

The default assignment experience in the portal recommends the **Log Analytics Contributor** role for the remediation tasks, but these then fail with the following error message:

> The template deployment failed with error: 'Authorization failed for template resource 'win-01' of type 'Microsoft.HybridCompute/machines'. The client '0fef0207-9fcf-4749-b552-12b2deafe21f' with object id '0fef0207-9fcf-4749-b552-12b2deafe21f' does not have permission to perform action 'Microsoft.HybridCompute/machines/write' at scope '/subscriptions/2ca40be1-7e80-4f2b-92f7-06b2123a68cc/resourceGroups/arc-hack/providers/Microsoft.HybridCompute/machines/win-01'.'.

Sure enough, the only action in the role is `Microsoft.HybridCompute/machines/extensions/write` but that is consistent with Microsoft.Compute and Microsoft.ClassicCompute, so perhaps it is an issue with the nested deployment template within the policy definition.

I think the solution is to either

* change the extension deployment so that it doesn't need `Microsoft.HybridCompute/machines/write`, (preferred) or
* add the `/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/b64e21ea-ac4e-4cdf-9dc9-5b892992bee7` role in addition to Log Analytics Contributor role

**Comment by richeney** [comment]
I am testing to see if the Dependency agent for linux Arc VMs also fails. 

As a workaround I believe that additionally assigning the Azure Connected Machine Onboarding role to the managed identity may be sufficient.

**Comment by camillemarie** [comment]
[A fix for this is in flight](https://github.com/Azure/azure-policy/pull/735/commits/b8df8b2f1081d81f48bd10221553245a44c73186#diff-6945102c0638adf69d5f7885ba05081548f0f90a83596a99c9e2071c3cb95436) and will be live by tomorrow.

**Comment by richeney** [comment]
Just in time for my partner hack today. Aewsome timing!!!
