### ISSUE TITLE
Configure Service Bus namespaces to use private DNS zones - does not assign identity to another subscription under a different management group

### ISSUE THREAD

**Issue by MikeForster100** [Azure/azure-policy#737]
#### Details of the scenario you tried and the problem that is occurring
Service bus policy: Configure Service Bus namespaces to use private DNS zones - it allows you to select the subscription and private dns zone name but does not assign the managed identity to the private dns zone (the subscription I selected is under a different management group, due to our hub and spoke setup).

If you manually assign the managed identity to the dns zone it works

No problem is encountered if the private dns zone is in the same management group.

**Comment by kenieva** [comment]
Hi @MikeForster100, users are now allowed to select user assigned managed identities. This enables you to select a managed identity that is the require zone. Thanks.
