### ISSUE TITLE
[Preview]: Configure backup on VMs with a given tag to an existing recovery services vault in the same location - Not working

### ISSUE THREAD

**Issue by kevinrosal** [Azure/azure-policy#739]
#### Details of the scenario you tried and the problem that is occurring
Policy is deployed with DeployIfNotExists effect.

When i tried deploying a new VM with the specified tag on the policy it doesnt automatically configure backup on the VM. then minutes after the policy reports the newly created VM as non-compliant

**Comment by tijmenamsing** [comment]
Hi @kevinrosal, have you found a solution for this? I encounter the same issue for the "Configure backup on VMs *without* a given tag to an existing recovery services vault in the same location" policy.

**Comment by binnum** [comment]
Hi @kevinrosal and @tijmenamsing, we are experiencing same issue as you guys, have tried with/without tag policies - did you find a solution?

**Comment by shanhix1** [comment]
Hi @kevinrosal, @tijmenamsing, and @binnum - thank you for raising this issue. Is there a delay in the deployment, or does the backup not get configured at all? Does manual remediation still work?

Posting links to the built-ins here for reference:
- https://github.com/Azure/azure-policy/blob/f2706e05bccaac0a7410f8613107a6ee3bd88afd/built-in-policies/policyDefinitions/Backup/VirtualMachineApplicationCentricBackup_Backup_Deploy_WithTag.json 
- https://github.com/Azure/azure-policy/blob/f2706e05bccaac0a7410f8613107a6ee3bd88afd/built-in-policies/policyDefinitions/Backup/VirtualMachineApplicationCentricBackup_Backup_Deploy_WithOutTag.json

**Comment by shanhix1** [comment]
Hi @kevinrosal, @tijmenamsing, and @binnum, just following up - are you still experiencing this issue?

**Comment by shanhix1** [comment]
Closing this issue for now - please re-open if issue persists.

**Comment by sshibily** [comment]
I am facing similar issue where neither backup gets automatically configured nor remediation tasks work. I use the policy **"Configure backup on VMs without a given tag to an existing recovery services vault in the same location"**

@shanhix1 Any help?
