### ISSUE TITLE
Alias Request: microsoft.sqlservers/auditingSettings

### ISSUE THREAD

**Issue by ezlbrmn** [Azure/azure-policy#74]
Scenario: we are checking compliance with following security requirement: Enable failure auditing for Azure SQL logins and access
Definition: TBD

**Comment by pilor** [comment]
The `Microsoft.Sql/auditingSettings.state` alias exists and an example of auditing that SQL server auditing is enabled is available here:  https://github.com/Azure/azure-policy/tree/master/samples/SQL/audit-sql-server-auditing
