### ISSUE TITLE
"Audit Windows machines that do not have a maximum password age of 70 days" shows non-compliant when max password age is fewer than 70 days

### ISSUE THREAD

**Issue by PDunbarCGI** [Azure/azure-policy#745]
#### Details of the scenario you tried and the problem that is occurring
Through Group Policy, set Maximum password age to 60 days.  Virtual Machines show as non-compliant.  However, if group policy is set to 70 days exactly, Virtual Machines show as compliant.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
1) Update check to include values less than 70
2) Make policy's maximum password age value configurable by parameter

#### If policy is Guest Configuration - details about target node
```
OsName               : Microsoft Windows Server 2012 R2 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19994.amd64fre.winblue_ltsb_escrow.210331-1613
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

>

**Comment by kenieva** [comment]
Hi, from what you have described, this policy is working as expect. It requires that the password be 70 days exactly. I will pass this request to the team to consider modifying the policy. The team is also working to supporting custom guest configuration policies that will allow to modify this policy. Thanks.

**Comment by Leighc87** [comment]
Hi, this isn't completed :( still doesn't work for 60 day configuration - which bests 70 days!
