### ISSUE TITLE
 Alias request: Microsoft.Authorization/denyAssignments/read

### ISSUE THREAD

**Issue by AshwinSarimin** [Azure/azure-policy#747]
**Scenario**

Need to use Azure Policy to exclude 'managed' storage accounts (created by managed applications like databricks or aro cluster) for checking security measures like disabling public blob access and enforcing TLS 1.2

**Definition**
```
"policyRule": {
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Storage/storageAccounts"
      },
      {
        "field": "Microsoft.Authorization/denyAssignments/read",
        "exists": "false"
      }
    ]
  },
  "then": {
    "effect": "[parameters('effect')]"
  }
```

**Comment by kenieva** [comment]
Hi @ashwinsangem, do the nature of managed by resources, those storage accounts won't be blocked by Policy.
