### ISSUE TITLE
Alias request: Microsoft.SerialConsole/consoleServices/default.disabled

### ISSUE THREAD

**Issue by CharlesMure** [Azure/azure-policy#749]
## Scenario

Serial Console can be update at subscription level using REST API
https://docs.microsoft.com/en-us/rest/api/serialconsole/getconsolestatus/getconsolestatus

I need to audit/enforce at scale (management group level) via Azure Policy the Serial Console configuration.

## Required Alias

Microsoft.SerialConsole/consoleServices/default.disabled
    
## Definition 

        {
            "properties": {
                "displayName": "Audit Serial Console status",
                "description": "Audit whether or not Serial Console is disabled for a given subscription",
                "parameters": { }
                },
                "policyRule": {
                    "if": {
                        "allOf": [
                            {
                                "field": "type",
                                "equals": "Microsoft.SerialConsole/consoleServices"
                            },
                            {
                                "field": "Microsoft.SerialConsole/consoleServices/default.disabled",
                                "equals": false
                            },
                        ]
                    },
                    "then": {
                        "effect": "audit"
                    }
                }
          }

**Comment by kenieva** [comment]
Hi @CharlesMure, please open an Azure support ticket so that we can route this ask to the appropriate team. Thank you.
