### ISSUE TITLE
New Zealand Information Security Manual policy: effect-b02aacc0-b073-424e-8298-42b22829ee0a is outdated

### ISSUE THREAD

**Issue by davidwhitenz** [Azure/azure-policy#757]
Currently the recommendation and included policy for the following in NZISM Azure Policy:
effect-b02aacc0-b073-424e-8298-42b22829ee0a
"Activity log should be retained for at least one year"

Is outdated as it is referencing log profiles instead of diagnostic logs:
https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log#legacy-collection-methods

![image](https://user-images.githubusercontent.com/61292861/117374900-23d76680-af22-11eb-8b37-17477ae53c45.png)

Policy:

![image](https://user-images.githubusercontent.com/61292861/117374683-b1ff1d00-af21-11eb-8326-37e0aae75520.png)

This should reflect either a different built in policy or the built in policy updated to use diagnostic logs instead of log profiles.

Optionally the policy can include the legacy options and also check for diagnostic log settings and if set be compliant.

**Comment by kenieva** [comment]
FYI @jomolesk

**Comment by BevanSin** [comment]
This matches my issue I raised here about needing the builtin policy to be updated to audit the diagnostic setting correctly.

https://github.com/Azure/azure-policy/issues/751

**Comment by jomolesk** [comment]
Adding @asheniam from Azure Monitor Essentials team

**Comment by shanhix1** [comment]
Hello, @asheniam - I was wondering if you had any updates about this? As @BevanSin mentioned, this is also observed in https://github.com/Azure/azure-policy/issues/751

**Comment by kenieva** [comment]
@asheniam - any updates?

**Comment by kenieva** [comment]
There is a separate effort of policies to help the transition to diagnostic log instead of log profiles.
