### ISSUE TITLE
Deploy if not exist policy - Function app "Microsoft.Web/sites/httpsOnly" field not showing correct value

### ISSUE THREAD

**Issue by jayaakshayan** [Azure/azure-policy#758]
Deploy if not exist policy - Function app "Microsoft.Web/sites/httpsOnly" field not showing correct value.

Even-though  the function app " HTTPS Only" value set to false, in the deploy if not exist compliance it is showing wrong value as "true" and the remediation not happening.

**_Function App settings:_**

![image](https://user-images.githubusercontent.com/42839520/117612834-7d8a9b80-b183-11eb-9f76-93bec05daf09.png)

**_Compliance Screenshot:_**
![image](https://user-images.githubusercontent.com/42839520/117612714-4ae0a300-b183-11eb-9659-3e5000119f8e.png)

**Comment by jayaakshayan** [comment]
This is custom policy and below is the definition. This works good for Webapp and only gives issue with the function app.

I have also tried to include kind as function app in the policy rule, still same issue.

{
  "properties": {
    "displayName": "Function App",
    "mode": "Indexed",
    "parameters": {},
    "policyRule": {
      "if": {
        "field": "type",
        "equals": "Microsoft.Web/sites"
      },
      "then": {
        "effect": "deployIfNotExists",
        "details": {
          "type": "Microsoft.Web/sites",
          "roleDefinitionIds": [
            "/providers/Microsoft.Authorization/roleDefinitions/de139f84-1756-47ae-9be6-808fbbe84772"
          ],
          "existenceCondition": {
            "field": "Microsoft.Web/sites/httpsOnly",
            "equals": "true"
          },
          "deployment": {
            "properties": {
              "mode": "incremental",
              "template": {
                "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                "contentVersion": "1.0.0.0",
                "parameters": {
                  "webappName": {
                    "type": "string"
                  },
                  "webappLocation": {
                    "type": "string"
                  },
                  "tags": {
                    "type": "object"
                  }
                },
                "resources": [
                  {
                    "name": "[parameters('webappName')]",
                    "tags": "[parameters('tags')]",
                    "type": "Microsoft.Web/sites",
                    "apiVersion": "2016-08-01",
                    "location": "[parameters('webappLocation')]",
                    "identity": {
                      "type": "SystemAssigned"
                    },
                    "properties": {
                      "httpsOnly": "true"
                    }
                  }
                ]
              },
              "parameters": {
                "webappName": {
                  "value": "[field('fullName')]"
                },
                "webappLocation": {
                  "value": "[field('location')]"
                },
                "tags": {
                  "value": "[field('tags')]"
                }
              }
            }
          }
        }
      }
    }
  }
}

**Comment by kenieva** [comment]
Hi @jayaakshayan, you still need to add the check for https set to true in the if condition. 

Sample here: https://github.com/Azure/Community-Policy/blob/master/Policies/WebApps/deploy-webapp-force-https/azurepolicy.json

**Comment by jayaakshayan** [comment]
HI @kenieva The above sample has been tested and even i could see the same bug with this template.

// Function app https only value is set to "false" but the deploy if not exist policy is not detecting correct value and it is wrongly reporting the resource as compliance.

Can you please test the same template from your end using function app ?

**Comment by jayaakshayan** [comment]
@kenieva managed to found the fix. You can close the ticket.

I have added the line marked in bold in my existing code which fixed  the issue.

        "then": {
            "effect": "[parameters('effect')]",
            "details": {
                "type": "Microsoft.Web/sites",
                **"name": "[field('name')]",**
                "existenceCondition": {
                    "field": "Microsoft.Web/sites/httpsOnly",
                    "equals": true
                },
