### ISSUE TITLE
Alias Request: microsoft.sql/servers/databases/auditingSettings

### ISSUE THREAD

**Issue by ezlbrmn** [Azure/azure-policy#76]
Scenario: we are checking compliance with following security requirement: Enable failure auditing for Azure SQL logins and access
Definition: TBD

**Comment by pilor** [comment]
`Microsoft.Sql/auditingSettings.state` will allow you to check this value in policy.  https://github.com/Azure/azure-policy/tree/master/samples/SQL/audit-sql-db-auditing is an example implementation
