### ISSUE TITLE
"Disable automounting API credentials to prevent a potentially compromised Kubernetes Pod resource to run API commands." does not consider ServiceAccount object

### ISSUE THREAD

**Issue by MarvinSchenkel** [Azure/azure-policy#763]
#### Details of the scenario you tried and the problem that is occurring
I have implemented a separate `ServiceAccount` object where I have set the `automountServiceAccountToken` to `false`. My pods reference this `ServiceAccount` by setting the `spec.serviceAccountName` to the name of the `ServiceAccount`. This is documented in the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server). However, the policy is violated.

Looking at the policy definition, the policy only seems to consider `spec.automountServiceAccountToken` on a `Pod`.

#### Suggested solution to the issue
Extend the policy to also check `ServiceAccounts` linked to a `Pod`.

**Comment by RamyasreeChakka** [comment]
@miwithro to take a look at this.

**Comment by RamyasreeChakka** [comment]
@Amirzadehm , @sw47 - FYI

**Comment by fseldow** [comment]
fixed by new rule to check mountVolumn if there is no automountServiceAccountToken field in pod

new rego:
https://store.policy.core.windows.net/kubernetes/block-automount-token/v1/template.yaml

**Comment by nehakulkarni123** [comment]
Thanks, @fseldow! @MarvinSchenkel, please feel free to reopen if you have any follow up questions.
