### ISSUE TITLE
Alias Request: Microsoft.Sql/servers/firewallRules

### ISSUE THREAD

**Issue by ezlbrmn** [Azure/azure-policy#77]
Scenario: we are checking compliance with following security requirement: " Allow All services"  should be set to off in Azure SQL Firewall
Definition: TBD

**Comment by pilor** [comment]
The following aliases exist:
```
Microsoft.Sql/servers/firewallRules/startIpAddress
Microsoft.Sql/servers/firewallRules/endIpAddress
```

Can you make use of those?
