### ISSUE TITLE
Transparent Data Encryption on SQL databases should be enabled: Policy GUID does not follow the correct pattern

### ISSUE THREAD

**Issue by msaravindh** [Azure/azure-policy#775]
#### Details of the scenario you tried and the problem that is occurring
The Policy **Transparent Data Encryption on SQL databases should be enabled** has the policy definition ID of **/providers/Microsoft.Authorization/policyDefinitions/17k78e20-9358-41c9-923c-fb736d382a12**.  The Policy Definition ID ideally should follow the regex pattern ^/providers/Microsoft.Authorization/policyDefinitions/([a-f]|[0-9]){8}-([a-f]|[0-9]){4}-([a-f]|[0-9]){4}-([a-f]|[0-9]){4}-([a-f]|[0-9]){12}$ and have characters [a-f][0-9] in it. However in this case there is a **k character** in the GUID(17**k**78e20-9358-41c9-923c-fb736d382a12) which is not expected. It could be the case that the GUID was wrongly generated.

#### Verbose logs showing the problem
NA
#### Suggested solution to the issue
The Policy GUID could be regenerated to follow the right pattern to ensure it has characters between [a-f][0-9] only.

#### If policy is Guest Configuration - details about target node
NA

**Comment by pilor** [comment]
Yes, this was an unfortunate mistake and we've taken steps to ensure it doesn't happen again.  However, the name of the existing built-in cannot be changed as it would break references to that resource ID.
