### ISSUE TITLE
WAF_AppGatewayMode_Audit: default mode Detection

### ISSUE THREAD

**Issue by davidwhitenz** [Azure/azure-policy#779]
#### Details of the scenario you tried and the problem that is occurring

The default mode for the WAF is set to Detection in the following policy:
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Network/WAF_AppGatewayMode_Audit.json

This means if you have a WAF policy that is in prevention mode, with the default settings this will flag as non compliant.

At the moment this is used in the NZISM policy set:
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policySetDefinitions/Regulatory%20Compliance/nz_ism.json#L648
effect-12430be1-6cc8-4527-a9a8-e3d38f250096

Which means by default we are non-compliant with a WAF policy in Prevention mode.

#### Verbose logs showing the problem

Any evaluated WAF policy that is in prevention will flag as non-compliant by default

Example:
![image](https://user-images.githubusercontent.com/61292861/121978473-61aa9300-cddc-11eb-991a-5a5a63e2ee8a.png)

Current compliant resource (in detection mode) example with policy defaults:
![image](https://user-images.githubusercontent.com/61292861/121978202-caddd680-cddb-11eb-8a2e-9fcfce82ffef.png)

Current non-compliant resource (in prevention mode) example with policy defaults:
![image](https://user-images.githubusercontent.com/61292861/121978295-05477380-cddc-11eb-8a70-bdc30c06bd7a.png)

#### Suggested solution to the issue

I believe the default setting should be Prevention with the allowance for people to override down to Detection if required.
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Network/WAF_AppGatewayMode_Audit.json#L35
From: "defaultValue": "Detection"
to: "defaultValue": "Prevention"

**Comment by davidwhitenz** [comment]
Also the same for the frontdoor policy:
"Web Application Firewall (WAF) should use the specified mode for Azure Front Door Service"
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Network/WAF_AFD_Mode_Audit.json#L35

**Comment by shanhix1** [comment]
Hi @davidwhitenz - This default value is by design because all regulatory compliance initiatives (including NZISM) are intended to stay in detection, or audit, mode, but not to enforce. To achieve the behavior you are looking for, I would recommend creating a custom policy that mirrors this built-in, and changing the default mode to 'Prevention' for that custom policy.
