### ISSUE TITLE
Alias Request: microsoft.network/virtualnetworks/subnets/NetworkSecurityGroup/SecurityRules

### ISSUE THREAD

**Issue by ezlbrmn** [Azure/azure-policy#78]
Scenario: we are checking compliance with following security requirement: Use subnet NSGs to make sure that ports allowed must match load balancer listener 
Definition: TBD

**Comment by pilor** [comment]
There are many aliases available on NSGs, securityRules, etc...  See [this docs page](https://docs.microsoft.com/en-us/azure/azure-policy/policy-definition#aliases) for information on how you can list all available aliases.

If there is a gap that prevents you from accomplishing your scenario please open a new issue.
