### ISSUE TITLE
disable automounting API credentials exclude namespace does not get updated after change of default policy

### ISSUE THREAD

**Issue by assaf-grth** [Azure/azure-policy#785]
#### Details of the scenario you tried and the problem that is occurring
I have several external components which I use in my cluster (like cert-manager) and need to exclude their namespace from this policy evaluation
The policy is assigned by default by the security center
I have set the policy parameter "Namespace exclusions" to exclude additional namespaces but the update is not reflected into the cluster (from Security Center -> Security Policy menu at Azure portal)

#### Verbose logs showing the problem
From the constraint template in the cluster (k8sazureblockautomounttoken):
    Excluded Namespaces:
      kube-system
      gatekeeper-system
      azure-arc

In Azure policy parameters:
![image](https://user-images.githubusercontent.com/52287325/123987656-0c6fa380-d9d0-11eb-8eeb-bde6f253894a.png)

#### Suggested solution to the issue
Make sure excluded namespaces are in sync with Azure policy definitions

**Comment by RamyasreeChakka** [comment]
@assaf-grth - Are you still seeing the issue? 
After a policy assignment is updated, it would take at most an hour for changes to sync to the cluster. If you are still seeing the issue, please share cluster resource ID, we will investigate. Also please feel free to raise a support request.

**Comment by assaf-grth** [comment]
I already have a support ticket in place with all the details,
Can I somehow ask for directing the ticket to you or the team?

**Comment by RamyasreeChakka** [comment]
@assaf-grth - Please inform the support engineer to direct the request to Azure Policy/ Dataplane team. We will take a look and investigate the issue.

**Comment by assaf-grth** [comment]
I will ask them
Thanks

**Comment by nehakulkarni123** [comment]
I see that a fix for this item is being tracked and is to be completed by the ASC team in early Aug, so I will close this item here.
