### ISSUE TITLE
Guest Configuration policies: Built-in policies won't work on Ubuntu 20.04 and later Ubuntu images

### ISSUE THREAD

**Issue by bowers** [Azure/azure-policy#787]
#### Details of the scenario you tried and the problem that is occurring
Built-in Guest Configuration policies, such as "Audit Linux machines that allow remote connections from accounts without passwords", fail to audit Ubuntu VMs more recent than Ubuntu 18.04.  Azure Policy does not identify VMs such as Ubuntu 20.04 LTS as resources subject to those policies. 

This is because many built-in Guest Configuration policies looks specifically for the offer name "UbuntuServer" in the Microsoft.Compute/imageOffer field.  The publisher of Ubuntu images changed the offer name format after Ubuntu 18.04.

* Old offer name: `"UbuntuServer"`
* Example new offer names: `"0001-com-ubuntu-server-hirsute"`

I think this applies to these built-in [Guest Configuration policy definitions](https://github.com/Azure/azure-policy/tree/master/built-in-policies/policyDefinitions/Guest%20Configuration) : 

* GuestConfiguration_AddSystemIdentityWhenNone_Prerequisite.json
* GuestConfiguration_AddSystemIdentityWhenUser_Prerequisite.json
* GuestConfiguration_AuditExtensionLinux_Prerequisite.json
* GuestConfiguration_AzureLinuxBaseline_AINE.json
* GuestConfiguration_DeployExtensionLinux_Prerequisite.json
* GuestConfiguration_InstalledApplicationForLinux_AINE.json
* GuestConfiguration_LinuxNoPasswordForSSH_AINE.json
* GuestConfiguration_LinuxPassword110_AINE.json
* GuestConfiguration_LinuxPassword121_AINE.json
* GuestConfiguration_LinuxPassword232_AINE.json 
* GuestConfiguration_LocalUsers_Linux_AINE.json
* GuestConfiguration_NotInstalledApplicationForLinux_AINE.json
* GuestConfiguration_PrerequisitePolicyLinux_Deploy.json

#### Suggested solution to the issue
This could be fixed by changing the filters to look for any string containing ubuntu, and excluding Ubuntu 12* via the imageVersion field:

Current:
```
"allOf": [
{
	"field": "Microsoft.Compute/imagePublisher",
	"equals": "Canonical"
},
{
	"field": "Microsoft.Compute/imageOffer",
	"equals": "UbuntuServer"
},
{
	"field": "Microsoft.Compute/imageSKU",
	"notLike": "12*"
}
]
```
This works:
```
"allOf": [
{
	"field": "Microsoft.Compute/imagePublisher",
	"equals": "Canonical"
},
{
	"field": "Microsoft.Compute/imageOffer",
	"contains": "ubuntu"
},
{
	"field": "Microsoft.Compute/imageVersion",
	"notLike": "12*"
}
]
```

**Comment by mgreenegit** [comment]
Acknowledged. Notifying @Nitinbps as well.

**Comment by nehakulkarni123** [comment]
Hi @nitinbps, any update on this?

**Comment by kenieva** [comment]
@nitinbps - any update?

**Comment by shanhix1** [comment]
Hi @bowers - please open a support ticket for this issue directly with the Guest Config team, and a support engineer can help you with this request.
