### ISSUE TITLE
ASC_Register_To_Azure_Security_Center_Deploy.json Duplicate of *_FFX?

### ISSUE THREAD

**Issue by MartinParis** [Azure/azure-policy#788]
#### Details of the scenario you tried and the problem that is occurring
These two policies share the same internal name, those names should be unique!
Internal name: ac076320-ddcf-4066-b451-6154267e8ad2

#### Verbose logs showing the problem
See the policies

#### Suggested solution to the issue
Change the name of one of them, the FFX one?

**Comment by shanhix1** [comment]
Hi @MartinParis - we were not able to duplicate this issue. There looks to be only one instance of this definition in the docs and in the GitHub repo:
https://docs.microsoft.com/en-us/azure/governance/policy/samples/built-in-policies#security-center
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Security%20Center/ASC_Register_To_Azure_Security_Center_Deploy.json
