### ISSUE TITLE
Alias Request: Microsoft.Network/loadBalancers/frontendIPConfigurations/subnet/networkSecurityGroup/securityRules/protocol

### ISSUE THREAD

**Issue by ezlbrmn** [Azure/azure-policy#79]
Scenario: we are checking compliance with following security requirement: Use subnet NSGs to make sure that ports allowed must match load balancer listener 
Definition: TBD

**Comment by pilor** [comment]
Its not clear what is being requested in this issue.  There are many aliases already available in this space.  If there is a gap please open a new issue with more details.
