### ISSUE TITLE
"Transparent Data Encryption on SQL databases should be enabled" is returning Non-compliant state for databases that have TDE enabled

### ISSUE THREAD

**Issue by difabricni** [Azure/azure-policy#791]
### Details of the scenario you tried and the problem that is occurring
Default ASC policy "Transparent Data Encryption on SQL databases should be enabled" is retuning Non-compliant state for SQL Databases even when they have TDE Enabled with customer-managed key.

### Suggested solution to the issue

**Current policy definition is configured like this:**
   "then": {
        "effect": "[parameters('effect')]",
        "details": {
          "type": "Microsoft.Sql/servers/databases/transparentDataEncryption",
          "name": "current",
          "existenceCondition": {
            "allOf": [
              {
                _"field": "Microsoft.Sql/transparentDataEncryption.status",
                "equals": "enabled"_
              }
            ]
          }
        }
      }

**Suggested solution;**
        "then": {
          "effect": "[parameters('effect')]",
          "details": {
            "type": "Microsoft.Sql/servers/databases/transparentDataEncryption",
            "name": "current",
            "existenceCondition": {
              "allOf": [
                {
                  _"field": "Microsoft.Sql/servers/databases/transparentDataEncryption/state",
                  "equals": "enabled"_
                }
              ]
            }
          }
        }

**Comment by pilor** [comment]
SQL changed the property in a new API version.  The built-in policies have been updated to reflect this.  
Example:  https://github.com/Azure/azure-policy/commit/064b26cf692ec637c2851b0545b6d4c9a40b4a60#diff-369eb2c04daba011c506a747e6189998efb5987db98d3a3a04e80463a2cd891b
