### ISSUE TITLE
Issue with Storage due to missing keyExpirationPeriodInDays

### ISSUE THREAD

**Issue by ManuInNZ** [Azure/azure-policy#793]
In the latest commit https://github.com/Azure/azure-policy/commit/cdb75bc196e7b16f590c9f80b8994b6e0a17668d#diff-0fde232b36ee34605586b0b4e0e03c68e86ece47bdf7662c30f4a76f7f1dd3d2R32

a new policy change for storage is referring to keyExpirationPeriodInDays which is not available and causes every storage account modification even through portal.

reproduction steps:
1. ensure the built-in-policies/policyDefinitions/Storage/StorageAccountKeysExpired_Restrict.json is applied to a resource group
2. create a new resource group
3. try to modify the storage account. You should get the following error
`Failed to save firewall and virtual network settings
Failed to save firewall and virtual network settings for storage account 'just4confirmation'. Error: A function or parameter in policy assignment 'd6ba2688b27c45ea974f1317' associated with the policy definition '044985bb-afe1-42cd-8a36-9d5d42424537' could not be validated. Please either fix the policy or remove the policy assignment to unblock. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'The policy language function 'addDays' second parameter value '' type is invalid. Actual type is 'String'. Expected type is 'Integer'. Please see https://aka.ms/policy-functions for usage details.'.`

Same using a cli command (PowerShell for example)
 ``` powershell
Update-AzStorageAccountNetworkRuleSet -ResourceGroupName myGroup -Name whateverthename -DefaultAction Allow
Update-AzStorageAccountNetworkRuleSet: A function or parameter in policy assignment 'd6ba2688b27c45ea974f1317' associated with the policy definition '044985bb-afe1-42cd-8a36-9d5d42424537' could not be validated. Please either fix the policy or remove the policy assignment to unblock. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'The policy language function 'addDays' second parameter value '' type is invalid. Actual type is 'String'. Expected type is 'Integer'. Please see https://aka.ms/policy-functions for usage details.'.
```

**Comment by ManuInNZ** [comment]
@bevansin FYI

**Comment by ManuInNZ** [comment]
@davidwhitenz good luck with your deployment 😄

**Comment by pilor** [comment]
This is the issue the author was attempting to fix.  Notified them that it is still an issue in some cases.

**Comment by pilor** [comment]
The fix will go out with the next release (starting July 26).  Short-term mitigations include disabling the policy or duplicating it and temporarily assigning a custom policy with the fix.

The complete rule with the fix:

```
{
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Storage/storageAccounts"
          },
          {
            "anyOf": [
              {
                "value": "[utcNow()]",
                "greater": "[if(and(not(empty(coalesce(field('Microsoft.Storage/storageAccounts/keyCreationTime.key1'), ''))), not(empty(string(coalesce(field('Microsoft.Storage/storageAccounts/keyPolicy.keyExpirationPeriodInDays'), ''))))), addDays(field('Microsoft.Storage/storageAccounts/keyCreationTime.key1'), field('Microsoft.Storage/storageAccounts/keyPolicy.keyExpirationPeriodInDays')), utcNow())]"
              },
              {
                "value": "[utcNow()]",
                "greater": "[if(and(not(empty(coalesce(field('Microsoft.Storage/storageAccounts/keyCreationTime.key2'), ''))), not(empty(string(coalesce(field('Microsoft.Storage/storageAccounts/keyPolicy.keyExpirationPeriodInDays'), ''))))), addDays(field('Microsoft.Storage/storageAccounts/keyCreationTime.key2'), field('Microsoft.Storage/storageAccounts/keyPolicy.keyExpirationPeriodInDays')), utcNow())]"
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "[parameters('effect')]"
      }
    }
```

**Comment by ManuInNZ** [comment]
Not sure if it was released yet however it seems you can also adjust storage account through ARM deployment still with that policy in place.

**Comment by pilor** [comment]
The updated policy has been deployed
