### ISSUE TITLE
LogAnalyticsWorkspaces_NetworkAccessEnabled_Modify.json policy unknown role definition

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-policy#794]
The role definition for policy LogAnalyticsWorkspaces_NetworkAccessEnabled_Modify.json seems it does not exists. There is no built-in role definition with ID 86695298-2eb9-48a7-9ec3-2fdb38b6878b.

**Comment by pilor** [comment]
Author is fixing it.  Desired role definition is https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#log-analytics-contributor

**Comment by kenieva** [comment]
This has been resolved.
