### ISSUE TITLE
"Deploy - Configure diagnostic settings for SQL Databases to Log Analytics workspace" is returning Non-Compliant state for databases with ALL diagnostic settings enabled and routing to Log analytics.

### ISSUE THREAD

**Issue by AISeanAshton** [Azure/azure-policy#795]
Details of the scenario you tried and the problem that is occurring - 

Currently have all diagnostic settings available enabled for the SQL Databases and routing to Log Analytics workspace but the policy is still returning Non-Complaint. I suspect the diagnostic settings for this resource have changed recently but the policy has not been updated to reflect the new diagnostic settings list. 

![image](https://user-images.githubusercontent.com/73120438/126209600-4687d9c4-c527-4390-8e10-18de5b5d134e.png)

![image](https://user-images.githubusercontent.com/73120438/126209719-c551cc10-92c9-4216-af5c-36efcc9d4e60.png)

Suggested solution to the issue

I believe the policy "Deploy - Configure diagnostic settings for SQL Databases to Log Analytics workspace" should be updated to include the new SQL Database diagnostic settings.

**Comment by jagadish222** [comment]
Use the below template to add extra logs for  "category": "DevOpsOperationsAudit", "category": "SQLSecurityAuditEvents", which are defined in the policy in order to get compliant


Template: 

{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "settingName": {
            "type": "String"
        },        
        "serverName": {
            "type": "String"
        },
        "dbName": {
            "type": "String"
        },
        "workspaceId": {
            "type": "String"
        }
 
    },
    "resources": [
        {
          "type": "microsoft.sql/servers/databases/providers/diagnosticSettings",
          "apiVersion": "2017-05-01-preview",
          "name": "[concat(parameters('serverName'),'/',parameters('dbName'),'/microsoft.insights/', parameters('settingName'))]",
          "dependsOn": [],
          "properties": {
            "workspaceId": "[parameters('workspaceId')]",
            "logs": [
              {
                "category": "SQLInsights",
                "enabled": true
              },
              {
                "category": "AutomaticTuning",
                "enabled": true
              },
              {
                "category": "QueryStoreRuntimeStatistics",
                "enabled": true
              },
              {
                "category": "QueryStoreWaitStatistics",
                "enabled": true
              },
              {
                "category": "Errors",
                "enabled": true
              },
              {
                "category": "DatabaseWaitStatistics",
                "enabled": true
              },
              {
                "category": "Timeouts",
                "enabled": true
              },
              {
                "category": "Blocks",
                "enabled": true
              },
              {
                "category": "Deadlocks",
                "enabled": true
              },
			  {
                "category": "DevOpsOperationsAudit",
                "enabled": true
              },
              {
                "category": "SQLSecurityAuditEvents",
                "enabled": true
              }
            ],
            "metrics": [
              {
                "category": "Basic",
                "enabled": true
              },
              {
                "category": "InstanceAndAppAdvanced",
                "enabled": true
              },
              {
                "category": "WorkloadManagement",
                "enabled": true
              }
            ]
          }
        }
    ]
}

**Comment by AISeanAshton** [comment]
Awesome, will give this a try. Thanks for the great examples

**Comment by nehakulkarni123** [comment]
Due to above exchange with a given template in response to the question, I will now close this issue.
