### ISSUE TITLE
"Windows machines should meet requirements for 'User Rights Assignment' " is returning non compliant 

### ISSUE THREAD

**Issue by jagadish222** [Azure/azure-policy#796]
Details on the issue:
I have set all the "User Rights Assignment" to the expected values from the policy but its still showing as non compliant.

Please go through the screen shot of my settings for user rights assignments

![user_rights_assignment](https://user-images.githubusercontent.com/37695042/126466942-3430ccc4-0907-4246-80de-bab0318d458d.png)

**Comment by nehakulkarni123** [comment]
Hi @jagadish222, if this issue is persisting and you need investigation into why it is non-compliant, please create an Azure support ticket. Feel free to reopen if you have any additional questions.
