### ISSUE TITLE
Alias Request: "Microsoft.SqlVirtualMachine/sqlVirtualMachines/sqlServerLicenseType"

### ISSUE THREAD

**Issue by vaibhavgujral** [Azure/azure-policy#799]
Scenario: **Audit if Hybrid Benefit is enabled on all SQL virtual machines**

Alias
Resource Provider: **Microsoft.SqlVirtualMachine**
Resource Type: **sqlVirtualMachines**
Property: **properties.sqlServerLicenseType**

Sample Policy:
```
{
  "mode": "All",
  "policyRule": {
    "if": {
      "anyOf": [
        {
          "allOf": [
            {
              "field": "type",
              "equals": "Microsoft.SqlVirtualMachine/sqlVirtualMachines"
            },
            {
              "allOf": [
                {
                  "field": "Microsoft.SqlVirtualMachine/sqlServerLicenseType",
                  "notEquals": "AHUB"
                }
              ]
            }
          ]
        }
      ]
    },
    "then": {
      "effect": "[parameters('effect')]"
    }
  },
  "parameters": {
    "effect": {
      "type": "String",
      "metadata": {
        "displayName": "Effect",
        "description": "Enable or disable the execution of the policy"
      },
      "allowedValues": [
        "audit",
        "auditIfNotExists",
        "disabled"
      ],
      "defaultValue": "audit"
    }
  }
}

**Comment by nehakulkarni123** [comment]
Hi Vaibhav, "Microsoft.SqlVirtualMachine/SqlVirtualMachines/sqlServerLicenseType" is a current alias. You can use the steps to find all available aliases [here](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#aliases). Looking at your policy definition, you would not be able to include 'auditIfNotExists' as an allowed value (see documentation on our effects [here](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/effects)). If you are experiencing other issues with your policy, please create an Azure support ticket.
