### ISSUE TITLE
Alias Request: microsoft.network/virtualnetworks/virtualNetworkPeerings

### ISSUE THREAD

**Issue by ezlbrmn** [Azure/azure-policy#80]
Scenario: we are checking compliance with following security requirement: VNET peering must not be enabled  or enabled only between owned/approved VNETs
Definition TBD

**Comment by pilor** [comment]
`Microsoft.Network/virtualNetworks/virtualNetworkPeerings/remoteVirtualNetwork.id` exists today.  If you need something more please let us know.
