### ISSUE TITLE
Alias Request: microsoft.network/virtualnetworks/subnets/serviceEndpoints

### ISSUE THREAD

**Issue by ezlbrmn** [Azure/azure-policy#81]
Scenario: we are checking compliance with following security requirement: To connect to Azure SQL from VNETs the use of SQL endpoint is mandatory 
Definition: TBD

**Comment by pilor** [comment]
The following aliases are now available:

```
Microsoft.Network/virtualNetworks/subnets/serviceEndpoints[*].locations[*]
Microsoft.Network/virtualNetworks/subnets/serviceEndpoints[*].service
```
