### ISSUE TITLE
Adding SSL Enforcement Azure policy for Postgresql server affects on Public-network access

### ISSUE THREAD

**Issue by Mina69** [Azure/azure-policy#811]
ISSUE TITLE:
    Adding SSL Enforcement Azure policy for Postgresql server affects on Public-network access. 

    ISSUE DESCRIPTION (this template):
    After enabling the policy, applying changes on "Deny public network access" option would give an error that it is denied by the policy.

Policy definition:

 ```
{
  "if": {
    "anyof": [
    {  
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.DBforPostgreSQL/servers"
        },
        {
          "field": "Microsoft.DBforPostgreSQL/servers/sslEnforcement",
          "exists": "true"
        },
        {
          "field": "Microsoft.DBforPostgreSQL/servers/minimalTlsVersion",
          "notEquals": "1.2"
        }
      ]
    },
    {  
      "allof": [
        {
          "field": "type",
          "equals": "Microsoft.DBforPostgreSQL/servers"
        },
        {
          "field": "Microsoft.DBforPostgreSQL/servers/sslEnforcement",
          "exists": "true"
        },
        {
          "field": "Microsoft.DBforPostgreSQL/servers/sslEnforcement",
          "notEquals": "Enabled"
        }
      ]
    }]
},
"then": {
  "effect": "[parameters('effect')]"
}
}
```

By clicking on Yes/No for "Deny public network access" in Postgresql server , I get an error that it is disallowed by that policy. 
If I disable the policy changes on that option would work fine.

The question is that why SSL policy should affect on public-access setup and how to prevent this issue?

**Comment by nehakulkarni123** [comment]
Hi, I'll check in with the PostgreSQL team and follow-up. If this is a built-in definition, can you provide the policy display name please?

**Comment by Mina69** [comment]
Hi @nehakulkarni123 , very nice. thanks. Looking forward to hear about that.  This is not a build-in policy. This is a policy that I've created to check SSL status in Postgresql server based on some azure documents.

**Comment by nehakulkarni123** [comment]
I see, thank you. For help fixing the policy, kindly submit a support ticket so that PostgreSQL can help you identify the best approach.
