### ISSUE TITLE
built-in-policies/policyDefinitions/Tags/InheritTag_Add_Modify.json gives contributor rights

### ISSUE THREAD

**Issue by Urglefloggah666** [Azure/azure-policy#812]
with the concept of least privilege in mind, should this policy be changed to use the built-in role "Tag Contributor" instead of "Contributor"?

**Comment by pilor** [comment]
Tag policies that were introduced after Tag Contributor was implemented utilize that role definition (i.e. https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Tags/AddTag_Subscription_Modify.json).  However, changing the role definition on an existing built-in policy would cause assignments of that built-in to think they need a new role assignment (when viewed in the portal) when they don't.  Future features may allow this change to be made without impacting existing assignments but at the moment its not clean enough to warrant making the change.

In the meantime duplicating the definition and changing the role definition (or removing it) is a reasonable approach if needed.
