### ISSUE TITLE
Kubernetes allowed container images to allow Array of multiple allowedContainerImagesRegex instead of one string

### ISSUE THREAD

**Issue by rjnmylife** [Azure/azure-policy#817]
Kubernetes cluster containers should only use allowed images should allow multiple Container Registry namespaces instead of single namespace.

The current Builtin policy, Kubernetes cluster containers should only use allowed images, allows us to pass a string wherein we can whitelist ACR registry by passing ^.+azurecr.io/.+$ value. However, can we pass multiple such values for other third party clouds such as ECR, GCR and also Docker hub, in addition to ACR? The current definition relies on the ContstraintTemplate yaml file which passes a String parameter. Is there a support for Array to pass multiple?

**Comment by nehakulkarni123** [comment]
Yes, you can do this today. You can use the '|' symbol to pass in multiple values as well as pass in values from third party value. Alternatively, you can use custom policy (now in [public preview](https://techcommunity.microsoft.com/t5/azure-governance-and-management/azure-policy-for-kubernetes-releases-support-for-custom-policy/ba-p/2699466)) to adjust the constraint template to take in an array parameter. 

Here's an example of what it would look like using the pipe:
^(docker\.io|quay\.io|k8s\.gcr\.io|.+azurecr\.io).*$
