### ISSUE TITLE
Support to manage parameter value inside jSON file

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#82]
Saying that I would like to allow a few subnets with public IP addresses similar to the following example

```
{
	"if": {
		"allOf": [
			{
				"field": "type",
				"equals": "Microsoft.Network/networkInterfaces"
			},
			{
				"not": {
					"field": "Microsoft.Network/networkInterfaces/ipconfigurations[*].publicIpAddress.id",
					"exists": false
				}
			},
			{
				"not": {
					"field": "Microsoft.Network/networkInterfaces/ipconfigurations[*].subnet.id",
					"in": "[parameters('subnetIds')]"
				}
			}
		]
	},
	"then": {
		"effect": "deny"
	}
}
```

Is there a backlog that Microsoft supports adding whitelist directly in my JSON definition? It is similar to strongType location which allows me to do as follows:

```
      {
        "field": "location",
        "notIn": [
          "southeastasia"
          "westeurope",
        ]
      },
```

@pilor

**Comment by pilor** [comment]
Sorry, I don't fully understand the question.  Do you want to provide a list of "acceptable values" for the "subnetIds" parameter to make it easier for users to assign the policy in the UX?

If so, you can accomplish that with the following:
```
"parameters": {
   "subnetIds": {
      "type": "array",
      "allowedValues": ["id1", "id2"]
   }
}
```

**Comment by thuansoldier** [comment]
@pilor  this does the work partially. The one you suggest is wonderful, but it only creates a choice. What I need is something like

```
"parameters": {
   "subnetIds": {
      "type": "array",
      "values": ["id1", "id2"]
   }
}
```
After deploying the template, all id1 and id2 are selected so I don't have to go to Azure Portal to check their boxes.

Thank you!

**Comment by pilor** [comment]
If you don't want them to be parameterized you can change the policy to this:
```
{
  "not": {
    "field": "Microsoft.Network/networkInterfaces/ipconfigurations[*].subnet.id",
    "in": ["id1", "id2"]
  }
}
```

If you want it to still be parameterized but have all the "allowedValues" checked by default you can use the below "defaultValue" specification.  This won't be reflected in the UX yet but will do the right thing if someone is assigning the policy programatically (PS/CLI/etc...).  The UX will start being defaultValue aware "soon".

```
"parameters": {
   "subnetIds": {
      "type": "array",
      "allowedValues": ["id1", "id2"],
      "defaultValue": ["id1", "id2"]
   }
}
```

**Comment by thuansoldier** [comment]
@pilor  Thank you very much for the new property called **defaultValue** introduced. Hopefully it goes to Azure Portal so testing would be faster.
