### ISSUE TITLE
CIS 1.1.0 Policy Ensure the storage container storing the activity logs is not publicly accessible does not work

### ISSUE THREAD

**Issue by gavhooper** [Azure/azure-policy#825]
Hi,
When using CIS 1.1.0 the control: "Ensure the storage container storing the activity logs is not publicly accessible" 

it uses the policy: "Storage account public access should be disallowed" 

As you can see the policy doesn't do exactly what the control suggests, it will flag up every storage account that is publicly accessible. It doesn't check to see if the storage account is actually storing activity logs. It is also not possible to exempt resources from this policy as it will affect other initiatives using that policy.

**Comment by nehakulkarni123** [comment]
Adding @jomolesk to determine how to adjust control description

**Comment by jomolesk** [comment]
Hi @gavhooper -- You are correct that this policy checks all storage accounts. There is currently no policy that checks specifically storage accounts that contain activity logs, so the more general policy is included. You could exempt specific resources from the CIS initiative assignment if this is causing issues for your scenario (for example, using the waiver exemption category, and including storage accounts that do not contain activity logs). This would not impact use of the same policy in other assignments. More on exemptions here: https://docs.microsoft.com/en-us/azure/governance/policy/concepts/exemption-structure

**Comment by nehakulkarni123** [comment]
I will close this item since John has provided an answer. If you have further questions, feel free to re-open or create a new issue.
