### ISSUE TITLE
Deploy Dependency agent for Linux Virtual machines policy not installing on Ubuntu 20.04-lts

### ISSUE THREAD

**Issue by pmatthews05** [Azure/azure-policy#829]
#### Details of the scenario you tried and the problem that is occurring
Built in policy [DependencyAgentExtension_Linux_VM_Deploy.json](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Monitoring/DependencyAgentExtension_Linux_VM_Deploy.json) does not install on Linux machines using the Ubuntu 20.04 LTS.

#### Verbose logs showing the problem
I have no logs.

#### Suggested solution to the issue
Update the policy rule to include Ubuntu 20.04 LTS around line 65.

**Comment by pmatthews05** [comment]
Not sure just updating the rule to include 20_04-lts is going to work. As I've just noticed the imageOffice I'm using is "0001-com-ubuntu-server-focal".

**Comment by nehakulkarni123** [comment]
Hi, I will check with the Monitoring team and follow up with any updates for you.

**Comment by jamesw4** [comment]
Just had this exact issue. It seems there are several policies not catching 20.04 LTS (all listed here https://github.com/Azure/azure-policy/search?q=18.04-LTS). Additionally it seems that the SKUs for Gen2 VM's have not been catered for. E.g. deploy gen 2 VM with 18.04-LTS and the SKU used it 18_04-lts-gen2. To be honest there looks to be similar issues for other distro's where the policy definitions have not kept up. I will raise another issue for this.

**Comment by shuft** [comment]
Any update on this, we also have some machines escaping policy :(

**Comment by JaimePalazuelosB** [comment]
Hi,

I had a similar issue with Guest Configuration policies, and it is because
the image offer for Ubuntu 20.04 has a different naming convention.

This is the code for Canonical publisher offers, where I have added what
would be the condition for the Ubuntu 20.04 offer:

{
                "allOf": [
                  {
                    "field": "Microsoft.Compute/imagePublisher",
                    "equals": "Canonical"
                  },
                  {
                    "field": "Microsoft.Compute/imageOffer",
                    "equals": "UbuntuServer"
                  },
                  {
                    "anyOf": [
                      {
                        "field": "Microsoft.Compute/imageSKU",
                        "in": [
                          "14.04.0-LTS",
                          "14.04.1-LTS",
                          "14.04.5-LTS"
                        ]
                      },
                      {
                        "field": "Microsoft.Compute/imageSKU",
                        "in": [
                          "16.04-LTS",
                          "16.04.0-LTS"
                        ]
                      },
                      {
                        "field": "Microsoft.Compute/imageSKU",
                        "in": [
                          "18.04-LTS"
                        ]
                      }
                                                            ,{
                                                                "field":
"Microsoft.Compute/imageOffer",
                                                                "in": [
"0001-com-ubuntu-server-focal"]
                                                            }
                    ]
                  }
                ]
              },

Kind regards,

Jaime

**Comment by kenieva** [comment]
Thank you @JaimePalazuelosB for providing a solution to this!

**Comment by jamesw4** [comment]
Why has this been closed?? @JaimePalazuelosB kindly provided the solution but no one has taken this and used it to fix the built in policy definition?

**Comment by kenieva** [comment]
Contacting the policy definition owners....
