### ISSUE TITLE
Alias request: Microsoft.Web/serverfarms

### ISSUE THREAD

**Issue by milannankov** [Azure/azure-policy#83]
I would like to be able to control the specifics of the plan that web apps are using. I couldn't find an existing aliases for Microsoft.Web/serverfarms which will allow for that.

https://docs.microsoft.com/en-us/azure/templates/microsoft.web/serverfarms

I think that the sku property is the main one that is missing.

**Comment by pilor** [comment]
The following 2 aliases exist:
```
Microsoft.Web/serverfarms/sku.name
Microsoft.Web/serverfarms/sku.capacity
```

Do they accomplish what you need?

**Comment by milannankov** [comment]
Yes, that is perfect. I didn't realize that those aliases are available. Maybe it would be great if we add links to the root readme.md on how people can check for the existing aliases before requesting a new ones - https://docs.microsoft.com/en-us/azure/azure-policy/policy-definition#aliases

**Comment by pilor** [comment]
Good suggestion, will do.
