### ISSUE TITLE
Alias request: Microsoft.compute/virtualMachines/networkInterfaces

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#84]
**Scenario**

There is a scenario in which controlled virtual machines should not have any Public IP addresses associated with its relatively NICs. 

**Definition** 

```
{
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Network/networkInterfaces"
        },
        {
          "not": {
            "field": "Microsoft.Network/networkInterfaces/ipconfigurations[*].publicIpAddress.id",
            "exists": false
          }
        },
        {
            "field":"type",
            "equals": "Microsoft.Compute/virtualMachine/networkProfile[*].networkInterfaces.id"
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  }
```
**Remark**

Currently Azure Policy supports listing out all NICs with PIP (Public IP) but I'd love to know which non-compliant VMs are in place. 

[**Update**] I also tested with NIC field`` as follows:

```
        {
            "not":{
            "field":"Microsoft.Compute/virtualMachines/networkInterfaces[*].id",
            "exists": false
            }
        }

```

But it seems like the result is not going to be out as expected (displaying non-compliant VMs)

@pilor

**Comment by pilor** [comment]
Unfortunately, policy doesn't currently support de-referencing IDs in a resource and performing additional checks on the referenced resource.  Right now the best you can do is flag the NICs that are non-compliant.

This is a feature that may be added at some point in the future but I don't have a timeline to share.
