### ISSUE TITLE
AKS Restricted Pod Security initiative: Customizing included policies

### ISSUE THREAD

**Issue by asankaf** [Azure/azure-policy#847]
We've noticed one of the policies included in the initiative "Kubernetes cluster pod security restricted standards for Linux-based workloads" shows non-compliant status. The policy in question is "Kubernetes cluster pods and containers should only run with approved user and group IDs". As of now, we can't adjust the parameters of each individual policy inside an initiative. That's the reason for the non-compliant status in our case. We tried adding the same policy as an individual policy with the correct parameters and it seems to work fine. But still, inside the Initiative, it shows the policy as non-compliant. Is there any way we can customize the included policies in an initiative (like configuring the parameters)?

**Comment by nehakulkarni123** [comment]
Hi @asankaf, if you are looking to change the values of certain parameters, you should be able to do this with the initiative as if. 

For further customization, we recommend that you duplicate the initiative as a custom initiative and customize it to your organization's needs.
