### ISSUE TITLE
Alias Request: Microsoft.Insights/DiagnosticSettings[*]/eventHubAuthorizationRuleId for Storage account sub services

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/azure-policy#855]
Scenario: We're trying to create a DeployIfNotExists policy that configures the new diagnostic settings configurations for each of the storage account elements. (File, Blob, Table, Queue)  When assessing the eventhub rule id the policy rule fails even when the eventhubruleID is properly set and generates a compliance error indicating that the value has not been set.  I suspect this is due to the current alias being aligned with the root storage account, while the configuration is against the sub-resource. 

The relevant part of the policy I'm using for configuration is as follows:
`{
    "mode": "All",
    "policyRule": {
        "if": {
            "field": "type",
            "equals": "Microsoft.Storage/storageAccounts"
        },
        "then": {
            "effect": "[parameters('effect')]",
            "details": {
                "type": "Microsoft.Storage/storageAccounts/tableServices",
                "roleDefinitionIds": [
                    "/providers/microsoft.authorization/roleDefinitions/749f88d5-cbae-40b8-bcfc-e573ddc772fa",
                    "/providers/microsoft.authorization/roleDefinitions/f526a384-b230-433a-b45c-95f59c4a2dec",
                    "/providers/microsoft.authorization/roleDefinitions/7f6c6a51-bcf8-42ba-9220-52d62157d7db"
                ],
                "existenceCondition": {
                    "allOf": [
                        {
                            "field": "Microsoft.Insights/diagnosticSettings/eventHubAuthorizationRuleId",
                            "equals": "[parameters('eventHubRuleId')]"
                        }
                     ]`

Requested Change:

Because we're referencing Microsoft.Storage/StorageAccount/TableServices instead of Microsoft.Storage/StorageAccount I suspect an alias like "Microsoft.Insights/diagnosticSettings/[*]/eventHubAuthorizationRuleId" or updating the current alias Microsoft.Insights/diagnosticSettings/eventHubAuthorizationRuleId to include the subresources would work.  I haven't tested the other Diagnostic setting target types, but suspect that having a similar configuration for them would also be required.

**Comment by kenieva** [comment]
Hi @jchancellor-ms  for help with a custom policy definition, please contact Azure support center. Thank you.
