### ISSUE TITLE
[Preview]: Sensitive data in your SQL databases should be classified should exclude the master database

### ISSUE THREAD

**Issue by bshamster1** [Azure/azure-policy#857]
When policy definition "[Preview]: Sensitive data in your SQL databases should be classified" checks the master database on an Azure SQL Server it comes back with a compliance reason of NotFound. However, we are unable to actually enable or disable data classification on the master database. Can this database be excluded from the definition without having to rely on creating policy exemptions?

**Comment by kenieva** [comment]
It seems that this definition has been removed from built-ins.
