### ISSUE TITLE
Synapse Private DNS Auto Deployment: Collision with Cosmos DB Subgroup

### ISSUE THREAD

**Issue by cloudchristoph** [Azure/azure-policy#858]
https://github.com/Azure/azure-policy/blob/b809e7ad6c38be290d093ef5c76f53afe6a076ee/built-in-policies/policyDefinitions/Synapse/SynapseWorkspaceUsePrivateDnsZones_DeployIfNotExists.json#L28

Because this Policy Definition does not check for the serviceId it would deploy an DNS entry for a Cosmos DB because Cosmos is also using "sql" as a subgroup.

Suggestion would be to add a serviceId check like in the ["Configure Cognitive Services accounts to use private DNS zones"](https://www.azadvertizer.net/azpolicyadvertizer/c4bc6f10-cb41-49eb-b000-d5ab82e2a091.html) policy.

**Comment by kenieva** [comment]
Contacting team owners on this issue....

**Comment by kenieva** [comment]
This definition has been updated.
