### ISSUE TITLE
Several policy definitions do not cater for Ubuntu Gen2 image SKU's

### ISSUE THREAD

**Issue by jamesw4** [Azure/azure-policy#860]
#### Details of the scenario you tried and the problem that is occurring

Several policies are not applying to gen2 Ubuntu VM's. See all policies in this list - https://github.com/Azure/azure-policy/search?q=18.04-LTS.

Gen 2 VM's for Ubuntu end up with a different SKU that is not included in this policy. E.g. 18_04-lts-gen2

#### Verbose logs showing the problem

N/A

#### Suggested solution to the issue

Update policy definition - see how its been done in this policy for Ubuntu - https://github.com/Azure/azure-policy/blob/19ca0d8cbc7af9cd1dd8562f0a14f15db288dd79/built-in-policies/policyDefinitions/Security%20Center/ASC_AzureSecurityLinuxAgent_AuditIfNotExists.json

**Comment by kenieva** [comment]
Some of these have been updated or deprecated. Thank you.
