### ISSUE TITLE
need to deny creation of appservice which has FTPS State = " All Allowed" as its value. Policy doesn't work

### ISSUE THREAD

**Issue by Kumudha1990** [Azure/azure-policy#864]
Hi,
 I am trying to deny creation of appservice through azure policy ( condition FTPS State = "All Allowed")

tried 2 policies

1.
==================================================

"policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "not": {
            "allOf": [
              {
                "anyOf": [
                  {
                    "field": "Microsoft.Web/sites/config/web.ftpsState",
                    "equals": "FtpsOnly"
                  }
                ]
              },
              {
                "anyOf": [
                  {
                    "field": "Microsoft.Web/sites/config/web.ftpsState",
                    "equals": "Disabled"
                  }
                ]
              }
            ]
          }
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  },

=====================================================================

{
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites/config"
        },
        {
          "field": "Microsoft.Web/sites/config/ftpsState",
          "equals": "AllAllowed"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }

neither one is working. its not denying the creation of appservice. no error as well.

any clues are welcome !

Thanks,

**Comment by continue47** [comment]
```
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "exists": "Microsoft.Web/sites"
        },
        {
          "field": "Microsoft.Web/sites/siteConfig.ftpsState",
          "equals": "AllAllowed"
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  }
}
```

This policy should deny changing the FTP State to "All Allowed". I tested it and it worked.

**Comment by nehakulkarni123** [comment]
Thanks @continue47! @Kumudha1990, feel free to re-open this issue if you have any additional questions-- otherwise, I will close this out.
