### ISSUE TITLE
Alias request: Microsoft.Network/virtualNetworks/addressSpace

### ISSUE THREAD

**Issue by nilanjandas79** [Azure/azure-policy#87]
Scenario

Would like to be able to create policies to deny Virtual Network creation in a specific addressSpace
For example see below:

{
    "type": "Microsoft.Authorization/policyDefinitions",
    "name": "disallow-vnet-address-space",
    "properties": {
        "displayName": "Disallow certain Vnet address Space",
        "description": "This policy disallows specified address Spaces for Virtual Network",
        "parameters": {
            "addrPrefix": {
                "type": "Array",
                "metadata": {
                    "description": "Virtual Network Address Spaces [comma separated]",
                    "displayName": "AddressSpaces"
                }
            }
        },
        "policyRule": {
            "if": {
                "anyOf": [
                    {
                        "allOf": [
                            {
                                "field": "type",
                                "equals": "Microsoft.Network/virtualNetworks"
                            },
                            {
                                "field": "Microsoft.Network/virtualNetworks/addressSpace",
                                "in": "[parameters('addrPrefix')]"
                            }
                        ]
                    }
                ]
            },
            "then": {
                "effect": "deny"
            }
        }
    }
}

**Comment by nilanjandas79** [comment]
Is there any ETA on this?

**Comment by pilor** [comment]
I don't have a solid ETA.  It has been authored and is in Microsoft.Network's pipeline for deployment.

**Comment by nilano365** [comment]
@erjadi , I believe my requirement is for entire VNET

**Comment by pilor** [comment]
`Microsoft.Network/virtualNetworks/addressSpace.addressPrefixes[*]`  is now available
