### ISSUE TITLE
Ingress Http Only Policy Error

### ISSUE THREAD

**Issue by pccrdotnet** [Azure/azure-policy#880]
When I try to use  this policy https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/IngressHttpsOnly.json with CmdLet **New-AzPolicyAssignment** the process at the final show an error:

New-AzPolicyDefinition: InvalidPolicyRuleEffectDetails : The policy definition 'ingress-https-only' rule is invalid. The policy effect 'details' property could not be parsed.

I tried getting more information about the error, but I do not understand why failed.

**Comment by pilor** [comment]
What is the full new-azpolicydefinition command that you are using?

**Comment by pccrdotnet** [comment]
Thank you for your time, the command was the next lines:

$name = "name-policy"
$rules = "policy.rules.json"
$params = "policy.parameters.json"
$assign = "policy.assign.json"
New-AzPolicyDefinition -Name $name -Policy $rules -Parameter $params

The policy.rules.json has the policy:

{
  "if": {
    "field": "type",
    "in": [
      "AKS Engine",
      "Microsoft.Kubernetes/connectedClusters",
      "Microsoft.ContainerService/managedClusters"
    ]
  },
  "then": {
    "effect": "[parameters('effect')]",
    "details": {
      "constraintTemplate": "https://store.policy.core.windows.net/kubernetes/container-no-privilege-escalation/v2/template.yaml",
      "constraint": "https://store.policy.core.windows.net/kubernetes/container-no-privilege-escalation/v2/constraint.yaml",
      "excludedNamespaces": "[parameters('excludedNamespaces')]",
      "namespaces": "[parameters('namespaces')]",
      "labelSelector": "[parameters('labelSelector')]",
      "values": {
        "excludedContainers": "[parameters('excludedContainers')]"
      }
    }
  }
}

**Comment by pilor** [comment]
You need to set the "-mode" of the policy definition in new-azpolicydefinition. The mode can be seen in properties.mode in the file linked in your original comment.

**Comment by pccrdotnet** [comment]
Thank you for your message, I set the parameter mode up with AKS options, -Mode "Microsoft.Kubernetes.Data" it work fine.
