### ISSUE TITLE
deny-nsg-inbound-allow-all - doesnt seem to be working as expected

### ISSUE THREAD

**Issue by asifkd012020** [Azure/azure-policy#883]
https://github.com/Azure/azure-policy/blob/master/samples/Network/deny-nsg-inbound-allow-all/azurepolicy.json

I have tried to implement this policy in deny mode and  I was able to create rules with any(*) source on inbound rules in NSG from Azure Portal.

Is this expected or there is a bug in the policy?

**Comment by kenieva** [comment]
This is old sample policy written in 2018 so it is likely that policy no longer works due to changes in NSGs.
