### ISSUE TITLE
AllowedHostPaths policy doesn't exclude containers from policy evaluation even though excludedContainers list is used

### ISSUE THREAD

**Issue by AshutoshNirkhe** [Azure/azure-policy#884]
I have created an initiative which holds all Kubernetes BuiltIn policies. We want to exclude some containers (mainly Daemonset pod containers) from Policy evaluation. While checking through some of the Policy definitions like AllowedHostPaths.json , we saw a parameter called 'excludedContainers'. We are passing those containers list to this parameter. But policy doesn't seem to respect the exclusion and is flagging all pods including those in excludedContainers. 

excludedContainers=["fluent-bit", "fluentbit", "node-exporter", "secrets-store", "provider-azure-installer", "node-driver-registrar"]
I haven't overridden any other policy parameters. What could be the issue/how can we debug such problems ?

**Comment by fseldow** [comment]
Hi @AshutoshNirkhe , 

The issue is that 'volumes' is one spec out of container level. So `excludedContainers` parameter in this policy might be bit different from other policies, it will only exclude one scenario: The readonly is set true, however the allowed hostpath is mounted as write.

The parameter description in this policy is not precise, will update it. 

For your scenario, my suggestion is to try parameter `excludedNamespaces`. Hope it may help.

**Comment by AshutoshNirkhe** [comment]
> Hi @AshutoshNirkhe ,
> 
> The issue is that 'volumes' is one pod level spec out of container. So `excludedContainers` parameter in this policy might be bit different from other policies, it will only exclude one scenario: The readonly is set true, however the allowed hostpath is mounted as write in certain container.
> 
> The parameter description in this policy is not precise, will update it.
> 
> For your scenario, my suggestion is to try parameter `excludedNamespaces` or `labelSelector`. Hope it may help.

Thanks @fseldow I see. labelSelector is useful if you only have a handful of resources that you want policy to evluate. So the only wider option we are left with is excludedNamespaces here. 
I hope 'excludedContainers' should work for most of other policies though, right ?

**Comment by fseldow** [comment]
> > Hi @AshutoshNirkhe ,
> > The issue is that 'volumes' is one pod level spec out of container. So `excludedContainers` parameter in this policy might be bit different from other policies, it will only exclude one scenario: The readonly is set true, however the allowed hostpath is mounted as write in certain container.
> > The parameter description in this policy is not precise, will update it.
> > For your scenario, my suggestion is to try parameter `excludedNamespaces` or `labelSelector`. Hope it may help.
> 
> Thanks @fseldow I see. labelSelector is useful if you only have a handful of resources that you want policy to evaluate. So the only wider option we are left with is excludedNamespaces here. I hope 'excludedContainers' should work for most of other policies though, right ?

Correct, it works for container related policies. `HostPath` is one special case. sorry for confusing you.

**Comment by AshutoshNirkhe** [comment]
> > > Hi @AshutoshNirkhe ,
> > > The issue is that 'volumes' is one pod level spec out of container. So `excludedContainers` parameter in this policy might be bit different from other policies, it will only exclude one scenario: The readonly is set true, however the allowed hostpath is mounted as write in certain container.
> > > The parameter description in this policy is not precise, will update it.
> > > For your scenario, my suggestion is to try parameter `excludedNamespaces` or `labelSelector`. Hope it may help.
> > 
> > 
> > Thanks @fseldow I see. labelSelector is useful if you only have a handful of resources that you want policy to evaluate. So the only wider option we are left with is excludedNamespaces here. I hope 'excludedContainers' should work for most of other policies though, right ?
> 
> Correct, it works for container related policies. `HostPath` is one special case. sorry for confusing you.

No worries and thanks got getting back on this!

**Comment by AshutoshNirkhe** [comment]
> > > Hi @AshutoshNirkhe ,
> > > The issue is that 'volumes' is one pod level spec out of container. So `excludedContainers` parameter in this policy might be bit different from other policies, it will only exclude one scenario: The readonly is set true, however the allowed hostpath is mounted as write in certain container.
> > > The parameter description in this policy is not precise, will update it.
> > > For your scenario, my suggestion is to try parameter `excludedNamespaces` or `labelSelector`. Hope it may help.
> > 
> > 
> > Thanks @fseldow I see. labelSelector is useful if you only have a handful of resources that you want policy to evaluate. So the only wider option we are left with is excludedNamespaces here. I hope 'excludedContainers' should work for most of other policies though, right ?
> 
> Correct, it works for container related policies. `HostPath` is one special case. sorry for confusing you.

@fseldow does it work for HostNetworkPorts policy ? https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/HostNetworkPorts.json#L128

**Comment by AshutoshNirkhe** [comment]
> > > > Hi @AshutoshNirkhe ,
> > > > The issue is that 'volumes' is one pod level spec out of container. So `excludedContainers` parameter in this policy might be bit different from other policies, it will only exclude one scenario: The readonly is set true, however the allowed hostpath is mounted as write in certain container.
> > > > The parameter description in this policy is not precise, will update it.
> > > > For your scenario, my suggestion is to try parameter `excludedNamespaces` or `labelSelector`. Hope it may help.
> > > 
> > > 
> > > Thanks @fseldow I see. labelSelector is useful if you only have a handful of resources that you want policy to evaluate. So the only wider option we are left with is excludedNamespaces here. I hope 'excludedContainers' should work for most of other policies though, right ?
> > 
> > 
> > Correct, it works for container related policies. `HostPath` is one special case. sorry for confusing you.
> 
> @fseldow does excludedContainers parameter work for HostNetworkPorts policy ? https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/HostNetworkPorts.json#L128

@fseldow also another issue regarding usage of allowedHostPaths is that if we provide few paths say ["/var/lib/kubelet", "/var/lib/docker"] which are intended to be used only by few of our Infra containers and not Application containers, there isn't any way to specify this configuration. So if I specify those 2 paths, anybody can use them which is not expected. Shall I raise a separate enhancement request ticket for that ?

**Comment by fseldow** [comment]
Hi @AshutoshNirkhe sorry for late response.
1. excludedContainers works for HostNetworkPorts
2. Correct that we currently do not have way to specify this configuration, if the Infra containers and application containers are in the same namespace.

**Comment by AshutoshNirkhe** [comment]
> Hi @AshutoshNirkhe sorry for late response.
> 
> 1. excludedContainers works for HostNetworkPorts
> 2. Correct that we currently do not have way to specify this configuration, if the Infra containers and application containers are in the same namespace.

Hi @fseldow I tried excludedContainers for HostNetworkPorts policy and its working fin, but thanks for the confirmation. I guess I will raise a separate issue for enhancement part to be considered for future policy releases. Closing, thanks.
