### ISSUE TITLE
Capitalisation of Policy allowed effect types is inconsistent

### ISSUE THREAD

**Issue by tap1992** [Azure/azure-policy#885]
#### Details of the scenario you tried and the problem that is occurring

Using a Infrastructure as code tool, we have been trying to create multiple Policies at once using the built-in definations, unfortunaltey due to the capitalisation of the allowed effect types (e.g. Deny or deny) it makes it very hard without having to manually define the capitalisation per policy.

#### Verbose logs showing the problem

No logs but the varying capitalisation can be seen on the two Policys below:
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/AKS_DisableLocalAccounts_Deny.json - Capital Deny
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/ContainerResourceLimits.json - lower-case deny.

#### Suggested solution to the issue

Match all effect's capitalisations in the allowed effects, or remove case sensativity.

-->

**Comment by pilor** [comment]
There are some older policies that use inconsistent casing which can't be fixed as it would break back-compat.  We have been validating that all new built-ins use pascal-cased effect parameter values for a while now so you won't see this moving forward.

There may be features in the future that will allow a breaking change in the casing in these policies but for now the existing policies cannot be changed (making allowedValues case-insensitive across the board is also a breaking change).
