### ISSUE TITLE
Azure policy "deny" effect doesn't work for resources created by Azure DevOps

### ISSUE THREAD

**Issue by jakubramut** [Azure/azure-policy#886]
#### Details of the scenario you tried and the problem that is occurring

We have a policy with "Deny" effect when the newly created RG(resource group) doesn't have specific tag.
Policy works fine when we try to create resources from arm/tf/portal (still the same api), but when we create the organization from Azure DevOps then it is created as a part of new RG in a specific subscription.
The newly created RG doesn't have required tag, but everything completes correctly, and the new organization + rg have been created.
The policy have worked for a long time, and already caught a couple of events but when Azure DevOps does the thing then the policy is ignored.
I tried to check the docs but there's no information regarding some possible exceptions for policy effects.
I read the documentation about known limitations but didn't find any mentions about Azure DevOps.

The policy has been created based on the one of the existing policies: 
https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F8ce3da23-7156-49e4-b145-24f95f9dcb46

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/56309429/149312320-11bc3ab0-8c3a-4e04-9ebc-811311b309ff.png)

![image](https://user-images.githubusercontent.com/56309429/149312439-4cd16e71-6b3d-40e6-ab03-6caee6ba6476.png)

![image](https://user-images.githubusercontent.com/56309429/149312657-b0cd95dc-d01d-4176-a45a-683f472cc9b5.png)

**Comment by kenieva** [comment]
Hi @jakubramut , are you able to create a support ticket on this? We will need to investigate the bug further. Thank you.
