### ISSUE TITLE
Allowed values extend with deny option

### ISSUE THREAD

**Issue by gudszent** [Azure/azure-policy#893]
Hi, 

Do you plan to extend the allowed values with deny option in this policy?
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Compute/Disks_ExportLimitNetworkAccess_Audit.json

I find 3 other policy, where should be there the deny.

BR
O.

**Comment by kenieva** [comment]
Hi @gudszent , at the current moment, there are no known plan to update these definitions to support deny. If you wish to use an deny effect, please customize the definition. Thank you.
