### ISSUE TITLE
Azure Security Benchmark Regulatory Compliance built-in initiative

### ISSUE THREAD

**Issue by guidovbrakel** [Azure/azure-policy#897]
In the Azure Security Benchmark Regulatory Compliance built-in initiative azure policy imitative a lot policy definitions have an audit or auditifnotexists effect. I would like to have them changed to Deny, that requires a lot of work of creating custom policies, and sometimes the effect is not available in the definition itself. Would it possible to have two initiaves, one with mainly audit effects, and another one with mainly Deny effects?
This is one is the one I'm talking about: https://docs.microsoft.com/en-us/azure/governance/policy/samples/azure-security-benchmark

**Comment by kenieva** [comment]
Forwarding this request to the Azure Security team....

**Comment by ronitr** [comment]
@guidovbrakel  -- the product team is working on a "secure by default" initiative to support enforcement for as many ASB policies as possible. In time, you should be seeing more built-in policies that support Deny, and indeed an 'enforcement' mode for the Azure Security Benchmark. Please stay tuned for more updates in this area in the coming months. Thanks!
