### ISSUE TITLE
fullName documentation is vague

### ISSUE THREAD

**Issue by byron70** [Azure/azure-policy#90]
Attempting to use fullName to restrict resources within particular set of management resource groups.

The documentation is a bit vague ```Returns the full name of the resource, including any parents (for example "myServer/myDatabase")```.  I take this could possibly be the resource ID, for instance, `/subscriptions/27bc029f-.../resourceGroups/CD--MGMT/providers/Microsoft.Network/networkInterfaces/vmw-mgmt-jump0161`

This is not working for me.
```
{
	"if": {
		"allOf": [
			{
				"field": "type",
				"in": [
					"Microsoft.Resources/resources",
					"Microsoft.Resources/subscriptions/resources",
					"Microsoft.Resources/subscriptions/resourcegroups/resources"
				]
			},
			{
				"field": "fullName",
				"contains": "[parameters('resourceGroupPrefix')]"
			}
		]
	},
	"then": {
		"effect": "deny"
	}
}
```
1) Is the above possible, or would we have to add more granular conditions for each resource type? I do not see any aliases in the Microsoft.Resources namespace.

2) What is fullName, the ID of a resource or as the documentation implies something more abbreviated `db-server-01/myDB`?

3) Will there every be the ability to reference fields by the native attribute (I have not seen any examples to this regard) instead of an alias, such as `"field": "Microsoft.Resources/resources/id|resourceGroup|managedBy"`?  This seems like an easy win, even though a future API release may break an existing rule.  Perhaps being able to pin a policy definition to an API version in the json of the definition.

**Comment by pilor** [comment]
What is the policy's intent?  Is it trying to ensure that individual resources don't use a special prefix that is set aside for resourceGroups?

fullName returns the name of the resource, including names of any parent resources.  It looks exactly like the example given with the following format:  {parentName1}/{parentName2}/.../{resourceName}.  If a resource has no parent then fullName = name.  I'll try to reword the documentation to make that more clear.

We don't plan to allow arbitrary JSON paths in policy rules.  If a user can bypass policy by using an api-version with a different path it makes it much harder for users to govern their environments with policy.  We do plan to get much closer to 100% of properties having an equivalent alias though.

**Comment by byron70** [comment]
I can be a bit more specific with our use-case. 

We are a managed services provider for health care and are trying to work permissions and policy so customers can do self-service within their tenant subscriptions. We have a "managed" resource group within every customer subscription's where our managed resources live, hardened images, VM appliances, storage accounts, networking, etc. We have also created a variety of custom roles and used policy to enforce role assignments only to those custom roles.  

Ideally what we are trying to prevent is denying users write access to our management resource group.  We have been struggling with this, as we need to allow customer the ability to create resource groups. This seems to give a self-service admin role, access into our managed resource group, as we must scope the role assignment to the subscription in order to allow resource group creation. 

We thought a policy that inspects/audits every new resource ID (/subscription/123-.../resourceGroups/somegroup/...) and deny's based on a string match of the resource group name would do the trick. 

In that we thought `fullName` was the resource identifier based on the documentation description. We thought maybe we were doing something incorrect, but digging deeper it doesn't seem possible at this point.

**Comment by pilor** [comment]
Yes, sorry, it is not possible quite yet.  We recently exposed the [[resourceGroup()]](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#resourcegroup) function in policy rules.  However, since rules currently only have a "field" accessor you can't write a condition that evaluates against the result of [resourceGroup().name].  We plan to expose this functionality but I don't have a concrete timeline to share yet.

If you are restricting users to custom roles and those roles don't contain the Microsoft.Authorization/policyAssignments/delete action you could assign a policyAssignment directly to your managed resource group in every subscription that denies the types you wish to deny.  You may also be able to accomplish your goal by [locking](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-lock-resources) the resource group.

Locks might be your only real option since the end user could always delete your entire resourceGroup without one (policy does not govern deletes).

**Comment by byron70** [comment]
The function evaluation seems like a great idea. From a compliance and mitigation perspective, we need granular evaluation of resources. An example (and not sure if this is possible already), is inspecting a network security group for "bad" rules, port 22 open to the world, etc. Another, ensuring SSL only on a load balancer, etc.

We looked at locking and may go that route for now. We can remove and re-add the locks when we do actions like refresh the images with new versions.

One last thing that might be useful is a user context available for inspection. So specific user X or group Y, could be denied a particular action on a particular resource with tag Z. IAM should do most of this; however complexity there can lead to gaps.

Closing this out, as I believe I have an answer for now. Excited to see where this product goes.

**Comment by egalinkin** [comment]
Has any progress been made on exposing this? We have a similar use case, but cannot seem to reference an RG name.

**Comment by allanmoller** [comment]
Having same issue here, we have choosen not to use environment specific subscriptions, thus instead we use resourcegroups to split environments (Dev/Pre-Prod/Prod). am trying to create a policy that only triggers if resourceGroup name contains specific prefix. Has there been any updates on this issue? @pilor ?

**Comment by pilor** [comment]
A condition against the resource group name would look like:

```
{
   "value": "[resourceGroup().name]",
   "like": "myPrefix*"
}
```

https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#value
