### ISSUE TITLE
Microsoft.Cache/Redis/redisConfiguration/

### ISSUE THREAD

**Issue by santiago845** [Azure/azure-policy#905]
**Scenario**
Need to use azure policy to audit the Azure Cache Redis resource when you choose the premium option the data persistance option must be disallowed, maybe, there is no such property related to that characteristic, please we need the creation for data persistance alias to use that feature
**Definition**
{
  "properties": {
    "displayName": "Redis-DataPersistance",
    "policyType": "Custom",
    "mode": "All",
    "description": "Data Persistence is only available for premium tier, if premium tier then verify Data persistence is disabled.",
    "metadata": {
      "category": "Redis",
      "createdBy": "",
      "createdOn": "",
      "updatedBy": "",
      "updatedOn": ""
    },
    "parameters": {
      "effect": {
        "type": "String",
        "metadata": {
          "displayName": "Effect",
          "description": "Policy Effect"
        },
        "allowedValues": [
          "Audit",
          "Disabled"
        ],
        "defaultValue": "Audit"
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Cache/Redis"
          },
          {
            "field": "Microsoft.Cache/Redis/redisConfiguration.datapersistance",
            "equals": "disabled"
          }
        ]
      },
      "then": {
        "effect": "[parameters('effect')]"
      }
    }
  }
}

**Comment by kenieva** [comment]
@santiago845 - it seems that this property is not exposed through the Redis Cache manifest file. You will need to contact that team for support so that can then create the alias. Thank you.
