### ISSUE TITLE
Can't create custom azure policy for AKS which require access to state data

### ISSUE THREAD

**Issue by Krupakarreddin** [Azure/azure-policy#911]
Currently i was unable to create custom azure policy for AKS which require access to state data.For example to create a policy for uniqueingresshostnames in AKS cluster ,it is impossible to know if an ingress's hostname is unique among all ingresses unless a rule has access to all other ingresses. To make such rules possible, we need to enable syncing of data into OPA. Kubernetes data can be replicated into OPA via the sync config resource.
Currently config cant be edited for azure policy addon

**Comment by nehakulkarni123** [comment]
Hi @Krupakarreddin, thanks for your request. We are currently investigating this capability and how to support it. If you're interested in hearing more about policy investments in the Kubernetes space, feel free to contact policypm@microsoft.com.
