### ISSUE TITLE
Deprecated policies, are they eternally Deprecated?

### ISSUE THREAD

**Issue by MartinParis** [Azure/azure-policy#913]
I was wondering how long they are kept. As long as they keep working I guess, but after that, are they then removed?
Or if they are still part of any setdefinition anywhere in the world they will not be removed?
It stated only here that they can become Deprecated, but nothing is said about their lifecycle after getting that state.

**Comment by nehakulkarni123** [comment]
Hi @MartinParis, we shed some light on our deprecation process [here](https://github.com/Azure/azure-policy/blob/master/built-in-policies/README.md#preview-and-deprecated-policies). When a policy gets deprecated or gets out of preview, there is no impact on existing assignments. Existing assignments continue to be evaluated & enforced like normal and continues to produce compliance results. To deter customers from making any new assignments, deprecated definitions are hidden in the definition list view in Azure Portal.
