### ISSUE TITLE
Add a changelog file

### ISSUE THREAD

**Issue by diegolagospagopa** [Azure/azure-policy#923]
Hi, 

Please can you think to create a changelog file, to be able to understand when a new policy is released. Because right now is very difficult to understand it.

Or can you help me, and suggest me a rss feed or blog with the new things.

Thx so much

**Comment by nehakulkarni123** [comment]
Hi @diegolagospagopa, you can view the commit history for each policy to see changes over time by [subscribing to get these notifications](https://docs.github.com/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#configuring-your-watch-settings-for-an-individual-repository). There is also an [atom feed](https://github.com/Azure/azure-policy/commits/master/built-in-policies.atom) of all the commits in the built-in-policies folder which can be used for a RSS feed.

We have more information [here](: https://github.com/Azure/azure-policy/blob/master/built-in-policies/README.md)

**Comment by diegolagospagopa** [comment]
Thx so much ;)
