### ISSUE TITLE
field Name doesn't support Array

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#94]
Is there a way that I can use Array type in field Name. Currently field name only supports String type. Below is the error when trying to set Array for field **Name**

> responseText: {"error":{"code":"InvalidPolicyParameters","message":"The  policy 'f91e1z4c-1d2b-43d3-aa85-e67e622290c1' could not be parameterized because of validation errors. Please check if policy parameters are properly defined. The inner exception 'Evaluation result of language expression '[parameters('vm')]' is type 'Array', expected type is 'String'.'."}}

Sample of rule

```
          {
               "field": "name",
               "notEquals" : "[parameters('vnetName')]"
          }
```
The parameter doesn't allow using Array.

```
{
    "vnetName":{
        "type":"string",
        "metadata":{
            "description":"Exceptional vNet to pass the rule",
            "displayName":"Exceptional vNet to pass the rule"
        }
    }
}
```

**Comment by pilor** [comment]
If you want to compare a field with a set of values (i.e. ensure "name" does not equal one of the values in "vnetNames") you can use the "notIn" condition instead of "notEquals".  That should allow you to change "vnetNames" to an Array and accomplish what it appears you are trying to achieve.
