### ISSUE TITLE
AppService_PublicNetworkAccess_AINE: why does it trigger although private endpoints used?

### ISSUE THREAD

**Issue by anrub** [Azure/azure-policy#949]
I assigned the [AppService_PublicNetworkAccess_AINE](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/App%20Service/AppService_PublicNetworkAccess_AINE.json) policy, and it matches non-compliant AppServices, that are using private endpoints. I don't understand why the policy is matching, altough there is no public network access used?

**Comment by techlake** [comment]
There is a property on the resource to disable public access. You must set that flag. This is by design (IMO since I'm not part of the Policy team.

**Comment by anrub** [comment]
But the property does not exist (not in the template and not in the portal). And the private endpoint means that there is no public network access.

**Comment by nehakulkarni123** [comment]
@anrub, can explain what you mean by 'the policy is matching'? Do you feel like the compliance is not what you expect?

Not sure if this is related to your question, but just want to clarify that public network access != private endpoints. This policy is meant to flag App Service resources that do not have public network access disabled _solely_-- there is another policy definition in our built-in library that users can leverage to programmatically apply a private endpoint resource on their App Service resources.

If you are still experiencing this issue-- feel free to re-open this issue.

**Comment by anrub** [comment]
I am not sure if I understand that correctly. The policy does not validate if there is public network access (e.g if there is private endpoint there is no public internet accesibility), but it is just a "flag" like a "tag" ? Would be good if that were somewhere noticed, like in a description of the policy or something.

How could I tag an appservice with that property? I don't see a field for this in terraform.
