### ISSUE TITLE
Feature request: Abality to assign more than 1 subscription

### ISSUE THREAD

**Issue by livetek3sr** [Azure/azure-policy#97]
Hi,

Actualy we can only assign a policy by subscription.
It would be great if we can choose more than 1 subscriptions.
In our case, we have 11 Subscriptions and 13 Azure Policy definition, we need to create 143 Policy to ensure that every subscriptions have the same policy.

Thanks.

**Comment by cemheren** [comment]
Hi,
Azure has a feature called Management Groups in public preview, which are logical containers for subscriptions. You can directly assign policies to Management Groups to reduce duplication. 

This is the public documentation for creating Management Groups: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management-groups-create

**Comment by livetek3sr** [comment]
Thanks ! I can confirm it's working great with this solution, I recommend this.
I close this issue.
