### ISSUE TITLE
AKS policy for Defender profile uses string to evaluate the policy and not a Boolean

### ISSUE THREAD

**Issue by rackalex** [Azure/azure-policy#977]
Hello,

The policy "Configure Azure Kubernetes Service clusters to enable Defender profile" (Deploy Definition) is using a string to evaluate the field "Microsoft.ContainerService/managedClusters/securityProfile.azureDefender.enabled". This is causing a correct configuration of AKS and Defender for Cloud to be always non-compliant. 

Currently the existenceCondition looks like this:

`    "policyRule": {
      "if": {
        "field": "type",
        "equals": "Microsoft.ContainerService/managedClusters"
      },
      "then": {
        "effect": "[parameters('effect')]",
        "details": {
          "type": "Microsoft.ContainerService/managedClusters",
          "deploymentScope": "subscription",
          "name": "[field('name')]",
          "evaluationDelay": "PT30M",
          "existenceCondition": {
            "field": "Microsoft.ContainerService/managedClusters/securityProfile.azureDefender.enabled",
            "equals": "true"
          },`

To reproduce this issue a new AKS cluster was configured and Defender for Containers feature was enabled.

A workaround was to duplicate the policy and change the evaluation rule to 'true' instead of '"true"'.
Please see the modified definition:

`    "policyRule": {
      "if": {
        "field": "type",
        "equals": "Microsoft.ContainerService/managedClusters"
      },
      "then": {
        "effect": "[parameters('effect')]",
        "details": {
          "type": "Microsoft.ContainerService/managedClusters",
          "deploymentScope": "subscription",
          "name": "[field('name')]",
          "evaluationDelay": "PT30M",
          "existenceCondition": {
            "field": "Microsoft.ContainerService/managedClusters/securityProfile.azureDefender.enabled",
            "equals": true
          },
`
Would it be possible to fix the policy?

**Comment by rackalex** [comment]
Can someone please react on this?

**Comment by rackalex** [comment]
Hello again, can someone please have a look at this please?

**Comment by eladperets** [comment]
Hi @rackalex, sorry for the delay and thanks for bringing this to our attention.
The 'equals' operator actually converts everything to string before the comparison, so it doesn't matter whether the value is `true` or `"true"`.

I suspect that the API contract for the evaluated resources has changed somehow, which can explain the issue you're seeing. We reached out to the team that owns this APIs (and the policy) for further investigation. We'll keep you posted.

**Comment by rackalex** [comment]
Hi @eladperets, thank you for your response. We have also converted the existing default policy into a custom policy with the change of the evaluation from `"string"` to `string` and this policy then had reported the expected retun (policy compliant). Regards, Alex

**Comment by wyp84** [comment]
Hi, we have the same issue here. Please let us know when this is fixed.

**Comment by eladperets** [comment]
@wyp84  @rackalex  this should have been fixed earlier this week, are you still having issues? is it the same issue as before where compliant resources show as non-compliant?

**Comment by rackalex** [comment]
Have redeployed the policy and could confirm the evaluation works now as expected. Issue solved!

**Comment by eladperets** [comment]
Great to hear it's working! and sorry again for the delayed response.

**Comment by wyp84** [comment]
Yes issue solved, thanks.
