### ISSUE TITLE
Roadmap to audit RBAC on resource

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#99]
Is there a roadmap to control permission on Azure resource? E.g I want to audit Microsoft.Compute to make sure only group of e.g. System Engineer to have access. 

@pilor

**Comment by pilor** [comment]
This is a good suggestion but something that isn't currently in the plan.  Can you request it in [Azure Resource Manager user voice](https://feedback.azure.com/forums/281804-azure-resource-manager)?

@LizMS as FYI.
