### ISSUE TITLE
Built-in: Add a tag to resources - Is there a way to create a blanket exemption for non-taggable resources?

### ISSUE THREAD

**Issue by Blackbaud-CameronBlack** [Azure/azure-policy#992]
We are new to Azure Policy and have decided to start small with the "Built-in Add a tag to resources" policy.  This works, but there are some resources that cannot be tagged and thus are showing as non-compliant (Virtual Clusters for SQL MI for example).

It looks like we can create exemptions for individual resources, but it doesn't look like we can do it for an entire hierarchy like Microsoft.Sql/virtualClusters.

Also, since there probably will be more resources that cannot be tagged that we aren't thinking about, is there a way to create a blanket exemption for resources that cannot be tagged?

**Comment by techlake** [comment]
I solved this with a custom Policy allowing for dynamic exclusion of resource groups based on wild-card. I can share this with you, if you ping me privately, I can share.

**Comment by Blackbaud-CameronBlack** [comment]
Microsoft support pointed me to the "[mode](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#mode)" setting for a policy.  You need to set it to "indexed" to skip non-taggable resources.

> The mode determines which resource types are evaluated for a policy definition. The supported modes are:
> 
> all: evaluate resource groups, subscriptions, and all resource types
> indexed: only evaluate resource types that support tags and location

**Comment by techlake** [comment]
This is incorrect. While indexed helps (is required) it does not solve the problem of Databricks, Purview, Synapse, etc.
