### ISSUE TITLE
Synapse minimum TLS policy is not working as expected  

### ISSUE THREAD

**Issue by mahmoudsamy27** [Azure/azure-policy#993]
#### Details of the scenario you tried and the problem that is occurring
After assigning the built it policy, no resources were evaluated. 
Created a duplicate policy and changed the mode to All, all worked as expected. 
#### Suggested solution to the issue
Please modify the built it policy and commit the change to reflect in Azure Portl

**Comment by nehakulkarni123** [comment]
Hi @mahmoudsamy27, Azure Policy built-in definitions are owned by various services across Azure-- can you please share the display name or ID of the built-in definition so I can relay your feedback to the right owners?

In the meantime-- you're correct to create a custom policy that fits your needs.

**Comment by shanhix1** [comment]
Hi @mahmoudsamy27 - this issue has been routed to the appropriate team to correct built-in policy **Azure Synapse Workspace SQL Server should be running TLS version 1.2 or newer** (/providers/Microsoft.Authorization/policyDefinitions/cb3738a6-82a2-4a18-b87b-15217b9deff4). Will close this issue when the change is made.

**Comment by shanhix1** [comment]
Hi @mahmoudsamy27, I am closing this issue as it has now been resolved by the owning team. See the new definition here: https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Synapse/SynapseWorkSpaceDedicatedSqlMinimalTlsSettings_Audit.json
